### PR TITLE
Fix a type error in `NewsContentVoter`

### LINKED ISSUE #7560: NewsBundle\Security\Voter\NewsContentVoter::getArchiveId(): Return value must be of type ?int, string returned
### Affected version(s)

5.3.15

### Description

image

After updating from 5.3.12 to 5.3.15, I get the following error when calling up the news in the BE:
Contao\NewsBundle\Security\Voter\NewsContentVoter::getArchiveId(): Return value must be of type ?int, string returned

According to fritzmg, the error is fixed if you change line 66 in 
"vendor\contao\news-bundle\src\Security\Voter\NewsContentVoter.php" 
to 

`$this->archives[$newsId] = (int) $this->connection->fetchOne('SELECT pid FROM tl_news WHERE id=?', [$newsId]);`

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #7560

We do not really have to distinguish between `false`, `null` and `0`, thus this PR fixes the issue by casting the value always to `int`. I also adjusted the tests to include a string integer.

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

**Review by aschempp — CHANGES_REQUESTED** [review]
Is there any reason to change this? I think a method that says `getArchiveId` should only return a valid archive ID, and allow you to distinguish if something is not a valid ID.

**Comment by fritzmg** [comment]
The reason for the change was just to simplify it while fixing #7560.

**Review by aschempp — DISMISSED** [review]
fine with me since this is a private method anyway. Thanks for the explanation 🙃

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
