### PR TITLE
Do not define ptable for tl_content

### LINKED ISSUE #5157: Editing News Item bring content from tl_article instead of tl_content
### Affected version(s)

4.13.7

### Description

After updaing to Contao 4.13.7, when try to edit news item content (or add new news item), it show content from "tl_article" with same pid of news item if exists.

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #5157

Same as https://github.com/contao/contao/pull/5158 for Contao 4.13.

### CODE REVIEW

**Comment by leofeyer** [comment]
@hamidabbaszadeh Can you confirm that this change fixes your issue?

**Comment by fritzmg** [comment]
I was able to reproduce the issue and confirm that this fixes the issue.

**Comment by ausi** [comment]
> I was able to reproduce the issue and confirm that this fixes the issue.

Me too

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
