### PR TITLE
Replaced the BE_CELL_SIZE cookie by a localstorage entry

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Comment by aschempp** [comment]
We're not removing existing cookies, are we?

**Comment by Toflar** [comment]
We don't need to. Nobody else is setting this cookie (in contrast to the `BE_PAGE_OFFSET` so there's no point in doing so.

**Comment by aschempp** [comment]
I was talking about the cookie already being present. But then again that can only be backend users and the cookie will expire automatically. Should be fine imho.

**Pull request merged**
