### PR TITLE
Remove left-over url field in tl_module

### PR DESCRIPTION
**Pull request by bytehead**
This is a left-over of the flash player integration from ealier days 😬

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by m-vo** [comment]
Isn't this a bug then, that should also land in 4.9/4.13?

**Comment by fritzmg** [comment]
> Isn't this a bug then, that should also land in 4.9/4.13?

I would not remove this field in Contao 4. People might use it and then suddenly "lose" it when they update to a newer bugfix version.

**Comment by bytehead** [comment]
IMO it's a bug, but also a possibly break.

**Comment by m-vo** [comment]
> IMO it's a bug, but also a possibly break.

:+1: Because this is another database field (which unfortunately is a limited resource), I'd vote for bug though.

**Comment by fritzmg** [comment]
> 👍 Because this is another database field (which unfortunately is a limited resource), I'd vote for bug though.

Yes, but with https://github.com/contao/contao/pull/4179#issuecomment-1047658782 this field will be changed to `text` anyway (in 4.9+) and thus it will be less of a problem.

**Comment by ausi** [comment]
I’d also vote for keeping the field in Contao 4, the likelihood that some extension or application reuses this field is very high I think.

**Review by m-vo — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
