### PR TITLE
Allow new major versions of third-party packages

### PR DESCRIPTION
**Pull request by leofeyer**
Another step towards #1889.

@contao/developers Both packages are fully compatible with Contao 4.9 as well, therefore I wonder if we should also backport the changes?

### CODE REVIEW

**Comment by aschempp** [comment]
Is there a reason to continue to support the old versions?

**Comment by Toflar** [comment]
I'm sure you checked but just making sure: Both packages released new major versions but the config is still the same?

**Comment by leofeyer** [comment]
> Is there a reason to continue to support the old versions?

Yes, kind of. The KNP menu bundle [does not support PHP 7.1 anymore](https://github.com/KnpLabs/KnpMenuBundle/blob/master/CHANGELOG.md), so if we drop support for the old version, we are implicitly raising the minimum PHP version.

We could drop support for the old CORS bundle though. Do you want me to?

---

> I'm sure you checked but just making sure: Both packages released new major versions but the config is still the same?

I have checked the changelogs for BC breaks and verified that we are not affected. There are no configuration changes mentioned:

* https://github.com/KnpLabs/KnpMenuBundle/blob/master/CHANGELOG.md
* https://github.com/nelmio/NelmioCorsBundle/blob/master/CHANGELOG.md

**Comment by aschempp** [comment]
We‘re not supporting PHP 7.1 either? 🤷‍♂️

**Comment by leofeyer** [comment]
Oh, you are right. We are on PHP 7.2+ ourselves. 🎉

**Comment by leofeyer** [comment]
I have removed the old versions in 38faaa8b9b3b3a9b7fed61ffaca80c1115b9a32b.

**Comment by fritzmg** [comment]
> I have removed the old versions in [38faaa8](https://github.com/contao/contao/commit/38faaa8b9b3b3a9b7fed61ffaca80c1115b9a32b).

What if someone has a dependency on the older versions though? They will not be able to update to Contao 4.10.

**Comment by leofeyer** [comment]
Exactly. They will have to check and allow the new major version, too, before they can upgrade.

**Comment by fritzmg** [comment]
> Exactly. They will have to check and allow the new major version, too, before they can upgrade.

I meant instances, where you can't do anything about it, since you have no control over the other dependency. Shouldn't we still allow the lowest possible dependencies, if we are still compatible? Not sure what the best practise here is.

**Comment by leofeyer** [comment]
I guess you are right. I have reverted the last commit.

**Comment by leofeyer** [comment]
What about backporting the changes to Contao 4.9?

**Comment by fritzmg** [comment]
> What about backporting the changes to Contao 4.9?

I would be in favor of that.

**Pull request merged**
