### PR TITLE
Ignore invalid important part values

### PR DESCRIPTION
**Pull request by ausi**
To prevent issues like #643 we should ignore invalid values I think.

### CODE REVIEW

**Comment by leofeyer** [comment]
How did the error occur in the first place? Is our version 4.8.0 update routine not working properly?

**Comment by ausi** [comment]
The comment https://github.com/contao/contao/issues/643#issuecomment-522273176 indicates that only a small number of images was affected. Maybe the image size couldn’t be determined correctly for them in https://github.com/contao/contao/blob/879e05ecc75a6bf70aabc1c3d867eb420f291f60/installation-bundle/src/Database/Version480Update.php#L141

**Comment by leofeyer** [comment]
Then I think I would prefer to validate the image size in the version 4.8.0 upgrade, because the issue can never occur in a fresh installation, can it?

**Comment by aschempp** [comment]
But there could be reasons or issues if the update did not work correctly, and leaving the backend in an unuseable state can't be a good solution…

**Comment by ausi** [comment]
How about adding the check to the image factory here: https://github.com/contao/contao/blob/879e05ecc75a6bf70aabc1c3d867eb420f291f60/core-bundle/src/Image/ImageFactory.php#L294-L318

This way we could also just convert the values to the new format instead of generating an error.

**Comment by leofeyer** [comment]
Sounds good to me. @aschempp WDYT?

**Comment by aschempp** [comment]
🤷‍♂ sounds fine, as long as the system is useable again…

**Comment by leofeyer** [comment]
Perfect. 👍

The only thing that still bothers me is the `trigger_error()`, because the only other place where we trigger an `E_USER_WARNING` error is in the `StringUtil::deserialize()` method if the string has potentially been manipulated. Maybe we should add a log entry in the system log instead? We are logging all other misconfigurations there as well.

**Comment by ausi** [comment]
> Maybe we should add a log entry in the system log instead?

Done.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
