### PR TITLE
Add the domain to the "root page dependent module" configuration

### PR DESCRIPTION
**Pull request by aschempp**
I currently have multiple domains in an installation, where the root page is always named after the language. This results in this useless view:

Bildschirmfoto 2024-11-20 um 17 20 22

This PR adds the domain name to the dropdown option. It should be cherry-pickable to Contao 5.3, or do we need a separate PR?

### CODE REVIEW

**Review by bytehead — DISMISSED** [review]

**Comment by leofeyer** [comment]
We need a PR for Contao 5.3 first and then optionally a backport PR (see https://github.com/contao/contao?tab=readme-ov-file#contao-413).

**Review by fritzmg — COMMENTED** [review]
What does the (collapsed) site structure look like in your example - wouldn't you need a more descriptive name there anyway?

Also the domain is not mandatory, thus it would result in

```
Modul wählen für "en []"
Modul wählen für "de []"
```

in such cases.

**Comment by bytehead** [comment]
Your `$rootPage->title` values are anyway weird, no? How does your page tree look like in the backend?

**Comment by aschempp** [comment]
> What does the (collapsed) site structure look like in your example - wouldn't you need a more descriptive name there anyway?

I'm using https://github.com/terminal42/contao-folderpage to group the root pages by domain 🙃

**Comment by aschempp** [comment]
> We need a PR for Contao 5.3 first and then optionally a backport PR (see https://github.com/contao/contao?tab=readme-ov-file#contao-413).

Rebased onto 5.3 then.

> Also the domain is not mandatory

I'm aware of that, but I think this would be OK as a known limitation, since it is highly suggested to add a domain anyway.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
