### PR TITLE
Support existing htaccess without RewriteRule

### PR DESCRIPTION
**Pull request by Toflar**
Implements contao/manager-bundle#70.

### CODE REVIEW

**Comment by aschempp** [comment]
I generally like this, but I think the `.htaccess` file should just get a special handling, instead of some "inline and name check". Like just call a method to copy or append the `.htaccess` after all other skeleton files have been copied.

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Comment by Toflar** [comment]
@leofeyer should we backport this to 4.4? It's not really a feature regarding how to use Contao. It's simplifying the installation of Contao and people will continue to install 4.4 until 2022 😄

**Comment by leofeyer** [comment]
Backported in 254f8f74c7ccc377b458c42851960035108cd18f.

**Pull request merged**
