### PR TITLE
Ignore minval/maxval in checkbox/radio/select fields

### LINKED ISSUE #1695: form field verification rules kept after change of field type
**Affected version(s)** contao 4.9

Reproduction on contao.org:

In the contact form I changed the minimum field length to 400 for the field 'a selection'. Saved. After that I changed the type of this field to radio button. Info shows that still length is being checked. 

Bildschirmfoto von 2020-05-03 19-24-39

This will lead to the error: "a selection must be 400" and form will not be sent.

### PR DESCRIPTION
**Pull request by aschempp**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1695

### CODE REVIEW

**Comment by fritzmg** [comment]
Hm, shouldn't `min` and `max` also be ignored?

**Review by fritzmg — CHANGES_REQUESTED** [review]
Hm, shouldn't `min` and `max` also be ignored?

**Comment by aschempp** [comment]
> Hm, shouldn't `min` and `max` also be ignored?

I thought about that too, but couldn't find them in the `tl_form_field` palettte?

**Comment by fritzmg** [comment]
They are not in the palette, but if you do

```php
$checkboxWidget->min = 400;
```

it might end up as the HTML5 `min` attribute as well? Haven't tested it though ;)

**Comment by Toflar** [comment]
Especially the fact that the palette doesn't mean anything in Contao...you can switch the type and you'll still have min and max values in the database...

**Comment by aschempp** [comment]
> Especially the fact that the palette doesn't mean anything in Contao...you can switch the type and you'll still have min and max values in the database...

no you don't, because there is no such field 😂

**Review by fritzmg — APPROVED** [review]

**Comment by qzminski** [comment]
I think you should also consider the `hidden` input type here.

**Comment by leofeyer** [comment]
@qzminski Can you make a new PR please?

**Pull request merged**
