### PR TITLE
Fix Escargot 0.6 compat and skip broken link checker

### PR DESCRIPTION
**Pull request by Toflar**
| Q                | A
| -----------------| ---
| Fixed issues     | -
| Docs PR or issue | -

Fixed compat with Escargot 0.6 which also automatically adds tags for `data` attributes found on links.

There have been reports in the forums that users have links that the broken link checker doesn't need to check because it will take forever and it's actually irrelevant.

That's possible using these changes by turning your `<a href="foobar">link</a>` into `<a href="foobar" data-skip-broken-link-checker>link</a>`.

### CODE REVIEW

**Comment by Toflar** [comment]
Failing tests unrelated 🤷‍♂️

**Comment by fritzmg** [comment]
Can we may be shorten the tag to `data-skip-link-checker`? :)

**Comment by leofeyer** [comment]
> Failing tests unrelated 🤷‍♂️

Fixed.

**Comment by Toflar** [comment]
> Can we may be shorten the tag to `data-skip-link-checker`? :)

I would like to keep the name consistent with the name of the subscriber if you don't mind :)

**Review by bytehead — DISMISSED** [review]

**Comment by Toflar** [comment]
I've taken advantage of this PR to also add timing information to the debug log which is imho a bug too (a log without time information isn't a super useful log at times ;)).

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
