### PR TITLE
Support dark variants for all icons

### LINKED ISSUE #6061: Convention for back end icons
### Description

Contao already creates picture elements for theme icons with a light and dark variant, however, this does not work for custom icons in extensions yet. Therefore, I‘d like to expand the `Image::getHtml()` functionality to all icons that follow a certain convention. What would you prefer?

**1. Explicit suffixes**

- `my-icon--light.svg`
- `my-icon--dark.svg`

```php
'action' => [
    'href' => 'key=action',
    // If my-icon.svg does not exist, we check for …--light.svg and …--dark.svg
    'icon' => 'bundles/vendorname/my-icon.svg',
],
```

**2. Suffix for dark icons only**

- `my-icon.svg`
- `my-icon--dark.svg`

```php
'action' => [
    'href' => 'key=action',
    // If my-icon.svg does not exist, we skip the icon (current behavior)
    'icon' => 'bundles/vendorname/my-icon.svg',
],
```

**Other possible suffixes**

- `my-icon-dark.svg`
- `my-icon.dark.svg`

@contao/developers WDYT?

### PR DESCRIPTION
**Pull request by leofeyer**
Implements #6061

### CODE REVIEW

**Comment by leofeyer** [comment]
As briefly discussed with @ausi, using the first variant described in #6061 (`*--light.svg` and `*--dark.svg`) will make things more complicated:

* There will be one `file_exists()` call more per icon.
* What happens if all three variants of an icon exist (`foo.svg`, `foo--light.svg`, `foo--dark.svg`)?

Let‘s still discuss this in the next call.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to try using an array if there are two icons, e.g. 

```php
[
    'icon' => ['iconLight.svg', 'iconDark.svg'],
]
```

**Comment by leofeyer** [comment]
I have tried it now and it does not really work. Not only would we have to review **every** `Image::getHtml()` call throughout the code base, there are also some cases that cannot be solved with an array:

1. The regular icon does not have a dark variant but the disabled variant does (e.g. `copy.svg` and `copy_.svg` and `copy_--dark.svg`). The only solution to this case would be to store an unnecessary copy of the regular icon as `copy--dark.svg`.

2. Dynamic icons like in the [ListWizard](https://github.com/contao/contao/blob/2a6d1c35365b5a8e7d5df6c7d113842d326bca29/core-bundle/contao/widgets/ListWizard.php#L85) that may or may not have a dark variant. Since we cannot know, we also don‘t know whether to pass in an array or not.

So a convention that can be checked in the `Image::getHtml()` method seems the only possible solution.

**Review by aschempp — DISMISSED** [review]
LGTM. Just a sidenote-thinking: wouldn't it be much better to CSS-rotate the fold icon instead of replacing it?

**Comment by leofeyer** [comment]
> wouldn't it be much better to CSS-rotate the fold icon instead of replacing it?

Yes, good idea. See #6153.

**Pull request merged**
