### PR TITLE
Render partial tree instead of disabling root trails with breadcrumb

### LINKED ISSUE #7366: Backend search for articles doesn't show all results
### Affected version(s)

4.13

### Description

Whilst trying to search for articles with a specific title, I didn't see all results.

E.g.
image

I've found out that it happens due to the following LOC within the eliminateNestedPages method:
https://github.com/contao/contao/blob/3cb2d3f5f021cfc60fdf3035c9727cc695912d29/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1615

https://github.com/contao/contao/blob/3cb2d3f5f021cfc60fdf3035c9727cc695912d29/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1601-L1618

After commenting that one out, I get all expected results.
image

### Reproducing the issue

I wasn't able to reproduce the issue within the demo but provided an anonymous sql dump.
[contaobug.sql.gz](https://github.com/user-attachments/files/16377688/contaobug.sql.gz)

1. Select the rootpage Page_1
2. Switch to `Articles`
3. Search for the Title `Problem_`
4. Do the same search when commenting out the mentioned LoC

### Related issues

It looks like this was coded by @aschempp in 2010/2011 and is related to the following two issues:
https://github.com/contao/core/issues/2475
https://github.com/contao/core/issues/3423

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/7366

As I tried to describe in the call, everything works fine if the tree is rendered from the root. You can see this in the current system by not filtering the tree for `Page_1`. The problem happens when the breadcrumb helper disables `showRootTrails`.

/cc @zoglo

### CODE REVIEW

**Comment by zoglo** [comment]
@aschempp just tested this one.
Whilst this PR properly builds the tree right now, it still has the same (wrong) amount of search results.
image

vs without Filter and just Page_1
image

**Comment by aschempp** [comment]
I fail to see what exactly is wrong here?

**Comment by zoglo** [comment]
> I fail to see what exactly is wrong here?

Your PR fixes the tree when searching for articles, however it still shows the **same** amount of results as initially reported as a bug.

Meaning that this "fixes" one bug (not showing the root trails correctly), not the other (not displaying all results)

**Comment by zoglo** [comment]
@aschempp

This does fix
* **_showing proper root trails_**
(I did stumble across this today again - this PR did fix the trail)

#7366 might just be a very specific case right now (maybe due to using `terminal42/contao-folderpage` + lots of `nesting`+ `redirects` and more)

**Review by zoglo — DISMISSED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Review by leofeyer — APPROVED** [review]

**Pull request merged**
