### PR TITLE
Show the video URL in the backend preview

### LINKED ISSUE #5078: content element "YouTube" -> video autoplaying in backend
### Affected version(s)

5.0.0-RC1

### Description

Steps to reproduce:
1. create new content element with element type "YouTube"
2. fill in Source -> "YouTube ID"
3. select all "Player options"
4. save content element

result: the YouTube-video is autoplayed in the contao backend.
should: the YouTube-video should not autoplay in the contao backend even if the checkbox "Autoplay" is checked (unnecessary data consumption, disturbing audio)

### PR DESCRIPTION
**Pull request by bytehead**
Fix #5078 

Bildschirmfoto 2022-08-04 um 08 42 38

### CODE REVIEW

**Review by aschempp — COMMENTED** [review]
are you intentionally showing a splash image if there is one instead of the link? I guess the splash image would have a click event that fails now (in the back end)?

**Comment by bytehead** [comment]
You mean to drop the whole `figure` in case of `as_editor_view`?

**Review by m-vo — APPROVED** [review]
LGTM ♥️

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
