### PR TITLE
Ensure that the license field in the MetaWizard contains a URL

### PR DESCRIPTION
**Pull request by Toflar**
Fixes https://github.com/contao/contao/issues/4164

This introduces validation on the `license` field. And while I was on it I thought I would implement it in a way that allows regular expression validation on any field with any error message but also a fallback for convenience 😎 
It also allows to make fields mandatory (by not specifying `^$` in the regex).

### CODE REVIEW

**Comment by Toflar** [comment]
Bildschirmfoto 2022-05-05 um 19 16 24

**Comment by Toflar** [comment]
Bildschirmfoto 2022-05-05 um 19 27 24

Now also with some highlighting :)

**Review by fritzmg — DISMISSED** [review]

**Review by ausi — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
