### PR TITLE
Update terminal42/service-annotation-bundle and fix Page annotation

### PR DESCRIPTION
**Pull request by aschempp**
version 1.1 of `terminal42/service-annotation-bundle` does no longer require the interface. I've also found and fixed a bug, the `@Page` annotation used the wrong interface!

### CODE REVIEW

**Comment by fritzmg** [comment]
If this is more of a bugfix, shouldn't this be based against the `4.9` branch then?

**Comment by aschempp** [comment]
The incorrect interface is for an annotation on Contao 4.10 only. There's not really a reason to change the dependency in the patch release imho.

**Comment by fritzmg** [comment]
> There's not really a reason to change the dependency in the patch release imho.

If we can be sure that anyone using the latest version of Contao 4.9 also has version `1.1` of the service annotation bundle, we can update the documentation accordingly. Otherwise we'll need to retain the interface forever and only mention it in a footnote, that you _might_ not need to use `implements ServiceAnnotationInterface`.

**Review by leofeyer — DISMISSED** [review]

**Comment by aschempp** [comment]
Good point, what do you think @leofeyer should I rebase this to 4.9 ?

**Comment by leofeyer** [comment]
I am fine either way I guess.

**Comment by aschempp** [comment]
PR in https://github.com/contao/contao/pull/1988 but I will need to rebase this PR because we used the service annotations a lot more in 4.10. Let's just keep this open until https://github.com/contao/contao/pull/1988 is merged.

**Comment by leofeyer** [comment]
#1988 has been merged.

**Comment by aschempp** [comment]
I've reverted the changes applied in 4.9, but we should merge 4.9 into 4.10 before this 😉

**Comment by leofeyer** [comment]
> but we should merge 4.9 into 4.10 before this 😉

Done.

**Comment by aschempp** [comment]
Just checked locally, this is RTM then.

**Pull request merged**
