### PR TITLE
Fix psalm InvalidCatch error

### LINKED ISSUE #2123: Exception cannot be caught?
**Affected version(s)**

Contao 4.9+

**Description**

According to Psalm, the exception in the following two methods cannot be caught, because it does not extend `Exception` or implement `Throwable` (see https://github.com/avalanche123/Imagine/blob/master/src/Exception/Exception.php):

https://github.com/contao/contao/blob/4b882d86b9bc8a74e4c8282bf53254cd5827cebf/core-bundle/src/Image/LegacyResizer.php#L96-L98

https://github.com/contao/contao/blob/4b882d86b9bc8a74e4c8282bf53254cd5827cebf/core-bundle/src/Image/LegacyResizer.php#L105-L107

@ausi Is this correct?

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2123

### CODE REVIEW

**Comment by fritzmg** [comment]
That won't catch all of the exceptions within the `Imagine\Exception` namespace, is that deliberate?

**Comment by ausi** [comment]
Yes, `enhanceImagineException` is only meant for exceptions that are caused by a not supported image format and these should all be `RuntimeExceptions` AFAIK.

**Comment by fritzmg** [comment]
I see. But since you only want to catch exceptions about not supported image formats, wouldn't it make more sense (and make it more readable) to catch `Imagine\Exception\NotSupportedException` directly, instead of its parent?

**Comment by ausi** [comment]
It would, but Imagine doesn’t throw a `NotSupportedException` in this case https://github.com/avalanche123/Imagine/blob/3db069bd870f45b5305e7d6bd4e08d45ebb22cef/src/Imagick/Image.php#L342

**Review by fritzmg — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
