### PR TITLE
Add a unique index to the tl_version table

### LINKED ISSUE #900: Mehrfache Vergabe von Versionsnummern
Bei der Verarbeitung von parallelen Requests, kann es zur mehrfachen Vergabe von Versionsnummern kommen.

image

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #900
| Docs PR or issue | -

This does not only fix #900, it also improves the DB queries:

### CODE REVIEW

**Review by aschempp — COMMENTED** [review]
does it actually fix the issue? Or will there be an exception now when clicking the e-mail link multiple times?

**Comment by leofeyer** [comment]
There will be an exception, which is fine IMHO.

**Comment by Mynyx** [comment]
Why not using a lock to avoid an exception?

**Comment by m-vo** [comment]
> Why not using a lock to avoid an exception?

Locking would be the wrong paradigm imo - if anything it should be fail & retry.

**Comment by leofeyer** [comment]
Locking does not make sense to me, either. We would end up with versions 1, 2, 3 and 4 which would all be identically. There is no point in that.

**Comment by Mynyx** [comment]
> Locking does not make sense to me, either. We would end up with versions 1, 2, 3 and 4 which would all be identically. There is no point in that.

This is based on the concrete example of the activation link. However, other changes that are not identical could overlap, too.

**Comment by leofeyer** [comment]
Is there a real world scenario that we can reproduce?

**Review by aschempp — CHANGES_REQUESTED** [review]
see https://github.com/contao/contao/pull/1564 for an approach that also correctly generates the version numbers.

**Pull request closed without merging**
