### PR TITLE
Fix undefined array key "panelLayout"

### PR DESCRIPTION
**Pull request by markocupic**
getting a warning when running Contao in dev mode on PHP 8.0

### CODE REVIEW

**Comment by markocupic** [comment]
Hi Fritz
I don't know what went wrong ;-(

**Comment by leofeyer** [comment]
@markocupic Since this is a bugfix, can you please rebase your PR on the `4.12` branch?

**Comment by markocupic** [comment]
I have no idea if I've done it right??? Rebasing, merging,... Help wanted ;-)

**Comment by markocupic** [comment]
Wouldn't it be easier, if I made a new pull request on base of the[ 4.12](https://github.com/contao/contao/tree/4.12) branch?

**Comment by bytehead** [comment]
> Wouldn't it be easier, if I madea new pull request on base of the 4.12 branch?

Possibly, unless you know how to rebase correctly 🙃

**Comment by markocupic** [comment]
> 

Ich bin lernfähig. ;-)

**Comment by leofeyer** [comment]
@markocupic What is the exact warning that you get?

**Comment by markocupic** [comment]
> @markocupic What is the exact warning that you get?
Hi Leo
Ok, I found out, that I only get the warning if I do not set the `$GLOBALS['TL_DCA']['tl_import_from_csv']['list']['sorting']['panelLayout']`



```php
$GLOBALS['TL_DCA']['tl_import_from_csv'] = array(
    'config'      => array(
        'dataContainer'    => 'Table',
        'enableVersioning' => true,
        'sql'              => array(
            'keys' => array(
                'id' => 'primary',
            ),
        ),
    ),
    'list'        => array(
        'sorting'           => array(
            'mode'        => 2,
            'fields'      => array('importTable ASC'),
           // 'panelLayout' => 'filter;sort,search,limit',
        ),

```

I assume that it was my mistake and that setting the key is mandatory here. 

This ist the warning that occurs in the debug mode only:

warning

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @markocupic.

**Pull request merged**
