### PR TITLE
Make the default (global) operations more consistent

### LINKED ISSUE #7702: Global operations appear without configuration
### Affected version(s)

Contao 5.3.17
PHP 8.2.24

### Description

I don't define the `all` key, but the `DefaultGlobalOperationsListener` set it anyway. I don't want an `all` key in my configuration. Same with all row operations as well.

grafik

### Reproduce

```php
// contao/dca/tl_test.php

$GLOBALS['TL_DCA']['tl_test'] = [
    'config' => [
        'dataContainer' => \Contao\DC_Table::class
    ]
];
```

`php bin/console debug:dca tl_test`

```
array:2 [
  "config" => array:2 [
    "dataContainer" => "Contao\DC_Table"
    "ondelete_callback" => array:1 [
      0 => array:2 [
        0 => "contao.listener.data_container.record_preview"
        1 => "storePrecompiledRecordPreview"
      ]
    ]
  ]
  "list" => array:2 [
    "global_operations" => array:1 [
      "all" => array:4 [
        "href" => "act=select"
        "class" => "header_edit_all"
        "attributes" => "accesskey="e""
        "label" => & null
      ]
    ]
    "operations" => array:4 [
      "edit" => array:4 [
        "href" => "act=edit"
        "icon" => "edit.svg"
        "button_callback" => Closure(DataContainerOperation $operation): void^ {#4730
          returnType: "void"
          class: "Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener"
          this: Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener {#10199 …}
          use: {
            $actionClass: "Contao\CoreBundle\Security\DataContainer\UpdateAction"
            $table: "tl_test"
            $new: null
          }
          file: "D:\Laragon\www\contao-5\vendor\contao\core-bundle\src\EventListener\DataContainer\DefaultOperationsListener.php"
          line: "180 to 184"
        }
        "label" => & null
      ]
      "copy" => array:4 [
        "href" => "act=copy"
        "icon" => "copy.svg"
        "button_callback" => Closure(DataContainerOperation $operation): void^ {#10633
          returnType: "void"
          class: "Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener"
          this: Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener {#10199 …}
          use: {
            $actionClass: "Contao\CoreBundle\Security\DataContainer\CreateAction"
            $table: "tl_test"
            $new: null
          }
          file: "D:\Laragon\www\contao-5\vendor\contao\core-bundle\src\EventListener\DataContainer\DefaultOperationsListener.php"
          line: "180 to 184"
        }
        "label" => & null
      ]
      "delete" => array:5 [
        "href" => "act=delete"
        "icon" => "delete.svg"
        "attributes" => "data-action="contao--scroll-offset#store" onclick="if(!confirm(''))return false""
        "button_callback" => Closure(DataContainerOperation $operation): void^ {#10831
          returnType: "void"
          class: "Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener"
          this: Contao\CoreBundle\EventListener\DataContainer\DefaultOperationsListener {#10199 …}
          use: {
            $actionClass: "Contao\CoreBundle\Security\DataContainer\DeleteAction"
            $table: "tl_test"
            $new: null
          }
          file: "D:\Laragon\www\contao-5\vendor\contao\core-bundle\src\EventListener\DataContainer\DefaultOperationsListener.php"
          line: "180 to 184"
        }
        "label" => & null
      ]
      "show" => array:3 [
        "href" => "act=show"
        "icon" => "show.svg"
        "label" => & null
      ]
    ]
  ]
]
```

### PR DESCRIPTION
**Pull request by aschempp**
This fixes multiple things:
1. fixes https://github.com/contao/contao/issues/7702
2. change core DCAs to rely on automatically prepend/append default (global) operations if no string-operations are defined
3. append default global operations after DCA operations (if both exist)
4. If an operation is not an array, simply skip it. This allows to achieve not-adding the default operations at all (e.g. by using `show => false`.
5. if the `operations`/`global_operations` is an empty array, we do not add any operations. This way it is possible to remove all (global) operations.

### CODE REVIEW

**Comment by fritzmg** [comment]
> 4\. If an operation is not an array, simply skip it. This allows to achieve not-adding the default operations at all (e.g. by using `show => false`.

Hm, this does not seem to work yet. I have tried with the following DCA:

```php
use Contao\DataContainer;
use Contao\DC_Table;

$GLOBALS['TL_DCA']['tl_foobar'] = [
    'config' => [
        'dataContainer' => DC_Table::class,
        'enableVersioning' => true,
        'sql' => [
            'keys' => [
                'id' => 'primary',
                'tstamp' => 'index',
            ],
        ],
    ],
    'list' => [
        'sorting' => [
            'mode' => DataContainer::MODE_UNSORTED,
            'panelLayout' => 'limit',
        ],
        'label' => [
            'fields' => ['name'],
            'format' => '%s',
        ],
        'operations' => [
            'show' => false,
        ],
    ],
    'fields' => [
        'id' => [
            'sql' => ['type' => 'integer', 'unsigned' => true, 'autoincrement' => true],
        ],
        'tstamp' => [
            'sql' => ['type' => 'integer', 'unsigned' => true, 'default' => 0],
        ],
        'name' => [
            'label' => ['Name', 'Name of the entry.'],
            'inputType' => 'text',
            'eval' => ['tl_class' => 'w50', 'maxlength' => 255, 'mandatory' => true],
            'sql' => ['type' => 'string', 'length' => 255, 'default' => ''],
        ],
    ],
    'palettes' => [
        'default' => '{Foobar},name',
    ],
];
```

With this no operations will be shown.

Same thing happens with the `global_operations`.

**Comment by aschempp** [comment]
Thats how it is intended. The "rules" say:
1. if there is any named default operation, do not add the default operations
2. if the operation config is not an array, skip it

As I said this is kinda confusing, but it's also just a side effect. The previous implementation of casting a string to an array did not make sense at all, because it would not produce a valid operation.

**Comment by fritzmg** [comment]
But what do you mean by 4.) then? i.e. what has changed here?

**Comment by aschempp** [comment]
```php
'operations` => [
    'show' => false,
]
```

This would not render any default operations. You can also add your own before/after, and it would not render the default. You could also use `edit` or any other default name. That's what I mean by "confusing", but I couldn't come up with a better option.

**Comment by aschempp** [comment]
Btw. this works out of the box without special handling, because a default name exists but the config is invalid, so it's simply ignored. It's not "allow false and skip if the name exists", its "name exists but config is invalid"

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
