### PR TITLE
Fix the `dotenv:dump` command

### PR DESCRIPTION
**Pull request by aschempp**
This will dynamically dump `APP_ENV=jwt` into the `.env.local.php` file, if the `.env` and `.env.local` do not contain `APP_ENV`.

### CODE REVIEW

**Comment by Toflar** [comment]
Let's discuss this on Thursday, that's way easier and quicker.

**Comment by fritzmg** [comment]
One thing I notice is that while `dotenv:dump` now dumps `APP_ENV=jwt` to the PHP file, `dotenv:dump prod` still dumps `APP_ENV=prod` to the PHP file - though that may be intentional anyway?

**Comment by fritzmg** [comment]
Other than that everything seems to work now as far as I tested 👍

**Review by fritzmg — DISMISSED** [review]

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to keep the factory and merge the PR as it is.

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
