### PR TITLE
add clr to DCA tl_page to correct layout

### PR DESCRIPTION
**Pull request by zonky2**
add clr to DCA tl_page to correct layout

### CODE REVIEW

**Comment by aschempp** [comment]
🤔  ich kann diesen Fehler in der Online-Demo nicht reproduzieren, in welchem Browser hast du das?

**Comment by bytehead** [comment]
Looks correct to me as it is (Contao official demo):
Bildschirmfoto 2020-05-26 um 08 50 54

**Comment by zonky2** [comment]
hmm FF 76.0.1 (64-Bit) Win, C 4.9.3

**Comment by fritzmg** [comment]
The problem is not a missing `clr`. For some reason some Widgets are a little higher now in the recent Firefox versions.

See https://github.com/contao/contao/issues/1721

**Review by fritzmg — CHANGES_REQUESTED** [review]
The problem is not a missing `clr`. For some reason some Widgets are a little higher now in the recent Firefox versions.

See https://github.com/contao/contao/issues/1721

**Comment by zonky2** [comment]
ok - I should close the fix?

**Comment by fritzmg** [comment]
You could update the PR to fix the CSS instead ;). Or make a new PR.

**Comment by zonky2** [comment]
ok

**Pull request closed without merging**
