### PR TITLE
Add a template element and module

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes https://github.com/contao/core-bundle/pull/1315#issuecomment-358484679
| Docs PR or issue | contao/docs#866

### CODE REVIEW

**Review by m-vo — DISMISSED** [review]
Not sure about `category: texts` but I do not have a better idea either. :slightly_smiling_face:

**Comment by bytehead** [comment]
maybe `misc` 🙃

**Review by bytehead — DISMISSED** [review]

**Comment by ausi** [comment]
> Not sure about `category: texts`

I followed the convention of the HTML element which is also in the `texts` category.

**Review by bytehead — DISMISSED** [review]

**Review by m-vo — DISMISSED** [review]

**Comment by aschempp** [comment]
I don't understand what this element is supposed to be useful for, maybe you can explain?

**Comment by ausi** [comment]
> I don't understand what this element is supposed to be useful for, maybe you can explain?

https://github.com/contao/core-bundle/pull/1315#issuecomment-358484679

**Comment by fritzmg** [comment]
Personally I would put it into the `includes` category, as you "include" a template.

Will there also be a template module?

**Comment by ausi** [comment]
> Will there also be a template module?

Would make sense IMO. 
@contao/developers please vote 👍 👎

**Comment by aschempp** [comment]
> > I don't understand what this element is supposed to be useful for, maybe you can explain?
> 
> [contao/core-bundle#1315 (comment)](https://github.com/contao/core-bundle/pull/1315#issuecomment-358484679)

well that pull request was merged. The only thing "missing" was your mention of _a key value wizard_ that noone took up to in that PR 😅 .
I use HTML modules a lot since then, but what I meant was what would the key value wizard be useful for? If I want the user to enter data in the back end, I would create an content element for that (or use your awesome custom-elements extension). But having a key value wizard **without** knowing what keys/values are available seems counterintuitive to me.

**Comment by ausi** [comment]
> If I want the user to enter data in the back end, I would create an content element for that

The same could be said about the usage of the HTML element with custom templates. You could create a custom element for that instead too.

> what would the key value wizard be useful for?

Arbitrary data that the template can use however it wants.

**Comment by aschempp** [comment]
> > If I want the user to enter data in the back end, I would create an content element for that
> 
> The same could be said about the usage of the HTML element with custom templates. You could create a custom element for that instead too.

yes, thats exactly my point. The HTML element and this template element are functionally equal. Contrary to elements that have settings. The only difference I spot is the "arbitrary key/value wizard". Maybe you can give a real life example what this would be useful for? I honestly don't want people to start using a key value wizard and tell their customers to "fill this and that in" instead of using custom elements 🤷

**Comment by ausi** [comment]
> Will there also be a template module?

Done in 1fec68a5ace0ad42c0cdaeed9037b9236bccdea9

**Review by m-vo — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by fkaminski** [comment]
Based on the 4.13.0 RC1, the content element is called "**Eigenes Template**" in German.
As a module, this can then be found under "**Individuelles Template**".

Maybe the name should be consistent?

**Comment by m-vo** [comment]
Agreed, but that's not related to the code but the translations managed on Transifex.

**Comment by fritzmg** [comment]
> Agreed, but that's not related to the code but the translations managed on Transifex.

Translations issues should still be reported here, as there is no other way to do it. @fkaminski may be open a separate issue about this.

**Comment by fkaminski** [comment]
see #3950

**Pull request merged**
