### PR TITLE
Allow to set the min/max HTML5 attributes for text form field (contao/core-bundle#1622)

### PR DESCRIPTION
**Pull request by qzminski**
This is a feature pull request for contao/core-bundle#1622. It changes the current behaviour of `minlength/maxlength` and `minval/maxval` attributes the way that `min/max` HTML5 attributes will be added automatically if the field is a type of `number`.

I am not sure if the implementation is 100% safe and won't cause any side effects, so any feedback is very much welcome!

### CODE REVIEW

**Review by Toflar — APPROVED** [review]
This looks good to me 😄 Thanks for the contribution!

> I am not sure if the implementation is 100% safe and won't cause any side effects, so any feedback is very much welcome!

It'll be for 4.7 only anyway with all the beta and RC phases so I'm sure there will be enough testing.

**Comment by leofeyer** [comment]
Thank you @qzminski.

**Comment by bennyborn** [comment]
Regarding #437 you've added two new fields `minval` and `maxval` but we're still left with no `minlength` attribute in FormTextField at all. Any particular reason why this is still missing?

**Comment by leofeyer** [comment]
What exactly do you mean?

**Comment by bennyborn** [comment]
The original PR added `minlength` as an attribute to `FormTextField`

https://github.com/contao/contao/commit/f7a5ff7afcbda38b186db87ed47a5eff060c2ff4#diff-eaeb0e9e7d7f46221212395ad816c32bR70

Since you reverted that changes we're still left with an `FormTextField` that is incapable of having such an attribute.

**~~While I noticed that it does not work very well with all browsers it still~~ seems to be HTML5 spec (https://developer.mozilla.org/de/docs/Web/HTML/Element/Input#attr-minlength) and I'd be happy to see it back.

I'm currently implementing a form where a field needs to have a specific minimum length and at the moment I need to do some template magic to add `minlength` as an attribute.

** Needed support for MSIE so this wouldn't help me this time.

**Comment by ausi** [comment]
> While I noticed that it does not work very well with all browsers

Browser support should be pretty good I think: <https://caniuse.com/#feat=input-minlength>

**Comment by leofeyer** [comment]
Fixed in 4fc8fe8541eeb068177d04daf9c51938808c745b.

**Pull request merged**
