### PR TITLE
Correctly check if a "jump to" page is set when generating event feeds

### PR DESCRIPTION
**Pull request by leofeyer**

### CODE REVIEW

**Comment by fritzmg** [comment]
This was introduced in https://github.com/contao/contao/commit/94cb91f7bead5a0c3416667e988cac09ae56c165 - was this done automatically via CS fix or manually?

**Comment by leofeyer** [comment]
What difference does this make?

**Comment by fritzmg** [comment]
> What difference does this make?

If it was automatic through rector/csfixer, it would also need to be adjusted there, that's why I am asking.

**Comment by aschempp** [comment]
I don't think rector would refactor that, it must have been done manually.

**Comment by fritzmg** [comment]
I would assume so too, just making sure.

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Rector does not know about our `getRelated()` method, so this was a manual change indeed. I reviewed the entire PR again this morning but this remained the only error.

**Pull request merged**
