### PR TITLE
Prevent installing the Symfony framework bundle in version 6

### PR DESCRIPTION
**Pull request by leofeyer**
We must not install `symfony/framework-bundle` in version 6, otherwise there will be a fatal error:

```
PHP Fatal error:  Declaration of Contao\CoreBundle\Controller\AbstractController::getSubscribedServices() must be compatible with Symfony\Bundle\FrameworkBundle\Controller\AbstractController::getSubscribedServices(): array in vendor/contao/contao/core-bundle/src/Controller/AbstractController.php on line 28
```

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Comment by bytehead** [comment]
But in the end (4.13 release), things should be compatible with 5.4 or 6 at the same time, no?

**Comment by Toflar** [comment]
It's just CI, doesn't matter

**Comment by leofeyer** [comment]
> But in the end (4.13 release), things should be compatible with 5.4 or 6 at the same time, no?

We would have to ship two different versions of the class (and probably other classes as well) to be compatible with both Symfony 5 and 6. I doubt that we want that.

Contao 4.13 LTS is bound to Symfony 5.4 LTS. It will not work with Symfony 6.

**Comment by leofeyer** [comment]
Oh, and we cannot even ship two different versions of the class, because if we added the return type to our `AbstractController`, every child class in every extension would break. So we can only change this in Contao 5.

**Pull request merged**
