### PR TITLE
Remove the parameters.yml file from the skeleton

### LINKED ISSUE #6070: Remove skeleton/config/parameters.yaml
### Description

I think we should remove the https://github.com/contao/contao/blob/aec63b668f40584cd242dae658b02ec4badd6555/manager-bundle/skeleton/config/parameters.yaml file and the corresponding import in https://github.com/contao/contao/blob/aec63b668f40584cd242dae658b02ec4badd6555/manager-bundle/skeleton/config/config.yaml#L2 because we don’t use these parameters anymore AFAIK.

### PR DESCRIPTION
**Pull request by leofeyer**
Implements #6070

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

**Comment by aschempp** [comment]
This would remove the defaut kernel secret, are you sure this still allows the application to boot and generate the auto secret etc.?

**Comment by ausi** [comment]
> This would remove the defaut kernel secret

The `secret` from the parameters.yaml is not used anywhere, it does not define the `kernel.secret` parameter. (AFAIK)

**Comment by fritzmg** [comment]
> The `secret` from the parameters.yaml is not used anywhere, it does not define the `kernel.secret` parameter. (AFAIK)

It is still used. If you do not define `APP_SECRET`, then the `secret` parameter is used as a fallback: 

https://github.com/contao/contao/blob/74c56f07e14a1ce2e0fda81c50abb066c6b4a7fa/manager-bundle/src/ContaoManager/Plugin.php#L208-L210

Same goes for the database credentials. If you do not use `DATABASE_URL`, then the `database_*` parameters are used as a fallback.

**Review by ausi — COMMENTED** [review]
> The `secret` from the parameters.yaml is not used anywhere

I was wrong it seems. I thought I searched for all `getParameter('secret')` 🙈

**Comment by leofeyer** [comment]
We can probably replace `secret` with `kernel.secret` in  line 209?

The `database_*` parameters are fine IMHO, because we still want to support them in case someone has a `parameters.yml` file in their app.

**Comment by ausi** [comment]
> The `database_*` parameters are fine IMHO, because we still want to support them in case someone has a `parameters.yml` file in their app.

But we probably need to adjust the Plugin code to check for `hasParameter('database_…')` so that it does not fail without the defaults from the parameters.yaml

**Comment by fritzmg** [comment]
> We can probably replace `secret` with `kernel.secret` in line 209?

That won't work since that's just `%env(APP_SECRET)%`. That's why we set

```php
$container->setParameter('env(APP_SECRET)', $container->getParameter('secret'));
```

in order to have a fallback to the `secret` parameter.

**Comment by fritzmg** [comment]
While we could introduce `hasParameter` everywhere and thus implement the skeleton in PHP, we might as well just leave the parameters skeleton may be (and only remove it in Contao 6, where we will drop support for these parameters altogether).

**Comment by ausi** [comment]
> While we could introduce `hasParameter` everywhere and thus implement the skeleton in PHP, we might as well just leave the parameters skeleton may be

I’d prefer the `hasParameter()` checks as I find it very confusing that I have a paramter `%secret%` in all my projects that always has the value `ThisTokenIsNotSoSecretChangeIt`, even though my `%kernel.secret%` is set correctly. This is actually how I noticed that these obsolete parameters are still there.

**Comment by leofeyer** [comment]
> That won't work since that's just `%env(APP_SECRET)%`.

I see. Then maybe we should indeed leave everything as is and discuss this again for Contao 6.

**Review by fritzmg — APPROVED** [review]

**Pull request merged**
