### PR TITLE
Fix the line height of the ellipsis containers

### LINKED ISSUE #7424: Limited line height cuts off characters
### Affected version(s)

5.3.x

### Description

In Firefox, at certain zoom levels (and also likely depending on the font rendering, i.e. the OS) the characters might get cut off in the system log:

\
This does not happen in Contao 4.13, but I could not figure out why. The CSS seems (largely) the same.
The effect is more pronounced in 5.4+:

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #7424

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by zoglo** [comment]
@leofeyer
since we've been talking about the `colorize()` function to also make the ellipsis match the color...
It can actually be refactored as the Hook is just part of the default case and people add their own logic if none of our cases apply... so it's possible to get rid of the preg_replace ❤️ 

https://github.com/contao/contao/blob/6f8621763e8ceb29a667ee90c85f7f2428e629a6/core-bundle/contao/dca/tl_log.php#L141-L170

So we can just go like this, wdyt?
```php
public function colorize($row, $label)
{
    $class = 'ellipsis';
	
    switch ($row['action'])
    {
        case 'CONFIGURATION':
        case 'REPOSITORY':
            $class .= ' tl_blue';
            break;

        case 'CRON':
            $class .= ' tl_green';;
            break;

        case 'ERROR':
            $class .= ' tl_red';
            break;

        default:
            if (isset($GLOBALS['TL_HOOKS']['colorizeLogEntries']) && is_array($GLOBALS['TL_HOOKS']['colorizeLogEntries']))
            {
                foreach ($GLOBALS['TL_HOOKS']['colorizeLogEntries'] as $callback)
                {
                    $label = System::importStatic($callback[0])->{$callback[1]}($row, $label);
                }
            }
            break;
    }

    return sprintf('<div class="%s">%s</div>', $class, $label);
}
```

image

**Comment by leofeyer** [comment]
I had the same idea but additionally I would pass `$class` as third parameter to the hook. This way third-party extensions can use the feature, too:

```php
public function colorizeLogEntries(array $row, string $label, string &$class): string
{
    $class = 'orange';

    return $label;
}
```

I will adjust your PR accordingly and then merge it.

**Comment by fritzmg** [comment]
Just noticed this was only merged into 5.4, but it is a bug that also affects 5.3 - and 4.13:

**Comment by zoglo** [comment]
@fritzmg leo wanted to backport this afaik

**Pull request merged**
