### PR TITLE
Try to fix the Codecov status report

### PR DESCRIPTION
**Pull request by leofeyer**
Also see https://community.codecov.io/t/codecov-status-stuck-at-waiting-for-status-to-be-reported-on-github/341/28

### CODE REVIEW

**Comment by leofeyer** [comment]
Sadly, Codecov has not yet fixed the issue. 😢

**Comment by aschempp** [comment]
Can/should we just disable Codecov then? 🤷

**Comment by leofeyer** [comment]
We would need an alternative then and AFAIR, I have already tried the other services and they did not work with GitHub Actions, either. Although Codecov did work at the beginning. 🤷‍♂️

**Comment by leofeyer** [comment]
Turns out the problem was caused by `actions/checkout@v2`. 😮 

See https://community.codecov.io/t/codecov-status-stuck-at-waiting-for-status-to-be-reported-on-github/341/41

**Comment by m-vo** [comment]
Nice find!

**Pull request merged**
