### PR TITLE
Allow passing an array of IDs to User::isMemberOf()

### LINKED ISSUE #2753: Show protected pages only in sitemap for contao searchcrawler
**Affected version(s)**
Contao 4.11

**Description**
With the new dynamic sitemap-generator it should be possible to fix this old ticket (https://github.com/contao/contao/issues/1407)

**How to reproduce**

1. Set `index_protected:true` in `config.yml`
2. Set robots-tag to `noindex,follow`
3. set `Protect page`

The page would appear in public sitemap.xml, but should only appear for the contaocrawler.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2753
| Docs PR or issue | -

To fix #2753 (do not show protected pages in the sitemap if there is no front end user or the user groups do not match), I have adjusted the `User::isMemberOf()` method to also accept an array of group IDs. This allows us to greatly simplify other checks as well:

### Current

```php
$blnFeUserLoggedIn = System::getContainer()->get('contao.security.token_checker')->hasFrontendUser();

while ($objCalendar->next())
{
	if ($objCalendar->protected)
	{
		if (!$blnFeUserLoggedIn || !\is_array($this->User->groups))
		{
			continue;
		}

		$groups = StringUtil::deserialize($objCalendar->groups);

		if (empty($groups) || !\is_array($groups) || \count(array_intersect($groups, $this->User->groups)) < 1)
		{
			continue;
		}
	}

	// …
}
```

### New

```php
$user = null;

if (System::getContainer()->get('contao.security.token_checker')->hasFrontendUser())
{
	$user = FrontendUser::getInstance();
}

while ($objCalendar->next())
{
	if ($objCalendar->protected && (!$user || !$user->isMemberOf(StringUtil::deserialize($objCalendar->groups))))
	{
		continue;
	}

	// …
}
```

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Review by aschempp — CHANGES_REQUESTED** [review]
Shouldn't we have a security voter instead of a new ~static~ method?

**Comment by leofeyer** [comment]
Where do you see a new static method?

**Review by aschempp — APPROVED** [review]
Sorry, I didn't realize the `isMemberOf` method already exists 😆

**Review by ausi — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
Does this actually solve #2753? I don't see any changes regarding that, but I suppose I am missing something?

**Comment by leofeyer** [comment]
Yes, it does. The changes are in the `Backend` class.

**Pull request merged**
