### PR TITLE
Deprecate the User::isMemberOf() method

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes the first part of #4818.

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Comment by aschempp** [comment]
Are you aware the permission voter only works for the front end, but this method works for the back end user as well? Not sure if we ever use (or should use) it for backend though.

**Comment by leofeyer** [comment]
Good point. Should we revert the changes or add a voter that votes on back end groups?

**Comment by aschempp** [comment]
there is never a reason to vote on the back end groups. Imho we should just keep the method (remove the deprecation). _If_ we want to add a deprecation it should be done on the `FrontendUser` class (add a method with deprecation that runs the parent method).

**Comment by leofeyer** [comment]
> there is never a reason to vote on the back end groups.

Why not?

**Comment by aschempp** [comment]
Because for the back end, groups "generate" a set of permissions for modules, elements, alexf etc. There is never a permission on a group.

For the front end thats the opposite, because pages, articles, elements etc. are given permission to groups.

**Comment by leofeyer** [comment]
> There is never a permission on a group.

Maybe not in your installations, but we cannot know how the feature is used in the wild.

**Comment by ausi** [comment]
> For the front end thats the opposite, because pages, articles, elements etc. are given permission to groups.

Don’t we have the same for pages and articles in the backend in `tl_page.chmod`?

**Pull request merged**
