### PR TITLE
Allow rendering a figure inline from PHP templates

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes none
| Docs PR or issue | contao/docs#647

The idea behind this PR is that you can also render the `image.html5` or `figure.html.twig` (or your custom variants of those) inline from a PHP template. It's the counterpart of #1528.

```php
<!-- Default image.html5 template -->
<?php echo $this->figure('/path/to/image.png', '_my_size', ['enableLightBox' => true]); ?>

<!-- Custom PHP image template (using legacy strategy) -->
<?php echo $this->figure($this->uuid, 5, ['metaData' => new MetaData([MetaData::VALUE_ALT => 'foo'])], 'my_custom_image']); ?>

<!-- Custom Twig template -->
<?php echo $this->figure($this->id, [200, 200, 'crop'], '@ContaoCore/Image/Studio/figure.html.twig'); ?>
```

Todo:
* [x] Tests (somehow)
* [x] Find out what happens if a template function and a variable have the same name
* [x] Consider applying `Figure` options to legacy template as well (so that you can overwrite arbitrary values) &rarr; see #2071

### CODE REVIEW

**Comment by fritzmg** [comment]
Shouldn't we also support PHP templates (may be via a different method)? If someone adjusted their `image` template for example, they cannot use this function in their templates. I don't use twig templates in Contao projects at all, but as I said before I'd like to have a helper function similar to the one that RockSolid Custom Elements provides.

**Comment by m-vo** [comment]
> Shouldn't we also support PHP templates (may be via a different method)

I'm torn between yes and no. :upside_down_face: 
But ultimately I think if you really want to have inline rendering, then you should use the modern way.

We could perhaps auto detect the strategy based on the file extension (and maybe even default to `image.html5`) and then decide if we would use the legacy variant (see below) or the Twig variant. We would need to duplicate a bit of code from the Twig extension but I think that's ok in this case. Wdyt?

---
You could still do this in your code (and would even benefit from autocompletion), but I agree that it's not the nicest:

```php
System::getContainer()->get(Studio::class)
  ->createFigureBuilder()
  ->from('/path/to/image.png')
  ->enableLightBox()
  ->build()
  ->applyToTemplate($imageTemplate = new FrontendTemplate('image'));

echo $imageTemplate->render();
```

**Comment by fritzmg** [comment]
> You could still do this in your code

Yeah, that's the point, I don't want to do that. I mean I can of course implement my own template function in all our projects via the `parseTemplate` hook, regardless of what is decided here. I just think it would be more beneficial for most users, to do it the Contao way. And to me it does not make sense to have to modify _two_ templates, one twig template and one PHP template, in order to have consistent front end output.

> (and would even benefit from autocompletion)

My IDE wouldn't know, that `System::getContainer()->get(Studio::class)` returns a `Studio` 😁

**Comment by m-vo** [comment]
> My IDE

Well, *my* IDE...

**Comment by m-vo** [comment]
>  I just think it would be more beneficial for most users, to do it the Contao way

I guess you're right. Let me see what I can do.

Edit: Here you go: 10c0ebf225dcb576c14394c0fd6b396d77828027

**Comment by fritzmg** [comment]
> ```
> <?php echo $this->figure($this->uuid, ['metaData' => new MetaData([MetaData::VALUE_ALT => 'foo'])], 'my_custom_image.html5']); ?>
> ```

But isn't it still weird to suddenly have to to define the extension of your template? Everywhere else in Contao you _must not_ provide the extension.

In my opinion this should not be done with Twig at all. To me, how Twig might be used in the front end in the future of Contao is an entirely different topic.

**Comment by m-vo** [comment]
> But isn't it still weird to suddenly have to to define the extension of your template? Everywhere else in Contao you must not provide the extension.

I just got that wrong in the documentation: You only need to do this for the Twig variant (where the filename is part of the template name). Fixed in in the original description.

> In my opinion this should not be done with Twig at all. To me, how Twig might be used in the front end in the future of Contao is an entirely different topic.

I disagree on this. Contao already uses Twig for various things (e.g. backend / maintenance template) and it works just fine.

**Comment by fritzmg** [comment]
Another nitpick: in our projects at least, when we use such a functionality in a template (be it either via `Controller::addImageToTemplate` or the helper from RockSolid Custom Elements), we never want to output the original image, i.e. we always pass a size configuration. In my opinion the size should be a dedicated argument for ease of use.

```php
<?= $this->figure('path/to/image.png', '_my_image_size'); ?>
```

But may be I am alone in this ;). Having to use `['size' => […]]` every time is just a minor nuisance anyway.

**Comment by m-vo** [comment]
> we never want to output the original image, i.e. we always pass a size configuration. In my opinion the size should be a dedicated argument for ease of use. 

see 7f5a4361153bb4f7bc5a7860f51ff61d0969fef5

**Comment by m-vo** [comment]
>  Find out what happens if a template function and a variable have the same name

Regarding this: I wonder if we should call the function `contao_figure()` instead. This would be less likely to clash + would also be in line with the twig variant.

**Comment by fritzmg** [comment]
But it wouldn't be in line with the already existing `asset` and `trans` method 😁

**Comment by ausi** [comment]
> Find out what happens if a template function and a variable have the same name

This should be no problem IMO: https://3v4l.org/lWOKs

The only break it would cause is if someone did set a closure for `figure` and called it with `$this->figure()` which worked because of the `__call` magic.

**Comment by m-vo** [comment]
Tests are finally implemented, now. This should imo be ready to go.

**Comment by leofeyer** [comment]
The CS check says otherwise. 🙈

**Comment by m-vo** [comment]
Oops... :blush: Fixed in 6f423e33d6e3fef54ded2589e7257f799b63e26b.

**Review by ausi — DISMISSED** [review]

**Comment by m-vo** [comment]
This PR is imo ready to go.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
