### PR TITLE
Add the TokenDeauthenticatedListener

### LINKED ISSUE #475: Use DeauthenticatedEvent
https://github.com/symfony/symfony/pull/31138

Should we use this to delete all related `tl_remember_me` items?

### PR DESCRIPTION
**Pull request by bytehead**
Implements #475

### CODE REVIEW

**Comment by bytehead** [comment]
@contao/developers The question came up if this is more likely a bug than a feature, WDYT?

**Comment by leofeyer** [comment]
Bug

**Comment by leofeyer** [comment]
As discussed in the Contao call, this is ready to be merged.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
