### PR TITLE
Correctly handle array values in DCs

### PR DESCRIPTION
**Pull request by aschempp**
see https://github.com/contao/contao/pull/3867

### CODE REVIEW

**Review by bytehead — DISMISSED** [review]

**Review by leofeyer — CHANGES_REQUESTED** [review]
I'm not sure about this. We explicitly chose `(string) $varValue === ''` so `0` is handled correctly in PHP 8. This PR changes the behavior (see https://3v4l.org/E3WXe).

**Comment by aschempp** [comment]
Ok, but what's the point of converting the value at all then? `0 === ''` will be `false` the same as `(string) 0 === ''`. The only difference I could make out is that `(string) false === ''` is empty/true but `false === ''` is not. But `false` is not really a valid database value, or is it?

Also, shouldn't `0` be considered empty for an integer field anyway?

**Comment by fritzmg** [comment]
> But false is not really a valid database value, or is it?

It is, as it is equivalent to `0` for tinyint fields for example.

> Also, shouldn't 0 be considered empty for an integer field anyway?

Only if the field does not allow `null`.

**Comment by aschempp** [comment]
I've update the implementation to check if value is scalar first. The `empty()` check was wrong anyway since it also meant an empty array was empty (see https://3v4l.org/n30EQ)

**Review by leofeyer — COMMENTED** [review]
I think the new code works as expected. Let's wait for @ausi's review though.

**Review by ausi — APPROVED** [review]

**Pull request merged**
