### PR TITLE
Add a button to the "invalid request token" template

### LINKED ISSUE #6924: Veralteter Fehlertext bei "Ungültiges Anfrage-Token"
### Affected version(s)

5.3.0

### Description

Mir wurde heute eine Fehlermeldung angezeigt "Ungültiges Anfrage-Token".

Dabei ist mir aufgefallen, dass der Text etwas veraltet ist: "In Contao 2.10 wurde die Referer-Prüfung…"
siehe Screenshot.

Denke mal wir sollten in Contao 5 micht mehr auf eine Änderung unter Contao 2.10 hinweisen.
screen-20240222_t0ZD0UMl

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #6924

I don‘t know if we really need a button though.

### CODE REVIEW

**Comment by fritzmg** [comment]
I'd say why not.

However, I only just now noticed that we always called it an "authentication token", which is not really correct, is it? Should we rename it to "request token"?

**Comment by leofeyer** [comment]
Definitely. Renamed in 42840fdcbf9d6ecc1ec0d5043a29a57a23ec6907.

**Review by fritzmg — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by aschempp** [comment]
This only works if the POST request went to the same URL as e.g. the form was displayed, right?

**Comment by leofeyer** [comment]
No idea. I only changed the wording and the CSS, so everything still works the same as before.

**Pull request merged**
