### PR TITLE
Add a "title" attribute to the debug mode menu item

### PR DESCRIPTION
**Pull request by xchs**
This adds the missing `title` attribute for the debug mode menu item.

Unit tests are failing because my [test file](https://github.com/contao/contao/pull/1230/commits/63cf466c08bbb90f0d5f7c4db1b81dacaf5987e7) needs to be revised. Could someone help me with this?

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]

**Comment by leofeyer** [comment]
@xchs Can you please fix the failing CI checks? Otherwise I cannot merge the PR.

**Comment by xchs** [comment]
I'm afraid, but as I said above, I definitely need someone's help here. The unit tests are failing because my test file is currently practically useless! I already know what the purpose of the tests should be, but currently, for example, there is no test string for the title passed to the corresponding methods anywhere.

**Review by leofeyer — APPROVED** [review]

**Comment by xchs** [comment]
@leofeyer Thanks a lot for fixing the tests.

**Comment by leofeyer** [comment]
Thank you @xchs.

**Pull request merged**
