### PR TITLE
Allow to configure the components-dir

### PR DESCRIPTION
**Pull request by richardhj**
For every Contao project, you must configure the contao-component-dir in the composer.json.
For a long time I thought that this config allows you to determine where the assets are located _and_ loaded from.

```json
{
    "extra": {
        "contao-component-dir": "my-contao-assets"
    }
}
```

However, the Contao Core bundle is not using this config and hardcodes the assets directory to `/assets`.

Because I have the use case of modifying where to load the contao assets from, I propose the `contao.component_dir` config.

Currently, `/assets` collides with the default file structure of Symfony projects.

### CODE REVIEW

**Comment by m-vo** [comment]
Just a quick heads up: The plans for the virtual filesystem were to abandon the path related configs and replace them with mount points in the future. So we would probably also have an asset storage configured instead of a container config. Not sure how long this will take, though, and I agree, that we should address the inconsistency,

**Comment by ausi** [comment]
I think we should use the config from the *composer.json* file directly, same as we do with `contao.web_dir` in: https://github.com/contao/contao/blob/4034b234a11241e225c67ad86ee94dec0cbf690a/core-bundle/src/DependencyInjection/ContaoCoreExtension.php#L110

**Comment by richardhj** [comment]
> Just a quick heads up: The plans for the virtual filesystem were to abandon the path related configs and replace them with mount points in the future. So we would probably also have an asset storage configured instead of a container config. Not sure how long this will take, though, and I agree, that we should address the inconsistency,

Is the way paved for a virtual filesystem for assets? Since the Contao core consistently uses the Asset component for files in /asset, it should be a rather easy change, no?

**Comment by richardhj** [comment]
> I think we should use the config from the _composer.json_ file directly, same as we do with `contao.web_dir` in:
> 
> https://github.com/contao/contao/blob/4034b234a11241e225c67ad86ee94dec0cbf690a/core-bundle/src/DependencyInjection/ContaoCoreExtension.php#L110

happily addressed.

**Comment by aschempp** [comment]
I'm not sure why we need the component dir at all, shouldn't we use Symfony Assets for everything, which knows the path through the Composer packages? (Not saying that works everywhere already)

**Review by ausi — DISMISSED** [review]

**Review by fritzmg — DISMISSED** [review]

**Comment by richardhj** [comment]
> I'm not sure why we need the component dir at all, shouldn't we use Symfony Assets for everything, which knows the path through the Composer packages? (Not saying that works everywhere already)

So we would not copy the assets to /assets/. And we won't need the contao-component-installer.

Instead, we would make sure the files are symlinked to /public/vendor/contao-components/...
(for this to work, it must be a symfony-bundle, or the asset compiler pass must be tweaked)

Correct? Any downsides?

**Comment by aschempp** [comment]
I think we currently use `/assets` because there is still a lot of hardcoded stuff out there. What I meant was if the Core (and somewhen extensions) would all use Symfony Assets, you would be free to configure it in the composer.json to any path you like (which does not meant the default has to change).

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @richardhj.

**Pull request merged**
