### PR TITLE
Always show the "edit source" icon

### LINKED ISSUE #819: Verschobene Icons in Dateiverwaltung wenn Recht für Quelltexteditor fehlt
Im Backend werden die Icons normalerweise stets bündig angezeigt und für nicht aufrufbare Aktionen wird ein graues Icon dargestellt, um die bündige Darstellung zu wahren:

image

Wenn einem regulären Benutzer jedoch das Recht `Dateien im Quelltexteditor bearbeiten` in der Dateiverwaltung fehlt, wird das Icon zum Quelltexteditor gar nicht angezeigt und die übrigen Icons sind verschoben:

image

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #819

### CODE REVIEW

**Comment by aschempp** [comment]
Why would we show an icon if there is no active icon ever in the list? I think showing enabled & disabled only makes sense if there's one or the other available.

**Comment by leofeyer** [comment]
Please read the original ticket. Your question has already been answered there.

**Comment by aschempp** [comment]
I did read the original issue. If it's true that I can possibly edit files in subfolders but not some parent folders, then I'm fine with this change? But is that the case?

**Comment by leofeyer** [comment]
That is not the point. We have discussed whether to remove disabled icons or not in contao/contao#195 and since there was no clear majority in favor of it, we have decided to always show disabled icons. Therefore the issue is valid.

**Comment by ausi** [comment]
> … since there was no clear majority in favor of it, we have decided to always show disabled icons.

But wasn’t the poll only about the first part of the comment in https://github.com/contao/contao/issues/195#issuecomment-441044059 *„we should only show icons (operations) if they are functional“* but not about the second part *„Generally, if a user is not allowed to delete a record, they should not see the inactive delete button.“*?

**Comment by leofeyer** [comment]
No, the poll was about both parts IMHO. Otherwise, how would we handle the following case?



> if a user is not allowed to delete a record, they should not see the inactive delete button

To meet this requirement, we would have to remove the inactive delete buttons while keeping the active ones and while keeping the other inactive buttons. That does not make sense, does it?

**Comment by ausi** [comment]
> how would we handle the following case?

Your screenshot is correct IMO because the user is generally allowed to delete pages (but not for all of them). 

If a user has no right to „edit source“ generally we should not show the inactive button, but if the user is allowed to „edit source“ for some files we should show the button (active or inactive depending on the specific file then).

**Comment by leofeyer** [comment]
I'd be fine with this logic, too. We just need to agree on either one. 😄

**Comment by aschempp** [comment]
> If a user has no right to „edit source“ generally we should not show the inactive button, but if the user is allowed to „edit source“ for some files we should show the button (active or inactive depending on the specific file then).

That's exactly what I meant above as well 😆

**Pull request closed without merging**
