### PR TITLE
Use real path for `.env.local`

### LINKED ISSUE #6065: Contao replaces symlink to .env.local with regular file
### Affected version(s)

4.13

### Description

Contao auto-generates `APP_SECRET` env variable if it is not set or has default value (added in #5951 and #5066). However, if a Contao installation was deployed by Deployer, then `.env.local` is a symlink, because it is a shared file according to [Symfony Deployer recipe](https://github.com/deployphp/deployer/blob/ed28cb1cba33747f08ea7c14d6801cdde10fab97/recipe/symfony.php#L18-L20). In that case, Contao erases the symlink and recreates `.env.local` as a regular file.

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #6065

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]

**Comment by ausi** [comment]
Wouldn’t a better fix be to use `file_put_contents()` here instead of `dumpFile()`: https://github.com/contao/contao/blob/aec63b668f40584cd242dae658b02ec4badd6555/manager-bundle/src/Dotenv/DotenvDumper.php#L73

This should work in all cases then, even where `realpath()` would fail (like with missing access rights for parent directories).

**Comment by fritzmg** [comment]
I see, so the issue is that `Filesystem::dumpFile` first creates a temp file and then moves the temp file to the original location (which will be the symlink), rather than using `file_put_contents` directly.

idk, feels kind of weird to not use Symfony Filesystem.

**Comment by ausi** [comment]
> idk, feels kind of weird to not use Symfony Filesystem.

I think not using the `dumpFile()` method is correct here as we do not want to replace the file itself, but only want to replace its contents.
Sadly, Symfony filesystem does not offer a method that does what we want here.

**Comment by leofeyer** [comment]
> idk, feels kind of weird to not use Symfony Filesystem.

That‘s true, but @ausi has a good point when he says that `realpath()` might cause permission issues.

**Comment by leofeyer** [comment]
> Sadly, Symfony filesystem does not offer a method that does what we want here.

Probably because there is `file_put_contents()` already and it does not need to be abstracted or decorated. Symfony also uses `file_put_contents()` internally in their `Filesystem` class.

**Review by leofeyer — CHANGES_REQUESTED** [review]
As explained by @ausi in https://github.com/contao/contao/pull/6066#issuecomment-1556945847, we should use `file_put_contents()` instead of `Filesystem::dumpFile()`.

**Comment by fritzmg** [comment]
> Symfony also uses `file_put_contents()` internally in their `Filesystem` class.

Symfony Filesystem always uses PHP's native methods (`Filesystem::mkdir` uses `mkdir`, `Filesystem::exists` uses `file_exists`, `Filesystem::touch` uses `touch`, etc.), plus additional functionality and fail safes around them. Symfony Filesystem is supposed to be an abstraction for these - at least that's what I thought. It is disappointing that this case cannot be handled with Symfony Filesystem.

**Comment by leofeyer** [comment]
You are missing the general concept of the `Filesystem` class. It is not meant to abstract every possible native PHP function; it only decorates them if necessary. For instance, there is an `isReadable()` method, which additionally checks `PHP_MAXPATHLEN`, but there is no `read()` or `getContents()` method, because `file_get_contents()` works just fine.

**Review by ausi — DISMISSED** [review]

**Comment by fritzmg** [comment]
Yes, but then we can technically never use `Filesystem::dumpFile` as we cannot make the assumption that the target is not a symlink and thus we'll have to change all usages of `Filesystem::dumpFile`, not just this one. By not using `Filesystem::dumpFile` we also lose the `IOException`. Imho this is all something that should be improved in Symfony itself and for the time being we should use `realpath` together with `Filesystem::dumpFile`.

But it's just my humble opinion - so changed in the past few commits ;)

**Comment by fritzmg** [comment]
Not using `Filesystem::dumpFile` also causes the directories not being automatically created.

This PR is now reverted to its original state using `realpath()`. But I also added a test and also fixed `SetDotEnvCommand` in the same way.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Comment by ausi** [comment]
I think this should probably be fixed in Symfony itself: https://github.com/symfony/symfony/pull/50437

**Pull request merged**
