### PR TITLE
Remove the last username from the session after use

### LINKED ISSUE #1627: Failed login attempt in front end module login form starts session
**Affected version(s)**

Contao 4.9

**Description**

Even if a login attempt in the front end module ``login form`` fails, a session is started and the ``PHPSESSID`` cookie is set.

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1627

See https://github.com/contao/contao/issues/1627#issuecomment-669228176

### CODE REVIEW

**Comment by leofeyer** [comment]
I think the purpose of the "last username" feature is that when you log out and later go back to the login module, your username is already filled in. IIRC, this no longer works after merging this PR, does it?

**Comment by asaage** [comment]
> I think the purpose of the "last username" feature is that when you log out and later go back to the login module, your username is already filled in. IIRC, this no longer works after merging this PR, does it?

to mitigate that i'd recommend autocomplete attributes on the inputs anyway:
```html
<input type="text" name="username" id="username" class="text" value="" required="" autocomplete="username">
```
```html
<input type="password" name="password" id="password" class="text password" value="" required="" autocomplete="current-password">
```
This is something chrome always complains about and i added that to the login template.
Similar autocomplete values can be added to the personal-data module formfields.

**Comment by ausi** [comment]
> I think the purpose of the "last username" feature is that when you log out and later go back to the login module, your username is already filled in.

This does not work currently and I don’t think it is expected to work as Symfony removes the “last username” from the session as soon as your login was successful. See https://github.com/contao/contao/issues/1627#issuecomment-669155322

As far as I understand this feature, the “last username” is stored in the session so that if you mistype your password you don’t have to reenter your username for the second attempt.

**Comment by fritzmg** [comment]
> As far as I understand this feature, the “last username” is stored in the session so that if you mistype your password you don’t have to reenter your username for the second attempt.

That's what I thought as well 👍 I've never seen the other use-case work, nor would I find it useful. In fact I would consider that a security issue. If I log out of a website on a public machine, I don't want my username to linger around.

> to mitigate that i'd recommend autocomplete attributes on the inputs anyway:

Oh yes, and please let's do it for the Install Tool as well. Browsers always confuse the input fields of the create admin user form 🙃

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by leofeyer** [comment]
> to mitigate that i'd recommend autocomplete attributes on the inputs anyway:

@asaage Will you create a PR for that?

**Comment by asaage** [comment]
> @asaage Will you create a PR for that?

didn't know that there was already a ticket for this (https://github.com/contao/contao/issues/1669) 🤷‍♂️

**Comment by leofeyer** [comment]
Never mind, I did it myself: #2432

**Pull request merged**
