### PR TITLE
Greatly simplify the PhpStan configuration

### PR DESCRIPTION
**Pull request by leofeyer**
While trying to figure out #1940, I realized that we do not need `contao/phpstan` anymore in Contao 4.10.

### CODE REVIEW

**Comment by leofeyer** [comment]
Gotta figure out tomorrow where the app cache is built now. 😄

```
PHP Warning: file_get_contents(/home/runner/work/contao/contao/core-bundle/var/cache/phpstan/appContao_CoreBundle_Tests_Functional_app_AppKernelPhpstanDebugContainer.xml): failed to open stream: No such file or directory in /home/runner/work/contao/contao/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 27
Warning: file_get_contents(/home/runner/work/contao/contao/core-bundle/var/cache/phpstan/appContao_CoreBundle_Tests_Functional_app_AppKernelPhpstanDebugContainer.xml): failed to open stream: No such file or directory in /home/runner/work/contao/contao/vendor/phpstan/phpstan-symfony/src/Symfony/XmlServiceMapFactory.php on line 27
```

**Comment by leofeyer** [comment]
Hm, it even works fine without the `phpstan/phpstan-symfony` and `psalm/plugin-symfony` packages (see 8baf34f715d8f4f9f558c3ce8caffc128e0166e1). @bytehead What am I missing here?

**Comment by Toflar** [comment]
"it even works" === no errors but less checks ;-) `symfony/phpstan-symfony` checks for correct return types on certain stuff. See the README.

**Comment by bytehead** [comment]
No errors could also mean not everything got tracked (afair). Otherwise it would not make sense for PHPStan to care about an additional extension for Symfony.

**Comment by bytehead** [comment]
Same with 

> I realized that we do not need contao/phpstan anymore in Contao 4.10.

What's the exact reason for?

**Comment by leofeyer** [comment]
Is there a way to make PhpStan/Psalm show the number of tests run?

**Comment by leofeyer** [comment]
> > I realized that we do not need contao/phpstan anymore in Contao 4.10.
> 
> What's the exact reason for?

The `universalObjectCratesClasses` option renders the `BackendTemplateReflection` class redundant and IIRC, the Symfony extension now understands all the `*DynamicMethodReturnType*` stuff natively.

Not 100% sure what the `ServiceHelper` class does, though. 🙈

**Comment by bytehead** [comment]
I see, PHPStan got a lot better since our first steps with it 👍

**Comment by bytehead** [comment]
May we have to add it again if we gain higher levels. Let's see. Apart from this LGTM.

**Review by bytehead — APPROVED** [review]

**Pull request merged**
