### PR TITLE
[WIP] Add support for using config parameters to define forms

### PR DESCRIPTION
**Pull request by gmpf**
This provides the possibility to define forms in a config file like so:

```yaml
contao:
    form:
        contact:
            title: 'Contact'
            sendViaEmail: true
            format: 'email'
            subject: 'Contact via website form'
            fields:
                email:
                    type: 'text'
                    name: 'email'
                    label: 'Email'
                    mandatory: true
                    rgxp: 'email'
                subject:
                    type: 'text'
                    name: 'subject'
                    label: 'Subject'
                    mandatory: true
                message:
                    type: 'textarea'
                    name: 'message'
                    label: 'Message'
                    mandatory: true
                    size:
                        - 12
                        - 40
                submit:
                    type: 'submit'
                    slabel: 'Send'
```

## TODO
This is a working prototype, there's still some necessary work and checking left to do:
- Support in `Contao\Controller::getForm()`
- Validate config schema and mandatory fields
- Permissions
- Naming of and within Contao\Form\Config
- Tests
- Separately: Export/Import in Form Generator back end module?

### CODE REVIEW

**Comment by fritzmg** [comment]
Related: #402

**Comment by leofeyer** [comment]
I am not sure if this is something we want to support.

Our idea behind #537 was to enable users to add all layout related things to their Git repository, where they already have layout related things such as style sheets or scripts.

Forms, however, are part of the content, so this concept does not apply to them IMHO.

**Comment by aschempp** [comment]
I agree with @leofeyer, I don't see why I would create application content from the bundle configuration? If I ever had the need for a custom form, that would be in an extension or a custom module, and I usually used https://github.com/codefox/contao-haste for that.

**Comment by gmpf** [comment]
I suppose this was closed as a result of today's Mumble call. I hadn't abandoned the idea, but this PR was opened with quite unfortunate timing: Almost immediately after I opened it, things became extremely busy elsewhere and haven't stopped being busy to this day.

There were some points I wanted to make relating to the points raised in the replies here, but I haven't had the time and especially not the mental focus to formulate them in a concise and cogent manner. Maybe at some later point… :-/

**Comment by fritzmg** [comment]
Forms can be part of complex _functionality_ of a web application and thus aren't strictly just content.

**Pull request closed without merging**
