### PR TITLE
Commit the composer.lock files of the tools

### PR DESCRIPTION
**Pull request by leofeyer**
As discussed with @Toflar, this should prevent the CI chain from suddenly failing if one of the tools releases a new version.

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]
do we need a way to make sure these are kept up to date? Like a weekly/montly CI ?

**Comment by Toflar** [comment]
I agree with @aschempp. It's great to lock the tools to a certain version so we don't have failing PRs all the time. However, we should ensure to run updates on them from time to time because the updates also come with better code quality for us :)

**Comment by m-vo** [comment]
> Like a weekly/montly CI ?

This would basically need a periodic job that mirrors the current CI but just runs `update` instead of `install`, right?

```diff
-   composer bin ecs install --no-interaction --no-progress
+   composer bin ecs update --no-interaction --no-progress

[…]
```

IMHO this could replace the current schedule to save resources.

**Comment by leofeyer** [comment]
I have added a cronjob that runs the CS job with updated dependencies. I have also removed the composer.lock file of the monorepo-tools, because we control the package ourselves.

**Review by bytehead — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Review by m-vo — APPROVED** [review]

**Pull request merged**
