### PR TITLE
Added new operation to tree view

### LINKED ISSUE #6711: Add a 'new'-Button to icon block
### Description

From a usability perspective, it would be nice if the 'NEW' icon or 'NEW' button for articles and page structure in the backend could find its way into the icon block.

backend-01
backend-02

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/6711

### CODE REVIEW

**Review by fritzmg — COMMENTED** [review]
The articles view is still missing the new button on the parent node though:

**Comment by aschempp** [comment]
There are no buttons on the parent node?

**Comment by fritzmg** [comment]
That's part of the feature request. Otherwise you would not be able to insert an article on the first position within a page. Only on the second position or higher.

**Comment by aschempp** [comment]
ah, right. I would have confused this to add a new page, but adding a new article at the top obviously makes sense. Could be a little harder to add though 😬

**Comment by fritzmg** [comment]
> Could be a little harder to add though 😬

I know 😁

**Comment by aschempp** [comment]
not _that_ hard though 😆 
added in 89bbf0d7687fa9f6c3deba0dca75af23de3ec50c

**Review by leofeyer — CHANGES_REQUESTED** [review]
That doesn‘t quite work yet.

1. In the site structure, the button only adds the option to "paste after" a site. What about "paste into"?

2. In the article view, there is a "paste into" button, however, it says _create new element after element_ which is incorrect.



Maybe we can add a button with a slide-out menu to choose between "after" and "into"?

**Comment by aschempp** [comment]
after or into only applies to the page tree then. Maybe we only add this to articles for now?

**Comment by leofeyer** [comment]
As discussed in the Contao call, we could add a right-click context menu that has additional buttons such as "new into" and "new after". It could also have options such as "add new child elements" similar to what Slack does:

**Pull request closed without merging**
