### PR TITLE
Fix the Doctrine platform recognition

### LINKED ISSUE #979: Database queries are not removed in Install Tool after execution
**Affected version(s)**
Contao 4.8.5 (maybe also 4.8.4, 4.8.3, 4.8.2, 4.8.1, 4,8,0)
PHP 7.3.11
MariaDB 10.3

**Description**  
The database commands "Alter Table..." remain in the Install Tool after execution. They can be executed several times. The table changes are executed as you can see in phpMyAdmin but not removed from install tool: If you execute the commands in phpMyAdmin (individually), you get an empty feedback.

**How to reproduce**
- Install Contao with Contao Manager
- run install tool
- press "update database"

### PR DESCRIPTION
**Pull request by leofeyer**
The logic of the `ParametersYamlPass` needs to be run before the `Plugin::addDefaultServerVersion()` method, otherwise the DB connection always fails and our `'server_version' => '5.5'` workaround will always be applied. This breaks the Doctrine platform recognition (see #979).

### CODE REVIEW

**Comment by aschempp** [comment]
What if we don't add the `server_version`?

**Comment by Toflar** [comment]
LGTM but why is that 4.9?

**Comment by leofeyer** [comment]
> What if we don't add the `server_version`=

Then we would have the problem described in https://github.com/contao/core-bundle/issues/1422 again. 😉 

> LGTM but why is that 4.9?

Because the `ParametersYamlPass` (and support for `env(DATABASE_URL)`) has only been added in Contao 4.9.

**Comment by m-vo** [comment]
But the referenced issue in #979 that this PR aims to fix occurs on Contao 4.8.5?

**Comment by leofeyer** [comment]
See https://github.com/contao/contao/issues/979#issuecomment-557469485

**Review by bytehead — APPROVED** [review]

**Pull request merged**
