### PR TITLE
Convert functional test SQL to YAML

### PR DESCRIPTION
**Pull request by aschempp**
requires https://github.com/contao/test-case/pull/5

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]
I wonder why we need news archive data for the existing tests but maybe that can be removed.
But not strictly related to this PR as that seems to be the migration only for now, so I'm approving.

**Review by leofeyer — CHANGES_REQUESTED** [review]
You should also adjust the `.github/workflows/ci.yml` file, which still tries to import the `contao_test.sql` dump. Also, we might need to raise the Composer requirement for `contao/test-case` to fix the prefer-lowest tests.

**Comment by aschempp** [comment]
> You should also adjust the .github/workflows/ci.yml file, which still tries to import the contao_test.sql dump. 

I can't find that, and it wouldn't make sense anyway? The SQL dump is/was loaded by the test case?

> Also, we might need to raise the Composer requirement for contao/test-case to fix the prefer-lowest tests.

Absolutely, but the new branch is not tagged. It should probably be v5 as it's a BC-break from the old implementation?

**Comment by leofeyer** [comment]
> I can't find that, and it wouldn't make sense anyway? The SQL dump is/was loaded by the test case?

True, we had already changed that.

> > Also, we might need to raise the Composer requirement for contao/test-case to fix the prefer-lowest tests.
> 
> Absolutely, but the new branch is not tagged. It should probably be v5 as it's a BC-break from the old implementation?

It should be enough to require `"contao/test-case": "^4.1"` in our composer.json.

**Comment by aschempp** [comment]
> It should be enough to require "contao/test-case": "^4.1" in our composer.json.

I don't think so? The base 4.1 version (from last week) does not contain my "bug fix"?

**Comment by leofeyer** [comment]
Yes, it does: https://github.com/contao/test-case/releases

**Review by leofeyer — APPROVED** [review]

**Pull request merged**
