### PR TITLE
Adding the option `data-only` to the backup create command, to onyl export the data

### PR DESCRIPTION
**Pull request by cliffparnitzky**
To have the option to onyl export the data, a new option for the backup create command is added.

### CODE REVIEW

**Comment by Toflar** [comment]
I don't really see the point of creating a backup without the schema. But I'm not against it either, however, the target branch for features has to be 5.x :)

**Comment by cliffparnitzky** [comment]
@Toflar The idea was born when maintaining the official demo. The exported SQL only contains the data. With this command, maintaining will be a little bit easier ;-).

**Comment by aschempp** [comment]
> The idea was born when maintaining the official demo. 

Instead of adding this for Contao 5, we should adjust our SQL import to also import schema data! This is always a PITA for a demo, because the SQL import needs to match the database structure. This would no longer be the case if we lift the restriction 🙃

**Comment by leofeyer** [comment]
As discussed in the Contao call, we do not want to add this feature because maintaining SQL dumps for themes is not what the feature was designed for.

**Pull request closed without merging**
