### PR TITLE
Always break out of Turbo frames when missing

### LINKED ISSUE #7501: Turbo X Non-OK responses
### Affected version(s)

5.4.1

### Description

When the edit operation results in a 500 response (in my case, a non-up-to-date database), the site shows "Content missing".
Screenshot 2024-09-02 at 22 04 54
Screenshot 2024-09-02 at 22 04 52

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #7501

In case a general error happens, the original `<turbo-frame>` will be missing on the error page when submitting an edit form. Turbo allows you to hook into this behavior via the [`turbo:frame-missing`](https://turbo.hotwired.dev/reference/events#turbo%3Aframe-missing) event. This PR fixes this by always breaking out of the frame when missing - which should be fine for our purposes in the back end.

### CODE REVIEW

**Comment by leofeyer** [comment]
Smart solution 🦊

**Review by m-vo — APPROVED** [review]
I'm not sure I like the behavior when developing new stuff but it's a clever solution for the typical scenarios and easy to disable if needed. :+1:

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Comment by fritzmg** [comment]
> I'm not sure I like the behavior when developing new stuff

Yes, that's why I added the warning instead. We could also change it to only show the warning when running watch, if need be.

**Pull request merged**
