### PR TITLE
Handle session being null in System::getReferer

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | -
| Docs PR or issue | -

Yet another array access problem notable with PHP8: in case `$session` is `null`, we should not try to access `$session['current']` / `$session['last']`…

### CODE REVIEW

**Comment by m-vo** [comment]
Failing test seems unrelated.

**Review by ausi — DISMISSED** [review]

**Comment by leofeyer** [comment]
How do I reproduce this? Because `$session` should never be `null` at this point.

**Comment by m-vo** [comment]
This happened when I had a BE page open in the browser and - after the session had expired for a while - I started working at it again. IIRC this error happened after the redirect from the login page.

**Comment by leofeyer** [comment]
Does the issue occur in Contao 4.9 as well?

**Comment by m-vo** [comment]
Likely, but it will only be noticed with PHP8 + default error reporting level.

**Comment by leofeyer** [comment]
Then we should fix it in Contao 4.9.

**Comment by m-vo** [comment]
It's rebased onto 4.9, now. 

I'm not sure what the failing tests are trying to tell me or if they are all unrelated.

**Review by ausi — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
