### PR TITLE
Enable the PhpdocTypesOrderFixer again

### PR DESCRIPTION
**Pull request by driftingly**
This can be enabled now that https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6243 has been merged.

Originally added [here](https://github.com/contao/contao/commit/4849881532595317a5c8ef7b99a9677b88f08ebf#diff-a95817c1c2b59c07bf78b5c0565bdf836c7459dee80a13573ae1689c04440040).

I originally created PR https://github.com/contao/contao/pull/4392 but couldn't seem to switch the base branch.

### CODE REVIEW

**Comment by m-vo** [comment]
> I originally created PR https://github.com/contao/contao/pull/4392 but couldn't seem to switch the base branch.

You can do this by clicking `Edit` near the title and then picking a branch from the select menu.

**Comment by driftingly** [comment]
When I did that the PR ended up having like 520 commits and a couple conflicts 🤷

**Comment by m-vo** [comment]
> When I did that the PR ended up having like 520 commits and a couple conflicts shrug

 That is expected as you based your commits onto the wrong branch then. To fix, you need to rebase your local branch.

E.g. run `git rebase <old-target-branch> --onto=<new-target-branch>` and then force push.

**Comment by driftingly** [comment]
Ah, thanks!

**Comment by m-vo** [comment]
The PHP-CS-Fixer version needs to be bumped to 3.6.0 as well. Currently it's a transitive dependency of ECS, so we either need to add it to make it a hard one or update to a version of ECS that requires it as well before this can be merged.

**Comment by ausi** [comment]
Updated ecs in 05cc6c6c940605754c4f830e25ae852f24fe1b41

**Review by ausi — APPROVED** [review]

**Review by m-vo — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @driftingly.

**Pull request merged**
