### PR TITLE
Unescape parameters in the installation bundle

### LINKED ISSUE #979: Database queries are not removed in Install Tool after execution
**Affected version(s)**
Contao 4.8.5 (maybe also 4.8.4, 4.8.3, 4.8.2, 4.8.1, 4,8,0)
PHP 7.3.11
MariaDB 10.3

**Description**  
The database commands "Alter Table..." remain in the Install Tool after execution. They can be executed several times. The table changes are executed as you can see in phpMyAdmin but not removed from install tool: If you execute the commands in phpMyAdmin (individually), you get an empty feedback.

**How to reproduce**
- Install Contao with Contao Manager
- run install tool
- press "update database"

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #979

### CODE REVIEW

**Review by bytehead — DISMISSED** [review]

**Review by Toflar — CHANGES_REQUESTED** [review]
Seems pretty important to me so I'd say it deserves a unit test 😊

**Review by ausi — DISMISSED** [review]

**Comment by leofeyer** [comment]
@Toflar Turns out we cannot unit test this, because the `Plugin` class does not use DI and I cannot mock the `DriverManager::getConnection()` call.

**Comment by Toflar** [comment]
And what do you want to tell me now? 😄 We should find a way to make it testable then. Maybe you could pass a mock class using the `driverClass` option? Wdyt?

**Review by aschempp — CHANGES_REQUESTED** [review]
As discussed, we should use `$container->resolveEnvPlaceholder(…, true)`

**Comment by leofeyer** [comment]
Changed in 6a670d7fe6655fc998df8ef4fe08ced7912d43b7. Now the code also works with a DATABASE_URL environment variable.

**Review by Toflar — DISMISSED** [review]
Smartass :) It's a bit hacky but it's a very welcome unit test and serves the purpose. Nice one!

**Review by aschempp — CHANGES_REQUESTED** [review]
Unit-testing internal methods is **always** wrong. `DriverManager::getConnection` is already a factory, so that's **very** easy to mock!

```
public function __constructor($connectionFactory = [DriverManager::class, 'getConnection']);

$connection = call_user_func($connectionFactory, $params);
```

**Review by aschempp — DISMISSED** [review]
I have updated the PR accordingly 😎

**Review by Toflar — DISMISSED** [review]

**Comment by leofeyer** [comment]
I am against these changes. The unit test is supposed to test the parameter resolving, not the database connection. There is absolutely no need to inject a dependency here, especially since it is only used in the unit tests.

**Review by Toflar — APPROVED** [review]
'- ignore -

**Review by Toflar — CHANGES_REQUESTED** [review]
Injecting the connection factory is correct. And if code adjustments are needed for unit tests it means that the class did not follow software architecture best practices before. That's clearly the case here.

**Comment by leofeyer** [comment]
Ok, you know what? We have 54 open issues for Contao 4.9 and only three weeks left to close them. I have more important things to do than to nitpick about an unimportant unit test. I am going to release Contao 4.8 without the fix and we can discuss this in January then. 🤷‍♂

**Comment by aschempp** [comment]
Your unit test is covering 9% of the file. It tests that the parameters are correctly resolved. But it does not test that that's related to passing the extension configuration, or that the database is correctly initialized.

leofeyer

My tests cover 19% of the file, including the DB connection. What's still missing is the extension handling, we should add another test to check if the return value is correct and that it returns version 5.5 on exception. Adding that test will not be possible with your unit test approach.
aschempp

**Comment by leofeyer** [comment]
Of course your tests covers more than mine, because you are now adding tests for previously uncovered stuff (such as the DB connection). 🤦‍♂ 

My unit test only tests exactly what has been changed in this PR.

I agree that we should add tests for the uncovered stuff. There are probably other uncovered methods, too. But please do this in a separate PR instead of highjacking this one.

**Review by Toflar — APPROVED** [review]
Neat! Thank you!

**Pull request merged**
