### PR TITLE
Require at least version 3.0 of webignition/robots-txt-file

### PR DESCRIPTION
**Pull request by leofeyer**
See https://github.com/webignition/robots-txt-file/issues/15

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

**Comment by ausi** [comment]
We could add support for 3.0 too: `^2.1.1 || ^3.0`.
Or should we upgrade to `^3.0` straight away?

**Comment by leofeyer** [comment]
We should definitely upgrade to version 3. I will adjust the PR accordingly.

**Comment by leofeyer** [comment]
It seems that @Toflar needs to allow version 3 in https://github.com/terminal42/escargot/blob/master/composer.json#L28 first. 😁

**Comment by Toflar** [comment]
Yes, there are already newer versions of Escargot. We need to merge the still remaining open PR's first so I can clean up the integration in Contao and bring everything to the latest version.

**Comment by Toflar** [comment]
Escargot is ready. Once #1057 and #1068 are merged, I'll provide a PR cleaning up namespaces (should be `Crawl` instead of `Search`) and adjusting everything to the latest Escargot 0.4 changes.

**Review by aschempp — COMMENTED** [review]
> It seems that @Toflar needs to allow version 3 in https://github.com/terminal42/escargot/blob/master/composer.json#L28 first. 😁

That's not needed *first*, Composer just won't install v3 until Escargot supports it. But if Contao is compatible with v3, we can still allow it in the composer.json

**Comment by leofeyer** [comment]
To make this work, I also had to raise the constraint for `terminal42/escargot` from `^0.3` to `^0.4`. @Toflar Is this change ok?

**Comment by Toflar** [comment]
> Escargot is ready. Once #1057 and #1068 are merged, I'll provide a PR cleaning up namespaces (should be `Crawl` instead of `Search`) and adjusting everything to the latest Escargot 0.4 changes.

I will do all the necessary changes once we have the back end implementation merged. I'll also give https://github.com/contao/contao/issues/1152 a shot in the same run.
But when I do this before the BE implementation is merged, that one has to be rebased quite a bit and I don't want to do that again :)

**Comment by Toflar** [comment]
Closing in favor of https://github.com/contao/contao/pull/1171.

**Pull request closed without merging**
