### PR TITLE
Set login constants in request listener

### PR DESCRIPTION
**Pull request by fritzmg**
#4968 + #5130 for Contao 4.13

### CODE REVIEW

**Comment by fritzmg** [comment]
The reason why the functional tests fail is the following:

1. When the functional tests are set up, our `DcaSchemaProvider` will initialize the `ContaoFramework` (see [1]) when loading fixtures.
2. However, this is done before there is a request in the request stack. Thus in our current logic the `ContaoFramework` will also already set the constants to `false`.
3. Later on in the functional test a request is pushed to the request stack and processed. Now our `LegacyLoginConstantsListener` wants to set the constants _again_, leading to an error.

[1]

```
contao\core-bundle\src\Framework\ContaoFramework.php:220
contao\core-bundle\src\Framework\ContaoFramework.php:121
contao\core-bundle\src\Doctrine\Schema\DcaSchemaProvider.php:317
contao\core-bundle\src\Doctrine\Schema\DcaSchemaProvider.php:58
contao\core-bundle\src\EventListener\DoctrineSchemaListener.php:35
contao\vendor\symfony\doctrine-bridge\ContainerAwareEventManager.php:68
contao\vendor\doctrine\orm\lib\Doctrine\ORM\Tools\SchemaTool.php:408
contao\vendor\doctrine\orm\lib\Doctrine\ORM\Tools\SchemaTool.php:115
contao\vendor\doctrine\orm\lib\Doctrine\ORM\Tools\SchemaTool.php:93
contao\test-case\src\FunctionalTestCase.php:138
contao\test-case\src\FunctionalTestCase.php:35
contao\core-bundle\tests\Functional\PageControllerTest.php:102
contao\core-bundle\tests\Functional\PageControllerTest.php:57
```

Now the question is how do we handle this. Checking whether the constants have already been set within `ContaoFramework::setLoginConstants` would fix the tests. However, this would not technically be correct as our functional tests would now potentially have the wrong value defined for these constants when the request is processed. On the other hand our functional tests do not really need these constants and in the real world a setup like this would never happen anyway. Besides, it would just be a known limitation of these legacy constants.

Thus for simplicity I would opt for checking whether the constants have already been defined.

**Review by aschempp — DISMISSED** [review]
LGTM. Yes we should check the constants anyway because one could reset the framework (or create a second instance like in tests).

**Comment by leofeyer** [comment]
> and in the real world a setup like this would never happen anyway.

Can we be sure about that?

> However, this is done before there is a request in the request stack.

Can we not define the constants if there is no request?

**Comment by fritzmg** [comment]
> Can we not define the constants if there is no request?

Then they would never be defined if there never is a request (e.g. on the command line).

**Comment by leofeyer** [comment]
But as you said, _this would not technically be correct as our functional tests would now potentially have the wrong value defined for these constants when the request is processed_. Do we really want to merge this? @contao/developers /cc

**Comment by ausi** [comment]
I think if we have functional tests that rely on the values of those constants they would need to run in a seperate process anyway. I think this should be merged.

**Review by ausi — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
