### PR TITLE
Added |blank flag to open links in new window

### PR DESCRIPTION
**Pull request by aschempp**
This allows to generate a link that opens in a new window

`{{link::123|blank}}` => `<a href="alias-123.html" target="_blank" …>`

### CODE REVIEW

**Comment by ausi** [comment]
Why using an insert tag flag for that? This seems to be against the insert tags concept IMO. `{{link::123::blank}}` would fit better to how the other insert tags work.

And is this not already possible by using `<a href="{{link_url::123}}" target="_blank">` ?

**Comment by leofeyer** [comment]
I'm not sure if that is a use-case that we have to support, but @fritzmg sure has a point here.

**Comment by aschempp** [comment]
My use case is using an insert tag where HTML is not supported. My most used case is a legal checkbox in a form, where I want to link to the legal page in a checkbox label.

**Comment by fritzmg** [comment]
To clarify: an _additional_ flag or attribute for the `{{link::*}}` insert tag is fine - I just meant it cannot be the only way. And I agree with this use case. This also works with `{{link_open::*}}`, correct? (that's were we would need it more often).

**Comment by ausi** [comment]
> `{{link::123::blank}}` would fit better to how the other insert tags work.

Suggested alternative: https://github.com/aschempp/contao/pull/7

**Comment by aschempp** [comment]
I disagree. In your concept, how would I create an absolute URL that opens in a new window? `{{link::42|absolute|blank}}` is exactly right and the order of flags does not matter.

**Comment by ausi** [comment]
> how would I create an absolute URL that opens in a new window?

`{{link::42::absolute::blank}}` or `{{link::42::blank::absolute}}`

**Comment by leofeyer** [comment]
I think we have decided against the `{{tag::value::value::value}}` syntax in favor of `{{tag::value?more=values}}` syntax, so this should either be `{{link::42|absolute|blank}}` or `{{link::42?target=blank|absolute}}`, shouldn't it?

**Comment by fritzmg** [comment]
> I think we have decided against the `{{tag::value::value::value}}` syntax in favor of `{{tag::value?more=values}}` syntax, so this should either be `{{link::42|absolute|blank}}` or `{{link::42?target=blank|absolute}}`, shouldn't it?

We already have `{{trans::*::*::*}}`, `{{asset::*::*}}`, `{{format_date::*::*}}` and `{{convert_date::*::*::*}}`.

**Comment by ausi** [comment]
> in favor of `{{tag::value?more=values}}` syntax,

This is not possible in this case I think because the url itself could already use `?` like `{{link::https://example.com/?query=foo::blank}}`

**Comment by aschempp** [comment]
> > I think we have decided against the `{{tag::value::value::value}}` syntax in favor of `{{tag::value?more=values}}` syntax, so this should either be `{{link::42|absolute|blank}}` or `{{link::42?target=blank|absolute}}`, shouldn't it?
> 
> We already have `{{trans::*::*::*}}`, `{{asset::*::*}}`, `{{format_date::*::*}}` and `{{convert_date::*::*::*}}`.

Yes, but these are value arguments to the insert tag. Flags are boolean, these values are not.

**Comment by ausi** [comment]
> Flags are boolean, these values are not.

What kind of boolen is `|nl2br` or `|strtolower`? Nearly all of them are functions (exception the cache related ones) and are executed in the specified order. They could even take arguments and it would fit the concept imo like `specialchars(double_encode)`, although no one does that currenty AFAIK.

**Comment by aschempp** [comment]
I'm sorry I did mean _flags can be boolean_ 😅 

> They could even take arguments and it would fit the concept imo like specialchars(double_encode), although no one does that currenty AFAIK.

I thought about adding that multiple times, but that's not supported atm.

**Comment by ausi** [comment]
> I did mean _flags can be boolean_ 😅

Not according to our own documentation: _“With flags, you can process insert tags further.”_

**Comment by leofeyer** [comment]
As discussed in Mumble on July 29th, we want to implement `{{link::123::blank}}`.

**Comment by ausi** [comment]
Closed in favor of #3230

**Pull request closed without merging**
