### PR TITLE
Use schema.org JSON-LD in the breadcrumb module

### PR DESCRIPTION
**Pull request by Toflar**
Not sure if people need to be able to change this in the template at all...we could also just add this data in `ModuleBreadcrumb`. Wdyt @contao/developers?

### CODE REVIEW

**Comment by fritzmg** [comment]
If we allow it I would go the same route as in the other places, i.e. provide a `getBasicSchemaOrgData` function instead of building the array directly in the template.

**Comment by Toflar** [comment]
Ah right, yes. Let's do that then.

**Comment by Toflar** [comment]
Done :) Not sure about the coding style here (I thought we're using the old array notation in old modules) but the CS fixer does not require any changes? @leofeyer?

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
