### PR TITLE
Correctly handle numeric paths

### LINKED ISSUE #5613: Cannot use folder names that consist of integers only in new DBAFS
### Affected version(s)

`4.13.*, 5.*`

### Description

If you use a folder that consists of just numbers e.g. a date `20221228`, you'll run into a sync issue:

```
TypeError:
basename(): Argument #1 ($path) must be of type string, int given

  at vendor/contao/core-bundle/src/Filesystem/Dbafs/Dbafs.php:340
  at basename(20221228)
     (vendor/contao/core-bundle/src/Filesystem/Dbafs/Dbafs.php:340)
  at Contao\CoreBundle\Filesystem\Dbafs\Dbafs->doComputeChangeSet(array(1), array('1a41cd8b8c96776309ac157678f86971', '20221228/9831d3c5-afe9-4df6-8e5e-6038c9a252b9' => '60d15be816eafb767c0f27e1ff6f9b19'), array(0, '20221228/9831d3c5-afe9-4df6-8e5e-6038c9a252b9' => 0), object(Generator), array('20221228/62390ab3-aa51-4c7a-bd1c-806292f4d30d'))
     (vendor/contao/core-bundle/src/Filesystem/Dbafs/Dbafs.php:206)
  at Contao\CoreBundle\Filesystem\Dbafs\Dbafs->sync('20221228/62390ab3-aa51-4c7a-bd1c-806292f4d30d')
     (vendor/contao/core-bundle/src/Filesystem/Dbafs/DbafsManager.php:273)
  at Contao\CoreBundle\Filesystem\Dbafs\DbafsManager->sync('notification_center/bulky_items/20221228/62390ab3-aa51-4c7a-bd1c-806292f4d30d')
     (vendor/contao/core-bundle/src/Filesystem/VirtualFilesystem.php:102)
```

I think this is due to PHP handling array keys that are numeric as integers. This is a bit too deep in the VFS implementation so I'd like to have @m-vo have a look at it 😇  

I guess nobody noticed that just yet because the file manager still uses the old DBAFS implementation.

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #5613 

This PR fixes a problem that is induced by PHP's very weird behavior of int-casting array keys that look like numeric strings (see https://3v4l.org/Spmcf). 

The fix consists of two parts: One being string casts in the internal code (`Dbafs` and `ChangeSet`) to work around the problem and two being a change to the `ChangeSet` API. With this change, you are now getting lists of objects instead of arrays with special keys. This is already an improvement but it also guarantees valid types when iterating and without the consumer needing to cast values:

```php
// before
foreach($changeSet->getItemsToUpdate() as $existingPath => $data) {
    // $existingPath could be an integer!
    $hash = $data[ChangeSet::ATTR_HASH];
    // …
}

// now
foreach($changeSet->getItemsToUpdate() as $item) {
    $existingPath = $item->getExistingPath(); // always a string
    $hash = $item->getHash();
    // …
}
```

I had to change some things API wise (everything marked `@experimental`) but I would consider the impact to be low as you wouldn't typically use these things in your own code (at least at the current point in time).

### CODE REVIEW

**Comment by m-vo** [comment]
@leofeyer Please ping me should there be a problem merging this PR upstream, I'll provide a separate PR in this case.

**Comment by Toflar** [comment]
Where exactly do we have tests with numeric-only paths now? :)

**Comment by m-vo** [comment]
There is a `testHandlesNumericKeys()` in the `ChangeSetTest` now. But we could also add one for the Dbafs class or the VFS integration tests.

**Comment by m-vo** [comment]
I slightly tweaked one of the existing integration tests, so that numeric paths are also covered in f54081769977cf1d4f4fb353255e1e4708618ddc.

**Review by Toflar — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Comment by leofeyer** [comment]
> @leofeyer Please ping me should there be a problem merging this PR upstream, I'll provide a separate PR in this case.

The merge PR is here: https://github.com/contao/contao/pull/5623/files

**Pull request merged**
