### PR TITLE
Disable widgets for configured settings

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/4868

It looks like Chosen does not support disabling a select menu. I decided to fix this only in Contao 4.13 because we only disable settings there. Patching Chosen seems out of scope to me for now.

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

**Comment by fritzmg** [comment]
> I decided to fix this only in Contao 4.13 because we only disable settings there.

This should be fixed in Contao 4.9 as well, as _any_ widget can be set to `readonly => true`. Also `select` with `chosen` are not the only widget where `readonly` does not work and if we want to fix them down the line as well it should also be done for 4.9 imho.

**Review by leofeyer — DISMISSED** [review]

**Comment by leofeyer** [comment]
The unit tests are still failing though.

**Review by fritzmg — CHANGES_REQUESTED** [review]
> I decided to fix this only in Contao 4.13 because we only disable settings there.

This should be fixed in Contao 4.9 as well, as _any_ widget can be set to `readonly => true` in 4.9 as well, not just in 4.13. Also `select` with `chosen` are not the only widget where `readonly` does not work and if we want to fix them down the line as well it should also be done for 4.9.

**Comment by aschempp** [comment]
Yes, its a general issue on multiple widgets. This PR fixes it for the system settings. Feel free to fix any other widgets you notice in 4.9, I just didn't find the time to test every widget. Also, this is about `disabled` not `readonly`, but I guess that does not really matter 😆

**Review by leofeyer — APPROVED** [review]

**Pull request merged**
