### PR TITLE
Correctly handle IDNA hostnames in the root page

### LINKED ISSUE #2239: IDN Domain wird nicht erkannt
Contao 4.9.5

Lege ich einen neuen Startpunkt einer Webseite an und trage die IDN-Domain `www.übungsgrammatik.de` als Domainnamen ein, steht nach dem Speichern nur noch `www.` im Textfeld drin. Entsprechend kann der Startpunkt nicht aufgerufen werden.

Trage ich nur `übungsgrammatik.de` für den Domainnamen ein, bleibt die Domain korrekt im Textfeld stehen. Allerdings bekomme ich beim Aufruf der Webseite dann „Es ist ein Fehler aufgetreten“ und im Log steht folgende Fehlermeldung:

```
request.CRITICAL: Uncaught PHP Exception LogicException: "Cannot use UTF-8 route patterns without setting the "utf8" option for route "/"." at /var/www/…/web/vendor/symfony/routing/RouteCompiler.php line 114 {"exception":"[object] (LogicException(code: 0): Cannot use UTF-8 route patterns without setting the \"utf8\" option for route \"/\". at /var/www/…/web/vendor/symfony/routing/RouteCompiler.php:114)"} []
```

Es funktioniert nur korrekt, wenn ich die Domain in der Punycode-Entsprechung eintrage.

### LINKED ISSUE #2335: Show correct Punycode for umlaut subdomains in Contao backend meta title
**Affected version(s)**

Contao 4.9.5 (other Contao releases not tested)

**Description**

The meta title in the backend shows the domain. It would be nice if the punycode would not be displayed here for umlaut subdomains, ie "demo.präfner.de" instead of "demo.xn--prfner-cua.de".

See also: #507 

**How to reproduce**

Call the Contao backend with an umlaut subdomain.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2335, #2239
| Docs PR or issue | -

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

**Review by ausi — APPROVED** [review]

**Comment by aschempp** [comment]
does this mean ever IDNA hostname needs to be re-saved to work?

**Comment by ausi** [comment]
> does this mean ever IDNA hostname needs to be re-saved to work?

As decoded IDNA domains never worked before, this should not be a problem IMO. 
Encoded IDNA hostnames do not need to be re-saved.

**Comment by aschempp** [comment]
Are you sure this didn't work with our own routing (in Contao < 4.7)?

**Comment by ausi** [comment]
No.

**Pull request merged**
