### PR TITLE
Fix the version panel alignment

### PR DESCRIPTION
**Pull request by fritzmg**
Currently the select is not aligned with the restore button:

image

(Firefox, Chrome)

This PR provides one way to fix it.

### CODE REVIEW

**Comment by fritzmg** [comment]
Personally I would prefer

```css
.tl_version_panel .formbody {
    display: flex;
    justify-content: flex-end;
    align-items: center;
    gap: 0.25em;
}
```

though. This would also make the compare button properly aligned.

**Comment by leofeyer** [comment]
The "correct" fix would be to add `vertical-align: middle` to this `button` element again.

**Comment by fritzmg** [comment]
> The "correct" fix would be to add `vertical-align: middle` to this `button` element again.

👍 done

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Comment by Aybee** [comment]
> .tl_version_panel .formbody {

`.tl_version_panel .tl_formbody {`

**Pull request merged**
