### PR TITLE
Mark used files in the file manager

### PR DESCRIPTION
**Pull request by stefan-at-work**
To get a better overview of the used files in the file manager, it would be helpful if they are marked accordingly. Especially with a large project you have a better chance to remove unnecessary files.

### CODE REVIEW

**Comment by fritzmg** [comment]
You need to base the PR against the master branch, not the 4.4 branch.

**Comment by stefan-at-work** [comment]
@fritzmg I don't know where or how to correct it

**Comment by fritzmg** [comment]
Just click "Edit", select the dropdown where it say "base: 4.4" and change it to "base: master".

**Comment by fritzmg** [comment]
oh wait, your base branch is already contao:4.4...

**Comment by m-vo** [comment]
Huh? This PR gets displayed as merged to me (with 35 changed files). 
What's the actual content and/or wrong with this?

OT: Regarding 'marking' of files - I don't think this can be done sufficiently as long as everyone can link diretly to them (either by manually setting a `src` or an extension adding further file fields).

**Comment by fritzmg** [comment]
Furthermore there can be {{file::}}, {{image::}} or {{picture::}} insert tags basically _anywhere_.

**Comment by stefan-at-work** [comment]
@m-vo @fritzmg - u r right. I did not consider that. PR can be closed.

**Comment by leofeyer** [comment]
> Huh? This PR gets displayed as merged to me (with 35 changed files).
> What's the actual content and/or wrong with this?

I surely did not merge this. It looks like both the head branch and the base branch are referring to `contao/contao`, so basically Stefan asked to merge the `4.4` branch into the `master` branch, which happend yesterday when I was merging upstream. 😄

**Comment by gmpf** [comment]
@stefan-at-work Would you mind sharing your work on this again, outside of this PR? Even if it cannot become a core feature, your code could still be very useful for others who need to implement this somewhere.

**Pull request merged**
