### PR TITLE
Strip root dir from normalized path

### PR DESCRIPTION
**Pull request by fritzmg**
In #1918 we changed `StringUtil::stripRootDir()` so that it normalizes both the `kernel.project_dir` and the given `$path` before stripping the the former from the latter.

However, in actuality the root dir is still stripped from the original, pre-normalized path. This still works, because normalizing would not change the length of the path - unless you have a weird operating-/filesystem with multiple character directory separators :) (not that that would be supported by PHP anyways).

However, I do think that technically we should strip from the _normalized_ path - and thus also return a normalized path (just like all `Path` methods would).

Btw. alternatively we could also use `Path::makeRelative($path, $projectDir)` instead and then for the exception check if the path starts with `../`?

@m-vo wdyt?

Changing this would also automatically fix another minor issue: in https://github.com/contao/contao/pull/7094 a new feature was introduced where you can now use container parameters for the `TL_PURGE` tasks, like so:

```php
// contao/config/config.php
use App\Maintenance\PurgeFoobarFolder;

$GLOBALS['TL_PURGE']['folders']['foobar'] = [
    'callback' => [PurgeFoobarFolder::class, '__invoke'],
    'affected' => ['%kernel.cache_dir%/foobar'],
];
```

However, this results in mixed directory separators:

Screen Shot 2024-11-10 at 10 30 09

Merging this PR upstream would automatically fix this, since `PurgeData` uses `StringUtil::stripRootDir()` and then the path would already be normalized.

### CODE REVIEW

**Comment by m-vo** [comment]
Is the mentioned bit with the automator path the only issue that is fixed with this? The function behaves weirdly anyway (see https://github.com/contao/contao/pull/1918 for instance), so I think I would avoid adjusting it if not really necessary and completely remove it in the future instead (though on first glance, the changes seem correct to me).

**Comment by fritzmg** [comment]
> Is the mentioned bit with the automator path the only issue that is fixed with this?

The only issue I encountered at least. That particular issue can also be fixed by using `Path::normalize()` in `PurgeData` of course, but I just find it weird that we determine the string length to be stripped on the normalized path - but then apply that on the non-normalized path.

**Comment by m-vo** [comment]
> but I just find it weird that we determine the string length to be stripped on the normalized path - but then apply that on the non-normalized path.

Well, we determine the length on the project dir, not on the given path. But the only thing `Path::normalize()` really does is to replace the single `\` character with `/` anyways. So the `substr()` operation is IMHO safe.

I would rather fix this in `PurgeData` tbh. The issue really is feeding non-normalized paths into `StringUtil::stripRootDir()`, which it is not supposed to handle. If we change this, we'll likely break things again, where people are using string-comparisons on paths.

**Comment by fritzmg** [comment]
> where people are using string-comparisons on paths.

If they do that it will be broken in any case.

**Comment by m-vo** [comment]
Well, it's definitively a behavior change:

```php
// Currently:
StringUtil::stripRootDir("$projectDir\\foo\\bar\\baz"); // "foo\bar\baz"

// With this PR:
StringUtil::stripRootDir("$projectDir\\foo\\bar\\baz"); // "foo/bar/baz"

**Comment by leofeyer** [comment]
Yes, and one that is likely to cause side effects!

**Comment by fritzmg** [comment]
👍 closing - see https://github.com/contao/contao/pull/7724 for fixing the mentioned issue in 5.4.

**Pull request closed without merging**
