### PR TITLE
Use `origId` if defined by alias element

### LINKED ISSUE #2823: Content include element broken with fragments
**Affected version(s)**

Contao 4.9 or Contao 4.10?

**Description**

If I include a content element which is a fragment controller with the content alias element Contao selects the wrong element class for the rendering. The issue appears because the element id is overridden here: https://github.com/contao/contao/blob/991282912ef0c590b92d25b67785463516a38890/core-bundle/src/Resources/contao/elements/ContentAlias.php#L42

### PR DESCRIPTION
**Pull request by discordier**
ContentAlias set's `origId` property for the id of the aliased element.
Therefore we need to use that one in the proxy, as otherwise the alias will get rendered by the proxy instead of the "aliased" element.

| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2823

### CODE REVIEW

**Comment by aschempp** [comment]
Looks like a duplicate of https://github.com/contao/contao/pull/2851 to me? 🙃

**Comment by aschempp** [comment]
Sorry thats not #2851. I can't find my other one (yet) 😂

**Comment by aschempp** [comment]
Well 🙄 it is actually solved by #2851 …

**Comment by discordier** [comment]
> Well  it is actually solved by #2851 …

Feel free to close then.

**Review by leofeyer — COMMENTED** [review]
Besides the failing CS job, the fix looks correct to me. We should merge it independently from #2851 IMHO.

**Review by leofeyer — APPROVED** [review]

**Review by aschempp — CHANGES_REQUESTED** [review]
I disagree. `origId` is not a valid model property, it is "randomly" set by the alias element. We shouldn't introduce a "feature" to use another ID than the model ID, because someone might have modified the model ID.

In the context of fragments, setting properties on the source model is pointless, because only the ID is taken and forwarded to the fragment handler (e.g. for ESI cases). There's a concept in place to forward other properties, that's what #2930 (successor of #2851)  implements.

**Comment by leofeyer** [comment]
Closing this in favor of #2930 then.

**Pull request closed without merging**
