### PR TITLE
Move the metadata fields back up in the news/events module

### LINKED ISSUE #1666: Meta data fields are in chapter "forwarding target"
**Affected version(s)**

Contao 4.9.2

**Description**
backend: news editing

Contao 4.9.2
meta data fields are in chapter "forwarding target".
grafik

Expected behavior:

Contao 4.9.0 (demo.contao.org)
seperate "meta data" chapter
grafik

Not in chapter "forwarding target"
grafik

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1666
| Docs PR or issue | -

### CODE REVIEW

**Review by aschempp — APPROVED** [review]

**Comment by fritzmg** [comment]
Extension developers have to keep in mind though that they will need to update their extensions, if they extend the palette of `tl_news` in their extensions - since now we have additional palettes there.

/cc @qzminski for `news_categories` for instance ;)

**Comment by fritzmg** [comment]
@ausi suggested to change the widget to a `select`, rather than `radio`. I agree that it should be changed - and may be add `:hide` to the fieldset too?

**Comment by leofeyer** [comment]
> @ausi suggested to change the widget to a `select`, rather than `radio`. I agree that it should be changed - 

I don't agree. Radio buttons are easier to operate on both mobile and desktop devices.

> and may be add `:hide` to the fieldset too?

The fieldset is hidden in the default palette.

**Comment by fritzmg** [comment]
> I don't agree. A select menu is easier to operate on both mobile and desktop devices.

So you do agree? 😁

**Comment by leofeyer** [comment]
Fixed my comment above. 😄

**Pull request merged**
