### PR TITLE
Do not set `database_version` in the install tool

### PR DESCRIPTION
**Pull request by aschempp**
Related to https://github.com/contao/contao/pull/3623

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by ausi** [comment]
@aschempp Did you test that if a `database_version` is already set in the parameters.yaml, but the connection fails and so the install-tool lets you reenter the credentials, that the `database_version` gets removed from the parameters in this case?

**Comment by leofeyer** [comment]
It does not. Our `ParameterDumper` class has no routines to remove values.

**Comment by aschempp** [comment]
I didn't test anything 😉

**Comment by ausi** [comment]
> Our `ParameterDumper` class has no routines to remove values.

Setting it to `null` might work I think.

**Comment by fritzmg** [comment]
We cannot know whether someone deliberately set `database_version` though - thus we also cannot automatically unset it.

**Comment by ausi** [comment]
> We cannot know whether someone deliberately set `database_version` though - thus we also cannot automatically unset it.

We already overwrite it currently, so unsetting it should be fine too IMO. This is however only done if the current connection fails and the user enters new credentials (and we would also only unset it in this case, not everytime the install tool gets accessed).

**Comment by leofeyer** [comment]
So do I merge this PR now?

**Comment by ausi** [comment]
I tested this PR now locally. If I enter new credentials in the install tool (only possible if the connection fails) the old value for `server_version` stays in the *parameters.yml* wich would cause even more issues and confusion.

When the install tool dumps the parameters yaml, all other `database_` parameters get reset, so I think we have to explicitly unset the `server_version`.

See https://github.com/aschempp/contao/pull/11

**Comment by leofeyer** [comment]
Fine with me. 👍

**Comment by aschempp** [comment]
PR updated. I think this will be mostly obsolete once the Manager allows you to set credentials, bit it certainly can't harm 😊

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
