### PR TITLE
Fix a phpDoc comment in the Pagination class

### PR DESCRIPTION
**Pull request by zonky2**
Fix type

### CODE REVIEW

**Comment by leofeyer** [comment]
@zonky2 This looks like a bugfix for Contao 4.9. Can you please rebase the PR on the `4.9` branch?

**Comment by m-vo** [comment]
You probably want to run `git rebase --onto 4.9 4.x patch-5` to get rid of the unrelated changes.

**Comment by zonky2** [comment]
@m-vo done

**Comment by leofeyer** [comment]
Thank you @zonky2.

**Pull request merged**
