### PR TITLE
Tune the back end theme

### PR DESCRIPTION
**Pull request by leofeyer**
Apparently a relevant number of users prefers the back end without the blue sidebar. 😄

### CODE REVIEW

**Comment by leofeyer** [comment]
We should probably improve the contrast of the menu section headlines and their icons.

**Comment by leofeyer** [comment]
And we should also add a dark theme:



However, it is going to be **a lot of work** to adjust all the icons and every detail…

**Comment by leofeyer** [comment]
And of course we should use CSS custom properties, so our extension developers can adjust their styles accordingly.

```css
:root {
  --bg: white;
  --text-color: #555;
  --link-color: #639A67;
  --link-hover: #205D67;
}

.dark-theme {
  --bg: #222;
  --text-color: white;
  --link-color: #B793E6;
  --link-hover: #3532A7;
}
```

**Comment by fkaminski** [comment]
> We should probably improve the contrast of the menu section headlines and their icons.
... However, it is going to be a lot of work to adjust all the icons

If it stays with this implementation (white, black/grey), it would probably make sense if then the icons are colorless too. 
At least easier in terms of contrast for dark/light mode with corresponding only one custom property.

```
:root {
  --clr-icon: #333;
 }
 
.dark-theme {
  --clr-icon: #eee;
}

<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16">
  <path fill="var(--clr-icon)" d="M11.347 2.056L8.341 5.061a.49.49 0 01-.689 0l-3-2.984a.49.49 0 00-.689 0L2.056 3.985a.486.486 0 00.002.687l3.009 2.974c.19.189.191.499.001.688l-3.02 3.019a.49.49 0 000 .689l1.895 1.895a.49.49 0 00.689 0l3.02-3.02a.49.49 0 01.689 0l3.028 3.027c.188.189.5.189.688 0l1.896-1.895a.491.491 0 000-.689l-3.028-3.027a.488.488 0 010-.689l3.005-3.006a.49.49 0 000-.689l-1.895-1.895a.488.488 0 00-.688.002z"/>
</svg>
```
You could still set matching color values over several properties this way. Regardless of the actual color theme, it might still be beneficial to define separate custom properties for each icon. You would then be more flexible in the future.


```
:root {
  --clr-primary: red;

  --clr-icon-delete: var(--color-primary);
  /* or individual
  --clr-icon-delete: pink;
  */ 
  --clr-icon-edit: var(--color-primary);
 }
 
.dark-theme {
  --clr-primary: green;

  --clr-icon-delete: var(--color-primary);
    /* or individual
  --clr-icon-delete: lightblue;
  */ 
  --clr-icon-edit: var(--color-primary);
}

<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16">
  <path fill="var(--clr-icon-delete)" d="M11.347 2.056L8.341 5.061a.49.49 0 01-.689 0l-3-2.984a.49.49 0 00-.689 0L2.056 3.985a.486.486 0 00.002.687l3.009 2.974c.19.189.191.499.001.688l-3.02 3.019a.49.49 0 000 .689l1.895 1.895a.49.49 0 00.689 0l3.02-3.02a.49.49 0 01.689 0l3.028 3.027c.188.189.5.189.688 0l1.896-1.895a.491.491 0 000-.689l-3.028-3.027a.488.488 0 010-.689l3.005-3.006a.49.49 0 000-.689l-1.895-1.895a.488.488 0 00-.688.002z"/>
</svg>
```

**Comment by aschempp** [comment]
I don't like the idea of colorless icons, just because they are currently also easily distinguishable through their color. Maybe that could only be applied to the "grey" versions that conflict with dark mode.

**Comment by fkaminski** [comment]
> I don't like the idea of colorless icons, just because they are currently also easily distinguishable through their color. Maybe that could only be applied to the "grey" versions that conflict with dark mode.

You are not bound to it but only one custom property would be needed. Examples with color information and custom properties per icon see above.

The suggestion is only, regardless of the icon colors, not to set them manually within the svg definition but also to assign custom properties and thus control them via css.

**Comment by leofeyer** [comment]
Related issues we could work: #3044

**Comment by m-vo** [comment]
> You are not bound to it but only one custom property would be needed. Examples with color information and custom properties per icon see above.

For svgs it is IMHO best practice to use `currentColor` for fill or stroke. This will inherit the color of the parent HTML element that was set via CSS. :relaxed: 

Here are some more PRs & Issues that might be related:
- https://github.com/contao/contao/pull/2053
- https://github.com/contao/contao/issues/3388
- https://github.com/contao/contao/issues/3708
- https://github.com/contao/contao/issues/4147
- https://github.com/contao/contao/issues/2218

**Comment by fkaminski** [comment]
> For svgs it is IMHO best practice to use `currentColor` for fill or stroke. This will inherit the color of the parent HTML element that was set via CSS.

As long as all svg's have only one color. 🤔

**Comment by leofeyer** [comment]
This will be a two-step process. Step 1 is to remove the blue sidebar and the orange top bar, so all areas are bright:



The next step – most likely in a separate PR for Contao 5.1 or later – will be to add a dark mode and adjust all icons accordingly. This will be the hardest part.

**Review by fritzmg — DISMISSED** [review]
Approving as I did not find any obvious issues while testing.

However I still strongly prefer this:

Screenshot 2022-07-20 at 08-38-09 News News Items c50 local

over this:

Screenshot 2022-07-20 at 08-37-24 News News Items c50 local

**Comment by leofeyer** [comment]
Using a solid border for the header makes it look better in Chrome and Firefox.

**Comment by leofeyer** [comment]
@fritzmg We really don‘t need to discuss this. Other CMS behave exactly the same way, so if you don‘t want to have a wide back end, simply resize your browser window accordingly. 🤷‍♂️ 

TYPO3



Wordpress

**Comment by fritzmg** [comment]
> We really don‘t need to discuss this

We already did once and re-introduced it. I do not understand why you want to remove the max-width again. What is the benefit within the current layout of the Contao back end?

> so if you don‘t want to have a wide back end, simply resize your browser window accordingly. 

I am not gonna constantly resize my browser window just because there is one application behaving out of line. That's the _opposite_ of responsive web design.

> Other CMS behave exactly the same way

That's a moot point in my opinion. You cannot make this decision solely based on "others do it too". You should base it on usability of _your_ user interface alone. Also Typo3 for example utilises the additional space much more in various locations than the current Contao back end can. And if you still want to draw comparisons to other web applications:

* https://www.apple.com has a max-width between 1024px and 1560px for its single column content and a max-width of 2560px for its double column content.
* https://store.google.com has a max-width of 1440px.
* https://www.microsoft.com has a max-width of 1600px.
* https://www.amazon.de has a max-width of 1500px for its product lists and product details and 1000px for the account back end.
* https://www.aramco.com has a max-width of 1440px for its content.

**Comment by fkaminski** [comment]
Leo's statements in this regard are not wrong to begin with.
However, I also find Fritz's statement justified.

Regarding "usability" I would find a future solution helpful which then optionally (if space is available) provides for example an additional column with context-related properties for editing. 
JM2C

**Comment by bennyborn** [comment]
To be honest... I don't like it at all. Not enough contrast and way too bright - hurts my eyes. If a "dark mode" will only be available with 5.1 so should this change be 🤷‍♂️

**Pull request merged**
