### PR TITLE
Version 4.9.0-RC2

### PR DESCRIPTION
**Pull request by leofeyer**

### CODE REVIEW

**Comment by richardhj** [comment]
Version 4.9.2-RC2 is correct? Prior release was 4.9.0-RC1 :-)

**Review by richardhj — APPROVED** [review]

**Comment by leofeyer** [comment]
Good find. 👍  I have fixed the issue title. The CHANGELOG.md and constants.php files already had the correct version number.

**Comment by bytehead** [comment]
Is it intentionally that #1299 will be missing in this release?

**Comment by leofeyer** [comment]
Yes, kind of. We are publishing another news about Contao 4.9 today and I want people to have an updated release candidate so they do not find and report the same issues over and over again.

**Review by fritzmg — APPROVED** [review]

**Pull request merged**
