### PR TITLE
Adjust the template studio layout

### PR DESCRIPTION
**Pull request by zoglo**
This PR adjusts the template studio layout to be more responsive on lower displays:

### Template studio

- Scrollbars width is now thin
- Makes sure the template studio tabs are in one row (similar to the jump-targets)
- Makes sure the template-info won't grow bigger with bigger namespaces (the width is not limited but the text is RTL now)
- Makes sure that the template section won't grow with the new theme-picker

Needs https://github.com/contao/contao/pull/7683 to be merged first (most likely needs adjustments after this)

### Screenshot

**Before (Extreme case)**
image

**After**
image

Can be tested using https://github.com/zoglo/contao/tree/chore/template-studio-layout

### CODE REVIEW

**Comment by m-vo** [comment]
> Adds postcss-nested to make sure we can use SCSS-Nesting

I'm not sure I like this, because all the other things we are currently doing is the (future-)-spec compliant way. The analog plugin for that would be `postcss-nesting` but that is probably already included in the stage 2 preset-env "nesting-rules" feature.

You only use this to abbreviate `#foo { #foobar { … }}` to `#foo {&bar {}}` or is there another "big" benefit?

**Comment by zoglo** [comment]
> [!NOTE]  
> Can be skipped, this has been removed in https://github.com/contao/contao/commit/a382fd43dfcfebf389705638854f89ed856c21bb

<details>
  <summary>Previous message...</summary>

> You only use this to abbreviate `#foo { #foobar { … }}` to `#foo {&bar {}}` or is there another "big" benefit?

I am actually making sure that it stays readable whilst not having unnecessary nesting like:

Right now
```scss
#template-studio {
    color: blue;
    
    #template-studio--tree {
        color: red;

         #template-studio--bar{
            color: green;
        }
    }
} 
```
Output
```css
#template-studio { color: blue; }
#template-studio #template-studio--tree { color: red }
#template-studio #template-studio--tree #template-studio--bar { color: green }
```

____

Without the plugin we'd have to do this (which I would be okay with)

```css
#template-studio {
    color: blue;
} 

#template-studio--tree {
    color: red;
}

#template-studio--bar {
    color: green;
}
```
Output
```css
#template-studio { color: blue; }
#template-studio--tree { color: red }
#template-studio--bar { color: green }
```

____

With the nesting

```scss
#template-studio {
    color: blue;
    
    &--tree {
        color: red;
    }
    
    &--bar {
        color: green;
    }
} 
```

Output
```css
#template-studio { color: blue; }
#template-studio--tree { color: red }
#template-studio--bar { color: green }
```

___

Would also make sure people that use SCSS won't have issues writing the css
</details>

**Comment by m-vo** [comment]
To be honest, I personally prefer nesting things like they are actually in the DOM, because to me this communicates how the hierarchy actually looks like. I don't care if the selectors are IDs or classes or whatever which lets me refactor things (for example switch a class with a data-attribute or an ID) and the specificity still works. Are there downsides to nested IDs? They surely have the same performance? But also I am no frontend dev and if that's how things are supposed to be, fine with me. :smile:

Btw.: The reason for the many IDs in the template studio is, that most of them are also targets for Turbo streams and these are by logic unique. In fact, at some places we even need them to be IDs, so that Turbo replaces them if already existent (see adding tabs).

**Comment by zoglo** [comment]
Removed the scss config in a382fd43dfcfebf389705638854f89ed856c21bb due to remembering that we wanted to go pure native css

> Are there downsides to nested IDs? They surely have the same performance? But also I am no frontend dev and if that's how things are supposed to be, fine with me. 😄

IDs are unique so they don't need to ever be nested, the more nesting, the bigger the ouput file - also neglible performance nowadays but no need to have unnecessary code (seen way worse things in my career)

> Btw.: The reason for the many IDs in the template studio is, that most of them are also targets for Turbo streams and these are by logic unique. In fact, at some places we even need them to be IDs, so that Turbo replaces them if already existent (see adding tabs).

And there is nothing against using ids <3

**Comment by zoglo** [comment]
Since this one has been ready for a while and is needed for working on the individual parts of the template studio, as it's changing the layouting, can we get this reviewed and merged anytime soon 👀 /cc @m-vo @leofeyer

**Comment by leofeyer** [comment]
Yes, I'll merge it first thing next week.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @zoglo.

**Pull request merged**
