### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xchs**
Remove the shell prompt sign.

### CODE REVIEW

**Review by leofeyer — CHANGES_REQUESTED** [review]
You should target your PR at the `4.4` branch, since it is wrong there as well.

**Comment by xchs** [comment]
See https://github.com/contao/contao/pull/192

**Comment by xchs** [comment]
@leofeyer I was unsure how to handle this. The two `README.md` from the `master` and the `4.4` branch differ (see the last changes added by @Toflar recently: https://github.com/contao/contao/commit/1dbb4a0e6ae2e87c9a4c533d1c461d1c0a6b6a34). Not that any information gets lost during merging here.

**Comment by leofeyer** [comment]
Now we are safe. 😄 Thank you @xchs.

**Comment by xchs** [comment]
Great!

**Pull request merged**
