### PR TITLE
Check for the `debug.stopwatch` service

### LINKED ISSUE #5978: Exception: You have requested a non-existent service "debug.stopwatch".
### Affected version(s)

5.x

### Description

How to reproduce:
* install Contao using composer (see composer.json below)
* turn on debug mode (APP_ENV=dev)
* open frontend page

Current behavior:
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "debug.stopwatch".

Expected behavior:
Show frontend page

Code:
```
		if (System::getContainer()->getParameter('kernel.debug'))
		{
			$objStopwatch = System::getContainer()->get('debug.stopwatch'); <<<<<<<<<<
			$objStopwatch->start($strStopWatchId, 'contao.layout');
		}
```

Reason:
"Debug mode on" does not automatically mean, that stop watch is installed! Change if condition e. g. to:

```
		if (System::getContainer()->has('debug.stopwatch'))
		{
			$objStopwatch = System::getContainer()->get('debug.stopwatch');
			$objStopwatch->start($strStopWatchId, 'contao.layout');
		}
```

composer.json:
```
{
    "type": "project",
    "license": "proprietary",
    "minimum-stability": "stable",
    "prefer-stable": true,
    "require": {
        "php": ">=8.1",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "contao/core-bundle": "^5",
        "php-http/guzzle7-adapter": "^1.0",
        "symfony/console": "6.1.*",
        "symfony/dotenv": "6.1.*",
        "symfony/flex": "^2",
        "symfony/framework-bundle": "6.1.*",
        "symfony/monolog-bundle": "*",
        "symfony/runtime": "6.1.*",
        "symfony/twig-bundle": "6.1.*",
        "symfony/yaml": "6.1.*",
        "toflar/psr6-symfony-http-cache-store": "^4.1",
        "twig/extra-bundle": "^2.12|^3.0",
        "twig/twig": "^2.12|^3.0"
    },
    "config": {
        "allow-plugins": {
            "composer/package-versions-deprecated": true,
            "symfony/flex": true,
            "symfony/runtime": true,
            "contao-components/installer": true,
            "php-http/discovery": true
        },
        "optimize-autoloader": true,
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php72": "*",
        "symfony/polyfill-php73": "*",
        "symfony/polyfill-php74": "*",
        "symfony/polyfill-php80": "*",
        "symfony/polyfill-php81": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd",
            "contao:install %PUBLIC_DIR%": "symfony-cmd",
            "contao:symlinks %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "contao-component-dir": "assets",
        "symfony": {
            "allow-contrib": "true",
            "require": "6.1.*"
        }
    }
}
```

See https://github.com/contao/contao/blob/120eb803d639bc5ee1dfea7899a897ac07d621d7/core-bundle/contao/library/Contao/Controller.php#L490-L494

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes https://github.com/contao/contao/issues/5978

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Review by aschempp — CHANGES_REQUESTED** [review]
I don't think we want to not use the stopwatch? Shouldn't we rather figure out why the stopwatch service is missing?

**Comment by fritzmg** [comment]
It is only required by the manager-bundle and thus a soft dependency of the core-bundle.

**Review by m-vo — APPROVED** [review]

**Comment by aschempp** [comment]
> It is only required by the manager-bundle and thus a soft dependency of the core-bundle.

So you would not expect to have the profiler information in a non-managed edition as well?

**Comment by fritzmg** [comment]
All the Symfony components also assume that the `debug.stopwatch` service isn't necessarily there. It's a soft dependency everywhere and the profiler also will tell you

> The Stopwatch component is not installed. If you want to see timing events, run: `composer require symfony/stopwatch`.

And even if `symfony/stopwatch` is installed, it might not be enabled.

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
