### PR TITLE
Show native language suffix only in user profile

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3267

Alternative to #3267

Shows the native suffix only in the user profile ~~or the member personal data module~~.

### CODE REVIEW

**Comment by aschempp** [comment]
I wonder whats the point of showing the native language suffix? I think that only ever made sense on the back end login screen, so you could switch to your local language if you didn't know the current. It does not make sense in the front end to me?

**Comment by fritzmg** [comment]
> It does not make sense in the front end to me?

I agree, but that would be a behaviour change.

**Comment by ausi** [comment]
> I think that only ever made sense on the back end login screen, so you could switch to your local language if you didn't know the current.

I think it also makes sense in the user profile (see https://github.com/contao/contao/pull/3267#issuecomment-892877521 ) as there is no language selection in the login form anymore.

> It does not make sense in the front end to me?

Agree, removed in 5a0b033a96e3c02b965f9103bbcdd99636806017

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
