### PR TITLE
Replace the "edit header" icon with an "edit child elements" icon

### LINKED ISSUE #3388: Standardise the edit icons
We should standardise the use of all edit icons. Currently they are used in different case.

For example the use of the pencil icon in the **site structure** and **articles**:
site
articles

Sometimes the pencil is for **editing the element itself** and sometimes for **editing child elements**. That's confusing. 

We should add a icon for editing child elements or consistently use the _header_ icon for editing elements itself.

I would like to see a new icon for editing child elements, despite I don't know how it should look like.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #3388

This makes so much more sense now!

It sure takes a little getting used to, but we shouldn‘t let that stop us. It is a massive improvement in terms of consistency and logic.

### CODE REVIEW

**Comment by aschempp** [comment]
Do we also need to change the _Save & Edit_ button?

**Comment by leofeyer** [comment]
Probably yes, but "save & edit child elements" is a bit long. Any ideas?

**Comment by leofeyer** [comment]
Done.



A shorter button text would be preferable, though.

**Comment by ausi** [comment]
I really think the icon should include the the pencil, so that users see that it is an edit action.



The edit all button is also a variation with the pencil, so this would be more consistent I think: https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/themes/flexible/icons/all.svg

**Comment by leofeyer** [comment]
Technically, it is not an edit view but a list view. Could we change the label from "edit content elements…" to "show content elements…" and leave the icon as is?

**Comment by ausi** [comment]
I think from a UX perspective it is still an edit action. Like “Edit the content of this article”.

**Comment by fritzmg** [comment]
But it views the content from this article. It does not directly edit the content of the article - apart from quick actions like publishing states and sorting.

**Comment by ausi** [comment]
> apart from quick actions like publishing states and sorting.

… and adding/creating and deleting.

**Comment by fritzmg** [comment]
> > apart from quick actions like publishing states and sorting.
> 
> … and adding/creating and deleting.

But then to be consistent we would have to add a pencil to the icons of the front end modules, page layout, responsive image sizes etc. as well. To me all these views are functionally the same: they primarily _list_ entries while allowing you to then edit or add entries, just like most other views that list entries.

**Comment by ausi** [comment]
> But then to be consistent we would have to add a pencil to the icons of the front end modules, page layout, responsive image sizes etc. as well. To me all these views are functionally the same: they primarily _list_ entries while allowing you to then edit or add entries, just like most other views that list entries.

Then we’d need icons for these child elements instead of a generic one, don’t we?
Like for content elements, news articles, events, newsletters and so on...

**Comment by fritzmg** [comment]
imho the one from this PR would simply be the default for the children view. Any extension can always add more child tables - and they will always also need to come up with an icon for those.

**Review by ausi — APPROVED** [review]

**Review by m-vo — APPROVED** [review]

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to merge the PR as is. In a follow-up PR, we could try to use specific icons for news, events etc. and use them instead of the generic "show child elements" button.

**Pull request merged**
