### PR TITLE
Correctly determine the Ajax URL

### PR DESCRIPTION
**Pull request by richardhj**
Correctly determine url (related #1225)
This fixes an issue with the file picker.

### CODE REVIEW

**Comment by richardhj** [comment]
Sorry, this is not correct.

The following error occurs in the console:
```
TypeError: options.field is undefinedmootao.min.js:39:28
    initialize https://test/bundles/contaocore/mootao.min.js?v=be380ba6:39
    initialize https://test/assets/mootools/js/mootools.min.js?v=2096ec36:1
    r https://test/assets/mootools/js/mootools.min.js?v=2096ec36:1
    e https://test/assets/mootools/js/mootools.min.js?v=2096ec36:1
    callback https://test/contao?do=themes&table=tl_layout&id=39&act=edit&rt=0lZkZew8_HV5x3ctjSu1Ln5NEyBsiCMco2jJ3f8WIuE&ref=xQumBzGl:443
    openModalSelector https://test/bundles/contaocore/core.min.js?v=b17da624:1
    <anonymous> self-hosted:876
    a https://test/assets/mootools/js/mootools.min.js?v=2096ec36:1
```

As a consequence, we need to alter #1225 by adding the following check:
`if (typeof options.field !== undefined && options.field !== null)` 

How to reproduce:
Use the file picker in the page layouts to select external CSS files.

**Comment by leofeyer** [comment]
Can you please check if the following code fixes the issue?

```js
		if (options && !options.url) {
			this.options.url = location.href;

			if (options.field) {
				var form = options.field.getParent('form');

				if (form.hasAttribute('action')) {
					this.options.url = form.getAttribute('action');
				}
			}
		}
```

**Comment by richardhj** [comment]
Yes, looking good :+1:

**Comment by ausi** [comment]
I would prefer:

```js
		if (options && !options.url && options.field && options.field.form && options.field.form.action) {
			this.options.url = options.field.form.action;
		}
```

A fallback to `location.href` is not required because the browser does that automatically if you access `form.action`.

@richardhj can you confirm that the this fix works?

**Comment by richardhj** [comment]
I adopted your snippet, @ausi!

This PR now fixes the my issue with the file picker, while #1214 remains resolved.
I minified the JS, @leofeyer please squash the commits :-)

**Review by ausi — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @richardhj.

**Pull request merged**
