### PR TITLE
Fix backend system font stack for IE 11

### PR DESCRIPTION
**Pull request by loilo**
The native font stack introduced to the Contao backend in 86f5fef breaks in Internet Explorer 11, resulting in the browser's default font to be loaded.

Contao backend with serif font in IE 11

The cause is the fonts being part of a `font` shorthand property (which seems to be [a known issue](https://booking.design/implementing-system-fonts-on-booking-com-a-lesson-learned-bdc984df627f#7134)).

The PR fixes this behavior by moving the font face out of the `font` shorthand property into its own `font-family`.

### CODE REVIEW

**Review by bytehead — DISMISSED** [review]

**Review by fritzmg — DISMISSED** [review]

**Comment by leofeyer** [comment]
Are you sure that `font:400 .875rem/1` without specifying a font family works? It does not according to [this page](https://css-tricks.com/snippets/css/font-shorthand/):

**Comment by loilo** [comment]
Going to have a look at it later today, currently commuting and not having access to an Internet Explorer (for the better or worse 😁).

**Comment by leofeyer** [comment]
I think the font shorthand requires a font family in every browser, not just IE. I quickly checked how GitHub defines the basic font formatting:



So I guess we should just do it the same way:

```
font-family:-apple-system,system-ui,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif;
font-size:.875rem;
font-weight:400;
line-height:1;
```

**Comment by loilo** [comment]
You're absolutely correct, the remaining `font` property does not work. Going to split that one up as well.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @loilo.

**Comment by loilo** [comment]
My pleasure. 🙂

**Pull request merged**
