### PR TITLE
Use custom routers to generate URLs from models

### PR DESCRIPTION
**Pull request by leofeyer**
This PR allows us to do the following:

```php
$pageModel = PageModel::findById(2);
echo $router->generate($pageModel); // will output en/foo.html
```

### TODO

* [ ] Agree on the implementation
* [ ] Check the priority
* [ ] Add a NewsModelRouter and CalendarEventsModelRouter
* [ ] Unit tests

### CODE REVIEW

**Review by Toflar — CHANGES_REQUESTED** [review]
Imho the concept is wrong. We shouldn't have an additional router.
The Symfony CMF router does exactly what we need (https://symfony.com/doc/master/cmf/components/routing/dynamic.html#linking-a-route-with-a-content) but @aschempp is more familiar with the topic.

**Comment by leofeyer** [comment]
> Imho the concept is wrong. We shouldn't have an additional router.

The implementation is taken from the Symfony docs: https://symfony.com/doc/current/cmf/components/routing/dynamic.html#generating-urls

**Comment by Toflar** [comment]
Sure, it's still not the approach we need.

**Comment by leofeyer** [comment]
Ok, then @aschempp please make sure to look into this for the Contao 4.9 release. I need the feature for the SERP preview widget.

**Pull request closed without merging**
