### PR TITLE
Fix PHPUnit deprecation warnings

### PR DESCRIPTION
**Pull request by m-vo**
Fixes the following warnings when running the unit tests:

```
There were 6 warnings:

1) Contao\CoreBundle\Tests\Contao\Database\ResultTest::testEmptyResult
Expecting E_WARNING and E_USER_WARNING is deprecated and will no longer be possible in PHPUnit 10.

2) Contao\CoreBundle\Tests\Contao\Database\ResultTest::testSingleRow
Expecting E_WARNING and E_USER_WARNING is deprecated and will no longer be possible in PHPUnit 10.

3) Contao\CoreBundle\Tests\Contao\Database\ResultTest::testMultipleRows
Expecting E_WARNING and E_USER_WARNING is deprecated and will no longer be possible in PHPUnit 10.

4) Contao\CoreBundle\Tests\Filesystem\FilesystemItemIteratorTest::testLimitThrowsOutOfRangeException
Expecting E_DEPRECATED and E_USER_DEPRECATED is deprecated and will no longer be possible in PHPUnit 10.

5) Contao\CoreBundle\Tests\Filesystem\VirtualFilesystemTest::testFailsWithNonUtf8Paths
Expecting E_ERROR and E_USER_ERROR is deprecated and will no longer be possible in PHPUnit 10.

6) Contao\CoreBundle\Tests\Twig\Loader\ContaoFilesystemLoaderTest::testIsFresh with data set "filemtime fails" (array(1623924000), false, true)
Expecting E_WARNING and E_USER_WARNING is deprecated and will no longer be possible in PHPUnit 10.
```

Todo:

* [x] 1-3
* [x] 4
* [x] 5
* [x] 6
* [x] rebase to 5.0

### CODE REVIEW

**Comment by leofeyer** [comment]
Can you please rebase the PR? Contao 5.0 has reached its end of life today.

**Comment by m-vo** [comment]
Did you close this intentionally?

**Comment by leofeyer** [comment]
That is also why I cannot reopen the PR. 🙈 Would you mind rebasing it or creating a new PR for Contao 5.1?

**Comment by m-vo** [comment]
> That is also why I cannot reopen the PR. see_no_evil Would you mind rebasing it or creating a new PR for Contao 5.1?

Sure, I cannot reopen it as well and therefore created a new PR: #5780.

**Pull request closed without merging**
