### PR TITLE
Use the active record in the protectFolder() callback

### LINKED ISSUE #1535: tl_files::protectFolder() should respect the save_callback()
**Affected version(s)**

Contao 4.4

**Description**

When manipulating a folder's name with a `save_callback`, the `input_field_callback` in the field `tl_files::protected` only takes `\Input::post('name')` and not the result from the `save_callback`.

Is this a bug or intended?

Bye Defcon0

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1535
| Docs PR or issue | -

@Defcon0 Can you please check if this fixes your issue?

### CODE REVIEW

**Comment by Defcon0** [comment]
Works well, although now `Validator::isInsecurePath()` isn't called anymore. Is this a problem?

**Comment by leofeyer** [comment]
The path should have been checked before it was stored in `$dc->activeRecord->path`. @ausi /cc

**Comment by ausi** [comment]
Yes, `checkFilename` makes sure that no slash is included in the name https://github.com/contao/contao/blob/0fbcab4c6dc1bd353a1e648de9ea128ac8e1c9f8/core-bundle/src/Resources/contao/dca/tl_files.php#L467

**Review by ausi — APPROVED** [review]

**Comment by Defcon0** [comment]
OK, great. Thanks for clarification.

**Pull request merged**
