### PR TITLE
Deprecated "allowedDownload" config for contao.downloadable_files

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
```php
if ($container->hasParameter('contao.downloadable_files'))
{
    $GLOBALS['TL_CONFIG']['allowedDownload'] = implode(',', $container->getParameter('contao.image.valid_extensions'));
}
```

~needs to be added to `Config::loadParameters` for BC~

Actually nvm., this is already handled by `$arrDeprecatedMap` :)

**Comment by aschempp** [comment]
Isn't the parameter always defined because there is a default value? But I asked this to @Toflar as well, if someone currently defined the `$GLOBALS['TL_CONFIG0']['allowedDownloads']` it would be ignored now?

**Review by fritzmg — APPROVED** [review]

**Comment by Toflar** [comment]
> But I asked this to @Toflar as well, if someone currently defined the `$GLOBALS['TL_CONFIG0']['allowedDownloads']` it would be ignored now?

It's just the same like for all the other settings we have deprecated over the course of the 4.x series. Concept is by @ausi so he would know.

**Comment by ausi** [comment]
> if someone currently defined the `$GLOBALS['TL_CONFIG0']['allowedDownloads']` it would be ignored now?

Yes, reading from `$GLOBALS['TL_CONFIG']['allowedDownloads']` would still work, but anything written to it will be ignored. We should probably add that information to the UPGRADE.md.

**Comment by Toflar** [comment]
We haven't done this with all the other ~20 parameters between 4.0 and 4.13 - what's suddenly different in this PR?

**Comment by ausi** [comment]
> We haven't done this with all the other ~20 parameters between 4.0 and 4.13 - what's suddenly different in this PR?

Nothing is different, but we should have documented the other ~20 parameters in the UPGRADE.md too I think.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to remove the `contao.downloadable_files` parameter again instead of merging this PR.

https://github.com/contao/contao/blob/d50e67901a36692f57f1a27680dced916ce6ddd6/core-bundle/src/Controller/ContentElement/AbstractDownloadContentElementController.php#L103-L105

As soon as we can edit the configuration in the Contao Manager, we will move all remaining settings into the container anyway.

**Comment by Toflar** [comment]
Because?

**Comment by leofeyer** [comment]
Because it only breaks the backwards compatibility and does not provide any advantage.

**Comment by Toflar** [comment]
But what should be done instead? Probably needs to remain up for discussion until I am part of it.

**Comment by ausi** [comment]
> But what should be done instead?

Only use the configuration from `$GLOBALS['TL_CONFIG']['allowedDownload']`

> Probably needs to remain up for discussion until I am part of it.

👍

**Pull request closed without merging**
