### PR TITLE
Show error 500 for unsupported image types

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes https://github.com/contao/contao/issues/1090#issuecomment-641820312

Based on #1814

### CODE REVIEW

**Comment by ausi** [comment]
I’m not sure if we should actually trigger this warning as we include `tif`, `tiff` and `webp` by default in the valid extensions list. This also breaks the tests now because the warning gets always triggered.

**Comment by aschempp** [comment]
Am I understanding correctly that eg. GD supports TIFF but ImageMagick does not?

There‘s no way to „retrieve“ the valid image types right?

**Comment by ausi** [comment]
> Am I understanding correctly that eg. GD supports TIFF but ImageMagick does not?

No, I think it’s the other way round. But which image types are supported depends on the setup. Both Imagick and GD can be set up with different supported image formats.

> There‘s no way to „retrieve“ the valid image types right?

I don’t think there is.

**Comment by leofeyer** [comment]
I'm for dropping the `verifyValidImageFileExtensions()` method again.

**Comment by ausi** [comment]
> I'm for dropping the `verifyValidImageFileExtensions()` method again.

Done in 127a162aeca66fa77f10ab4d4958e955a69f2bd7

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
