### PR TITLE
Show headlines in article teasers again

### LINKED ISSUE #7025: Headline within article-teaser is not shown
### Affected version(s)

5.3.x

### Description
The content-element "teaser" does not output the article title as a headline anymore.

Contao 4.13:
https://github.com/contao/contao/blob/14e9ef4bc8b82936ba2d0e04164581145a075e2a/core-bundle/src/Resources/contao/templates/elements/ce_teaser.html5#L4-L6

This part in the twig template has no function as it's never being shown
https://github.com/contao/contao/blob/7c69ccbf7b0fda33dd38a63feee6b18264d20d6c/core-bundle/contao/templates/twig/content_element/teaser.html.twig#L5-L19

### Possible solution
- moving the headline block inside of content
- using text rather than value because it doesn't exist within _headline.html.twig

```twig
{% trans_default_domain "contao_default" %}
{% extends "@Contao/content_element/_base.html.twig" %}
{% use "@Contao/component/_read_more.html.twig" %}

{% block content %}
    {% block headline %}
        {% include "@Contao/component/_headline.html.twig" with {headline: {unit: 'h1', text: article.title}} %}
    {% endblock %}

    {% block teaser %}
        {{ article.teaser|default|insert_tag|raw }}
    {% endblock %}

    {% block link %}
        {% with {title: 'MSC.readMore'|trans([article.title])} %}
            {{ block('read_more_component') }}
        {% endwith %}
    {% endblock %}
{% endblock %}

### PR DESCRIPTION
**Pull request by zoglo**
Fixes #7025 

- Block has to be moved into the content
- the key for `unit` has to be `tag_name` to work with _headline https://github.com/contao/contao/blob/da1b9ea8998ca8547a8041d3560cb3efbdaee755/core-bundle/contao/templates/twig/component/_headline.html.twig#L20
- the key for `value` has to be `text` to work with _headline
https://github.com/contao/contao/blob/da1b9ea8998ca8547a8041d3560cb3efbdaee755/core-bundle/contao/templates/twig/component/_headline.html.twig#L24

### CODE REVIEW

**Comment by ausi** [comment]
> Block has to be moved into the content

But this is not the case with all the other templates I think.

Can we instead just set the `headline` variable to the expected value?

```twig
{% set headline = { tag_name: 'h1', text: article.title } %}
```

**Comment by zoglo** [comment]
> > Block has to be moved into the content
> 
> But this is not the case with all the other templates I think.
> 
> Can we instead just set the `headline` variable to the expected value?
> 
> ```
> {% set headline = { tag_name: 'h1', text: article.title } %}
> ```

It's not the case because this template renders the headline based on the article title and doesn't work like all the other content elements.

If it would have worked, it would have thrown an error due to text not existing :)

**Comment by m-vo** [comment]
IMHO the correct fix is to add `{% set headline = {tag_name: 'h1', text: article.title} %}` outside of the `content` block and remove the `headline` block. Adding the line changed the outcome in the tests as expected for me.

**Comment by zoglo** [comment]
@m-vo  @ausi I was confused about your approach first but you are totally right.

However, changing it to
```twig
{% trans_default_domain "contao_default" %}
{% extends "@Contao/content_element/_base.html.twig" %}
{% use "@Contao/component/_read_more.html.twig" %}

{% set headline = {tag_name: 'h1', text: article.title} %}

{% block content %}
    {% block teaser %}
        {{ article.teaser|default|insert_tag|raw }}
    {% endblock %}

    {% block link %}
        {% with {title: 'MSC.readMore'|trans([article.title])} %}
            {{ block('read_more_component') }}
        {% endwith %}
    {% endblock %}
{% endblock %}
```

also needs the updated tests in https://github.com/contao/contao/pull/7026/commits/a5febfdd83c3b3af77991af2ff3717677c74c544 because previously it didn't test the headline at all.

**Review by m-vo — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @zoglo.

**Pull request merged**
