### PR TITLE
Unlock `dragonmantank/cron-expression` version 3

### PR DESCRIPTION
**Pull request by fritzmg**
Unlocks version 3.x for `dragonmantank/cron-expression`.

### CODE REVIEW

**Comment by leofeyer** [comment]
Now the prefer-lowest tests fail with `@hourly is not a valid CRON expression` 🤔

**Comment by fritzmg** [comment]
I see, the `@` aliases were part of the `CronExpression::factory` in 2.x, which is deprecated since 3.0.2. Changed it to allow ~^3.0.2~ ^3.1.0 only instead.

**Comment by fritzmg** [comment]
In addition the new `3.3.x` version allows us to register custom aliases - including the `@minutely` alias which did not exist before. This way you can now use both

```php
#[AsCronJob('minutely')
```

and

```php
#[AsCronJob('@minutely')
```

Before only the former was possible, as the latter was not a valid alias within `dragonmantank/cron-expression`.

**Comment by leofeyer** [comment]
> Before only the former was possible, as the latter was not a valid alias within `dragonmantank/cron-expression`.

Why not?

**Comment by fritzmg** [comment]
> Why not?

You'll have to ask the developers of `dragonmantank/cron-expression`/`mtdowling/cron-expression`. Only the following aliases were ever supported by default:

https://github.com/dragonmantank/cron-expression/blob/65b2d8ee1f10915efb3b55597da3404f096acba2/src/Cron/CronExpression.php#L72-L79

3.x supports a few more, but still no `@minutely`:

https://github.com/dragonmantank/cron-expression/blob/adfb1f505deb6384dc8b39804c5065dd3c8c8c0a/src/Cron/CronExpression.php#L40-L48

**Comment by leofeyer** [comment]
Ah, it is because `@minutely` is not a supported special string (see [crontab.5.en.html](https://manpages.debian.org/buster/cron/crontab.5.en.html)).



Then we should not add it, either.

**Comment by fritzmg** [comment]
We still need to support `minutely` anyway, so we might as well support `@minutely` (was my thinking).

**Comment by leofeyer** [comment]
Not sure about that. Neither the original `crontab` nor the `cron-expression` library supports `@minutely`, so we should not, either. It will confuse people when tools such as https://crontab.guru tell them their expression is invalid.

I understand that we have to support `minutely` but I would prefer to continue mapping it to `* * * * *`, because that is a valid expression. And I would also suggest to trigger a deprecation if one of our custom expressions is used.

**Comment by fritzmg** [comment]
Alright, reverted 👍

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
