### PR TITLE
Do not validate widgets that do not submit input

### LINKED ISSUE #2210: Disabled settings trigger errors upon saving
**Affected version(s)**

Contao 4.10

**Description**

Since #1382, settings defined in the app configuration are disabled in the back end. When trying to save the form, however, these fields trigger errors:

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2210
| Docs PR or issue | -

### CODE REVIEW

**Review by ausi — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Comment by aschempp** [comment]
Is there a reason this was only changed in 4.10?

**Comment by leofeyer** [comment]
I guess we could backport the changes. Not sure about the side-effects though.

**Comment by aschempp** [comment]
if it has side effects, it will have them on 4.10 too, so we need to fix them anyway 🤷

**Comment by leofeyer** [comment]
Yes, but we should wait and see if there are any side effects in 4.10 before we also break 4.4 and 4.9. 🤷🏻‍♂️

**Pull request merged**
