### PR TITLE
Add a link to the Contao manual in the back end

### LINKED ISSUE #2491: Link to Contao Manual (Documentation) within Backend
Maybe it would be helpful to provide a link to the documentation in the Contao backend ...

### PR DESCRIPTION
**Pull request by MDevster**
Fixes #2491
Requires that https://github.com/contao/to.contao.org/pull/45 is merged!

grafik
grafik

### CODE REVIEW

**Comment by aschempp** [comment]
Cool! How does it look on mobile?

**Comment by aschempp** [comment]
Also, please remove the translations, everything but english is managed on transifex.com

**Comment by MDevster** [comment]
> Cool! How does it look on mobile?

grafik

**Comment by aschempp** [comment]
ah, I forgot they are still the same 😂 
It looks like the question mark icon is smaller than the others, or is that an optical illusion?

**Review by fritzmg — CHANGES_REQUESTED** [review]
The icon is currently 20x20px and not cropped to the content. It should be 14x14px and cropped to the content.

**Comment by MDevster** [comment]
@fritzmg 
> The icon is currently 20x20px and not cropped to the content. It should be 14x14px and cropped to the content.

If i set it to 14x14px, the icon is smaller than alert. What do you mean with cropped to the content?
`width="14" height="14" viewBox="0 0 24 24"` doesn´t do the job.

grafik

**Comment by fritzmg** [comment]
> What do you mean with cropped to the content?

The icon is currently 20x20px, with a transparent area around the actual icon. The SVG needs to be cropped to 14x14px.

**Comment by MDevster** [comment]
@fritzmg cropped to 14x14px, doesn´t do the job. The icon is to small. Maybe someone can export the SVG correctly, it doesn't work for me.
grafik

**Comment by fritzmg** [comment]
Add the changed SVG to your PR for analysis.

**Comment by fritzmg** [comment]
You only changed `width` and `height` attribute, but the icon itself needs to be changed within the view box.

**Comment by MDevster** [comment]
final version!
grafik
grafik

**Review by fritzmg — CHANGES_REQUESTED** [review]
There are still some line ending changes of the translation files which should be reverted.

**Comment by aschempp** [comment]
Tests also need to be updated for the new menu item 😊

**Comment by leofeyer** [comment]
Would you mind if we used the same icon as on contao.org?



You do not have to do the work yourself, just let me know if you‘d be OK with the change.

**Comment by leofeyer** [comment]
Or maybe we should use the classic "help" icon in both the back end menu and the black bar on contao.org?



Basically any of https://feathericons.com will do.

**Comment by MDevster** [comment]
@leofeyer Feel free to change the icon

**Review by leofeyer — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @MDevster.

**Pull request merged**
