### PR TITLE
Allow searching content elements and members by ID

### LINKED ISSUE #124: Suche bei Artikel um ID für Inhaltselement erweitern
**Description**  
Suche bei Artikel um ID für Inhaltselement erweitern

### PR DESCRIPTION
**Pull request by christianbarkowsky**
Fixes #124

also added at tl_memebers

### CODE REVIEW

**Review by fritzmg — COMMENTED** [review]
#124 mentions articles, however this PR only implements it for content elements and members. Shouldn't it be added to _all_ DCAs with a search panel?

Also you have targeted this towards Contao 4.13. If this is a bugfix, you need to target it towards Contao 4.9. Otherwise 5.x

**Comment by leofeyer** [comment]
> Shouldn't it be added to _all_ DCAs with a search panel?

No, according to the original issue, it is only required for potentially related records.

**Comment by aschempp** [comment]
What's a _potentially related record_ to you?

**Comment by christianbarkowsky** [comment]
What is actually with this? @leofeyer @aschempp

**Comment by leofeyer** [comment]
> Shouldn't it be added to all DCAs with a search panel?

You did not answer this question.

> Also you have targeted this towards Contao 4.13. If this is a bugfix, you need to target it towards Contao 4.9. Otherwise 5.x

And you did not answer this comment, either.

**Comment by christianbarkowsky** [comment]
> Shouldn't it be added to all DCAs with a search panel?

Currently not. Perhaps in the future.


> Also you have targeted this towards Contao 4.13. If this is a bugfix, you need to target it towards Contao 4.9. Otherwise 5.x

Its marked as a feature. A must for 5.x and nice for 4.13.

**Comment by fritzmg** [comment]
> Its marked as a feature.

It's marked as a bug, not a feature.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @christianbarkowsky.

**Pull request merged**
