### PR TITLE
Add foreignKey declaration for form and module fields

### PR DESCRIPTION
**Pull request by rorych**
As asked in the [slack support channel](https://contao.slack.com/archives/CK4J0KNDB/p1706188166398299), there seems to be no reason why the tl_content fields form and module do not have a foreignKey declaration. For the use of "getRelated" method or other logic following the "foreignKey" DCA standards there should be a declaration in my opinion. Hence the pull request.

### CODE REVIEW

**Comment by fritzmg** [comment]
This should be added to `4.13` as a bugfix imho.

**Comment by rorych** [comment]
I made two pull requests, one for 5.3 and one 4.13:
https://github.com/contao/contao/pull/6822

**Comment by leofeyer** [comment]
> This should be added to `4.13` as a bugfix imho.

What makes you think that this is a bugfix?

**Comment by fritzmg** [comment]
> What makes you think that this is a bugfix?

Every database reference field should always have `'foreignKey'` (or `'relation') defined so that `Model::getRelated()` can work (plus so that things like the info popup can show the title, rather than just the ID).

**Comment by leofeyer** [comment]
Where in the back end does this problem occur?

**Comment by rorych** [comment]
It's less a visual but more a logical one. The fields clearly hold a foreignkey of a contao core table, but there is no real relation defined. So if you are building a bundle which depends on the foreignkey logic, it would be correct to set the foreignkeys for these two fields - like everywhere else in the core.

Visually you can see a difference in the info-bubble: 
Without:
ids instead of form or module name:title
With:
name:title of related table

**Comment by fritzmg** [comment]
> Where in the back end does this problem occur?

The issue is also within your PHP controller:

```php
// src/Controller/ContentElement/ExampleElementController.php
namespace App\Controller\ContentElement;

use Contao\ContentModel;
use Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController;
use Contao\CoreBundle\DependencyInjection\Attribute\AsContentElement;
use Contao\FormModel;
use Contao\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

#[AsContentElement(category: 'texts')]
class ExampleElementController extends AbstractContentElementController
{
    protected function getResponse(Template $template, ContentModel $model, Request $request): Response
    {
        /** @var FormModel $formModel */
        if ($formModel = $model->getRelated('form')) { // Cannot work without tl_content.form having foreignKey or relation defined.
            // …
        }
        
        return $template->getResponse();
    }
}
```

**Comment by leofeyer** [comment]
@rorych Agreed. Can you please rebase the PR on the `5.3` branch so I can merge it?

**Comment by fritzmg** [comment]
> I made two pull requests, one for 5.3 and one 4.13:

I think the changes can be merged upstream, but it does not hurt to have it for 5.3 too. However, your PR for 4.13 needs a rebase, as it has too many changes in it.

**Comment by rorych** [comment]
I hope everything is correct now :)

**Comment by leofeyer** [comment]
No, now there are 458 changed files. That cannot be right. 🙈

**Comment by rorych** [comment]
Okay, so i don't have to pr to 5.3 but 5.x right?
Now it's back to 1 file again.

**Comment by fritzmg** [comment]
No, you need to base your PR against `5.3`. You started out with `5.x` and then changed the base to `5.3` afterwards - without rebasing your code. You will need to either rebase your branch - or start from scratch starting from the `5.3` branch this time (or actually `5.2`, technically...).

**Comment by rorych** [comment]
Sorry for the trouble, i find it difficult using the git(hub) logics/gui coming from simple private BitBucket repos.
I'll redo my work tomorrow, as i'm a bit lost right now and don't want to mess up more... 
Should i start from the 5.2 or 5.3 branch now? i'm confused by your comment.

**Comment by fritzmg** [comment]
> Should i start from the 5.2 or 5.3 branch now? i'm confused by your comment.

In principle bugfixes always go into the oldest still supported major version (that is affected). In this case this would be Contao 4.13 and 5.2, as the latter still receives support until Feb 14th - and will receive one last bugfix release before that.

**Comment by leofeyer** [comment]
Yes, you actually don‘t have to do anything here. Your PR for the `4.13` branch will be merged upstream.

**Comment by rorych** [comment]
Should i close this 5.x PR in that case?

**Comment by leofeyer** [comment]
Yes. I have just merged the PR for Contao 4.13. 🎉

**Comment by rorych** [comment]
Resolved via [pr6825](https://github.com/contao/contao/pull/6825)

**Pull request closed without merging**
