### PR TITLE
Require pdo_mysql extension

### PR DESCRIPTION
**Pull request by aschempp**
see https://github.com/contao/contao-manager/issues/606

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
I don't think that this is correct. The app configuration is provided by the manager-bundle and not the core-bundle, therefore the requirement should be in the `composer.json` of the manager-bundle, shouldn't it? If someone uses Contao without the Managed Edition, we should not make assumptions about their DB back end.

**Comment by Toflar** [comment]
Contao uses `FIND_IN_SET()` and other MySQL-specific requirements. Doesn't it?

**Comment by bytehead** [comment]
I'm just curious, would it work also with SQLite?

**Comment by fritzmg** [comment]
Actually may be this should only be a requirement of the `contao/manager-bundle`? Or may be it should not be a requirement at all and we have to use a different approach? After all regardless of whether you are using the Managed Edition or not: you can choose which database driver to use yourself. Isn't only the entry in the `skeleton/config/config.yml` causing a hard dependency? But then again, you could overwrite that in your own config.

**Comment by leofeyer** [comment]
> Contao uses `FIND_IN_SET()` and other MySQL-specific requirements. Doesn't it?

Yes, but these also work with the PHP mysqli extension. We must not assume pdo_mysql unless in the manager-bundle, where we explicitly refer to the PDO constants.

**Comment by m-vo** [comment]
> I'm just curious, would it work also with SQLite?

> you can choose which database driver to use yourself

In theory that's true. :smile:  In reality there are quite some places where it only works with MySQL. I once had a look and think it would be doable to get to a state where every database that's supported by dbal would work with Contao (minus the optimizations). But still a lot of work.

**Comment by fritzmg** [comment]
> In theory that's true. 😄 In reality there are quite some places where it only works with MySQL. I once had a look and think it would be doable to get to a state where every database that's supported by dbal would work with Contao (minus the optimizations). But still a lot of work.

Choosing between `mysqli` and `pdo_mysqli` should be possible.

**Comment by aschempp** [comment]
If a user is supposed to be able to choose between `pdo_mysql` and `mysqli`, maybe we shouldn't use these constants at all?

**Comment by leofeyer** [comment]
It is fine to use the constants in the `config.yml` file, because that is also where you configure the DB back end. If someone wants to use mysqli, they only have to adjust one single file.

**Comment by fritzmg** [comment]
Yes, we can simply add a note in the Contao manual outlining what you have to do, if you want to use `mysqli` instead of `pdo_mysql`. e.g.

```yml
# config/config.yml
doctrine:
    dbal:
        connections:
            default:
                driver: mysqli
                options: ~
```

**Comment by fritzmg** [comment]
Actually that does not work. Even if you add

``` 
doctrine:
    dbal:
        connections:
            default:
                driver: mysqli
                options: ~
```

to your own `config/config.yml`, it will still fail:

```
  [RuntimeException]
  An error occurred while executing the "contao:install-web-dir" command:                                                                                                                                              
  In FileLoader.php line 180:


    [Symfony\Component\Config\Exception\LoaderLoadException]

    The file "vendor\contao\contao\manager-bundle\src/Resources/skeleton/config\config.yml" does not contain valid YAML: The constant "PDO::MYSQL_ATTR_MULTI_STATEMENTS" is not defined at line 52 (near "!php/const PDO::MYSQL_ATTR_MULTI_STATEMENTS: false") in vendor\contao\contao\manager-bundle\src/Resources/skeleton/config\config.yml (which is being imported from "vendor\contao\contao\manager-bundle\src/Resources/skeleton/config/config_prod.yml").




  Exception trace:
    at vendor\symfony\config\Loader\FileLoader.php:180
   Symfony\Component\Config\Loader\FileLoader->doImport() at vendor\symfony\config\Loader\FileLoader.php:104
   Symfony\Component\Config\Loader\FileLoader->import() at vendor\symfony\dependency-injection\Loader\FileLoader.php:66
   Symfony\Component\DependencyInjection\Loader\FileLoader->import() at vendor\symfony\dependency-injection\Loader\YamlFileLoader.php:196
   Symfony\Component\DependencyInjection\Loader\YamlFileLoader->parseImports() at vendor\symfony\dependency-injection\Loader\YamlFileLoader.php:132
   Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load() at vendor\symfony\config\Loader\DelegatingLoader.php:40
   Symfony\Component\Config\Loader\DelegatingLoader->load() at vendor\contao\contao\manager-bundle\src\ContaoManager\Plugin.php:141
   Contao\ManagerBundle\ContaoManager\Plugin::Contao\ManagerBundle\ContaoManager\{closure}() at vendor\symfony\dependency-injection\Loader\ClosureLoader.php:38
   Symfony\Component\DependencyInjection\Loader\ClosureLoader->load() at vendor\symfony\config\Loader\DelegatingLoader.php:40
   Symfony\Component\Config\Loader\DelegatingLoader->load() at vendor\contao\contao\manager-bundle\src\ContaoManager\Plugin.php:145
   Contao\ManagerBundle\ContaoManager\Plugin->registerContainerConfiguration() at vendor\contao\contao\manager-bundle\src\HttpKernel\ContaoKernel.php:186
   Contao\ManagerBundle\HttpKernel\ContaoKernel->registerContainerConfiguration() at vendor\symfony\http-kernel\Kernel.php:699
   Symfony\Component\HttpKernel\Kernel->buildContainer() at vendor\symfony\http-kernel\Kernel.php:595
   Symfony\Component\HttpKernel\Kernel->initializeContainer() at vendor\contao\contao\manager-bundle\src\HttpKernel\ContaoKernel.php:314
   Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer() at vendor\symfony\http-kernel\Kernel.php:136
   Symfony\Component\HttpKernel\Kernel->boot() at vendor\symfony\framework-bundle\Console\Application.php:169
   Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands() at vendor\symfony\framework-bundle\Console\Application.php:75
   Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor\symfony\console\Application.php:149
   Symfony\Component\Console\Application->run() at vendor\contao\contao\manager-bundle\bin\contao-console:38
```

So if we want to support MySQL drivers other than `pdo_mysql`, I think we have to change the Manager Bundle, so that it adds `doctrine.dbal.connections.default.options` via the Manager Plugin (`if (class_exists(PDO::class))`), not via the Skeleton.

**Comment by ausi** [comment]
How about using the constant value `1013` directly?

**Comment by fritzmg** [comment]
That won't work either:

```
In InvalidOption.php line 24:

  [Doctrine\DBAL\Driver\Mysqli\Exception\InvalidOption]  
  Failed to set option 1013 with value ""


Exception trace:
  at vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\Mysqli\Exception\InvalidOption.php:24
 Doctrine\DBAL\Driver\Mysqli\Exception\InvalidOption::fromOption() at vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\Mysqli\MysqliConnection.php:263
 Doctrine\DBAL\Driver\Mysqli\MysqliConnection->setDriverOptions() at vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\Mysqli\MysqliConnection.php:75
 Doctrine\DBAL\Driver\Mysqli\MysqliConnection->__construct() at vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\Mysqli\Driver.php:16
 Doctrine\DBAL\Driver\Mysqli\Driver->connect() at vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:362 Doctrine\DBAL\Connection->connect() at vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:427
 Doctrine\DBAL\Connection->getDatabasePlatformVersion() at vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:387
 Doctrine\DBAL\Connection->detectDatabasePlatform() at vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php:330
 Doctrine\DBAL\Connection->getDatabasePlatform() at vendor\doctrine\doctrine-bundle\ConnectionFactory.php:77
 Doctrine\Bundle\DoctrineBundle\ConnectionFactory->getDatabasePlatform() at vendor\doctrine\doctrine-bundle\ConnectionFactory.php:57
 Doctrine\Bundle\DoctrineBundle\ConnectionFactory->createConnection() at var\cache\prod\ContainerNxq3off\appProdProjectContainer.php:727
 ContainerNxq3off\appProdProjectContainer->getDoctrine_Dbal_DefaultConnectionService() at var\cache\prod\ContainerNxq3off\getContao_Cache_WarmInternalService.php:8
 require() at var\cache\prod\ContainerNxq3off\appProdProjectContainer.php:685
 ContainerNxq3off\appProdProjectContainer->load() at var\cache\prod\ContainerNxq3off\getCacheWarmerService.php:15
 ContainerNxq3off\appProdProjectContainer->{closure}() at vendor\symfony\symfony\src\Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate.php:29
 Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate->__construct() at var\cache\prod\ContainerNxq3off\getCacheWarmerService.php:16
 require() at var\cache\prod\ContainerNxq3off\appProdProjectContainer.php:685
 ContainerNxq3off\appProdProjectContainer->load() at vendor\symfony\symfony\src\Symfony\Component\DependencyInjection\Container.php:304
 Symfony\Component\DependencyInjection\Container->get() at vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:686
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at vendor\contao\contao\manager-bundle\src\HttpKernel\ContaoKernel.php:216
 Contao\ManagerBundle\HttpKernel\ContaoKernel->initializeContainer() at vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php:135
 Symfony\Component\HttpKernel\Kernel->boot() at vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php:64
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at vendor\symfony\symfony\src\Symfony\Component\Console\Application.php:148
 Symfony\Component\Console\Application->run() at vendor\contao\contao\manager-bundle\bin\contao-console:48 
```

**Comment by ausi** [comment]
Even if you overwrite it with `options: ~` ?

**Comment by fritzmg** [comment]
> Even if you overwrite it with `options: ~` ?

No, but if you have to overwrite it anyway, then we might as well leave the constant in.

**Comment by leofeyer** [comment]
> So if we want to support MySQL drivers other than `pdo_mysql`, I think we have to change the Manager Bundle, so that it adds `doctrine.dbal.connections.default.options` via the Manager Plugin (`if (class_exists(PDO::class))`), not via the Skeleton.

That is correct IMHO.

**Pull request closed without merging**
