### PR TITLE
Deprecate Calendar::addEvent()

### PR DESCRIPTION
**Pull request by ausi**
See https://github.com/contao/contao/pull/5141#discussion_r945846928 and https://github.com/contao/contao/pull/5152#issuecomment-1215214386

### CODE REVIEW

**Comment by aschempp** [comment]
Isn't this method supposed to be used by third party modules? Pretty sure a lot of calendar extensions use that 🤔

**Comment by fritzmg** [comment]
Extensions likely use the `getAllEvents` hook - unless they completely override the XML generation for example.

**Review by aschempp — APPROVED** [review]
I now noticed this is only a helper class, I though it is part of a front end module. Then we should be fine to change that 👍

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
