### PR TITLE
Tag the http cache with page trail

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/4699

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by ausi** [comment]
https://github.com/contao/contao/issues/4699#issuecomment-1131600298

> Wouldn’t it fit the current concept better if we would fix this in the backend?
> 
> We currently invalidate all parent (ptable) and all child (ctable) items, I think we should extend that so that parent and child items from tree views are handled the same way.

With the implementation of this pull request, changing any content element in one of the pages in the trail would clear the cache which is not desired, is it?

**Review by Toflar — CHANGES_REQUESTED** [review]
The root page id is missing. This means the problem with e.g. the maintenance mode or any root page layout changes would not be applied.

Also, I personally do think this is correct but @ausi and @fritzmg said they'd rather invalidate the whole tree in the back end. How come @fritzmg is now approving this?

**Comment by aschempp** [comment]
> With the implementation of this pull request, changing any content element in one of the pages in the trail would clear the cache which is not desired, is it?

No, that's not the case. Changing a content element would purge the `tl_content.XX` ID, which is not present on child pages. It would not purge the page cache ID. However, changing the title of a parent page would purge all child pages. But that could be desired, e.g. for a breadcrumb or because not the title but the permissions was changed.


> The root page id is missing.

I don't think that's true. `PageModel::loadDetails()` does this:

```
if ($type != 'root')
{
    $trail[] = $objParentPage->pid;
}
```

Which means the **parent ID** of all pages are added, and the parent ID of the first page within a root will be the root ID.

**Review by Toflar — APPROVED** [review]

**Comment by Toflar** [comment]
This will be hard to merge in 4.13 as we have a entity tagger service there. I wonder if that service should somehow automatically understand if we have a tree structure and tag the parents itself. Or maybe we need some kind of `getTrail()` interface on the model, I don't know. /cc @m-vo

**Comment by ausi** [comment]
> No, that's not the case. Changing a content element would purge the `tl_content.XX` ID, which is not present on child pages.

I’m unable to reproduce that.

Saving a content element purges the following tags in my test:

- `contao.db.tl_content.XX`
- `contao.db.tl_article.XX`
- `contao.db.tl_page.XX`
- `contao.db.tl_page`

**Comment by ausi** [comment]
For reference, we agreed on the current concept (tag few, invalidate many) here: https://github.com/contao/contao/issues/2137#issuecomment-681944410

**Comment by Toflar** [comment]
Yeah, I can see the problem. This is because we already take all the parents and children in https://github.com/contao/contao/blob/5.x/core-bundle/src/Resources/contao/classes/DataContainer.php#L1487.
So I wonder why it doesn't work if I edit the root page? It should invalidate all children then, no? 🤔

**Comment by ausi** [comment]
> So I wonder why it doesn't work if I edit the root page? It should invalidate all children then, no? 🤔

Yes, it should, but we just have not implemented this for tree structures yet, but only for ptable and ctable.

**Comment by Toflar** [comment]
Ah, I agree we should do this instead then. Let me fix that.

**Comment by Toflar** [comment]
Meh, a lot more questions arise so stopping here and marking `up for discussion`.

**Review by ausi — CHANGES_REQUESTED** [review]
See https://github.com/contao/contao/pull/4714#issuecomment-1135542708

**Comment by fritzmg** [comment]
> How come @fritzmg is now approving this?

It seemed like a sensible solution. But I was not aware that editing one content element would then also invalidate the whole trail.

**Comment by m-vo** [comment]
>  I wonder if that service should somehow automatically understand if we have a tree structure and tag the parents itself. Or maybe we need some kind of getTrail() interface on the model, I don't know

Hmm, I tried to automate things for entities, but gave up on that idea, because everything was very use-case-dependent. I mean, we could know what the usage is and if a change affects you or not for specific fields/combinations, but not in general.

**Comment by leofeyer** [comment]
As discussed in the Contao call, this should not be necessary. @Toflar will create a follow-up PR.

**Pull request closed without merging**
