### PR TITLE
Do not make a response private if the session is empty

### PR DESCRIPTION
**Pull request by Toflar**
Same as https://github.com/contao/contao/pull/6801 for the `MakeResponsePrivateListener`.

### CODE REVIEW

**Review by fritzmg — COMMENTED** [review]
Isn't this also missing for the [ContaoCsrfTokenManager](https://github.com/contao/contao/blob/a3d78cba240b25db9736491e22507f9fd5fa9cb8/core-bundle/src/Csrf/ContaoCsrfTokenManager.php#L102)?

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Comment by leofeyer** [comment]
> Isn't this also missing for the [ContaoCsrfTokenManager](https://github.com/contao/contao/blob/a3d78cba240b25db9736491e22507f9fd5fa9cb8/core-bundle/src/Csrf/ContaoCsrfTokenManager.php#L102)?

I think so, too.

**Comment by fmenzel** [comment]
Has this been applied to the ContaoCsrfTokenManager yet?

**Comment by fritzmg** [comment]
Yes, see https://github.com/contao/contao/pull/7052
But it has not been released yet.

**Pull request merged**
