### PR TITLE
Correctly add the install tool redirect in prod

### PR DESCRIPTION
**Pull request by aschempp**
Looks like the `/contao/install.php` redirect did never work in prod environment? 🤔

### CODE REVIEW

**Comment by bytehead** [comment]
Tests do fail...

**Comment by aschempp** [comment]
so we have a test that verifies the redirect is not there in production. But I can't imagine this to be right, wdyt @contao/developers ?

**Comment by leofeyer** [comment]
Contao 4 has been around for years now, so if the redirect never worked, we might as well remove it at this point.

**Comment by aschempp** [comment]
That's true 😂 
Since we already remove that in Contao 5, I think we'll just keep it as is. Closing this then.

**Pull request closed without merging**
