### PR TITLE
Add insert tag flags utf8_ucfirst, utf8_lcfirst, utf8_ucwords

### LINKED ISSUE #6227: Add flags utf8_ucfirst, utf8_lcfirst, utf8_ucwords
### Description

I am currently building a French website where I am using insert tags. I want the first letter of each word that I am using the insert tags for to be capitalized. For this I am using the flag `|ucfirst` which works fine for the majority of cases. However, if the first letter of the word starts with a special character (e.g. as in "économie") then this flag does not work.

I would therefore suggest adding a version of this flag as well as two further flags that perform a unicode-conscious conversion. Based on the already existing flags `utf8_strtolower` and `utf8_strtoupper` I would therefore suggest the following naming:

- `utf8_ucfirst`
- `utf8_lcfirst`
- `utf8_ucwords`

FYI: Before posting this request, I searched the repository for any existing tickets regarding this topic and found this:
https://github.com/contao/core/issues/991
I am not sure, if this was ever implemented -- however in my Contao 4 installation and according to the [official documentation ](https://docs.contao.org/manual/en/article-management/insert-tags/) these flags don't exist yet:

### PR DESCRIPTION
**Pull request by ausi**
Fixes #6227

### CODE REVIEW

**Comment by Toflar** [comment]
I don't really like this to be honest. I mean we're talking about insert tags here that are used by users. In what world would they ever NOT want to have multi-byte `strtoupper()`? Can't we just always use the multibyte variants for `ucfirst` and Co.? 🤔

**Comment by Toflar** [comment]
Or maybe we should just implement a much more powerful `string()` flag or so, that would make use of `symfony/string`? Then we can deprecate the other ones. Just thinking out loud, not sure if that's a good idea but it would cover a lot more use cases :D

**Comment by leofeyer** [comment]
> Can't we just always use the multibyte variants for `ucfirst` and Co.? 🤔

I think so, too.

**Comment by ausi** [comment]
Closed in favor of #6940 and #6941

**Pull request closed without merging**
