### PR TITLE
Use real path for `.env.local`

### LINKED ISSUE #6065: Contao replaces symlink to .env.local with regular file
### Affected version(s)

4.13

### Description

Contao auto-generates `APP_SECRET` env variable if it is not set or has default value (added in #5951 and #5066). However, if a Contao installation was deployed by Deployer, then `.env.local` is a symlink, because it is a shared file according to [Symfony Deployer recipe](https://github.com/deployphp/deployer/blob/ed28cb1cba33747f08ea7c14d6801cdde10fab97/recipe/symfony.php#L18-L20). In that case, Contao erases the symlink and recreates `.env.local` as a regular file.

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #6065 

Same as https://github.com/contao/contao/pull/6066 for Contao 4.9.

### CODE REVIEW

**Comment by ausi** [comment]
If we get lucky and https://github.com/symfony/symfony/pull/50437 gets merged, we can close this I think.

**Comment by fritzmg** [comment]
Your PR is for Symfony 5.4 (Symfony 4.4 is security only).

**Comment by ausi** [comment]
Contao 4.9 is compatible with `symfony/filesystem` 5.4 https://github.com/contao/contao/blob/0f0bea8048d667cc0906a9da1e88e8d5af0c2e92/composer.json#L99 but yes, some setups might still use 4.4 due to conflicting dependencies.

**Comment by fritzmg** [comment]
Ah nice, didn't realise 👍

**Comment by ausi** [comment]
> If we get lucky and [symfony/symfony#50437](https://github.com/symfony/symfony/pull/50437) gets merged, we can close this I think.

Symfony 6.2.12 and 5.4.25 got released today including this fix.

I think this can be closed. Or do you want to explicitly support Symfony 4.4 too @fritzmg ?

**Comment by fritzmg** [comment]
No, since `symfony/filesystem` `5.4` is installable in Contao 4.9, we can close this imho 👍

**Pull request closed without merging**
