### PR TITLE
Do not add CSS class to multiple elements

### LINKED ISSUE #2203: CSS-Klasse wird mehrfach ausgegeben
**Affected version(s)**

Contao 4.9.5

**Description**

- Ein neues Inhaltselement vom Typ Modul einfügen und in den Experteneinstellungen die Klasse `test-01` hinzufügen.
- Ein zweites Inhaltselement vom Typ Modul einfügen und in den Experteneinstellungen die Klasse `test-02` hinzufügen.

CSS-Ausgabe im Frontend beim ersten Element:
`mod_listing test-01 ce_table listing block`

CSS-Ausgabe im Frontend beim zweiten Element:
`mod_listing test-01 test-02 ce_table listing block`

Aus irgendeinem Grund, wird die Klasse vom ersten Element auch im zweiten Element ausgegeben.

Problem trat bei mir nach einem Update von 4.9.2 auf 4.9.5 auf.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2203
| Docs PR or issue | -

This reverts commit 17080345cf4d3febcd899b98600a54fbd37542c5.

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
We need to fine a new solution for https://github.com/contao/contao/issues/1947 though as well, right?

**Comment by leofeyer** [comment]
Yes, but that is a separate issue. This PR is about fixing the bug introduced by 1708034.

**Comment by aschempp** [comment]
so we need to reopen https://github.com/contao/contao/issues/1947 ? Why not fix it in this PR?

**Comment by leofeyer** [comment]
Because we do not know how to fix it yet.

**Comment by leofeyer** [comment]
I have reopened #1947.

**Pull request merged**
