### PR TITLE
Move the logic from LogoutHandler to LogoutSuccessListener

### LINKED ISSUE #2862: Deprecated classes in Symfony 5.1
Deprecated since Symfony version 5.1

Interfaces:

- `Symfony\Component\Security\Http\Logout\LogoutHandlerInterface`
- `Symfony\Component\Security\Http\Logout\LogoutSuccessHandlerInterface`

Classes:
- `Symfony\Component\Security\Http\Logout\DefaultLogoutSuccessHandler`

We should check if we can update/remove the usage of those classes (without breaking compatibility with other Symfony versions), or otherwise keep this issue active until we increase the Symfony requirement to 5.1 or higher.

Related: #2857

**Update 2021-07-19:** Also check `Symfony\Component\EventDispatcher\LegacyEventDispatcherProxy` from #3206

### LINKED ISSUE #3998: LogoutHandler not executed for back end logouts
### Affected version(s)

4.12, 4.13

### Description

In Contao 4.12 and 4.13 the `Contao\CoreBundle\Security\Logout\LogoutHandler` is not executed for back end logouts in the Contao Managed Edition, only for front end logouts (which also means the `postLogout` hook is not executed). In Contao 4.9 said `LogoutHandler` is correctly executed for front end and back end logouts. You'll also notice that you won't find any _User "…" has logged out_ system log entries for back end logouts in 4.12 and up.

Interestingly the `Contao\ManagerBundle\Security\Logout\LogoutHandler` _is_ called.

### PR DESCRIPTION
**Pull request by bytehead**
Fixes #2862 and #3998

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by leofeyer** [comment]
What do you think about https://github.com/bytehead/contao/pull/5?

**Comment by bytehead** [comment]
> What do you think about https://github.com/bytehead/contao/pull/5?

Fine with me, if we agree on changing the constructor signature (@ausi / @fritzmg)?

**Comment by leofeyer** [comment]
You are right, we should not remove the constructor arguments. I have adjusted the PR accordingly.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
