### PR TITLE
Use host name without port in some controllers

### LINKED ISSUE #4602: Sitemap, Robots and Favicon controller always return 404 with domain and port
### Affected version(s)

4.13, 5.x

### Description

1. Configure a DNS entry for your root page, e.g. `contao.local`
2. Run the application on some port, e.hg. `8000`
3. Request contao.local:8000/sitemap.xml

The response will always be 404, because `$request->server->get('HTTP_HOST')` always includes the port. The port however is not configured in the DNS page settings, because it is supposed to be port agnostic – hence the matching fails. 

See [RobotsTxtController](https://github.com/contao/contao/blob/2f178ccfbaaa1db7eb1f3a9018d530e3338e7796/core-bundle/src/Controller/RobotsTxtController.php#L46), [SitemapController](https://github.com/contao/contao/blob/2f178ccfbaaa1db7eb1f3a9018d530e3338e7796/core-bundle/src/Controller/SitemapController.php#L45) and [FaviconController](https://github.com/contao/contao/blob/2f178ccfbaaa1db7eb1f3a9018d530e3338e7796/core-bundle/src/Controller/FaviconController.php#L46).

As the other issues with DNS settings and ports other than 80 it probably only affects some dev environments, but since it is supposed to be port agnostic, I think we should fix this.

### PR DESCRIPTION
**Pull request by bezin**
Fixes #4602

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by fritzmg** [comment]
@bezin can you make a separate PR for Contao 4.9 for the `FaviconController` and `RobotsTxtController`?

**Comment by Toflar** [comment]
Looks good to me but I'd like to have tests for that in order to not have regression bugs :)

**Comment by bezin** [comment]
I added a test draft for SitemapController. Not sure if this is the way to go tbh. Maybe one test case with domain and port is sufficient?

**Comment by Toflar** [comment]
Oh :D Yeah I think one isolated testcase that just asserts that `findPublishedFallbackByHostname()` is called with the correct host whould be enough. The rest is not relevant for that imho.

**Review by Toflar — APPROVED** [review]
Perfect! ❤️

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bezin.

**Pull request merged**
