### PR TITLE
Optimize importing DB fixtures in the functional tests

### PR DESCRIPTION
**Pull request by leofeyer**
This PR ensures that DB fixtures are not reloaded if they have not changed. Since we are heavily using data providers in the functional routing tests, fixtures had been reloaded for every single test. Together with https://github.com/contao/test-case/commit/70e5a1432900ef1139331764a5f9b3173961bb96, I was able to decrease the execution time from 51.41 seconds to 22.05 seconds. 💪

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Comment by Toflar** [comment]
That means that if a test changes the data during the test, the next one will be affected. Doesn't it?

**Comment by leofeyer** [comment]
That is correct. However, a test is not supposed to change the database directly; it should load a new fixture set instead.

**Review by Toflar — CHANGES_REQUESTED** [review]
I completely disagree with this statement. Every test can do whatever it wants to do with the data, that's the whole purpose of functional tests.
Fixtures put the database in a fixed state before running a test. The test itself can then update, delete, modify the database the way it likes and assert things work properly in isolation.
The tests coming after that must have the same fixed and clean state again which they won't have anymore with this PR.

If you want to optimize this, you need to compare if the database has remained completely unchanged during a test.

**Comment by leofeyer** [comment]
> The tests coming after that must have the same fixed and clean state again which they won't have anymore with this PR.

True.

**Comment by Toflar** [comment]
By the way, I'm using https://github.com/dmaicher/doctrine-test-bundle in my projects, you might want to give this a shot and see if that speeds up our testsuite and works for us too :)

**Comment by m-vo** [comment]
What we probably could eliminate, though, is booting a new kernel on each `static::loadFixtures()` call, can't we?

**Comment by leofeyer** [comment]
Yes, I have optimized that in #1872.

**Comment by leofeyer** [comment]
FYI, I have tried `dmaicher/doctrine-test-bundle` but it did not speed things up any further.

**Comment by leofeyer** [comment]
> That means that if a test changes the data during the test, the next one will be affected.

I have been rethinking this and I conclude that @Toflar's objection – albeit correct – does not apply here. The routing test does not alter the database except for importing new fixtures, therefore the optimization is fine in this particular case IMHO.

@ausi @aschempp WDYT?

**Comment by aschempp** [comment]
@Toflar is absolutely correct, the whole point of a DB fixtures is to ensure a fixed DB structure **for each test**. 

However, as this optimization is only for one test, and we **know** this test does not change the DB, I can agree to it. But it can't be a general rule…

**Comment by leofeyer** [comment]
Correct. That's why I said "his objection does not apply here" and not "his objection is wrong". 😉

**Comment by Toflar** [comment]
Just leaving this here for the future: I would've never approved this change and some day, someone will go down the rabbit hole and debug why their tests do not work out as expected and land back here.

**Comment by leofeyer** [comment]
I highly doubt that, because the optimization only applies to one single, specific class that is fully under our control. I do not see how this could ever affect another class, leave alone someone else's tests. 🤷‍♂️

**Pull request merged**
