### PR TITLE
Use the Stimulus color picker instead of the old MooTools one

### PR DESCRIPTION
**Pull request by zoglo**
## Description

_Previous attempt to "fix" #7548 for the upcoming contao 5.5 release_

Replaces the color-picker with the [stimulus-color-picker](https://www.stimulus-components.com/docs/stimulus-color-picker) and uses the monolith theme.

Making changes / rebuilding the assets needs a `npm ci` :)

### Changes / Additions

**Stimulus-controller*
Instead of simply adding the component, I did add a controller to override the onsave method to comply with Contao by stripping the first `#` if it exists, it still correctly loads the value.

**CSS**
There is a little bit of custom CSS that I added to make sure there is a dark-mode + aligning it within the widget.

## Screenshots

image
image

## What about multiple fields?

Even MooRainbow only ever allowed a single field to be used to save the value. This is handled by the controller itself as it will pick the first `data-contao--color-picker-target`.

image

## What about MooRainbow?

There is extensions that still use MooRainbow, I'd deprecate MooRainbow but not remove it in Contao 5.x
https://github.com/contao-community-alliance/contao-multicolumnwizard-bundle/blob/8537e008ce15e366f46c6017764f07015379d5b4/src/EventListener/Mcw/ColorPicker.php#L96
https://github.com/heimrichhannot/contao-multi-column-editor-bundle/blob/7a410c939b33493220a0260a6b6bda0720b92c21/src/Widget/MultiColumnEditor.php#L671

### CODE REVIEW

**Comment by leofeyer** [comment]
As discussed in the call, the color field should replace the color picker icon, not the text field. We need a JavaScript that writes the selected value into the text field.

**Comment by leofeyer** [comment]
@ausi Which color picker would you prefer in your themes?

**Comment by leofeyer** [comment]
As further discussed, we want to use https://www.stimulus-components.com/docs/stimulus-color-picker 😄

**Comment by zoglo** [comment]
@aschempp I'm unsure how we'd be able to handle the deprecation notice. Would it only ever trigger if it would find a MooRainbow Instance? Is it possible to switch them to this controller instead like in the `scroll-offset-controller` or the `toggle-fieldset-controller`?

**Comment by leofeyer** [comment]
IMHO we can merge the PR as it is now. If a third-party extension uses the `MooRainbow` class, it will have (or at least should have) directly  required `contao-components/colorpicker` anyway.

**Comment by zoglo** [comment]
Should we remove these lines as well @leofeyer ?
https://github.com/contao/contao/blob/ab582f78482977745b1403d4173c92c8316c7ee7/core-bundle/contao/templates/backend/be_main.html5#L15 and https://github.com/contao/contao/blob/ab582f78482977745b1403d4173c92c8316c7ee7/core-bundle/contao/templates/backend/be_main.html5#L25 

and obviously that as well?
https://github.com/contao/contao/blob/ab582f78482977745b1403d4173c92c8316c7ee7/composer.json#L51

There is no other occurence that I am aware of

**Comment by leofeyer** [comment]
Yes, all of them. A third-party extension can add them again dynamically.

**Comment by zoglo** [comment]
Removed them in df9ce314d17a0f5d6eaf470dcc8814ad6013d873 however there's a failing monorepo check, unsure how to handle that one.

**Comment by leofeyer** [comment]
You also have to remove the dependency in the `core-bundle/composer.json` file.

**Comment by zoglo** [comment]
Failing coverage check is unrelated (seems to happen to other PRs as well)

**Review by leofeyer — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @zoglo.

**Pull request merged**
