### PR TITLE
fix mtime check in generateScriptTag

### PR DESCRIPTION
**Pull request by fritzmg**
If you use `Template::generateScriptTag(…)` without a custom `$mtime` parameter, the expected behaviour would be that the filemtime is pulled automatically from the file. However this does not work currently since the default value for that parameter is `false` and the function checks for `$mtime === null` instead of `$mtime === false`.

### CODE REVIEW

**Comment by leofeyer** [comment]
Ah, that is because we changed the default in contao/core-bundle#1404.

**Comment by fritzmg** [comment]
Isn't this the wrong milestone? This only affects Contao 4.6+. This feature is not present in Contao 4.4 or 4.5.

**Comment by leofeyer** [comment]
You are right. Fixed. 😊

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Comment by fritzmg** [comment]
I just noticed a discrepancy between `Template::generateStyleTag` and `Template::generateScriptTag`:

After the change from https://github.com/contao/contao/pull/42 (this PR), `generateScriptTag` has a default value of `false` for the `$mtime` parameter and checks for `false` on that parameter when determining whether to pull the `mtime` from the file itself.

In `generateStyleTag` on the other hand, the default value of `$mtime` is also `false`, but it checks for `null` on that parameter when determining whether to pull the `mtime` from the file itself.

So `generateStyleTag` has the following behavior:

* If you pass `false`, cache busting __will not__ will be used. _(Default)_
* If you pass `null`, the `mtime` will be pulled from the file and cache busting will be used.
* If you pass something other than `false` or `null` cache busting will be used.

While `generateScriptTag` has the following behavior now:

* If you pass `false`, the `mtime` will be pulled from the file and cache busting will be used. _(Default)_
* If you pass `null`, cache busting parameter __will not__ be used.
* If you pass something other than `false` or `null`, cache busting will be used.

**Comment by leofeyer** [comment]
Then we should revert the changes from this PR so the script tag method behaves identically to the style tag method.

**Comment by fritzmg** [comment]
Agreed. Sorry for the confusion. I'll also adjust #136 accordingly.

**Comment by leofeyer** [comment]
Reverted in cc1150ecc49dcf0f13e4fc00690756ae2889b4bc.

**Pull request merged**
