### PR TITLE
Make `config.sql` optional in the DCA

### LINKED ISSUE #4050: DCA table not created without keys definition
### Affected version(s)

4.9+

### Description

If you create the following DCA:

```php
// contao/dca/tl_foobar.php
$GLOBALS['TL_DCA']['tl_foobar'] = [
    'config' => [
        'dataContainer' => 'Table',
    ],
    'fields' => [
        'foobar' => [
            'sql' => ['type' => 'integer', 'unsigned' => true, 'default' => 0],
        ],
    ],
];
```

`contao:migrate` will not create the table. It will only create the table if `config.sql.keys` is defined, for example:

```php
// contao/dca/tl_foobar.php
$GLOBALS['TL_DCA']['tl_foobar'] = [
    'config' => [
        'dataContainer' => 'Table',
        'sql' => [
            'keys' => [
                'foobar' => 'index',
            ],
        ],
    ],
    'fields' => [
        'foobar' => [
            'sql' => ['type' => 'integer', 'unsigned' => true, 'default' => 0],
        ],
    ],
];
```

However, if you want Contao to create an arbitrary table and you do not need any primary key or regular index, it should not be required to define one, should it?

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #4050

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Comment by m-vo** [comment]
Now `$this->blnIsDbTable = true;` will get set every time (L592). Is this correct?

**Comment by leofeyer** [comment]
It will not be set if there are no fields (`empty($fields)`).

**Comment by m-vo** [comment]
> It will not be set if there are no fields (empty($fields)).

But that means my custom DCA that did not have a `sql` section to begin with because it uses entities (and that has fields) will now receive that setting. Maybe that doesn't make a difference, I'm just wondering.

**Comment by fritzmg** [comment]
Yeah, may be `$this->blnIsDbTable` should be true if there was either `config.sql` set _or_ `fields.<field>.sql`.

**Comment by leofeyer** [comment]
> either `config.sql` set _or_ `fields.<field>.sql`

What is the use case for having a table with only keys but no columns?

**Comment by frontendschlampe** [comment]
After updating to 4.9.27 I got the following error in Install Tool:

```
Doctrine\DBAL\Exception:
No columns specified for table tl_metamodel_item

  at vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:254
  at Doctrine\DBAL\DBALException::noColumnsSpecifiedForTable('tl_metamodel_item')
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:1567)
  at Doctrine\DBAL\Platforms\AbstractPlatform->getCreateTableSQL(object(Table), 1)
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php:144)
  at Doctrine\DBAL\Schema\SchemaDiff->_toSql(object(MySQL57Platform), false)
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaDiff.php:100)
  at Doctrine\DBAL\Schema\SchemaDiff->toSql(object(MySQL57Platform))
     (vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Schema.php:431)
  at Doctrine\DBAL\Schema\Schema->getMigrateToSql(object(Schema), object(MySQL57Platform))
     (vendor/contao/installation-bundle/src/Database/Installer.php:142)
  at Contao\InstallationBundle\Database\Installer->compileCommands()
     (vendor/contao/installation-bundle/src/Database/Installer.php:58)
  at Contao\InstallationBundle\Database\Installer->getCommands()
     (vendor/contao/installation-bundle/src/Controller/InstallationController.php:383)
  at Contao\InstallationBundle\Controller\InstallationController->adjustDatabaseTables()
     (vendor/contao/installation-bundle/src/Controller/InstallationController.php:104)
  at Contao\InstallationBundle\Controller\InstallationController->installAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:31)
```

I talked to @discordier and MM uses this function since the beginning of Catalog. That's a problem if it's changed now. :-/

**Comment by fritzmg** [comment]
@frontendschlampe please create a new issue about that.

**Pull request merged**
