### PR TITLE
use image alt or label if insert tag alt is not set

### PR DESCRIPTION
**Pull request by MDevster**
Implements contao/core-bundle#936.

### CODE REVIEW

**Comment by MDevster** [comment]
issue https://github.com/contao/core-bundle/issues/936

**Review by Toflar — APPROVED** [review]

**Comment by ausi** [comment]
Instead of using both meta alt and title for the `alt=""` attribute we should use meta alt for `alt=""` and meta title for `title=""` IMO.

**Comment by leofeyer** [comment]
@ausi The `image` insert tag does not support the `title` tag (yet). But I agree that we should not use the image title as alternative text, so I have adjusted the PR accordingly. Can you please check again?

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @MDevster.

**Pull request merged**
