### PR TITLE
Use Throwable instead of Exception

### PR DESCRIPTION
**Pull request by leofeyer**
I am not 100% sure if there are cases where we want to catch exceptions but not throwables?

### CODE REVIEW

**Comment by Toflar** [comment]
I don't think we want that? Why would we want to catch PHP internal errors here? We'e throwing userland exceptions everywhere and we only catch those which is correct imho.

**Comment by leofeyer** [comment]
IDK. We have had issues with this in the past (e.g. b2976b75590e9490843bd0246122fa1644ce660f), so I wanted to discuss it.

**Comment by Toflar** [comment]
Yeah it's different in the exception listeners because they shall catch both of course :)

**Comment by leofeyer** [comment]
I agree. @aschempp Do you agree as well?

**Review by Toflar — CHANGES_REQUESTED** [review]
I actuall don't request changes, I think the PR is not relevant :)

**Comment by aschempp** [comment]
🤷‍♂  I think it's true that it makes no sense to catch any error… except for cases where we handle errors or _know_ to catch errors and not only exceptions.

**Pull request closed without merging**
