### PR TITLE
Only consider the main request in the `MergeHttpHeadersListener` class

### PR DESCRIPTION
**Pull request by Toflar**
Looks like `header_remove()` does not work properly in all cases so we have to remember which ones are already cleared and diff them manually. Otherwise we'll keep merging the same headers over and over forever which causes performance issues (more apparent in Contao 5 due to more sub requests).

### CODE REVIEW

**Comment by ausi** [comment]
But wouldn’t this mean, that if two sub requests send the same header, now in the second subrequest this header would be ignored?

**Review by leofeyer — DISMISSED** [review]

**Comment by Toflar** [comment]
> But wouldn’t this mean, that if two sub requests send the same header, now in the second subrequest this header would be ignored?

Yes. Which is the logic we want. The responses themselves are merged as well. We only fetch the ones added during the very subrequest and then clear: https://github.com/contao/contao/blob/4.13/core-bundle/src/EventListener/MergeHttpHeadersListener.php#L99-L100

**Comment by aschempp** [comment]
If a subrequest adds **the very same header** again, it is currently added to that subrequests response again. With this PR it would not be added again.

However, I think we should change the `MergeHttpHeadersListener` to only handle the main request. That would fix fragments problems as well.

**Review by bytehead — APPROVED** [review]

**Comment by Toflar** [comment]
As discussed during the Contao call today, we decided to only run the listener on the main request as this is a helper for super-legacy elements which - in case they used some `header()` feature - only worked for the main request anyway.

**Review by fritzmg — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
