### PR TITLE
Update ModuleRegistration.php

### LINKED ISSUE #2240: \Controller::redirect() not working in save_callback in ModuleRegistration
**Affected version(s)**

Contao 4.9.5

**Description**

If i use the \Controller::redirct()-Method in a DCA save_callback in ModuleRegistration, the Widget shows "This exception has no message. Use $exception->getResponse() instead." 
I think its because of the thrown RedirectResponseException.

### PR DESCRIPTION
**Pull request by SGehle**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2240

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
Please catch and re-throw the parent class `ResponseException` not just redirects.

**Comment by m-vo** [comment]
btw.: This is a textbook example why you should never catch `\Exception` in your business logic.

**Comment by fritzmg** [comment]
@SGehle the same problem exists in `ModulePersonalData`. Can you confirm this and update accordingly?

**Comment by SGehle** [comment]
Yes, i can confirm the same problem - fixed it.

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @SGehle.

**Pull request merged**
