### PR TITLE
Add font smoothing for Safari on retina displays

### PR DESCRIPTION
**Pull request by leofeyer**

### CODE REVIEW

**Comment by m-vo** [comment]
Shouldn't this go into 4.4?

**Comment by leofeyer** [comment]
No, because Contao 4.4 uses a web font instead of a native font stack.

**Review by bytehead — APPROVED** [review]

**Comment by m-vo** [comment]
Ah, right. My bad.

**Comment by ausi** [comment]
I think we should not add this. See https://usabilitypost.com/2012/11/05/stop-fixing-font-smoothing/

**Comment by leofeyer** [comment]
I think so, too. It turned out to be a problem on my iMac. 🙈

**Pull request closed without merging**
