### PR TITLE
Add a PHP CS Fixer action

### PR DESCRIPTION
**Pull request by leofeyer**
This PR adds a GitHub action that automatically fixes CS issues in pull requests.

### CODE REVIEW

**Review by Toflar — APPROVED** [review]
Cool!

**Comment by aschempp** [comment]
What if I disagree with the CS Fixer? 😂

**Comment by m-vo** [comment]
Does this add a commit on my branch as soon as I initially create a PR/push changes with non compliant CS? What happens if the checkbox 'allow edits from maintainers' isn't checked?

**Comment by leofeyer** [comment]
> What if I disagree with the CS Fixer? 😂

That is not an option. 😂 

> What happens if the checkbox 'allow edits from maintainers' isn't checked?

We will ask you to do so then.

**Pull request merged**
