### PR TITLE
Correcting polish translation - branch 4.4

### PR DESCRIPTION
**Pull request by qbadev**
General correction of polish translation. Mainly misspelings, but also punctation and factual corrections.

Update 1: my last pull request was mistakenly compared to contao/contao:master instead contao/contao:4.4
Update 2: latest commit includes changes widely discussed with @qzminski

### CODE REVIEW

**Comment by qzminski** [comment]
@leofeyer looks good to me, so if you would be that kind and merge it, that would be superb. Those changes also apply to versions above 4.4.

**Comment by leofeyer** [comment]
I have pushed the changes to Transifex. Now we have to rebase the PR onto the `4.9` branch, so I can do the same for the Contao 4.9 translation.

**Comment by leofeyer** [comment]
@qbadev @qzminski Can you please rebase the PR and review the translation for the `4.9` and `4.10` branches? Right now, the changes are in Contao 4.4 only.

**Comment by qzminski** [comment]
@qbadev do you know how to do that, or should I take care of that?

**Comment by qbadev** [comment]
@qzminski 
I do not know exactly what is to be done. Rebasing my commit into 4.9 branch? So, should I create another PR for 4.9 (of course after rebasing)?

**Comment by qzminski** [comment]
Hey @leofeyer shall we create a new PR, or rebase on 4.9 and force push this one? 🤔

**Comment by leofeyer** [comment]
As you like. It does not matter in this case.

**Comment by qzminski** [comment]
@qbadev up to you then. You can reach me for help at kamil.kuzminski@codefog.pl.

**Pull request closed without merging**
