### PR TITLE
Allow SVG images in favicons

### PR DESCRIPTION
**Pull request by Toflar**
Fixed restricting favicons to `.ico` only.
See https://caniuse.com/#feat=link-icon-svg

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Comment by aschempp** [comment]
Are you sure this is correct? Browsers always request `favicon.ico` from the root site. Browsers _might_ support a `<meta` tag with an SVG icon, but our root page icon is only for the fallback route, and that route cannot return an SVG icon imho?

**Comment by Toflar** [comment]
The way I understood the spec is that in case the link meta tag is missing, the browser shall request `/favicon.ico` and use that. Browsers require `Content-Type: image/svg+xml` to be present to handle the SVG accordingly which should happen automatically due to our mime type guesser. Hmmm, maybe that guesses `image/svg` though, so we might want to hardcode `image/svg-xml`...
We could also add a `Vary: Content-Type` although I don't see this super critical as our reverse proxy is going to be invalidate the cache entry anyway when you change the selection and the browsers likely cache whatever they want to anyway^^

**Comment by aschempp** [comment]
On caniuse.com, the Reference section links _Specification_ to https://html.spec.whatwg.org/multipage/links.html#rel-icon, which is titled **4.6.6.8 Link type "icon"**. That section says

> In the absence of a link with the icon keyword, for Document objects whose URL's scheme is an HTTP(S) scheme, user agents may instead run these steps in parallel:
>
> 1. Let request be a new request whose url is the URL record obtained by resolving the URL "/favicon.ico" against the Document object's URL, client is the Document object's relevant settings object, destination is "image", synchronous flag is set, credentials mode is "include", and whose use-URL-credentials flag is set.
>
> 2. Let response be the result of fetching request.
>
> 3. Use response's unsafe response as an icon as if it had been declared using the icon keyword.

So _maaayyybeee_ that actually works …

**Comment by leofeyer** [comment]
> and that route cannot return an SVG icon imho?

That's a valid point IMHO. Our `favicon.ico` route cannot return an SVG icon, can it? AFAIK, you need a link tag such as `<link rel="icon" type="image/svg+xml" href="favicon.svg">`.

@ausi /cc

**Comment by Toflar** [comment]
Of course it can? It does now?

**Comment by leofeyer** [comment]
But doesn't the browser expect `image/x-icon` if the file is called `favicon.ico`?

**Comment by Toflar** [comment]
No, that‘s the whole idea of this spec :)

**Comment by leofeyer** [comment]
I have tested this in Chrome, Firefox and Safari on Mac OS.

1. It does not work in any browser with the guessed MIME type `image/svg`.

2. Once I had overwritten the MIME type, Chrome and Firefox correctly loaded the SVG favicon. Safari did render the favicon when I requested `/favicon.ico` in the URL, however, it refused showing it in the tab bar.

3. Safari also refused to show the SVG favicon if if was added via `<link rel="icon"`, so I guess that is ok.

So we definitely have to overwrite the MIME type with `image/svg+xml` to make this work.

**Comment by Toflar** [comment]
See https://github.com/contao/contao/pull/1554

**Pull request merged**
