### PR TITLE
Fix the multiple checkbox selection (with SHIFT key) not working in picker

### PR DESCRIPTION
**Pull request by qzminski**
It does not work because in the picker we don't have a `#tl_select` element which is available only in the `Edit multiple` DCA view.

The feature was introduced in https://github.com/contao/core/pull/7781.

/cc @aschempp

### CODE REVIEW

**Comment by aschempp** [comment]
This should actually be fixed in 4.4 as well, right?

**Comment by qzminski** [comment]
No idea, you told me to do the PR against master 😅

**Comment by aschempp** [comment]
> Can you create a PR for Contao to fix that? Its a bug in my view, but 4.4 does not have it, so it should be pointed at 4.8/master.

🤷‍♂ your link clearly points to 3.5, so my 4.4 assumption was wrong 😉

**Comment by leofeyer** [comment]
Fixed in 0005b12292c12b7149673c423f071ec88d819814.

**Pull request closed without merging**
