### PR TITLE
Add logging for functional tests

### PR DESCRIPTION
**Pull request by fritzmg**
We already define the `var/cache` and `var/logs` directory in our functional test's `AppKernel`. Actually enabling logging makes it easier to track down errors that only happen during functional tests. wdyt?

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]
LGTM. How often will `rotating_file` replace the file? Ideally it would be replaced on every test run, right?

**Comment by leofeyer** [comment]
> Ideally it would be replaced on every test run, right?

Yes, that is how it should be (but is not yet).

Also, is `debug` really the best log level? It adds a lot of noise compared to `info` in my opinion.

**Review by leofeyer — CHANGES_REQUESTED** [review]
As discussed, the log file should be overwritten on every run and the default log level should be discussed.

**Comment by fritzmg** [comment]
I have raised the log level to `error` now and also included the stack trace in the log.

> the log file should be overwritten on every run

We could of course purge the log directory every time the `AppKernel` boots. But if an error happens in two tests, the latter would overwrite the former, as these are independent runs.

I would leave it as is, as this is only relevant when you want to actually track down an error (which is not the norm).

**Comment by leofeyer** [comment]
But now we also log expected exceptions such as `request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Unused arguments: foo" at ExceptionConverterListener.php line 90`. Since these exceptions are supposed to be thrown, they should be ignored to prevent them from flooding the log file.

**Comment by fritzmg** [comment]
We cannot distinguish these, can we?

**Comment by leofeyer** [comment]
I don‘t know. @contao/developers /cc

**Comment by leofeyer** [comment]
As discussed in the Contao call, this cannot be solved. We will close the PR for the time being.

**Pull request closed without merging**
