### PR TITLE
Handle nested content elements when generating the preview URL

### LINKED ISSUE #6829: Frontend preview does not work in nested elements
### Affected version(s)

5.3

### Description

If the front end preview link is clicked when viewing nested elements, the front end does not show the current page.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #6829

### CODE REVIEW

**Comment by ausi** [comment]
This needs to be fixed in Contao 5.2 as well, as all content elements seem to be affected, not only nested ones.

**Comment by ausi** [comment]
I think I broke `BackendPreviewListener::getIdFromRequest()` in https://github.com/contao/contao/commit/eb37857c26de5fd3a230d583681e78ced0178ce4#diff-8223859aeb4b5c90b907606bd48bb61af8df95c1fe27643af4e91e32ee86dfd1

We should make sure that `getIdFromRequest()` always returns the ID of the article IMO.

**Comment by aschempp** [comment]
Yeah I implemented my own preview listener recently, for my own table that also has content elements (similar to news). It would be great to get the ID of the article, but I don't think this can be generalized?

**Comment by aschempp** [comment]
I wonder what `key` in the event is supposed to be… wouldn't it make more sense to have e.g. `DataContainer::getCurrentRecord()`?

**Comment by leofeyer** [comment]
> We should make sure that `getIdFromRequest()` always returns the ID of the article IMO.

How would we do that? The `BackendPreviewListener` is not specific to articles or content elements and therefore should not have a special handling for `'tl_article' === $request->query->get('do')`. The `PreviewUrlCreateListener` on the other hand explicitly only handles articles and pages.

```php
if ($request->query->has('ptable')) {
    $do = substr($request->query->get('ptable'), 3);
}
```

If this is what bothers you, we could also add an optional third parameter `string|null $table = null` to the `PreviewUrlCreateEvent`. Then `$do` would still be `article` but we could still distinguish between the two cases.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to add a third parameter `$table` to the `PreviewUrlCreateEvent`. The goal is to always pass the correct ID and table, so we have to adapt the logic from `DC_Table::findCurrentPid()` for the ID and add more logic for the table.

A helpful tool would be a service to decode DCA URLs. @ausi wants to give this a try.

**Comment by ausi** [comment]
Related: #7010

**Comment by leofeyer** [comment]
Closed in favor of #7010.

**Pull request closed without merging**
