### PR TITLE
Do not index documents if the canonical URL does not match

### PR DESCRIPTION
**Pull request by Toflar**
https://github.com/contao/contao/issues/3097#issuecomment-952045251

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by fritzmg** [comment]
Should we may be backport this to `4.9` as well? I would consider it a bug that non-matching canonical URLs can be added to the search index currently.

**Comment by Toflar** [comment]
I asked and we decided not to :)

**Comment by fritzmg** [comment]
Ah, I missed that then ;)

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
