### PR TITLE
Do not forward our CSP functions to the Nelmio CSPRuntime

### LINKED ISSUE #6970: CSPNonce Twig - get wrong nonce when CSP is disabled in RootPage
### Affected version(s)

5.3.x

### Description

If you use  {{ csp_nonce('script-src') }} in twig with CSP deactivated in the root page, you will get the nonce from nelmio.
This is a bit confusing. It would be better not to return a nonce here.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #6970

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
We specifically implemented this so that we can share the Twig function name with `nelmio/security-bundle`.

I do not think this should be removed - especially for cases where Contao is used alongside a regular Symfony application.

May be we can skip forwarding if CSP is not enabled via the Security Bundle instead.

**Comment by leofeyer** [comment]
> May be we can skip forwarding if CSP is not enabled via the Security Bundle instead.

What do I need to change for this?

**Comment by fritzmg** [comment]
I am not sure yet.

Btw. keep in mind that this is a purely cosmetic issue.

**Comment by leofeyer** [comment]
You mean because the nonce from the Nelmio bundle does not break anything?

**Comment by fritzmg** [comment]
Yes, having a `nonce` attribute in your HTML code that is not actually present in a CSP response header would not break anything (the `nonce` would be present in the CSP response header if you enabled nelmio's CSP functionality in your config).

**Pull request closed without merging**
