### PR TITLE
Improve the post update/install CLI hint

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
I wonder if there's a reason not to automatically run `contao:migrate` for a Contao Managed Edition after installing packages?

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Comment by leofeyer** [comment]
> I wonder if there's a reason not to automatically run `contao:migrate` for a Contao Managed Edition after installing packages?

@aschempp IDK. Maybe we should create a new issue and label it "up for discussion"?

**Comment by Toflar** [comment]
I don't think that makes sense, I would personally never want that because I want to see what actually changes. Migrations should never happen without having somebody to look over the changes.

**Comment by aschempp** [comment]
> Migrations should never happen without having somebody to look over the changes.

But that's not how it currently works. If you open the install tool, all `runonce.php` files are executed automatically. The install tool offers to run each query individually, but most of the cases you simply run all of them. Maybe keep some drop culumns, but you always need to add stuff.

I agree it might not be wanted in a *local* environment, where you possibly don't have a database, or you want to check the migrations first. But a managed edition on a webserver probably always should run time …

**Comment by Toflar** [comment]
> But that's not how it currently works.

Yeah, and the way it currently works is bad 😄

**Pull request merged**
