### PR TITLE
Enforce the MySQL strict mode

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | followup to #3131 for 4.x
| Docs PR or issue | todo

This will prevent the installer from running when MySQL strict mode is disabled.

### CODE REVIEW

**Comment by m-vo** [comment]
This probably  needs to be rebased + adjusted once #3131 is merged upstream.

**Review by ausi — DISMISSED** [review]

**Comment by aschempp** [comment]
I wonder if 
a) people can actually change this on their regular hosting?
b) if we can, shouldn't we just add the option ourselves (like we do with other options)?

also, I remember we had plenty of issues with strict mode before, or what that _another strict mode_ 😅

**Comment by m-vo** [comment]
> also, I remember we had plenty of issues with strict mode before, or what that another strict mode 😅

That likely was `ONLY_FULL_GROUP_BY`?

**Comment by fritzmg** [comment]
Maybe Contao should instead ensure that no data is saved that might get truncated by the database? Users will for sure have no control over the database server configuration.

**Comment by m-vo** [comment]
>I wonder if
a) people can actually change this on their regular hosting?

>  Users will for sure have no control over the database server configuration.

The fix the installer suggests is using `SESSION` config. IMO that should work everywhere. But we should test it for sure.

**Comment by ausi** [comment]
> also, I remember we had plenty of issues with strict mode before

That’s why we add a warning in #3131 so that if someone has problems with strict mode they can notice ahead of time.

> > a) people can actually change this on their regular hosting?
> > Users will for sure have no control over the database server configuration.
> 
> The fix the installer suggests is using `SESSION` config. IMO that should work everywhere. But we should test it for sure.

I couldn’t find any information that suggests you need special permissions for `SET sql_mode`. The MySQL documentation even says “Each client can change its session sql_mode value at any time.”.

**Review by bytehead — DISMISSED** [review]

**Comment by aschempp** [comment]
> I couldn’t find any information that suggests you need special permissions for SET sql_mode. The MySQL documentation even says “Each client can change its session sql_mode value at any time.”.

Yes, we can/could do that through connection options at runtime. I did mean if someone can change the server defaults, which is unlikely I think.

**Comment by leofeyer** [comment]
I have adjusted the explanation text. @m-vo WDYT?

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
