### PR TITLE
Do not make tl_user.admin an excluded field

### LINKED ISSUE #748: Feld tl_user admin bei Bearbeiten von Benutzergruppen im Abschnitt Erlaubte Felder ausblenden
Eine Vergabe des Rechtes für das Feld tl_user admin im Abschnitt "Erlaubte Felder" beim Bearbeiten von Benutzergruppen wird offenbar aus Sicherheitsgründen ignoriert. Das heißt auch Benutzer, die das Recht für dieses Feld haben, können keinen Benutzer zu Administrator machen.

Der Klarheit wegen würde es sich daher anbieten, das Feld tl_user admin beim Bearbeiten von Benutzergruppen im Abschnitt "Erlaubte Felder" auszublenden.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #748

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
That's not the whole change, is it? Now the field would show up for all users? There should also be a onload_callback to remove it from the palette?

**Comment by leofeyer** [comment]
Did you test this? Because the `getExcludedFields()` method only adds fields that match the following condition:

```php
      if ($vv['exclude'] || $vv['orig_exclude'])
```

**Comment by leofeyer** [comment]
Or did you maybe miss this line?

https://github.com/contao/contao/blob/0236382bf085f0a210409957c4b9c70c184f810b/core-bundle/src/Resources/contao/dca/tl_user.php#L506-L507

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
> Or did you maybe miss this line?
> 
> https://github.com/contao/contao/blob/0236382bf085f0a210409957c4b9c70c184f810b/core-bundle/src/Resources/contao/dca/tl_user.php#L506-L507

Yeah I missed that line, no idea why it's already there and not in this PR 😂

**Pull request merged**
