### PR TITLE
Handle dynamic parent tables in the `Controller::getParentEntries()` method

### LINKED ISSUE #6824: Submitting nested content element runs into recursion
### Affected version(s)

5.3-dev

### Description

I played around the new nested content element feature in Contao and immediately run into an recursion issue.  After debugging this the issues is in `Contao\Controller::getParentEntries()` called by `Contao\Versions::create()`.

https://github.com/contao/contao/blob/2cf7bbc56bc236e5d2c66e660488e711d3368845/core-bundle/contao/library/Contao/Controller.php#L1285-L1321

```php
$arrParent = [
"tl_content.id=1214"
"tl_content.id=125"
"tl_content.id=40"
"tl_content.id=24"
"tl_content.id=1"
"tl_content.id=19"
"tl_content.id=1"
];
```

Looking at the collected parents it starts to loop between the entry ID 1 and entry ID 19. This is caused by ignoring the dynamice `ptable` of the content element. The `ptable` information is only fetched from the configuration https://github.com/contao/contao/blob/2cf7bbc56bc236e5d2c66e660488e711d3368845/core-bundle/contao/library/Contao/Controller.php#L1299 

That's not correct. The ptable entry might be different in each entry fetched from the database. In my example above `tl_content.id=125` already has a `ptable=tl_article` .

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #6824

Now that we have merged #6645, we can revert these changes.

### CODE REVIEW

**Comment by ausi** [comment]
As info for other reviewers, this reverts the changes to `getParentEntries()` made here: https://github.com/contao/contao/commit/8ed8a059ef8e4ea3b420dccde595f5f5973e6750#diff-5d8e5f6404d79ec664e67c00607bb1e8d4f7fad38c49b0dac7167afbfeded3d2

**Comment by dmolineus** [comment]
This fix is incorrect, I believe. As far as I understand https://github.com/contao/contao/pull/6645, `tl_content.ptable` will still be `tl_content` for nested content elements. So the problem will still occur. Also, the previous implementation of Controller::getParentEntries() is already broken in the dynamic ptable context, even without nested elements.

Example: I'm visiting a content element of a news entry in the backend and call Controller::getParentEntries() on a content element that belongs to an article. The method would assume that it belongs to the news item. The use case is very theoretical, which is why it hasn't happened before. But now with nested elements, it is a problem.

**Comment by leofeyer** [comment]
@dmolineus I have added a `ptable` check to the SQL query in ef335edfdf62c1199909ed91c273a67c8fd454c3. Please check again.

**Comment by ausi** [comment]
See https://github.com/leofeyer/contao/pull/10

**Comment by dmolineus** [comment]
@leofeyer @ausi Now it works like expected. :+1:

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by leofeyer** [comment]
Hm… 🤔

**Pull request merged**
