### PR TITLE
Add a z-index to the limit toggler

### LINKED ISSUE #6660: limit_toggler button (...) does not work anymore
### Affected version(s)

5.x

(It does not affect 5.2.x)

### Description

I tried to test the `limit_toggler` button within the new 5.x version to check out following issue:
- https://github.com/contao/contao/issues/3707

The issue seems to be resolved in the pereparations for the 5.3 LTS but the dom changed so the `limit_toggler` [...] can not be clicked anymore (moved out of cte-preview).

image
image

Adding a "z-index: 1" to `.limit_toggler button span` solves the issue.

### PR DESCRIPTION
**Pull request by zoglo**
Fixes #6660

- Adds a z-index to the limit-toggler to make it clickable again

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
How can I reproduce the problem e.g. with the official demo?

**Comment by de-es** [comment]
Das Problem tritt aktuell nur in 5.x auf, nicht in 5.2. Daher in der offiziellen Demo nicht nachstellbar. Hatte es auch schon bemerkt, aber @zoglo war schneller. :+1:

**Comment by leofeyer** [comment]
Bei mir tritt das Problem auch in der neuesten `5.x` nicht auf, daher die Frage, wie ich es in der Official Demo (nicht der Online-Demo) reproduzieren kann.

**Comment by zoglo** [comment]
@leofeyer 
I am also using the contao-demo for testing and it happens using Chrome, as well as Firefox on Windows when trying to click the '...' (limit-toggler) of a content-element.

Navigate into Articles -> Edit the content elements of an article (e. g. Content-Elements) -> try to click any toggler
image

In the following screenshot (I resized the window), it's even hidden behind the table:
image

**Comment by leofeyer** [comment]
Thank you @zoglo.

**Pull request merged**
