### PR TITLE
Use the 2fa/* subpackages instead of scheb/2fa

### LINKED ISSUE #2663: Require subpackages instead of scheb/2fa
**Affected version(s)**

Contao 4.9

**Description**

As far as I can see this, we should use

- `scheb/2fa-bundle`
- `scheb/2fa-backup-code`
- `scheb/2fa-trusted-device`

instead of `scheb/2fa`.

See https://github.com/contao/contao/pull/2617#issuecomment-763559539

Also check https://github.com/contao/contao/pull/2617#issuecomment-763567478.

### PR DESCRIPTION
**Pull request by bytehead**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2663 
| Docs PR or issue | n/a

See #2663

### CODE REVIEW

**Comment by bytehead** [comment]
Exchange `bacon/qr-code` with `scheb/2fa-qr-code` can't be done in a bugfix release, as we use our own authenticator instead of the one from `scheb/2fa-totp`.

**Comment by leofeyer** [comment]
IMHO we are missing two packages:

```
scheb/2fa-totp                   # Add two-factor authentication using TOTP
scheb/2fa-qr-code                # Add to render QR-codes for Google Authenticator / TOTP
```

Without `2fa-totp` we do not have an authentication provider, do we?

**Comment by bytehead** [comment]
We have our own provider and authenticator and the interfaces are provided by `scheb/2fa-bundle`.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
