### PR TITLE
Update form.php for CSV with UTF-8 BOM

### PR DESCRIPTION
**Pull request by Physiklehrer**
siehe https://github.com/contao/contao/issues/1466

### CODE REVIEW

**Comment by leofeyer** [comment]
@ausi WDYT?

**Comment by m-vo** [comment]
I'm using `league/csv` to create csv output, there all the [BOM handling](https://csv.thephpleague.com/9.0/connections/bom/) is already nicely abstracted. Maybe that's an alternative to consider.

**Comment by aschempp** [comment]
I only ever know of issues with the UTF8 BOM, not sure why we would want to add that?

**Comment by leofeyer** [comment]
Exactly. 😄

**Comment by Physiklehrer** [comment]
Formulargenerator -> Per E-Mail versenden -> Datenfomat: CSV-Datei

If the user opens the CSV attached to the mail with Microsoft Excel, the cell "Hr. Müller" will be displayed as "Hr. M%OPGeller", since Microsoft does not use UTF-8 as default. With the UTF-8 BOM, Microsoft Excel gets to know that this file is UTF-8-encoded and will display it correctly.

So I think it is worth it to add the BOM in this special case for compatibility with Microsoft Excel. Otherwise the option "CSV attachement" ist not really useful in non-english contao-environments for people using Microsoft.

PS: I know, the better solution would be to use LibreOffice or making a pull request for Microsoft Office to use UTF-8 by default, but it is not on github :-)

**Comment by fritzmg** [comment]
👍 for adding it optionally

**Comment by Physiklehrer** [comment]
> 
> 
> 👍 for adding it optionally

good idea! Just another entry to the select menu?
- raw data
- xml file
- csv file
- csv file (Microsoft Excel)
- E-Mail

**Comment by ausi** [comment]
@Physiklehrer are you using the latest version of Microsoft Excel?

[This article](https://donatstudios.com/CSV-An-Encoding-Nightmare) writes that the issue should have been fixed in 2019 by Microsoft.

**Comment by m-vo** [comment]
Excel also prefers `;` instead of `,` as a separator btw. - the latter triggers an extra window to select the format instead of opening right away. Not sure if this has also changed in the newest version.

**Comment by Mynyx** [comment]
> Excel also prefers `;` instead of `,` as a separator btw.

That depends on your locale.

**Comment by m-vo** [comment]
Ah, that's interesting!

**Comment by fritzmg** [comment]
True, that's why CSV exports are usually configurable. If you need compatibility for MS Excel under Windows with a German locale, then the CSV needs to contain the BOM and use `;` as a separator. Even in MS Excel 2019 / Excel for Office 365 16.0

**Comment by ausi** [comment]
It [looks like](https://superuser.com/a/686415) you can make a locale-independet excel CSV document by adding `sep=,` to the top of the file. 

If that’s correct, I’m 👍 for a new “CSV (Microsoft Excel)” format that just adds `"\u{FEFF}sep=,\n"` to the beginning of the file.

**Comment by Physiklehrer** [comment]
I think it should be "\u{FEFF}sep=;\n" as we explode with semicolon as separator. But testing with this was not successfull yet.

I will try later, first I have to teach my collegues using the LMS Moodle because of school closure...

**Comment by ausi** [comment]
Using `sep=` together with UTF-8-BOM doesn’t seem to work in Excel.

In my test the following code worked:

```php
mb_convert_encoding("\u{FEFF}sep=;\n" . \StringUtil::decodeEntities(…), 'UTF-16LE', 'UTF-8')
```

**Comment by Physiklehrer** [comment]
> mb_convert_encoding("\u{FEFF}sep=;\n" . \StringUtil::decodeEntities(…), 'UTF-16LE', 'UTF-8')

I can confirm that this is working with MS Excel. Thanks a lot, please feel free to modify/delete my PR!

**Comment by ausi** [comment]
I think we should tag this issue as feature for Contao 4.10 and add “CSV (Microsoft Excel)” as a new format that uses the code from https://github.com/contao/contao/pull/1467#issuecomment-600186366
@contao/developers WDYT?

**Comment by Toflar** [comment]
Yes, we sure cannot apply it by default because it would break the existing export.
Sigh, standards...it would be so easy to just follow the standards...

**Comment by leofeyer** [comment]
I have created a separate issue for the feature request: #1866

**Pull request closed without merging**
