### PR TITLE
Fixed incorrect service tag

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
🤦‍♂  my local copy actually does have a reset method… implemented in the vendor folder…

**Comment by Toflar** [comment]
What? https://github.com/contao/image/blob/master/src/DeferredImageStorageFilesystem.php does not have a `reset()` method?

**Comment by aschempp** [comment]
My local vendor folder does… obviously should have been added to `contao/image` 😂

**Comment by aschempp** [comment]
see #1105

**Pull request closed without merging**
