### PR TITLE
Replace the token in the storage for preview link authentication

### LINKED ISSUE #6223: Problems opening more than one preview link
### Affected version(s)

4.13.26

### Description

If I have more than one preview link, only opening the first one works. After that I am asked to enter a username and password. If I delete all cookies I can also open the second link.

How to reproduce this:

- Login in the back end and go to the preview of the site.
- Generate two preview links (Restrict access to specified URL is checked and the link is activated).
- Copy both preview links to your clipboard and log out from the back end.
- Open the first link from your clipboard, the page will be displayed.
- Open the second link from your clipboard, you are asked to log in.

### PR DESCRIPTION
**Pull request by ausi**
~~Attempt to~~ fix #6223

This seems to work, ~~but I’m not sure if the `null !== $previewLinkId` is the correct way to distinguish if we want to replace the token or not.~~ ~~I think I got it: `$this->security->getToken() instanceof FrontendPreviewToken` is the check we need here I think. @aschempp WDYT?~~ __Update:__ see https://github.com/contao/contao/pull/6226#issuecomment-1642389214

### CODE REVIEW

**Comment by aschempp** [comment]
why would we ever not update the token storage? And how can this have worked in any other front end preview case?

**Comment by ausi** [comment]
I think it depends on the firewall of the current request. 
If `[@security.firewall.map]->getFirewallConfig(…)->getContext()` is `contao_frontend` we should update the token storage, otherwise we should use the session.

> why would we ever not update the token storage?

Because for the backend firewall we would lose the login information of the currently logged in user, after using the `BackendPreviewSwitchController`.

> And how can this have worked in any other front end preview case?

The `FrontendPreviewAuthenticator` is mainly used in the backend, thats why this always worked. And for the preview link it only worked if there is no token in the session yet.

**Comment by ausi** [comment]
I updated the PR now to check for the firewall context instead of `instanceof FrontendPreviewToken`.

**Comment by aschempp** [comment]
ah, I think I understand. The new preview links are handled in the front end firewall? Is the session correctly saved if there is no token already existing (the firewall is likely not initialized and handling the token storage)?

**Comment by ausi** [comment]
> The new preview links are handled in the front end firewall?

Yes, this was always the case AFAIK.

> Is the session correctly saved if there is no token already existing (the firewall is likely not initialized and handling the token storage)?

Yes, after deleting all cookies in the browser, accessing the preview link URL worked as expected (using `tokenStorage->setToken()`) with the current state of this PR.

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
