### PR TITLE
Do not add protected pages to the XML sitemap

### LINKED ISSUE #1407: Geschützte Seiten aus sitemap.xml ausschließen
**Affected version(s)**
Contao 4.9

**Description**
Damit Seiten vom Contao-Crawler indexiert werden, muss der Robot-Tag auf "follow" stehen.
Bei dieser Einstellung wird die Seite allerdings auch in der sitemap.xml eingetragen.

Ich möchte allerdings nicht, dass geschützte Seiten in der sitemap.xml aufgeführt werden.

Wäre es denkbar, dass eine explizite Option _Von xml-Sitemap ausschließen_ integriert wird?

**How to reproduce**
1. Seite mit Robots-Tag "noindex,follow" versehen.
2. Seite erscheint auf öffentlicher sitemap.xml

siehe auch:
https://github.com/contao/contao/issues/1395

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1407
| Docs PR or issue | -

### CODE REVIEW

**Comment by fritzmg** [comment]
But we still need to tell the indexer about the protected pages, if it is supposed to index those, right?

**Comment by leofeyer** [comment]
Hm, I guess you are right.

**Comment by fritzmg** [comment]
iirc the solution we discussed was to create a separate sitemap for the indexer, where protected pages are included (if enabled).

**Comment by leofeyer** [comment]
Yes, in Contao 4.10. This PR is just the fix for Contao 4.9.

**Comment by fritzmg** [comment]
But that would mean you will never be able to properly index protected pages with the search indexer in Contao 4.9.

**Comment by contaoacademy** [comment]
> But that would mean you will never be able to properly index protected pages with the search indexer in Contao 4.9.

This would be bad. So the old behaviour would be even better

**Comment by leofeyer** [comment]
I have adjusted the code in 9754ca4cfa53ea24e9f77c80055eb77731376cc4. Now protected pages will only be excluded if the method is generating an XML sitemap.

**Comment by fritzmg** [comment]
But doesn't the search indexer still use the regular XML sitemap and thus it won't know of the protected pages?

**Comment by leofeyer** [comment]
No, why do you think so?

**Comment by fritzmg** [comment]
The crawler uses the `RobotsSubscriber`, which in turn uses the XML sitemap.

**Comment by aschempp** [comment]
> But that would mean you will never be able to properly index protected pages with the search indexer in Contao 4.9.

That is not true. The XML is only to aid the crawler, if the pages appear on your website they will still be indexed in protected mode.

**Comment by fritzmg** [comment]
> That is not true. The XML is only to aid the crawler, if the pages appear on your website they will still be indexed in protected mode.

That assumes too much about the link structure. What if you have news or events, that are only accessible by members, but your newslist only ever shows the last X entries and the rest is only discoverable via the search functionality. The crawler will never know about these pages, if they do not appear in the XML sitemap.

**Comment by Toflar** [comment]
Yeah, that's why we said we need to turn the sitemap into their own controllers adding those links if private and otherwise not. It's mentioned in some ticket but it's quite a big chunk of work which is why we said 4.10 (= somewhen, some day in the future).

**Comment by leofeyer** [comment]
You probably mean 4.11, but otherwise 👍🏻.

This fix is still necessary for Contao 4.9, though, otherwise protected pages will show up in the XML sitemap (see #1407).

**Comment by aschempp** [comment]
hasn't that been the case ever since? They are still not accessible… protected pages can be in the navigation as well, depending on your configuration.

**Comment by fritzmg** [comment]
> This fix is still necessary for Contao 4.9, though, otherwise protected pages will show up in the XML sitemap (see #1407).

But that's a devil's circle. This issue occurs precisely because you _want_ to index protected pages. However, with this fix, protected pages might not be discovered by the crawler at all and thus are in turn not indexed. And if you do not want to index protected pages, this fix is not needed.

**Comment by Toflar** [comment]
> You probably mean 4.11, but otherwise 👍🏻.

No we agreed on 4.10 but as long as nobody is working on it that just means "future" :)

**Comment by fritzmg** [comment]
> hasn't that been the case ever since?

No, protected pages were previously excluded from the sitemap. But protected pages were still indexed by the search indexer (see the `$blnIsSitemap` parameter of `getSearchablePages`).

**Comment by leofeyer** [comment]
Again, this is a two part change:

Part 1 (bugfix): Hide protected pages in the XML sitemap, because the XML sitemap will be read by Google and there is no point in providing the Google crawler with links that end up in a 401 error.

Part 2 (feature): Make XML sitemaps dynamic, so we can generate different versions for Google (without protected pages) and our own crawler (with protected pages).

**Comment by fritzmg** [comment]
I get that, I am just pointing out, that only implementing Part 1 in Contao 4.9 will leave Contao 4.9 (the current LTS) in a state where it is impossible to index protected pages via the crawler, if they aren't linked from within other discoverable content.

**Comment by contaoacademy** [comment]
> I get that, I am just pointing out, that only implementing Part 1 in Contao 4.9 will leave Contao 4.9 (the current LTS) in a state where it is impossible to index protected pages via the crawler, if they aren't linked from within other discoverable content.

I totally agree with @fritzmg. If only Part 1 is integrated, a lot of my protected content isn't discoverable by the crawler. So nobody could use the search function in my protected member area. This would be worst case.

I think Part1 and Part2 must be integrated together. If this isn't possible I would recommend not to fix this in Contao 4.9 LTS only with Part 1

**Comment by leofeyer** [comment]
Agreed. I have reopened the original issue.

**Pull request closed without merging**
