### PR TITLE
Skip the temp folder check if there is no initialization hook

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1685
| Docs PR or issue | -

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

**Review by m-vo — DISMISSED** [review]

**Review by aschempp — CHANGES_REQUESTED** [review]
That wont work. It would not load the initconfig if there is a hook and no file.

**Comment by fritzmg** [comment]
> That wont work. It would not load the initconfig if there is a hook and no file.

That's fine, isn't it? The `initconfig.php` does not need to be loaded, if the system is not fully installed yet. Once `system/tmp/` is present, both the hook (if any are registered) will be executed and the initconfig will be loaded.

**Comment by leofeyer** [comment]
I have adjusted the logic again in 448b85df799e8645a8ba07334b01f2d530cc7be4. Gradually we have gone through all variants. 😄

**Review by fritzmg — APPROVED** [review]

**Comment by aschempp** [comment]
> > That wont work. It would not load the initconfig if there is a hook and no file.
> 
> That's fine, isn't it? The `initconfig.php` does not need to be loaded, if the system is not fully installed yet. Once `system/tmp/` is present, both the hook (if any are registered) will be executed and the initconfig will be loaded.

Well then we could keep the original version 😆

**Review by aschempp — APPROVED** [review]

**Comment by fritzmg** [comment]
> Well then we could keep the original version 😆

Hm, which one? In the original original version, the `initconfig.php` would never be included ever ;)

**Review by ausi — APPROVED** [review]

**Pull request merged**
