### PR TITLE
Support relative URLs as canonical URLs

### PR DESCRIPTION
**Pull request by ausi**
Fixes second part of #6081
See https://github.com/contao/contao/pull/6134#pullrequestreview-1475244520

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by aschempp** [comment]
why do we need to modify protocol-relative URLs? Isn't that valid for a canonical link?

**Comment by fritzmg** [comment]
It seems to be best practise to use absolute URLs, rather than any form of relative URL, even though technically any form of relative URL is valid as well. Hence the check for an absolute URL that was already there.

**Comment by ausi** [comment]
> why do we need to modify protocol-relative URLs? Isn't that valid for a canonical link?

It is valid, but Google explicitly states that they recommend absolute URLs:  
https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls?hl=en#rel-canonical-link-method Bildschirmfoto 2023-06-13 um 10 35 11

**Comment by ausi** [comment]
I added an `UrlUtil` class in a77e62d6ed8bd039a337011084e3c2c80974addc that takes care of resolving the relative URLs.

**Review by fritzmg — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
