### PR TITLE
Reset the custom template if the element type changes

### LINKED ISSUE #2567: Unbekannte Option bei Template Auswahl
**Affected version(s)**

Contao 4.9.9

**Description**

Beispielszenario:

1. Es gibt für ce_headline ein eigenes Template "ce_headline_test.html" (nur anderer Name, Inhalt gleich)
2. Ich lege ein Element Überschrift an, weise ihm das Template zu und speichere
3. Ich ändere den Elementtyp auf Text
4. Im Dropdown "Inhaltselemente-Template" steht nun "Unbekannte Option"
5. Ich speichere
6.  Im Frontend wird nun folgendes Markup erzeugt:

`<h2 class="ce_text first last"></h2>`

Das führt natürlich zu Fehldarstellungen auf der Website.

step1
step2

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2567
| Docs PR or issue | -

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
That won't work for elements that use a custom template. If we want to do this, then I think we need to create an independent "default template finder" service which will then used by this callback and the callback from https://github.com/contao/contao/pull/1909

**Comment by leofeyer** [comment]
You are right. I have reworked the implementation in a76a3fead81903ea2460a98b74399624929dc722 so it no longer requires to know the default template name.

**Comment by fritzmg** [comment]
New implementation looks good to me. However should we really introduce new functionality in the legacy `tl_` classes? I think any new callbacks should always be implemented as a service with appropriate service tags.

**Comment by leofeyer** [comment]
If that is our claim, such small issues will never be fixed anymore. The relationship between effort and benefit should be reasonable. 🤷🏻‍♂️

**Review by fritzmg — APPROVED** [review]
The effort would be low if we enabled auto-wiring for event listeners 🙈 🐱‍👤

**Comment by leofeyer** [comment]
Maybe, if it were not for the effort of discussing this and convincing everyone. 😉

**Pull request merged**
