### PR TITLE
Correctly load the DCA labels

### LINKED ISSUE #2467: Buttons ohne Beschriftung
**Affected version(s)**
Contao 4.9.9 (nur hierin getestet)

**Description**
Wenn man einen Artikel-Include erstellt und einen Artikel beziehen möchte öffnet sich das Popup zur Artikel auswahl. Dort sind oben die beiden Buttons toggleNodes und all ohne Beschriftung.
Unbenannt

Schritte zum reproduzieren (demo.contao.org)
1. Neues Inhaltselement vom Typ Artikelinklude anlegen
2. Popup öffnen und beliebigen Artikel auswählen
3. Oben in der Leiste sind die Buttons `toggleNodes `und `all ` ohne Beschriftung.

Frage hierzu: wenn man auf toggleNodes draufklickt, was soll nocheinmal passieren? ich erhalte hier nur einen reload der Seite.

### LINKED ISSUE #2483: Extensions break labels in tl_page
**Affected version(s)**

Contao 4.9, happening since 4.9.6
Contao 4.10

**Description**

Similar to #1311 the labels in `tl_page` are not being loaded correctly when editing a page.
I haven't had the chance to analyze this further but was able to pin it down to the exact 4.9 release this started
to happen in (which was 4.9.6) and it only seems to happen after `var/cache` is cleared.

This happened in a "clean" installation with only the following two extensions added:
https://github.com/numero2/contao-proper-filenames
https://github.com/numero2/contao-marketing-suite

Neither of those extensions cause a problem prior to the mentioned version.

**Steps to reproduce**
1. Fresh installation of Contao 4.9.6
2. Add the two extensions
3. Manually clear the `var/cache` directory
4. Take a look at the editing mask of the Site structure

image

### PR DESCRIPTION
**Pull request by aschempp**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2536

see #2536 for the discussion

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
Unfortunately this does not fix #2536 in my case. Though oddly enough, some labels have the correct reference and some do not.

**Comment by fritzmg** [comment]
Consider the following example:

```php
// contao/languages/en/tl_foo.php
\Contao\System::loadLanguageFile('tl_member');

$GLOBALS['TL_LANG']['tl_foo']['firstname'] = &$GLOBALS['TL_LANG']['tl_member']['firstname'];
$GLOBALS['TL_LANG']['tl_foo']['message'] = ['Message', 'Foobar description.'];
```

With your PR, `$GLOBALS['TL_DCA']['tl_foo']['fields']['firstname']['label']` will still be `null`:

```php
$foo = new FooModel();

// …

System::loadLanguageFile('tl_foo');

dump($GLOBALS['TL_DCA']['tl_foo']['fields']['firstname']['label']); // null
dump($GLOBALS['TL_DCA']['tl_foo']['fields']['message']['label']); // ['Message', 'Foobar description.']
```

**Comment by aschempp** [comment]
Why would you expect the firstname not to be null, it only references itself 😁

Maybe we should use `array_key_exists` instead of `isset` though 🤔

**Comment by fritzmg** [comment]
> Why would you expect the firstname not to be null, it only references itself 😁

It does not reference itself, it references a translation from `tl_member`.

**Comment by aschempp** [comment]
`$GLOBALS['TL_LANG']['tl_foo']['firstname'] = &$GLOBALS['TL_LANG']['tl_member']['firstname'];`

That's a reference to itself …

**Comment by aschempp** [comment]
I don't understand why the example refers to loading language files that reference each other, and not to DCA?

**Comment by fritzmg** [comment]
Not sure what you mean. The issue is, that with your fix, labels that are in turn references to labels of a different language file will not work.

// ah sorry, I made a copy & paste error. I updated the comment.

**Review by leofeyer — APPROVED** [review]
I can confirm that this PR fixes #2467. @fritzmg Can you please check if it fixes your problem in #2536 as well? And that it does not reintroduce the bug we fixed in #2200.

**Comment by leofeyer** [comment]
> ```
> // contao/languages/en/tl_foo.php
> \Contao\System::loadLanguageFile('tl_member');
> 
> $GLOBALS['TL_LANG']['tl_foo']['firstname'] = &$GLOBALS['TL_LANG']['tl_member']['firstname'];
> $GLOBALS['TL_LANG']['tl_foo']['message'] = ['Message', 'Foobar description.'];
> ```
> 
> With your PR, `$GLOBALS['TL_LANG']['tl_foo']['firstname']['label']` will still be `null`:

Do you mean `$GLOBALS['TL_LANG']['tl_foo']['firstname']['label'] = &$GLOBALS['TL_LANG']['tl_member']['firstname']`? Otherwise it is clear to me why it does not work.

**Comment by aschempp** [comment]
you're all confusing DCA and TL_LANG here 😂

**Comment by leofeyer** [comment]
Oh yes, I am. 🤦🏻‍♂️

**Comment by fritzmg** [comment]
As I mentioned [here](https://github.com/contao/contao/pull/2536#issuecomment-738815427) if we really want the `DcaLoader` to not enforce loading the language file as well, then `DcaLoader::addDefaultLabels` must not rely on `$GLOBALS['TL_LANG']` at all. Therefore we would need to _always_ create the reference to `$GLOBALS['TL_LANG']` for the `label` (if not set in the DCA itself) and remove the `isset($GLOBALS['TL_LANG'][…][…])` check. Not sure if that would have any side effects though.

// ah the check is only there for operations anyway. So I am not sure how to fix this.

**Comment by leofeyer** [comment]
I don't fully understand. Is there a concrete use-case in which the changes from this PR fail?

**Comment by fritzmg** [comment]
Yes, the one I described here: https://github.com/contao/contao/pull/2540#issuecomment-738811482

**Comment by leofeyer** [comment]
It seems a little odd to me to assign a not existing language array to another language array by reference and to expect the labels to be available later. Are we doing this in the core?

> Maybe we should use `array_key_exists` instead of `isset` though 🤔

How would this solve @fritzmg's use case?

**Comment by fritzmg** [comment]
> It seems a little odd to me to assign a not existing language array to another language array by reference and to expect the labels to be available later. Are we doing this in the core?

Why non existent? That is the content of my language file:

```php
// contao/languages/en/tl_foo.php
\Contao\System::loadLanguageFile('tl_member');

$GLOBALS['TL_LANG']['tl_foo']['firstname'] = &$GLOBALS['TL_LANG']['tl_member']['firstname'];
$GLOBALS['TL_LANG']['tl_foo']['message'] = ['Message', 'Foobar description.'];
```

After executing `System::loadLanguageFile('tl_member');` I expect `$GLOBALS['TL_LANG']['tl_member']` to be present. And thus by extension, I expect later on `$GLOBALS['TL_DCA']['tl_foo']['fields']['firstname']['label']` to be filled, if I load the DCA of `tl_foo`.

**Comment by aschempp** [comment]
> Therefore we would need to always create the reference to $GLOBALS['TL_LANG'] for the label (if not set in the DCA itself) and remove the isset($GLOBALS['TL_LANG'][…][…]) check.

That's exactly what this PR does? 😂

**Comment by fritzmg** [comment]
> That's exactly what this PR does? 😂

Yes, I know, I edited my comment afterwards. So I am not sure why it is not working in my use case and how to fix it.

**Comment by leofeyer** [comment]
I suggest that we merge this PR as is, because it does fix #2467, and reopen #2536 to further debug @fritzmg's issue. Any objections?

**Pull request merged**
