### PR TITLE
5.0 Make form list searchable by form.id

### PR DESCRIPTION
**Pull request by Ernestopheles**
Fixes:  form list not searchable by form.id

### CODE REVIEW

**Comment by Ernestopheles** [comment]
Unable to pro
DeepinBildschirmfoto_Bereich auswählen_20220726221459
pose the corresponding file change

**Comment by fritzmg** [comment]
You can just add the following to your Contao instance:

```php
// contao/dca/tl_form.php
$GLOBALS['TL_DCA']['tl_form']['fields']['id']['search'] = true;
```

**Comment by m-vo** [comment]
@Ernestopheles You chose the wrong target branch.

**Comment by m-vo** [comment]
Closing this as there also does not seem to be a branch containing changes in your fork.

**Pull request closed without merging**
