### PR TITLE
Fix the help wizard

### LINKED ISSUE #7689: Error beim aufrufen vom Hilfe-Assistent bei Elementtyp
### Affected version(s)

5.3.17

### Description

Wenn man den Hilfe-Assistent bei Elementtypen aufrufen möchte kommt ein Error.

```
TypeError:
Contao\CoreBundle\EventListener\DataContainer\ContentElementTypeListener::getAllowedElements(): Argument #1 ($ptable) must be of type string, null given, called in /vendor/contao/core-bundle/src/EventListener/DataContainer/ContentElementTypeListener.php on line 36

  at vendor/contao/core-bundle/src/EventListener/DataContainer/ContentElementTypeListener.php:61
  at Contao\CoreBundle\EventListener\DataContainer\ContentElementTypeListener->getAllowedElements(null, null)
     (vendor/contao/core-bundle/src/EventListener/DataContainer/ContentElementTypeListener.php:36)
  at Contao\CoreBundle\EventListener\DataContainer\ContentElementTypeListener->setDefault(object(DC_Table))
     (vendor/contao/core-bundle/contao/drivers/DC_Table.php:224)
  at Contao\DC_Table->__construct('tl_content')
     (vendor/contao/core-bundle/contao/controllers/BackendHelp.php:73)
  at Contao\BackendHelp->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:108)
  at Contao\CoreBundle\Controller\BackendController->helpAction()
     (vendor/symfony/http-kernel/HttpKernel.php:181)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:76)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:197)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:42)
```

### PR DESCRIPTION
**Pull request by bytehead**
Fixes #7689.

Not sure if it's the right way to fix or if we should check which elements to show in the help window.

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
I think we should rather return in `setDefault` if  `$dc->parentTable` and/or `$dc->currentPid` is empty.

**Comment by bytehead** [comment]
What's the outcome of `getOptions` then? If empty array, the help wizard is also blank.

**Comment by aschempp** [comment]
Well that's the same as it is now, right?

**Comment by bytehead** [comment]
It's not.

**Comment by ausi** [comment]
> Well that's the same as it is now, right?

No, the current state of this PR returns all types that are available to the user which is the correct behavior.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
