### PR TITLE
Fix Input::isPost() behavior for empty requests

### LINKED ISSUE #5039: Crawler: "Missing Ajax action"
### Affected version(s)

5.0.0-RC1

### Description

Running the crawler in Systemwartung -> Crawler -> "Nach defekten Links suchen" the following error is shown in /var/logs:

```
[2022-07-25T19:58:30.580670+02:00] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://contao5.xyz.td/contao?act=crawl&crawl_subscriber_names%5B0%5D=broken-link-checker&do=maintenance&jobId=142c04b8-376a-40a8-bda7-808674eeb5a9&ref=xrz-XiHk","method":"POST"} []
[2022-07-25T19:58:30.584267+02:00] request.CRITICAL: Uncaught PHP Exception Exception: "Missing Ajax action" at /var/www/clients/web/contao5/vendor/contao/core-bundle/contao/classes/Ajax.php line 61 {"exception":"[object] (Exception(code: 0): Missing Ajax action at /var/www/clients/web/contao5/vendor/contao/core-bundle/contao/classes/Ajax.php:61)"} []
```

### PR DESCRIPTION
**Pull request by ausi**
Fixes #5039

### CODE REVIEW

**Comment by fritzmg** [comment]
Shouldn't we rather check for `$action = Input::post('action')` in `BackendMain.php#111` instead? I think `Input::isPost` should continue to return true if it's a POST request, regardless of whether there are any POST variables.

**Comment by leofeyer** [comment]
> I think `Input::isPost` should continue to return true if it's a POST request, regardless of whether there are any POST variables.

Me too.

**Comment by ausi** [comment]
`Input::isPost()` is a replacement for the `if ($_POST)` check.
But I agree we should probably check all occurrences of `isPost()` and verify what we actually want to check there.

> Shouldn't we rather check for `$action = Input::post('action')` in `BackendMain.php#111` instead?

:+1:

**Comment by ausi** [comment]
PR updated, changes to `isPost()` reverted.

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
