### PR TITLE
Add a title to the collapsed element button

### PR DESCRIPTION
**Pull request by aschempp**
see #6024 (but does not fully fix that issue)

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

**Review by leofeyer — CHANGES_REQUESTED** [review]
Shouldn‘t the title change to `Contao.lang.collapse` once the element is expanded?

**Comment by aschempp** [comment]
I didn't even know you can collapse an expanded element 😂 changed in c52698f3bb56c75678bf14a2e907d84723ea3ec2

**Comment by leofeyer** [comment]
How do we handle this in Contao 5? The functionality has been rewritten in the `limit-height.js` file, so I cannot merge the changes upstream.

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/6076 for the Contao 5.1 PR

**Comment by leofeyer** [comment]
The title is set correctly now, but it is not converted to a tooltip:



---

It should look like this, shouldn‘t it?

**Comment by aschempp** [comment]
it did work for me, did you clear the browser cache?

**Comment by leofeyer** [comment]
I did. But it did not fix the problem.

**Pull request closed without merging**
