### PR TITLE
Set Samesite=LAX on unsecured connections avoid browser warnings

### LINKED ISSUE #2185: CSRF: Cookie-Deletion and unsecure connections causes Browser-Warnings (SameSite=none without secure)
**Affected version(s)**

contao >= 4 till dev-master

**Description**

as discussed [here](https://github.com/isotope/core/issues/2154), Symfony removes Cookies by fulfill the correlate Cookie-Value with the string `deleted`. The result is a Cookie with SameSite-Attribute `none` which leads in a Browser-Warning (on unsecured connections). Since Symfony 4.4, it is possible to set the SameSite-Attribute for Cookie-Clearance and we should utilize this feature.

### PR DESCRIPTION
**Pull request by HenryVolkmer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2185 

this Fix needs to merged in Master and lts-Versions too.

### CODE REVIEW

**Comment by fritzmg** [comment]
Currently _no_ `SameSite` flag is set with the _delete_ response - which means the browser's default applies. And presumably, the browser's default will be something, that should always work, given the circumstances.

I was unable to reproduce the problem. This is how I tested it:

* I visited a Contao (4.9.5) page via `http` (_not_ `https`) that contains a form using Google Chrome 84.0.4147.135
* I submitted the form, which initiates a session and thus responds with a CSRF Token and Session Cookie.
* I deleted the Session Cookie and visited a page that does not require a session.
* Contao responds with `Set-Cookie: csrf_contao_csrf_token=deleted; expires=Sun, 25-Aug-2019 09:21:55 GMT; Max-Age=0; path=/; httponly`

There was no browser warning about a malformed Cookie.

**Comment by HenryVolkmer** [comment]
@fritzmg for sure you have read the [Chromium Blog](https://blog.chromium.org/2020/05/resuming-samesite-cookie-changes-in-july.html) about the temporarily rollback of the SameSite enforcements in Chrome Browsers:

 ```
In April, we temporarily rolled back the enforcement of SameSite cookie labeling to ensure stability for websites providing essential services in the critical initial stage of COVID-19 response.
```
And i bet, you also checked this [Announcement](https://www.chromestatus.com/feature/5633521622188032).

Please check against all existing Browsers and Implementations of Blink (WebKit on ios) and Gecko.
if one fails, this issue is valid.

(Spoiler: start tests against Firefox v79)

**Comment by HenryVolkmer** [comment]
> Currently _no_ `SameSite` flag is set with the _delete_ response - which means the browser's default applies.

wtf?

**Comment by fritzmg** [comment]
> (Spoiler: start tests against Firefox v79)

I am able to reproduce the Warning with Firefox v79.0 with my steps above. In our original discussion in one of the last mumble calls we did not anticipate any problems caused by the _warning itself_ - which seems to be the case though (see the [issue in Isotope](https://github.com/isotope/core/issues/2154)).

@contao/developers May be it is best to always set the `SameSite` attribute, instead of relying on the browser's default? https://web.dev/samesite-cookie-recipes/#how-to-implement-samesite-today suggests to do this too.

> You can also choose to do nothing and just allow the browser to enforce its default, but this comes with the risk of inconsistent behavior across browsers and potential console warnings for each cookie.

**Comment by HenryVolkmer** [comment]
> ... In our original discussion in one of the last mumble calls we did not anticipate any problems caused by the _warning_ itself - which seems to be the case though (see the [issue in Isotope](https://github.com/isotope/core/issues/2154)).

By now its a Warning, in several Months, the cookie will be rejected and wont override the current cookie (no deletion will be performed). So, its a urgent issue.

**Comment by fritzmg** [comment]
> By now its a Warning, in several Months, the cookie will be rejected and wont override the current cookie (no deletion will be performed). So, its a urgent issue.

Presumably, once the browser is updated to reject the cookie, its defaults will be updated too. It would not make sense for the browser to reject a cookie based on its own defaults. Therefore there wouldn't be any warning any more for cookies that do not set the `SameSite` attribute. Chrome's future default for `SameSite` will be `Lax` and so will likely be Firefox's. At least that's what we assumed in said public mumble call.

**Comment by aschempp** [comment]
@fritzmg does that mean this PR should not be merged (and closed)?

**Comment by fritzmg** [comment]
Not necessarily, see https://github.com/contao/contao/pull/2186#issuecomment-679029124

Imho this is something we should put up for discussion. Also I want to test the specific issue that happens in Isotope, but I simply haven't had the time yet to do so.

**Comment by leofeyer** [comment]
As discussed in Mumble on September 24th, the warning is HTTP only and should be fixed by using HTTPS.

**Comment by HenryVolkmer** [comment]
by doing so, contao ist NOT compatible with http anymore:

- no intranets
- no reverse-proxy scenarios
- no Load Balancing

please dont do that.

**Comment by fritzmg** [comment]
> by doing so, contao ist NOT compatible with http anymore:

That is not true. See https://github.com/contao/contao/pull/2186#issuecomment-679033407

**Comment by ausi** [comment]
> by doing so, contao ist NOT compatible with http anymore

A warning in the developer console of the browser does not mean that Contao is incompatible.

The warning explicitly states that the cookie `is missing the “secure” attribute`, which is only possible for HTTPS.

> * no intranets

Intranets should also use HTTPS.

> * no reverse-proxy scenarios
> * no Load Balancing

Reverse proxies and load balancing should not be affected by this because Contao sets the `secure` flag for cookies in such setups.

**Pull request closed without merging**
