### PR TITLE
Also test PHP 7.4 and fix the monorepo split job

### PR DESCRIPTION
**Pull request by leofeyer**

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]
LGTM

Just saying: This must also be tested for 4.4 as well as 4.8 :)

**Comment by leofeyer** [comment]
For the time being, Contao 4.4 and 4.8 will continue to use the old CI chain. Once Contao 4.8 is EOL, I will backport the changes to the `4.4` branch.

**Comment by Toflar** [comment]
No problem, but they have to be tested against PHP 7.4 on the old CI chain anyway.

**Review by bytehead — DISMISSED** [review]

**Comment by leofeyer** [comment]
Ah, I see, you are referring to the `allow_failures` setting in the `.travis.yml` file. 👍

**Review by bytehead — APPROVED** [review]
LGTM

**Pull request merged**
