### PR TITLE
Stop using == '' with regard to PHP 8

### PR DESCRIPTION
**Pull request by leofeyer**
See https://3v4l.org/XfAXs

### CODE REVIEW

**Comment by m-vo** [comment]
For reference, this is the RFC: https://wiki.php.net/rfc/string_to_number_comparison

If I get this correctly many of the comparisons in this PR are actually comparing strings where `==` imo is still correct (even for `'0'`). I don't think we should transform them into another representation with type juggling involved but rather make them strict or leave them unchanged.

What about `case` and `in_array` (without 3rd parameter) statements that also use non-strict comparisons?

**Comment by ausi** [comment]
> many of the comparisons in this PR are actually comparing strings

Most of these checks are boolen checks like `empty()`. I think they are more correct in most cases because an empty `array()` and the string `'0'` is mostly considered to be false in our codebase I think.

**Review by ausi — DISMISSED** [review]

**Comment by m-vo** [comment]
Well I'm thinking about all the "boolean" values or numbers with an empty state from the db that we get via dbal/models. Things like `$objComments->addReply` (&rarr; `'1'`, `''`) or `$objParent->start` (&rarr; `''`, `'0'`, `'123'`, ...) that  are actually strings and are only interpreted as boolean/integer. They either won't contain `0` (int) or `0` would mean something different.

I'd rather see them written like this:
```php
$objComments->addReply === '1'
$objComments->addReply === ''

$objParent->start !== '' && $objParent->start > $time
```

**Comment by ausi** [comment]
What if someone sets `$objComments->addReply = true;` before the comparison? The model can come from the registry so this is possible in many cases I think.

**Comment by m-vo** [comment]
Ah, you got a point there.

**Comment by m-vo** [comment]
What about `in_array`? https://3v4l.org/TqmZG

Do we have any relevant cases of this as well in the codebase?

**Comment by leofeyer** [comment]
We have one `in_array(0, ` case, which however does not cause problems. To be sure, we have still adjusted it in 984fc19427b0771f3efdbf78d38d5d936db0fc45.

**Review by m-vo — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Pull request merged**
