### PR TITLE
Add the `#[Override]` attribute

### PR DESCRIPTION
**Pull request by leofeyer**

### CODE REVIEW

**Comment by ausi** [comment]
It looks like this does not generate a warning but throws a fatal error instead?

`PHP Fatal error: …::…() has #[\Override] attribute, but no matching parent method exists in…`

In this case I’d favor using something different that is only checked by our static analysis tools. Does something like `@override` exist?

**Comment by fritzmg** [comment]
I agree that having a fatal error is a bit troublesome. If a dependency happens to change their method that we override, we would have to react immediately on it (via `contao/conflicts`), otherwise the Contao instance will be incapacitated. On the other hand if we do not use `#[Override]` the Contao instance might still work, but behave unexpectedly.

**Comment by m-vo** [comment]
Interfaces should be covered by BC, everything else that we're overriding must/should also be public API. So there is not much left which I would expect to go wrong. IMHO not really a problem.

To make this useful in any way, a fatal error seems like the only sensible choice to me.

**Comment by leofeyer** [comment]
I fully agree with @m-vo. If we don‘t want this to be enforced, we simply shouldn‘t use it.

**Comment by ausi** [comment]
I think I’m OK with the fatal error as well.

**Pull request closed without merging**
