### PR TITLE
Show custom Twig templates in the back end dropdowns

### LINKED ISSUE #3274: Allow selecting Twig templates in every back end dropdown
**Affected version(s)**

Contao 4.12

**Description**

Allow selecting `.html.twig` templates in every back end dropdown. Currently only templates where a `.html5` version exists will be listed. This includes the variant templates (underscore + variant name suffix).

### LINKED ISSUE #3805: Different Twig templates cannot be selected in the backend
**Affected version(s)**

4.12

**Description**

Wenn ich zwei verschieden Twig-Templates anlege z.B. ce_image.html.twig und ce_image_test.html.twig dann können diese in den Template-Einstellungen im Backend  nicht ausgewählt werden.
siehe auch https://contao.slack.com/archives/CK4J0KNDB/p1639302648298700

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #3274 

This is a rather simple solution to also get the custom Twig templates (`ce_text_foobar.html.twig`) to show up in the back end dropdowns. We need a more sophisticated one, that replaces the `TemplateLoader` completely, later on. But this will only be doable in Contao 5.

With this PR we're now merging the results from the new template hierarchy with the ones from the `TemplateLoader`. In theory the former would be sufficient because it also contains all PHP templates, but I think implementing it this way is safer, because it will still include files that were manually added.

### CODE REVIEW

**Comment by mlwebworker** [comment]
Wenn ich das Testen will, müsste ich was genau auschecken?

**Comment by m-vo** [comment]
> Wenn ich das Testen will, müsste ich was genau auschecken?

Entweder checkst du den Branch auf dem Remote [m-vo:twig/be-template-selection](https://github.com/m-vo/contao/tree/twig/be-template-selection) aus oder du fügst die Änderungen an den zwei Dateien (`services.yml` + `Controller`) einfach kurz händisch ein.

**Comment by mlwebworker** [comment]
Danke, werde ich mir nachher mal anschauen.

**Comment by mlwebworker** [comment]
Gerade getestet. 
4.13-RC3 
Windows 10 
XAMPP und PHP 7.4.27 
Meine testweise angelegten Twig-Templates werden sauber im Drop-Down angezeigt, wenn sie direkt unter /templates liegen.
Der Zugriff auf das Originaltemplate ist nach wie vor möglich.
Damit kann man die Nutzer hoffentlich überzeugen die Twig-Templates zu testen.
Danke Moritz

**Comment by aschempp** [comment]
Thank you @m-vo ❤️ 

Do I understand correctly that the dropdown (still) shows `ce_text_foobar` and not `ce_text_foobar.html.twig` also for a Twig template?

**Comment by mlwebworker** [comment]
@aschempp 
Es wird angezeigt das Originaltemplate aus dem Core ce_foobar.html5 und die Twig-Templates ce_foobar.html.twig und ce_foobar_v1.html.twig...
Liegt im Templates Ordner ein Template ce_foobar.html5, dann werden die twig-Templates ignoriert.

Screenshot 2022-02-14 093102

Twig-Templates in Unterordnern von Templates wurden bei meinem Test nicht berücksichtigt.

**Comment by m-vo** [comment]
> Do I understand correctly that the dropdown (still) shows ce_text_foobar and not ce_text_foobar.html.twig also for a Twig template?

Yes, the key of the hierarchy is the identifier without extension.

**Review by ausi — DISMISSED** [review]
Not sure about `System::getContainer()->get(TemplateHierarchyInterface::class)`. Apart from that 👍❤️

**Comment by aschempp** [comment]
> Not sure about `System::getContainer()->get(TemplateHierarchyInterface::class)`.

To be consistent, I would say `contao.twig.filesystem_loader` should be public and we should fetch that from the container. We also changed fetching `PageRegistry::class` to the actual service name etc.

**Comment by m-vo** [comment]
> [](https://github.com/m-vo)To be consistent, I would say contao.twig.filesystem_loader should be public and we should fetch that from the container. We also changed fetching PageRegistry::class to the actual service name etc.

~~I now went with an alias `contao.twig.hierarchy` in 98d7109c4cf745f694175b80adb5ed4460828ef1 because IMHO this should be logically decoupled from the filesystem loader. But I'm fine with using the direct reference as well.~~

I used the `contao.twig.filesystem_loader` now directly in the legacy code and added a type hint for the interface.

**Review by ausi — DISMISSED** [review]

**Review by ausi — DISMISSED** [review]

**Review by aschempp — DISMISSED** [review]
❤️

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Comment by andyKempf** [comment]
Hey,
stupid question: I have the problem in Contao 4.13.1
After I saw here that the bug was fixed, I do not know if:

- I might have done something wrong
- or the bugfix does not yet exist in Contao 4.13.1

Does anyone know more?
By the way: the Twig support is great! Thanks a lot for that!

Many greetings from Munich
Andi

**Pull request merged**
