### PR TITLE
Update Monolog to version 3

### LINKED ISSUE #6706: Add support for Monolog 3
### Description

One of my extensions requires "https://github.com/browscap/browscap-php" as a dependency.

For PHP 8.3 I need version 7.3 or later in which the Monolog dependency has been increased to Monolog `"^3.5.0"`.

Monologue 3 has been available since mid-2022, at least with PHP 8.1.
Version 3.5.0 has been available since October 2023.

Upgrade instructions can be found here.
https://github.com/Seldaek/monolog/blob/main/UPGRADE.md

Symfony already supports Monolog with 6.4.
`"monologue/monologue": "^1.25.1|^2|^3"`

### PR DESCRIPTION
**Pull request by Wusch**
Fixes #6706

First try to update monolog to verson 3. Please check the unit tests.

### CODE REVIEW

**Review by fritzmg — COMMENTED** [review]
Is it not possible to stay compatible with `monolog/monolog: ^2.0 || ^3.0`? `symfony/monolog-bridge` appears to be compatible with 1.x, 2.x and 3.x as well.

**Comment by Toflar** [comment]
I think it's fine to be compatible with v3 only, it's been a cleanup and things like log levels are converted to enums etc. so being compatible with multiple versions is not super easy. Also, I don't think it makes a lot of sense.

I'm pretty sure that quite a few extensions will rely on Monolog stuff being present without requiring it themselves in their `composer.json` like we used to have with doctrine/dbal. So we should try to minimize the issues by considering this a feature for 5.4 (or later) and keeping the current 5.3 LTS as is.

@Wusch you have until the end of the month if you want to finish that for Contao 5.4 - do you want to finish it? Changes look pretty good, we just need to get the tests working :)

**Comment by fritzmg** [comment]
> I think it's fine to be compatible with v3 only, it's been a cleanup and things like log levels are converted to enums etc. so being compatible with multiple versions is not super easy

The constants are still there in `Monolog\Logger`, just deprecated. As far as I can see that's the only major change in this PR so it should still be easy to stay compatible with all monolog versions.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Wusch.

**Pull request merged**
