### PR TITLE
Remove the old .gif theme images

### PR DESCRIPTION
**Pull request by leofeyer**
Seems we have forgotten to remove them. 🙈

### CODE REVIEW

**Comment by ausi** [comment]
~~Should we remove them in Contao 5.1? Otherwise every usage of these images in extensions would now suddenly fail.~~

**Comment by fritzmg** [comment]
We should also mention that in the `DEPRECATED.md` of Contao 4.

**Comment by leofeyer** [comment]
> Should we remove them in Contao 5.1? Otherwise every usage of these images in extensions would now suddenly fail.

I‘d prefer to remove them in Contao 5.0. There is no BC promise for themes, otherwise we would have to wait for Contao 6.

**Comment by leofeyer** [comment]
I have added an `UPGRADE.md` entry.

**Review by Toflar — APPROVED** [review]

**Pull request merged**
