### PR TITLE
Improve the search result highlighting performance

### PR DESCRIPTION
**Pull request by ausi**
This should improve performance for wildcard-heavy searches.

### CODE REVIEW

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by Toflar** [comment]
Shouldn't that go to 4.9?

**Comment by ausi** [comment]
You are probably right. This should be backported. But to version 4.4 I guess?

**Comment by ausi** [comment]
Backport: #2001

**Pull request merged**
