### PR TITLE
Fix the unit tests

### PR DESCRIPTION
**Pull request by leofeyer**
I am afraid that this will be different with the manager plugin <2.10. 🙈

### CODE REVIEW

**Comment by ausi** [comment]
Should the test verify the actual order? If not, we could sort the array before the assertion.

**Comment by leofeyer** [comment]
It is helpful if the command shows the actual order, just in case it matters (e.g. because the security bundle needs to come after the framework bundle).

**Comment by leofeyer** [comment]
@aschempp Can we make version 2.10 of contao/manager-plugin the minimum requirement for the manager bundle? Or can we have different versions of the same package in the `require` and `require-dev` sections of our composer.json?

**Comment by ausi** [comment]
> It is helpful if the command shows the actual order, just in case it matters (e.g. because the security bundle needs to come after the framework bundle).

We could test these requirements directly instead.

```php
$this->assertTrue(array_search(FrameworkBundle::class, $bundles) < array_search(SecurityBundle::class, $bundles));
```

**Review by ausi — APPROVED** [review]

**Pull request merged**
