### PR TITLE
Remove the orderField support in the picker widgets

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]

**Review by leofeyer — CHANGES_REQUESTED** [review]
We cannot remove this yet, because the `orderField` is still needed for the image gallery. However, @ausi already has an idea how to solve this. 🦊

**Comment by ausi** [comment]
> We cannot remove this yet, because the `orderField` is still needed for the image gallery.

It seems that the file tree order field is still here: https://github.com/contao/contao/blob/23b6373c8a52b576911ef4acc53de209f7ef7fe2/core-bundle/src/Resources/contao/widgets/FileTree.php#L74

So this pull request should be fine as it only removes the order field for the pageTree and the Picker, not the fileTree.

**Comment by Toflar** [comment]
Yeah, I only removed the deprecated stuff.

**Review by ausi — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
