### PR TITLE
Load the default language when generating the calendar feeds

### PR DESCRIPTION
**Pull request by leofeyer**
Otherwise, a `Trying to access array offset on value of type null` warning is triggered here:

https://github.com/contao/contao/blob/71bed4b3face7471a08becfd4c1a2fae83232578/calendar-bundle/contao/classes/Calendar.php#L356

@fritzmg We could also load the language file in the `Calendar` class if you prefer.

### CODE REVIEW

**Comment by aschempp** [comment]
This looks strange to me, the default language files should be loaded when the framework is initialized, so maybe that's missing somewhere?

**Comment by fritzmg** [comment]
> This looks strange to me, the default language files should be loaded when the framework is initialized, so maybe that's missing somewhere?

No, the default language file is only loaded by the respective controller or controller-like class. e.g. `PageRegular`, `BackendMain`, etc. It is not loaded when executing `ContaoFramework::initialize()`.

**Review by fritzmg — DISMISSED** [review]
We also load the `default` language file in the `LegacyCron` in Contao `4.13`:

https://github.com/contao/contao/blob/d2b1b88aade102513648caf61c994f69c5ec10fb/core-bundle/src/Cron/LegacyCron.php#L81-L82

This will become moot anyway if we re-implement the calendar feed as a controller, just like the news feed.

**Comment by leofeyer** [comment]
The fix is wrong. We must load the feed language instead, which might be different per file. I will adjust the PR accordingly.

**Comment by fritzmg** [comment]
Alternatively we could change it to use the translator.

**Review by aschempp — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Pull request merged**
