### PR TITLE
Revert 'Use the user data instead of magic methods'

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes https://github.com/contao/contao/pull/7433#issuecomment-2292960677

### CODE REVIEW

**Comment by fritzmg** [comment]
But that reintroduces the original issue. Though personally I am fine with having the known limitation that you cannot add a field called `roles` to `tl_user`.

**Comment by leofeyer** [comment]
If we didn‘t use the magic methods, we would have to add an `if ($field == 'alexf')` special handling at several places.

**Comment by leofeyer** [comment]
> If we didn‘t use the magic methods, we would have to add an `if ($field == 'alexf')` special handling at several places.

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Closing this in favor of #7462.

**Pull request closed without merging**
