### PR TITLE
Allow to create a model from array data instead of database result

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by leofeyer** [comment]
Why not `(new Model())->setRow($data)`?

**Comment by ausi** [comment]
> Why not `(new Model())->setRow($data)`?

Maybe because of missing support for relations and registry?

**Comment by leofeyer** [comment]
I'm not sure about relations but adding `->attach()` will attach the model to the registry.

**Comment by aschempp** [comment]
Because there is no reason at all a model should require a database result. Especially not if you want to move away from the Contao Database class in Contao 4 😉

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
