### PR TITLE
Fix the basic entities migration

### LINKED ISSUE #5300: Migration 4.13 -> 5.0
### Affected version(s)

5.0.2

### Description

The migration to Contao 5 will not succeed if you do not have all core extensions installed. Problem is https://github.com/contao/contao/blob/5.x/core-bundle/src/Migration/Version500/BasicEntitiesMigration.php where the tables are referenced.

```
/usr/bin/php8.1 vendor/bin/contao-console contao:migrate

                                                                                                                        
 [INFO] Creating a database dump to "backup__20220921132359.sql.gz" with the default options. Use --no-backup to disable
        this feature.                                                                                                   
                                                                                                                        

Pending migrations
------------------

 * Contao\CoreBundle\Migration\Version500\BasicEntitiesMigration
 * Contao\CoreBundle\Migration\Version500\BooleanFieldsMigration
 * Contao\CoreBundle\Migration\Version500\MemberCountryUppercaseMigration
 * Contao\CoreBundle\Migration\Version500\OrderFieldMigration
 * Contao\NewsBundle\Migration\FeedMigration
 * MadeYourDay\RockSolidCustomElements\Migration\BasicEntitiesMigration

 Execute the listed migrations? (yes/no) [yes]:
 > yes

Execute migrations
------------------

15:24:02 CRITICAL  [console] Error thrown while running command "contao:migrate". Message: "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.tl_calendar' doesn't exist" ["exception" => Doctrine\DBAL\Exception\TableNotFoundException^ { …},"command" => "contao:migrate","message" => "An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.tl_calendar' doesn't exist"]

In ExceptionConverter.php line 49:
                                                                                                                                                     
  An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.tl_calendar' doesn't exist  
                                                                                                                                                     

In Exception.php line 28:
                                                                                                      
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.tl_calendar' doesn't exist  
                                                                                                      

In Connection.php line 69:
                                                                                                      
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'xxx.tl_calendar' doesn't exist  
                                                                                                      

contao:migrate [--with-deletes] [--schema-only] [--migrations-only] [--dry-run] [--format FORMAT] [--no-backup] [--hash HASH]

```

### PR DESCRIPTION
**Pull request by ausi**
Fixes #5300

### CODE REVIEW

**Review by m-vo — APPROVED** [review]

**Comment by MDevster** [comment]
Works like a charm!

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by MDevster** [comment]
@leofeyer Is there a possibility to release the fix already as 5.0.3?

**Comment by leofeyer** [comment]
New releases are coming up this week. 👍

**Pull request merged**
