### PR TITLE
Stop using the `src/Resources` directory

### PR DESCRIPTION
**Pull request by leofeyer**
We already have over 80 commits that just move resources between `*-bundle/contao` and `*-bundle/src/Resources/contao`, so we can merge upstream from Contao 4 to 5:

https://github.com/search?q=repo%3Acontao%2Fcontao+Move+the+resources&type=commits

Luckily, we can already get rid of `src/Resources` in Contao 4.13 to prevent these kind of commits from flooding the repo.

### CODE REVIEW

**Comment by ausi** [comment]
I’m not sure if this is a good idea in a patch release. Couldn’t it be that some applications or extensions rely on certain files to be found in `src/Resources`?

> We already have over 80 commits that just move resources between `*-bundle/contao` and `*-bundle/src/Resources/contao`, so we can merge upstream from Contao 4 to 5

Maybe there is a better solution for this that doesn’t require these commits… 🤔

**Comment by leofeyer** [comment]
I doubt that there is. I have already tried using symlinks, but they are overwritten during the upstream merge.

> Couldn’t it be that some applications or extensions rely on certain files to be found in src/Resources?

They certainly should not. But maybe we can fix this by adding symlinks from `src/Resources/contao/` to `contao/`?

**Comment by ausi** [comment]
> I doubt that there is.

Did you try something like `merge -sort --find-renames=25%`?

**Comment by aschempp** [comment]
I am sure I and other are using the resources file where they are expected. So I fully agree with @ausi we shouldn't do that in a patch release …

**Comment by leofeyer** [comment]
> Did you try something like `merge -sort --find-renames=25%`?

Unfortunately, `git merge -sort` does not make a difference. And `--find-renames=25%` does not seem to be supported anymore.

**Comment by leofeyer** [comment]
@ausi and I will implement another workaround if the problem persists.

**Pull request closed without merging**
