### PR TITLE
Changed wrong table name in comment on permissions

### PR DESCRIPTION
**Pull request by stefanschleich**

### CODE REVIEW

**Comment by leofeyer** [comment]
Since this is a bugfix, please base your PR on the `4.4` branch.

**Comment by stefanschleich** [comment]
> Since this is a bugfix, please base your PR on the `4.4` branch.

I'm not sure how to do this. Just by committing the file with the changes made to 4.4 version of it?

**Comment by leofeyer** [comment]
Yes.

**Comment by leofeyer** [comment]
Thank you @stefanschleich.

**Pull request merged**
