### PR TITLE
Always report the installation as being complete

### PR DESCRIPTION
**Pull request by ausi**
The existence of the *localconfig.php* is no longer a requirement for an installation to be “complete”.

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by ausi** [comment]
Needs to be merged after #4935 
(the failing tests should then resolve themself)

**Review by m-vo — APPROVED** [review]

**Comment by leofeyer** [comment]
The tests are failing because we are still using the method here:

https://github.com/contao/contao/blob/b1233f34a9990937ace27c5d5329473b4cb3824e/core-bundle/src/Framework/ContaoFramework.php#L223-L225

I think we can remove these lines as well, can‘t we?

**Comment by fritzmg** [comment]
@leofeyer see https://github.com/contao/contao/pull/4938#issuecomment-1172925642

#4935 needs to be merged first. Then that would be gone anyway (see https://github.com/contao/contao/pull/4935/files#diff-11c0c0e6a08183ce10e460bd6381f63a6b7a773abf1692e4e1b85f85dec0558b).

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
