### PR TITLE
Correctly cache Contao translations that only exist as Symfony translations

### LINKED ISSUE #6741: Symfony translations are not loaded if no Contao language file exists
### Affected version(s)

5.3

### Description

I have created a new DCA with translations in `/translations/contao_tl_my_dca.en.yaml`. The file is not loaded as long as there is no _legacy_ language file, e.g. in `/contao/languages/en/tl_my_dca.php`. As soon as I add the legacy file, even if it is empty, the Symfony translations are loaded as expected.

### PR DESCRIPTION
**Pull request by fritzmg**
Fixes #6741

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

**Review by ausi — COMMENTED** [review]
Do we also need to create an empty cache file so that we do not search for language files here? https://github.com/contao/contao/blob/4034b234a11241e225c67ad86ee94dec0cbf690a/core-bundle/contao/library/Contao/System.php#L474-L480

**Comment by fritzmg** [comment]
True. I think we can change the logic of the `ContaoCacheWarmer` a bit in general. We already retrieve the catalogue for a locale in the lines above and I think we can set the `$processed` state to `true` there instead.

**Comment by fritzmg** [comment]
The addition of

```php
if (!str_starts_with($domain, 'contao_')) {
    continue;
}
```

is actually another bugfix. There was no check previously and thus bogus Contao language cache files were created.

**Review by ausi — APPROVED** [review]

**Review by aschempp — APPROVED** [review]
Manually tested this in my project, seems to do the job 👍

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
