### PR TITLE
Remove CLS in file manager

### LINKED ISSUE #6662: Layout shift in file manager in Chrome due to images
### Affected version(s)

4.13.x, 5.2.x, 5.x

### Description

There is a cumulative layout shift issue in Chrome in the file manager. In Firefox all the `` occupy their size according to the `width` and `height` attributes as expected, causing no layout shift while the images are loading:

\
However, in Chrome this is not working:

\
Causing the layout to shift while the images are loaded (or lazy loaded after scrolling). Even though the inspector tells us, that the correct intrinsic size is determined:

\
I think part of the problem is that we are lacking `display: block` (or `inline-block`) for these `` - but that does not fix the issue in Chrome.

@ausi may be you have an idea why this is happening?

### PR DESCRIPTION
**Pull request by zoglo**
Fixes #6662

____

**Description**

- When scrolling down within the file browser, Chromium-based browsers do not take the img attributes into account when being lazy loaded. This PR fixes the issue

____

**Solution**

- Remove width: auto from preview-images within the backend and only add it when aspect-ratio is not supported

____

**Reference**

- https://github.com/contao/contao/issues/6662
- https://caniuse.com/mdn-css_properties_aspect-ratio
- https://caniuse.com/mdn-html_elements_img_aspect_ratio_computed_from_attributes

### CODE REVIEW

**Comment by aschempp** [comment]
Does the `aspect-ratio` check have any effect since we're not setting `aspect-ratio` on the images at all? Not sure why they have an `width: auto` (and `height:auto`) if they have size properties in the HTML anyway?

**Comment by zoglo** [comment]
> Does the `aspect-ratio` check have any effect since we're not setting `aspect-ratio` on the images at all? Not sure why they have an `width: auto` (and `height:auto`) if they have size properties in the HTML anyway?

@aschempp with that check, we are actually making sure that those with Safari < 14.2 aka the old non updated Macs will not have any issues. See it more as a BC Layer for the 9% of Safari users.

And the width and height auto is legacy I suppose

**Comment by ausi** [comment]
I don’t think we can remove `width: auto` here. 
E.g. an image like `` would be distorted then.
To me this looks like a bug in chrome (or a missing feature). Not sure if or how we can work around this.

**Comment by zoglo** [comment]
> I don’t think we can remove `width: auto` here. E.g. an image like `` would be distorted then. To me this looks like a bug in chrome (or a missing feature). Not sure if or how we can work around this.

We still have the ``max-width: 100px`` with the ``height: auto`` in effect, which will fallback with the browser-native aspect-ratio:
image
image

And hence the fallback for any browser not supporting https://caniuse.com/mdn-html_elements_img_aspect_ratio_computed_from_attributes

**Comment by ausi** [comment]
> We still have the `max-width: 100px` with the `height: auto` in effect, which will fallback with the browser-native aspect-ratio

But the image would still be distorted as it is displayed as 100x75 instead of 63x75 then.

**Comment by zoglo** [comment]
> But the image would still be distorted as it is displayed as 100x75 instead of 63x75 then.

Do you have steps to reproduce that in a browser that does support the elements image aspect ratio?

**Comment by ausi** [comment]
All browsers (Firefox, Chrome, Safari) behave the same here, see https://codepen.io/ausi/pen/WNmvJaW

**Comment by zoglo** [comment]
Been trying to think of a better solution but you are right @ausi .

My first approach was giving .tl_file a min height but that would only be possible for images that have a preview.
Browsers behave differently and the only way to actually fix this would be having a width 100% and removing the max-height, however, this would lead to the container growing in size for portrait images.

Unsure how this could be fixed due to the preview images not having a static size

**Comment by fritzmg** [comment]
> All browsers (Firefox, Chrome, Safari) behave the same here, see https://codepen.io/ausi/pen/WNmvJaW

Curiously in the file manager the image does not get distorted 🤔 

> Unsure how this could be fixed due to the preview images not having a static size

They do through their `width` and `height` attributes. It's just Chrome that misbehaves here.

**Comment by ausi** [comment]
As discussed in the call today I will try to report the Chrome bug.

**Comment by ausi** [comment]
> To me this looks like a bug in chrome (or a missing feature).

https://issues.chromium.org/issues/324445632

**Comment by leofeyer** [comment]
I will close this pull request then, as there is nothing more to do on our side.

**Pull request closed without merging**
