### PR TITLE
Do not require symfony/symfony

### PR DESCRIPTION
**Pull request by leofeyer**
Currently Contao 4.6 implicitly requires at least Symfony 4.1, because we need `symfony/http-kernel` and `symfony/monolog-bridge` in at least version 4.1.

However, if we stop requiring `symfony/symfony`, all components but the two mentioned above could be installed in version 3.4, 4.0 or 4.1, therefore this PR replaces requirements for `symfony/symfony` and for `symfony/framework-bundle` with their respective components.

@contao/developers Do you prefer merging this PR so Contao 4.6 is compatible with Symfony 3.4 or do you prefer to keep `symfony/symfony` with Contao 4.6 not being compatible with Symfony <4.1 anymore?

### CODE REVIEW

**Comment by bytehead** [comment]
I'm definitely for merging this! 👍

**Comment by Toflar** [comment]
> because we need symfony/http-kernel and symfony/monolog-bridge in at least version 4.1.

Just for some background info: why is this?

**Comment by leofeyer** [comment]
To fix the logging:

https://github.com/contao/contao/blob/ccab8095832d255f9cad159e95c6d067305ad234/manager-bundle/src/Resources/skeleton/app/config_prod.yml#L14

The feature has been added in version 4.1.

**Comment by Toflar** [comment]
Okay, any reason why we do not allow 4.2?

**Comment by leofeyer** [comment]
Because it has not yet been released. 😄

**Comment by Toflar** [comment]
I'm fine with the changes then, thanks for the additional info!

**Comment by aschempp** [comment]
I don't think it makes sense to allow some components in 4.1 and some in 3.4. That will only cause issues in the long run. The only reason to allow 3.4 would be so someone that **really** requires 3.4 can still update, but that possibly won't work because some of the components are not compatible …

Honestly I'm usually in favor of keeping compatibility, but if we raise the dependency to 4.1 then we can also get rid of some stupid stuff like our `SessionListener` that needs to work across multiple incompatible versions…

**Comment by aschempp** [comment]
Also, allowing a constraint of `symfony/http-kernel 3.4` for all dependencies only makes the solver slow because it can never be installed when all bundles have a requirement on `contao/core-bundle`…

**Comment by fritzmg** [comment]
Currently a lot of bundle extensions aren't compatible with Contao 4.6, since their DCA callback and Hook listener services are not defined as "public". As a workaround, one could just require `symfony/dependency-injection:^3.0` - however that does not work in Contao `4.6.0` due to the dependency in the core-bundle on `symfony/http-kernel:^4.1` which in turn requires `symfony/dependency-injection:^4.1`. This means I have to wait until all my dependencies have been updated for Contao 4.6 (wherever applicable), before I can use it in production.

**Comment by ghost** [comment]
A new issue thereto has been created at contao/contao#30.

**Pull request merged**
