### PR TITLE
Add the Osano Cookie Consent cookie to the cookie deny list

### PR DESCRIPTION
**Pull request by Mynyx**
Add the cookie ``cookieconsent_status`` of [Osano Cookie Consent](https://www.osano.com/cookieconsent) to the cookie blacklist.

See https://github.com/osano/cookieconsent/blob/0817f677a412bfef7edb6e26901377b0a3a193c2/src/options/popup.js#L15

### CODE REVIEW

**Comment by andreheeke** [comment]
Shouldn't we rather find a general solution how to manually add more cookies to the blacklist? Otherwise, everyone will soon have the idea to push their tool into the Contao repository.

**Comment by fritzmg** [comment]
You can already define your  own white list. See https://docs.contao.org/dev/reference/config/#environment-variables-for-the-contao-managed-edition

**Comment by fritzmg** [comment]
Also the Osano Cookieconsent script should switch to `localStorage`, since it is purely client side - or at least only fall back to using Cookies for legacy browsers. There was a PR for that a while ago, but it got rejected: https://github.com/osano/cookieconsent/pull/97

**Comment by Mynyx** [comment]
> Otherwise, everyone will soon have the idea to push their tool into the Contao repository.

Osano Cookie Consent is not just any tool, it is one of the most popular, according to their own statement the most popular.

**Review by Toflar — DISMISSED** [review]

**Comment by Toflar** [comment]
> Shouldn't we rather find a general solution how to manually add more cookies to the blacklist? Otherwise, everyone will soon have the idea to push their tool into the Contao repository.

The idea of the blacklist is to increase the possibility of cache hits without forcing every single Contao user to deep-dive into the topic of caching. We just want to generate good results by default.
If you know what you're doing and you understand the concept, you can specify the whitelist. This then increases the cache hits to the maximum :)

**Comment by leofeyer** [comment]
I fully agree with @Toflar. We should try to add as many commonly used tools as possible to the blacklist, so Contao works nicely with them out of the box.

**Review by aschempp — DISMISSED** [review]

**Review by aschempp — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Mynyx.

**Pull request merged**
