### PR TITLE
Set the max-age to 0 in the back end

### LINKED ISSUE #1928: No cache headers in back end responses
**Affected version(s)**

Contao 4.9

**Description**

In Contao 4.4, any back end request also returned the following headers:

```
Cache-Control: max-age=0, must-revalidate, private
Expires: Fri, 10 Jul 2020 12:56:44 GMT
```

(`Expires` will always be the current time). In Contao 4.9 however, this is not the case any more. This in itself is not problematic, but it breaks the back end, if someone happens to have

```
ExpiresByType text/html "access plus 6 hours"
```

in their `.htaccess`, since this causes the back end requests to be cached by the browser for the configured time.

Shouldn't we disallow caching of back end responses in the private cache with the appropriate response headers? Quite a few users in the Contao community already stumbled over this issue.

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1928
| Docs PR or issue | -

### CODE REVIEW

**Comment by aschempp** [comment]
Why would that be necessary? The back end always has a (session) cookie? (Except for the login screen)

**Comment by leofeyer** [comment]
According to @Toflar:



See https://github.com/contao/contao/issues/1928#issuecomment-656686180

**Comment by fritzmg** [comment]
Shouldn't this may be be done in a response listener instead, where you check the scope?

**Comment by fritzmg** [comment]
Also currently back end responses in the `prod` env have

```
Cache-Control: private
```

but in the `dev` env that response header is missing. Shouldn't it also be present in the `dev` env?

**Comment by Toflar** [comment]
I would actually rather set `Cache-Control: no-store`.

**Comment by leofeyer** [comment]
> Shouldn't this may be be done in a response listener instead, where you check the scope?

Why? We are also setting the front end response headers in the `FrontendTemplate` class:

https://github.com/contao/contao/blob/d0ec9de119f3b2e1f16d916d7a2d11c353744a0c/core-bundle/src/Resources/contao/classes/FrontendTemplate.php#L88-L91

**Comment by aschempp** [comment]
> but in the `dev` env that response header is missing. Shouldn't it also be present in the `dev` env?

I think we need to find the reason for this and fix that, instead of some _arbitrary_ new headers just for the sake of it.

**Comment by leofeyer** [comment]
True. I have reopened the original issue and will close this PR now.

**Pull request closed without merging**
