### PR TITLE
Add the "template" insert tag

### LINKED ISSUE #665: Also check /contao/templates in the "file" insert tag
The `{{file::template.html5}}` insert tag can be used to include a template file. However, it only looks in the `/templates` directory and not in `/contao/templates`, therefore I always end up using a custom insert tag that checks both directories.

@contao/developers Do you think we should enhance the `{{file}}` insert tag to check both directories?

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #665

### CODE REVIEW

**Comment by m-vo** [comment]
Being primed by the twig discussion I think the embedded files are assets and not templates because they are lacking any context. The fact that there could be PHP code included that would make the output 'impure' IMHO is a very wrong design approach. 

The following questions come to my mind:
 - if this is implemented: Should we deprecate the `file` insert tag?
- In general: how can I disable certain core insert tags? (e.g. if users embedding arbitrary templates is a security concern)

**Comment by leofeyer** [comment]
> * if this is implemented: Should we deprecate the `file` insert tag?

No. The `file` insert tag does something different.

> * In general: how can I disable certain core insert tags?

This question does not belong here, as it has nothing to do with the pull request.

**Comment by m-vo** [comment]
>This question does not belong here, as it has nothing to do with the pull request.

It sure has as I would want to disable this special insert tag if this would be merged.

**Comment by ausi** [comment]
If we want to add this insert tag, it should use a real template object instead of just `include`ing the file IMO. Otherwise templates that are added with `{{template::*}}` have the `InsertTags` object as `$this` instead of a template object which would create errors for things like `$this->insert(…)`.

But I’m also not sure about the security implications.

**Comment by fritzmg** [comment]
> If we want to add this insert tag, it should use a real template object instead of just `include`ing the file IMO.

I agree, and I thought this was what was originally agreed on in #665

**Comment by aschempp** [comment]
I agree as well, we should use `new FrontendTemplate()` to allow for inheritance etc

**Review by aschempp — CHANGES_REQUESTED** [review]
Still standing by my statement (shut up PR reminder)

**Comment by leofeyer** [comment]
> As discussed in Mumble on November 28th, we do not want to support the `/contao/templates` path in the `{{file}}` insert tag.

**Comment by fritzmg** [comment]
@leofeyer but that has nothing to do with this issue? This issue is about being able to insert a template from `templates/` in the `FrontendTemplate` context via a `{{template::*}}` insert tag.

**Comment by leofeyer** [comment]
See the original issue: #665

**Comment by fritzmg** [comment]
Yes, but why scrap the whole idea?

**Comment by ausi** [comment]
> Yes, but why scrap the whole idea?

Because of the security implications. Allowing to insert a template with arbitrary data would enable every user to output practically anything they want.

**Comment by fritzmg** [comment]
Which is already possible with `{{files::*}}`? What would be the difference to parsing the template in the `FrontendTemplate` context?

**Comment by ausi** [comment]
> What would be the difference

Currently, you can only include files from the root templates folder and you can only set `$_GET` parameters which are “protected” by the `Input` class.

**Pull request closed without merging**
