### PR TITLE
Use Lucide icons in the back end

### LINKED ISSUE #7091: Use Lucide icons in the back end
### Description

At the moment, we use a mixture of our own icons and the deprecated Feather icons in the back end. To make the back end more consistent and to make it easier for third-party developers to find icons, we want to use [Lucide icons](https://lucide.dev) in the future.

Related issues: #820 #2218 #5391 #5926

### PR DESCRIPTION
**Pull request by leofeyer**
Implements #7091

### CODE REVIEW

**Comment by leofeyer** [comment]
I‘m quite happy with the new icons except for the "edit child records" one. Maybe someone has a better idea regarding both the icon and the color.

**Comment by heimseiten** [comment]
I like the between-horizontal-start in Contao orange for the child icon.

**Comment by contaoacademy** [comment]
Will the new icons also be integrated into the 5.3 LTS?

**Comment by fritzmg** [comment]
> Will the new icons also be integrated into the 5.3 LTS?

No, it's a new feature.

**Comment by aschempp** [comment]
I like it! Ideas/findings
 - try to use the `copy-plus` icon for copying records
 - try `layout-list` for child elements
 - try `component` or `package` icon for theme modules
 - try `save` icon for theme export
 - try `import` icon for theme import
 - try `git-compare-arrows` for comparing templates as well as comparing versions
 - try `clipboard-paste` where arrow is not only inside the pasteboard (and adjusted version for paste after)
 - the default tree node icon (e.g. in favorites list or template file) does not look updated
 - the disabled delete icon looks incorrect (see screenshot)
    Bildschirmfoto 2024-06-15 um 20 54 31
- are template folder intentionally marked with a lock icon?
- the icon for internal and external redirect look the same? Maybe use something with `external-link`?

**Comment by leofeyer** [comment]
> * try to use the `copy-plus` icon for copying records

I‘d rather keep the current icon, because `copy-plus` is harder to distinguish from "copy with children":



---

> * try `component` or `package` icon for theme modules

<del>The component icon doesn‘t look good next to the layout icon. And I don‘t like the 3D effect of the package icon, because it does not match any other icon.</del> Solved in 840af49989487aeaf80d350bada6237672da3b54.

---

> * try `save` icon for theme export
> * try `import` icon for theme import

Like this?



---

> * the default tree node icon (e.g. in favorites list or template file) does not look updated

I cannot reproduce. Can you make a screenshot?

> * the disabled delete icon looks incorrect (see screenshot)

I cannot reproduce this, either. Maybe a browser cache problem?



---

> * are template folder intentionally marked with a lock icon?

They have always been:



---

> * the icon for internal and external redirect look the same? Maybe use something with `external-link`?

This is intentional. You only need to know that it is a redirect page; whether the redirect is internal or external is a detail that does not need to be reflected in the status icon.

**Comment by fritzmg** [comment]
> This is intentional. You only need to know that it is a redirect page; whether the redirect is internal or external is a detail that does not need to be reflected in the status icon.

I have to disagree here, this is a rather important distinction.

**Comment by leofeyer** [comment]
No, it is not. We even discussed merging the two page types because it really makes no sense to have both.

**Comment by aschempp** [comment]
I like the import export much better this way.

Also noticed this when trying to move a root page, can you reproduce that (the root paste icon is left-aligned)?
Bildschirmfoto 2024-06-17 um 14 58 00

**Comment by aschempp** [comment]
Also noticed the `plus` icon looks really big everywhere, I think it should be similar in size to the eye. That would also look better in the global operation for adding a record (next to the back icon).

Bildschirmfoto 2024-06-17 um 15 16 11

**Comment by aschempp** [comment]
> > * the default tree node icon (e.g. in favorites list or template file) does not look updated
> 
> I cannot reproduce. Can you make a screenshot?

Here's what templates look like for me

Bildschirmfoto 2024-06-17 um 15 40 43

**Comment by fritzmg** [comment]
> No, it is not. We even discussed merging the two page types because it really makes no sense to have both.

In the absence of a folder page you typically use the internal redirect redirect page when creating a folder structure in your site structure, for menu items that are only there to contain other menu icons (and show them on hover for the desktop for example). The internal redirect also redirects you automatically to its first child, if no redirect page is selected.

In the external redirect page you have to define any arbitrary URL. It does not have any special logic. Using it as a container as described above makes no sense, as the target URL is mandatory.

Merging the two also does not make any sense to me, at least currently. As long as we have both it also important to be able to visually distinguish between the two. (i.e. having links to external resources, like links to social pages etc., should be clearly distinguishable from the other pages).

**Comment by fritzmg** [comment]
> Like this?
> 

Shouldn't it be the other way around? I find it confusing that an arrow pointing _away_ from something actually _imports_ something, and that an arrow pointing _towards_ something _exports_ something.

**Comment by asaage** [comment]
> Shouldn't it be the other way around? I find it confusing that an arrow pointing _away_ from something actually _imports_ something, and that an arrow pointing _towards_ something _exports_ something.

unless that "something" resembles a local disk 🙈

**Comment by asaage** [comment]
> The internal redirect also redirects you automatically to its first child, if no redirect page is selected.

essential feature - don't remove that please!

**Comment by leofeyer** [comment]
> I find it confusing that an arrow pointing _away_ from something actually _imports_ something, and that an arrow pointing _towards_ something _exports_ something.

That is because you **upload** the file to be imported and you **download** the file to be exported.

**Comment by leofeyer** [comment]
> > The internal redirect also redirects you automatically to its first child, if no redirect page is selected.
> 
> essential feature - don't remove that please!

There are no plans to remove any functionality! A unified redirect page type could also provide the "redirect to first child" feature.

**Comment by leofeyer** [comment]
> Also noticed this when trying to move a root page, can you reproduce that (the root paste icon is left-aligned)?

Fixed in 408a154e8f59b32edbc94b765e302df23e8a4f68.

> Also noticed the `plus` icon looks really big everywhere, I think it should be similar in size to the eye.

It is. You have to compare against its disabled state:

**Comment by aschempp** [comment]
I would prefer something like `file-spreadsheet` for the CSV import icon in table wizard.

Bildschirmfoto 2024-06-19 um 10 49 38

**Comment by leofeyer** [comment]
> I would prefer something like `file-spreadsheet` for the CSV import icon in table wizard.

For consistency, we should use the same icon as for the other import actions. Fixed in 9254063b87323b3bed7d835ca4e7d625409f3077.

**Comment by leofeyer** [comment]
> Shouldn't it be the other way around? I find it confusing that an arrow pointing _away_ from something actually _imports_ something, and that an arrow pointing _towards_ something _exports_ something.

Changed in b43708b82a4fabb08cd775bcd89923e557d6683f.

**Comment by leofeyer** [comment]
All suggestions have been addressed. I will now merge the PR so I can start working on the follow-up PRs. If you find any other problem, please create a new issue on GitHub.

**Pull request merged**
