### PR TITLE
Use a template for the article element

### LINKED ISSUE #5752: Templates and css-ID/Class for Include-Elements
### Description

Is there any reason why not all Include-Elements have an individual template like all other content elements?
- Article has neither a template no a css-ID/Class input field. This results in a missing and adjustable covering `<div></div>`
- Content-Element has no template (but it has css-ID/Class)
- Form has no template (but it has css-ID/Class)
- Module has no template (but it has css-ID/Class)
All further have both.

Especially the Article-Element may becomes useless if the included one is not the only in the parent article because there is no chance for css styling this element.

As workaround only manual HTML-elements with `<div class="..." ></div>` are a solution but in this case insert-tags are the more simple solution.

So fare the Article-Element has not really an advantage.

A comparable problem is already discussed years ago for HTML-elements [https://github.com/contao/core/issues/1148](url)

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/5752

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
I thought we don‘t add new `.html5` templates anymore because content elements are controllers now? Although there is no `ArticleController` class. 🤔 @m-vo /cc

**Comment by ausi** [comment]
> I thought we don‘t add new `.html5` templates anymore because content elements are controllers now?

Agree, I think we should add an `ArticleController` to implement this feature.

**Comment by aschempp** [comment]
> I think we should add an ArticleController to implement this feature.

This would mean all (legacy) content elements would be executed in a subrequest, whereas they are currently executed in the main request. Not sure that's a good idea …

**Comment by fritzmg** [comment]
> This would mean all (legacy) content elements would be executed in a subrequest, whereas they are currently executed in the main request. Not sure that's a good idea …

But all elements will be implemented as fragment controllers, will they not? Including all the different types of include elements.

**Comment by ausi** [comment]
As discussed today we want to implement this as a fragment controller.

Maybe this can be implemented as a nested content element, https://github.com/contao/contao/pull/5814

**Comment by aschempp** [comment]
Closing this PR since I'm not planning to implement that. Anyone else is free to open a new PR 😊

**Pull request closed without merging**
