### PR TITLE
Remove support for deprecated value in tl_article.printable

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]
~~I think you should also add~~

```
$this->Template->printable = false;
```

**Comment by ausi** [comment]
> I think you should also add

This is already there, or at which position do you think it should be added?

https://github.com/contao/contao/blob/6552e7115f9edb0fabb03b69c5d6d2cf749ddc75/core-bundle/src/Resources/contao/modules/ModuleArticle.php#L179

**Review by ausi — APPROVED** [review]

**Comment by fritzmg** [comment]
Yes, I realised while writing the comment - I accidentally submitted it 🙈

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
