### PR TITLE
Increase the speed of the functional tests

### PR DESCRIPTION
**Pull request by ausi**

### CODE REVIEW

**Comment by m-vo** [comment]
before: 
image

after:
image

:tada:

**Review by aschempp — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Comment by ausi** [comment]
@fritzmg @m-vo execution times from the current state of this PR would be interesting ☺️

**Comment by fritzmg** [comment]
I tested under MariaDB `10.6.3` with `innodb_stats_on_metadata=0` and `performance_schema=0`:

| Branch | Min | Max | Avg |
| --- | ---:| ---:| ---:|
| **4.13** | 3:01.149 | 3:10.287 | 3:05.486 |
| #4376 | 1:05.768 | 1:07.659 | 1:06.911 |

**Comment by m-vo** [comment]
MariaDB 10.6.7 with or without performance monitoring takes ~34s now. Previously over 5minutes.

**Review by m-vo — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]
This is amazing! 🚀

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
