### PR TITLE
Include mounted root pages in the topMostRootIds

### LINKED ISSUE #5283: Anlegen von Seiten bei frischen Installationen nicht möglich
### Affected version(s)

4.13.9

### Description

Mit einer frischen Installation von Contao 4.13.9 konnte ich lediglich "Startpunkt einer Website" hinzufügen. 

image

Das Anlegen neuer Seiten ist nicht möglich. Ich kann zwar beliebig viele Startpunkte hinzufügen, diese dann aber auch nicht mehr bearbeiten oder löschen:

image

Workaround: Downgrade auf 4.13.8, um eine Seite anzulegen, danach wieder Update auf 4.13.9 und ich kann dann zumindest unter der neu angelegten Seite weitere Elemente anlegen. Aber das Bearbeiten von Startpunkten oder Einfügen in Startpunkten ist nicht möglich.

### PR DESCRIPTION
**Pull request by ausi**
Fixes #5283

Reverts #5268 and applies a different fix

### CODE REVIEW

**Comment by ausi** [comment]
As far as I understand it, all IDs that are in `$this->visibleRootTrails` are considered readonly and get no action buttons. So we should not add a mounted page to this array.

But when loading the `$topMostRootIds` we should include all mounted pages too so that we get all root pages (directly mounted as well as readonly ones)

**Review by Toflar — APPROVED** [review]
Should we add `array_unique()`?

**Comment by ausi** [comment]
> Should we add `array_unique()`?

Not needed I think as the query would handle that, and also `$this->root` should never overlap with `$this->visibleRootTrails`.

**Review by Toflar — CHANGES_REQUESTED** [review]
Blocking this because I'm not entirely sure this is correct. `$topMostRootIds` should only include the IDs from `$this->root` which are root themselves (`pid=0`). Otherwise the tree will start rendering subpages from the top, no?

**Review by Toflar — APPROVED** [review]
Ah, it should work because `pid=0` is part of the query. It's fine then :)

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
