### PR TITLE
Support hyphens in custom template names

### LINKED ISSUE #725: Templates mit "-" im Dateinamen nicht mehr erkannt/auswählbar
Betrifft Contao ab 4.8.1

Laut Spooky werden nur noch Templatenamen mit "_" erkannt, TEmplates mit "-" werden im Backend in der Liste nicht mehr angezeigt und sind damit nach einem Update und der Bearbeitung eines Elements oder Artikels auf das Default Template zurückgeworfen.

Da einige meiner Projekte ein "-" im Templatenamen haben und auch einige Kauftemplates diese Namensvergabe haben ist das ein ziemliches Problem, was nur mit einigem Arbeitsaufwand wieder gerade zu kriegen ist (Projekt mit mehr als 5.000 Elementen)

Welchen Grund hat der Wegfall der Unterstützung des Bindestrichs?

Siehe auch https://community.contao.org/de/showthread.php?75906-Templates-nach-Update-nicht-mehr-ausw%C3%A4hlbar

### PR DESCRIPTION
**Pull request by leofeyer**
This PR fixes #725, however, since the underlying problem is caused by a wrong template naming scheme, I am not sure whether we should merge this.

@contao/developers WDYT?

### CODE REVIEW

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
Maybe we should allow *any* character after the base template name, not just hyphen and underscore.

**Comment by ausi** [comment]
> Maybe we should allow _any_ character after the base template name, not just hyphen and underscore.

You mean something like this?

```php
$strGlobPrefix = substr($strGlobPrefix, 0, -1) . '[!A-Za-z0-9]';
```

**Comment by leofeyer** [comment]
No, I think @aschempp really means **any** character for reasons of backwards compatibility.

* `mod_article.html5`
* `mod_article_custom.html5`
* `mod_article-custom.html5`
* `mod_articlecustom.html5`
* `mod_article.custom.html5`

Contao <4.8 will show all variations above in the drop-down menu I believe (did not yet test).

**Comment by fritzmg** [comment]
And `mod_article_list` as well, which we wanted to avoid?

**Comment by leofeyer** [comment]
Exactly. Therefore I think that `[_-]` is enough (until further notice).

**Comment by aschempp** [comment]
> And `mod_article_list` as well, which we wanted to avoid?

that's not true. I would (have) include(d) anything after the template name. We can still skip anything that matches existing templates (and their derivates).

**Pull request merged**
