### PR TITLE
Always make our fragments public

### PR DESCRIPTION
**Pull request by aschempp**
Controllers must be public for the router to call the action

### CODE REVIEW

**Review by richardhj — APPROVED** [review]

**Comment by leofeyer** [comment]
If this is a bugfix, it needs to be created against the `4.6` branch please.

**Comment by aschempp** [comment]
> If this is a bugfix, it needs to be created against the 4.6 branch please.

Fixed

**Review by leofeyer — CHANGES_REQUESTED** [review]
Can you also update the test class please?

**Review by leofeyer — APPROVED** [review]

**Comment by aschempp** [comment]
> Can you also update the test class please?

Done 😎

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
