### PR TITLE
Tolerate missing files when listing filesystem items in controllers

### LINKED ISSUE #5956: Empty Downloads content element results in error 500
### Affected version(s)

5.1.2

### Description

Add a new CE from type "Downloads". Do not choose any files and save ...

`Contao\CoreBundle\Filesystem\FilesystemUtil::listContentsFromSerialized(): Argument #2 ($sources) must be of type array|string, null given, called in /var/www/sgv/htdocs/vendor/contao/core-bundle/src/Controller/ContentElement/DownloadsController.php on line 120`

### PR DESCRIPTION
**Pull request by m-vo**
Fixes #5956

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Comment by ausi** [comment]
How does this fix the `Contao\CoreBundle\Filesystem\FilesystemUtil::listContentsFromSerialized(): Argument #2 ($sources) must be of type array|string, null given` error?

Wouldn’t we have to change the type hint to something like `array|string|null $sources`?

Are we sure we want to bypass the DBAFS by default here?

**Comment by leofeyer** [comment]
> Are we sure we want to bypass the DBAFS by default here?

I‘m not.

**Comment by m-vo** [comment]
> How does this fix the `Contao\CoreBundle\Filesystem\FilesystemUtil::listContentsFromSerialized(): Argument #2 ($sources) must be of type array|string, null given` error?

Hmm, weird. I don't remember anymore. Seems like I was chasing another error `Could not read resource from storage: Unable to read from "files/foo/bar.jpg".` when a file was deleted. I'll have to look into this issue again.

(The idea to skip the DBAFS was, that you'll then get a definitive list of files, even if some were removed in the meantime. But maybe this is the wrong concept and we should rather make the consumer handle this.)

**Comment by leofeyer** [comment]
As discussed in the Contao call, the fix is most likely not correct. @m-vo will look into it again.

**Review by Toflar — CHANGES_REQUESTED** [review]
Removing approval as dicussed during Contao call on July 27th.

**Pull request closed without merging**
