### PR TITLE
Use the Contao short URL service for keyboard shortcuts

### PR DESCRIPTION
**Pull request by leofeyer**
Follow-up on #4124.

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]

**Comment by leofeyer** [comment]
I have reviewed the other links as well and I found quite a few other things that needed to be fixed, too. 🙈

**Review by Toflar — APPROVED** [review]
❤️

**Review by bytehead — APPROVED** [review]

**Comment by aschempp** [comment]
why did you revert moving the link out of the language file?

**Comment by leofeyer** [comment]
Because it only worked for this one link. The others cannot be removed, therefore we might as well leave them all in the language files. Transifex handles links very nicely, so it should not matter:

**Pull request merged**
