### PR TITLE
Add more image quality settings

### PR DESCRIPTION
**Pull request by ausi**
As discussed in contao/core-bundle#1488

### CODE REVIEW

**Comment by ausi** [comment]
https://github.com/contao/image/commit/e9829efb171eed31ab3868390588a7319fb8cf32 has to be released first before this can be merged.

**Comment by ausi** [comment]
Can be merged after #354

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by Metis77** [comment]
Thank you.

**Pull request merged**
