### PR TITLE
Add tests for the image studio macros

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     |  -
| Docs PR or issue | -

This PR introduces (long overdue) tests for the image studio macros.

It also fixes two small things: A typo in one of the macro descriptions (b978e03f36f8ee4da95c7e3bfa1121aa937df239) and not rendering the `title` attribute if it is empty (25002f6a129bc7c353fc2d309f82a5d7458a70c2).

/cc @ausi

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

**Comment by leofeyer** [comment]
@m-vo The failing prefer-lowest tests are related to the PR. Can you please check?

**Comment by m-vo** [comment]
Will do.

**Comment by m-vo** [comment]
Tests are green now with aef662e845520ffa2d78d611eff0e041e135c47e.

Our Twig dependency was too low: the `_self` import for macros was only working since 2.11 (ultimately fixed in 2.11.3).

(edit: just removed the `v` from the version constraint in https://github.com/contao/contao/commit/0545256c65435b111635560e557752452d2369ea)

**Review by ausi — DISMISSED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
