### PR TITLE
Remap commonly used removed icons

### LINKED ISSUE #5902: Missing backend icons
### Affected version(s)

5.1

### Description

In 406ed123d5cc5c7b9424b4f7534fdafb8cd1401d a lot of icons got deleted (like header.svg, settings.svg,…).

Was this on purpose?

Many extensions may rely on these icons (especially header.svg for extensions that are compatible with 4 and 5) so this might be an unexpected break from Contao 5.0 to 5.1, at least it was for my extensions ☺️

### PR DESCRIPTION
**Pull request by ausi**
Fixes #5902 but I’m not sure if it wouldn’t be better to bring these two icons (and maybe more) back.

### CODE REVIEW

**Comment by aschempp** [comment]
Have the icons been removed or moved to the icons folder?

**Comment by ausi** [comment]
> Have the icons been removed or moved to the icons folder?

Removed, see #5902

**Comment by fritzmg** [comment]
I think we should add all of them again and only remove them in Contao 6. Not having these kinds of things in the BC promise is rather inconvenient for extension developers and there is no real benefit of removing them anyway.

**Comment by leofeyer** [comment]
I would prefer to map the icons as @ausi does in this PR, because the old icons would not have a dark variant if we restored them.

**Comment by leofeyer** [comment]
As discussed in the call, we want to restore the `header.svg` and `settings.svg` files and add a dark-mode variant for them. We also want to check if we should restore the `published.svg` icon.

**Pull request closed without merging**
