### PR TITLE
Improve how headlines can be adjusted in Twig

### LINKED ISSUE #6550: Twig: simplify extending headlines for all elements
### Affected version(s)

5.X

### Description

As discussed in slack, it's quite difficult to extend headlines for all content elements and the headline element at the moment.

@m-vo suggested using the following (somehow ugly) solution

```
{% use "@Contao/component/_headline.html.twig" %}

{% block headline_attributes %}
    {% set headline = headline|merge({attributes: attrs(headline.attributes|default).addClass('foobar')}) %}
    {{ parent() }}
{% endblock %}
```

and this works for elements that extend component/_headline.html.twig, but not for the headline element itself. 
Updating `content_element/_hedline.html.twig` (and maybe refactoring component/_headline) should fix this problem.

### PR DESCRIPTION
**Pull request by m-vo**
This is an alternative approach to #6732 with the purpose to fix #6550.

With this PR the following things are possible:

* Adjusting any block of the `_headline` component will both affect headlines (e.g. inside content elements) as well as the headline content element itself.
* The content element wrapper attributes (from `content_element/_base`) are applied to the headline component - so any changes here, like a custom data attribute on content element level, are also usable for the headline content element even though there is no additional wrapper.

#### Adding a wrapper around the headline content element
```twig
{# content_element/headline.html.twig #}
{% extends "@Contao/content_element/headline.html.twig" %}

{% block wrapper %}
    <div style="border: 1px solid red">{{ parent() }}</div>
{% endblock %}
```

#### Adding a wrapper around _all_ headlines
```twig
{# component/_headline.html.twig #}
{% use "@Contao/component/_headline.html.twig" %}

{% block headline_inner %}
    <div style="border: 1px solid blue">{{ parent() }}</div>
{% endblock %}
```

#### Adding a data attribute to _all_ content elements (including headlines)
```twig
{# content_element/_base.html.twig #}
{% extends "@Contao/content_element/_base.html.twig" %}

{% set attributes = attrs(attributes|default).set('data-foo', 'bar') %}
```

#### Targeting "real" wrappers
In order for the wrapper attributes to be reusable, I moved them up the scope in the base template. As a side-effect this allows to disgustingly manipulate them on all elements or just those with real wrappers:

```twig
{# content_element/_base.html.twig #}
{% extends "@Contao/content_element/_base.html.twig" %}

{% set attributes = attrs(attributes|default).set('data-scope', 'all-elements') %}

{% block wrapper %}
    {% set attributes = attrs(attributes|default).set('data-scope', 'real-wrappers') %}
    {{ parent() }}
{% endblock %}
```

/cc @falkgeist, @denniserdmann

### CODE REVIEW

**Comment by leofeyer** [comment]
I lean towards considering this a bugfix that we should merge into the `5.3` branch.

**Review by ausi — DISMISSED** [review]

**Comment by leofeyer** [comment]
@m-vo Can you rebase this onto the `5.3` branch please?

**Comment by m-vo** [comment]
Sure, will do!

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
