### PR TITLE
Merge the "overwrite metadata" with the default metadata

### LINKED ISSUE #5889: Images: Only overwrite the metadata from the file manager (and not license or additional meta fields)
### Affected version(s)

Contao 4.13.18

### Description

The `License URL` for images in the file manager is not outputed in the frontend if the `Overwrite metadata` checkbox is selected for content element type `image`. If I remove the checkbox and do not overwrite the metadata from the file management, then the license data will be outputed in the frontend.

Also when I add a new input meta field (i.e. `License Text`) in the file manager, then the meta data will not be shown in the frontend, too.

Example:

grafik

I added the additional meta field `License Text` to the file manager of Contao as described (https://docs.contao.org/dev/reference/dca/fields/#meta-wizard-fields):

```
// contao/dca/tl_files.php
$GLOBALS['TL_DCA']['tl_files']['fields']['meta']['eval']['metaFields']['license_text'] = array('type'=>'textarea', 'allowHtml'=>true);
```

grafik

grafik

When I deactivate the checkbox "Overwrite metadata" than all meta fields of the image will be shown in the frontend:

grafik

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #5889

### CODE REVIEW

**Comment by m-vo** [comment]
API-wise (for the `FigureBuilder`) I would prefer something like `addMetadata` over `setOverwriteMetadata` I think.

~~Isn't this change breaking BC, though?~~
The `ModelMetadataTrait` still returns the empty values of the current row, so how does this solve the issue?

**Comment by leofeyer** [comment]
> API-wise (for the `FigureBuilder`) I would prefer something like `addMetadata` over `setOverwriteMetadata` I think.

But we are not adding metadata, we are overwriting existing metadata with potentially empty values. Therefore, the method name makes sense to me.
 
> The `ModelMetadataTrait` still returns the empty values of the current row, so how does this solve the issue?

See the original issue #5889. We must not unset custom metadata fields. The logic for the default metadata fields is fine.

**Comment by m-vo** [comment]
The comments in the `FigureBuilder` for the new property/method now say

> User defined metadata. This will be added to the default if set.

and 

>  The metadata will be merged with the default metadata from the FilesModel.

which does not sound at all like "overwriting". To me this is a very confusing API. If you set something here, the metadata will be *merged* with the existing one. It allows overwriting, but it does not replace the existing entries. That's why `addMetadata` would have been a better name IMHO. Then its also obvious, that the original method `setMetadata` - in contrary - completely sets/replaces any potentially existing metadata.

Also, I still don't understand how it solves the original issue (suppress vs keep) and why this was merged without a review? There is no explanation in #5889 - maybe you discussed something in the last call and forget to add a comment with the conclusion?

**Comment by fritzmg** [comment]
Currently, we can only overwrite _all_ metadata in a content element - and not just specific fields (see #599). That being said, the expected solution for #5889 likely was a combination of the current caveat while retaining all metadata that you cannot currently overwrite in a content element. Which is what this PR implemented. Hence also the naming of the `setOverwriteMetadata` method - as it represents the fixed logic when enabling `tl_content.overwriteMetadata`.

**Comment by oexler** [comment]
The changes have broken some of our code.
We use the old `Contao\Controller::addImageToTemplate()` method with a singleSRC and no FilesModel.
Now `FigureBuilder->onDefineMetadata()` returns null, so the `FileMetadataEvent` has no metadata set.

So in our `FileMetadataEvent` we have no information about the file.
A workaround from our side is to use overwriteMeta and a FilesModel for `addImageToTemplate`, but we don't know if Contao should behave this way.

**Comment by leofeyer** [comment]
Please open a new ticket and let us know how to reproduce your issue.

**Pull request merged**
