### PR TITLE
Do not try to register Contao 3 classes as services

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by Toflar** [comment]
Can you please add a description? I don't understand.

**Comment by fritzmg** [comment]
@Toflar the `services.php` (or even your own resource loading definition in your `services.yml`) will register all classes as services in the defined namespace. However, in Contao you still might have things like Models, or old legacy classes that extend from `\Contao\System` somewhere down the line and are not supposed to be registered as services. Usually you would define these subnamespaces to be excluded in your `services.yml`. I think @aschempp wants to automatically exclude any class that inherits from `\Contao\System` to be registered as a service - if they cause an error.

Somewhat related to https://github.com/symfony/symfony/issues/34053

**Comment by Toflar** [comment]
Can't we exclude anything coming from `Resources/contao`?

**Comment by fritzmg** [comment]
Those classes would not be within `Resources`, but rather in their own namespace. e.g. `App\ContentElement\MyContentElement`.

**Review by fritzmg — DISMISSED** [review]

**Review by bytehead — DISMISSED** [review]

**Review by leofeyer — CHANGES_REQUESTED** [review]
Unfortunately, this does not solve the issue. The `$definition->hasErrors()` is never `true` in my case. 🤷‍♂

**Comment by fritzmg** [comment]
@leofeyer which error happens?

**Comment by leofeyer** [comment]
```
In DefinitionErrorExceptionPass.php line 54:

Cannot autowire service "App\Content\ContentDownloader":
    argument "$objElement" of method "Contao\ContentElement::__construct()"
    has no type-hint, you should configure its value explicitly.
```

**Comment by aschempp** [comment]
I have updated the PR. We're now automatically removing any class extending from the legacy framework from autoloading, I would argue that these can/should never be services (if you need them, you can still add them manually).

I'm also removing any class that has a legacy class in the constructor, as these can/should never be services that can be injected.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
The latest changes fix the problem for me. 👍

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
