### PR TITLE
Add option to contao:setup command to disable cache cleaning/warmup

### PR DESCRIPTION
**Pull request by Wusch**
In our deployment we want to skip the cache cleaning after a composer install and do it later.

### CODE REVIEW

**Comment by m-vo** [comment]
If you need something different, I would suggest to call the individual commands the `ContaoSetupCommand` is calling yourself. It's only a helper, anyways.

**Comment by leofeyer** [comment]
The command does more than just call a series of individual commands, so the pull request seems reasonable to me.

**Comment by aschempp** [comment]
so are we adding a `--no-symlinks` option etc. as well? The only thing it does in addition to the commands is auto-generate a secret?

**Comment by m-vo** [comment]
I would rather add a command to auto-generate a secret, then. And keep this command as a thin helper that calls the others. 🤔

**Comment by leofeyer** [comment]
> If you need something different, I would suggest to call the individual commands the `ContaoSetupCommand` is calling yourself. It's only a helper, anyways.

> so are we adding a `--no-symlinks` option etc. as well? The only thing it does in addition to the commands is auto-generate a secret?

I agree with you both. @Wusch Can you implement what you need with your own helper?

**Comment by aschempp** [comment]
So this PR can be closed, right?

**Pull request closed without merging**
