### PR TITLE
Add a PHPUnit extension to test for deprecated classes

### PR DESCRIPTION
**Pull request by ausi**
This is an alternative to #2517

It adds a before-all-tests and an after-all-tests hook to phpunit and tests the deprecated classes before and throws an error after the tests. This has several benefits:

- Test execution order (or using `--filter`) is no longer a problem as all deprecated classes get loaded (and verified) before the first test is executed
- Fixes deprecations for functional tests too, where other methods (like #2517) have problems.
- Single point in the codebase where we can check if we need to actually react to a deprecation when migrating to a new Symfony version for example.

For clarification: This is for file scoped deprecations (= `trigger_error` outside the class definition) that get triggerd only once when the class file gets autoloaded.

### CODE REVIEW

**Review by m-vo — DISMISSED** [review]

**Comment by ausi** [comment]
@leofeyer should I create this PR for Contao 4.11 too before we merge this one to verify that the concept works there too?

**Comment by leofeyer** [comment]
I don't think that is necessary.

**Comment by ausi** [comment]
Depends on contao/test-case#11 being merged and released as 4.3.0

**Review by m-vo — APPROVED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
