### PR TITLE
Add an image size voter

### PR DESCRIPTION
**Pull request by aschempp**
@contao/developers what I find confusing is that a user can have access to only a limited number of image sizes, but they can still see all images sizes. They can also edit all images sizes. But only if they add a new image size, it is added to their user permission to make it accessible in the widget dropdown. Is that something we intentionally do?

### CODE REVIEW

**Comment by leofeyer** [comment]
> Is that something we intentionally do?

Probably not. 🙈 But @ausi might know.

**Comment by ausi** [comment]
AFAIK we only have permissions per image size for being accessible in the widget dropdown. If a user has access to the image sizes admin view is not related to that. For the admin view we do not have specific permissions per image size. I think this is correct and the image-sizes-widget-dropdown-permission should not get mixed with the general CRUD-permissions for tl_image_sizes.

> > Is that something we intentionally do?
> 
> Probably not. 🙈 But @ausi might know.

This feature is from @qzminski and @aschempp see https://github.com/contao/core-bundle/pull/319 so they should know the intention best ☺️

**Comment by aschempp** [comment]
yeah, I was just confused by the fact that a user might not have access to an image size in the widget, but can edit it. So a user can not see an option in the list, but can duplicated said option and then have access to the new one. Not sure that's really intended?

For example with forms, the user permission to limit the forms affects both the list in the back end as well as the widget in the form element dropdown.

**Comment by leofeyer** [comment]
> So a user can not see an option in the list, but can duplicated said option and then have access to the new one. Not sure that's really intended?

It is not. We should fix this IMHO.

**Comment by aschempp** [comment]
> It is not. We should fix this IMHO.

I thought so, too. However, there is currently no permission to add or delete an image size, like there ususally is for e.g. news archives. Which means if a user is given access to the image size theme module, they should be able to do anything to that (CRUD). Which ultimately means they should have all image sizes… 🤔

**Comment by aschempp** [comment]
I have created a new issue (https://github.com/contao/contao/issues/6693) for the open question. This PR should be RTM and implements the current behaviour.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
