### PR TITLE
Check the cookie headers in the `isSessionEmpty()` method

### LINKED ISSUE #7167: Invalid request token error when sending invalid form again
### Affected version(s)

4.13, ~5.3~

### Description

Unfortunately there is still another regression with the changes from #6801, #6959 and #7052. There can be situations where you encounter an "invalid request token" error during regular use. See the following reproduction:

1. Create a form.
2. Activate **Disable HTML5 validation**.
3. Add a mandatory text form field.
4. ~Add the security question form field.~
5. Add a submit button.
6. Add the form to a page.
7. Open the page in the front end **without any pre-existing cookies**.
8. Submit the form without any input in the text field - you will see the form again with the error message next to the mandatory field.
9. ~Immediately~ submit the form again ~(within 5 seconds I think)~.
10. You will see the invalid request token error message.

```
Contao\CoreBundle\Exception\InvalidRequestTokenException:
Invalid CSRF token. Please reload the page and try again.

  at vendor/contao/contao/core-bundle/src/EventListener/RequestTokenListener.php:102
```

I notice the following behaviour:

1. The initial GET request to the page with the form does not respond with any cookies, which is expected.
2. The `POST` request that will show the form again (as the form does not validate) responds with a `PHPSESSID` cookie, which is expected as the form's values are stored in the session for a short period. However, there is _no_ CSRF token cookie in the response, which I think is unexpected. Whenever there is a session cookie there should always be a CSRF token cookie.
3. Contao' security form field will make an AJAX request to `_contao/captcha/…`. There will be a CSRF token cookie in the response - but there might also be a `PHPSESSID=delete` instruction in the response.
4. There will be a second AJAX request to `_contao/captcha/…` which then also deletes the CSRF token cookie.

I think overall the core issue is that the CSRF token cookie is missing in the response of the POST request.

### PR DESCRIPTION
**Pull request by ausi**
Attempt to fix #7167

### CODE REVIEW

**Comment by fritzmg** [comment]
What about `ContaoCsrfTokenManager::isSessionEmpty()` - do we need to incorporate it there too?

**Review by fritzmg — APPROVED** [review]
Otherwise verified that this fixes https://github.com/contao/contao/issues/7167

**Comment by ausi** [comment]
> What about `ContaoCsrfTokenManager::isSessionEmpty()` - do we need to incorporate it there too?

I don’t think so, as there only the request is in question (and not the response).

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
