### PR TITLE
Keep unknown insert tags as plain strings

### PR DESCRIPTION
**Pull request by ausi**
See #4409

### CODE REVIEW

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by Toflar** [comment]
Imho that should also be documented in the `UPGRADE.md`. It's kind of important.

**Comment by leofeyer** [comment]
Not sure. The `UPGRADE.md` is meant to document breaking changes IMHO and the PR does not break anything.

**Comment by m-vo** [comment]
Yeah, but people are using `Controller::replaceInsertTags('…')` as an argument for functions and this might now break. Not saying that you should do this at all. :smile:

**Pull request merged**
