### PR TITLE
Correctly update the file name when synchronizing the DBAFS

### LINKED ISSUE #6862: File names in DB are not updated correctly when they are renamed on the server
### Affected version(s)

5.2.8

### Description

I have a strange behaviour when renaming files directly on the server.

1. I copy a file via FTP to the server into a subfolder of "/files" - e.g. image.jpg
2. I perform a synchronisation in the backend under "Files"
3. Now I change the file name via FTP (e.g. to image1.jpg) and synchronise the files again - the change is recognised
4. The new file name (image1.jpg) is displayed in the backend, but the old file name (image.jpg) is still displayed in the "name" column in the DB

And it's also not possible to search for the new file name in the backend.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #6862

### CODE REVIEW

**Comment by fritzmg** [comment]
> However, I had to omit $dataToUpdate['extension'] because there is no $itemToUpdate->isFile() method. Such a method only exists in the ItemToCreate class but not in the ItemToUpdate class, most likely because we do not support changing the file type from file to folder or from .jpg to .png.

Our sync supports that though: 

> Found the file or folder "files/slide0.jpg" at "files/foo/foo0.jpg.txt"

**Comment by LIVID-Media** [comment]
Thanks, now it's working.

**Comment by leofeyer** [comment]
> Our sync supports that though:
> 
> > Found the file or folder "files/slide0.jpg" at "files/foo/foo0.jpg.txt"

See #6877 for an alternative approach that also checks the file type.

**Review by ausi — DISMISSED** [review]

**Comment by m-vo** [comment]
See https://github.com/leofeyer/contao/pull/11 for the failing tests.

**Review by ausi — APPROVED** [review]

**Pull request merged**
