### PR TITLE
Re-use the tl_member.password field in ModuleCloseAccount

### LINKED ISSUE #2492: ModuleCloseAccount does not use password field from tl_member
**Affected version(s)**

Contao >= 4.9

**Description**

`ModuleCloseAccount` should be consistent with all the other member related modules.

Each member related module (`ModulePersonalData`, `ModulePassword`, `ModuleChangePassword`,...) uses the fields located in the `tl_member` DCA - `ModuleCloseAccount` does not. There is currently no way to modify the password field in any way without simply copying the `ModuleCloseAccount` class.

In my case I needed to add a placeholder attribute to all fields from `tl_member` which are `feEditable`. This works in all modules other than `ModuleCloseAccount`.

I'd like to propose the following change:

```php
    /**
     * Generate the module
     */
    protected function compile()
    {
        $this->import(FrontendUser::class, 'User');

        System::loadLanguageFile('tl_member');
        $this->loadDataContainer('tl_member');

        // Initialize the password widget
        $arrField = $GLOBALS['TL_DCA']['tl_member']['fields']['password'];
```

### PR DESCRIPTION
**Pull request by bennyborn**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2492 

This PR re-uses the password field from tl_member DCA like instead of creating a new one. This way it's possible to modify the properties of the field like it's already the case with all other member related modules.

### CODE REVIEW

**Comment by leofeyer** [comment]
The password field in the module uses different settings than the one in `tl_member`, therefore we are not re-using it currently. What exactly do you need to modify?

**Comment by bennyborn** [comment]
> What exactly do you need to modify?

As I wrote in the original issue I needed to add a placeholder. 

But it doesn't matter what my exact use-case was rather than not being able to modify the field at all. Maybe someone wanted to give it a different label or overwrite the inputType to a custom widget. None of that is possible if the field is simply defined inline.

Furthermore I see no real reason not to re-use the field. 
The settings are almost the same except for some minor eval attributes (`minlength`, `feEditable`, `feGroup`, `tl_class`) which should cause no problems.

**Comment by bennyborn** [comment]
@leofeyer I've just re-added the `hideInput` option in the eval and fixed the missing field name. This way it works like the original field with the added benefit to be able to modify it via the `tl_member` DCA.

**Review by aschempp — CHANGES_REQUESTED** [review]
the field in `tl_member` also has a different input type, so this won't work either…

**Comment by bennyborn** [comment]
> the field in `tl_member` also has a different input type, so this won't work either…

I noticed that too but actually there seems to be no need to change the type. It works absolutely fine.

**Review by fritzmg — APPROVED** [review]

**Comment by aschempp** [comment]
I can hardly believe that, because the password field type generates two inputs (to confirm the password) 🤔

**Comment by bennyborn** [comment]
Because @leofeyer just assigned me.... Where are we going from here? It seems to work from my side, @fritzmg also approved it. If @aschempp has any doubts be my guest testing the changes.

**Comment by leofeyer** [comment]
Current configuration:

```php
		$arrField = array
 		(
 			'name' => 'password',
 			'inputType' => 'text',
 			'label' => $GLOBALS['TL_LANG']['MSC']['password'][0],
 			'eval' => array('hideInput'=>true, 'preserveTags'=>true, 'mandatory'=>true, 'required'=>true)
 		);
```

New configuration:

```php
		'password' => array
		(
			'label'                   => &$GLOBALS['TL_LANG']['MSC']['password'],
			'exclude'                 => true,
			'inputType'               => 'password',
			'eval'                    => array('mandatory'=>true, 'preserveTags'=>true, 'minlength'=>Contao\Config::get('minPasswordLength'), 'feEditable'=>true, 'feGroup'=>'login', 'tl_class'=>'clr', 'hideInput'=>true),
			'save_callback' => array
			(
				array('tl_member', 'setNewPassword')
			),
			'sql'                     => "varchar(255) NOT NULL default ''"
		),
```

This is quite different IMHO, starting with the field type currently being `text` (one input field) and afterwards being `password` (two input fields). I doubt that we can re-use the field.

**Comment by aschempp** [comment]
I just tested this as suggested by @bennyborn and he's actually right, the input field "works". That's however because the field type is hardcoded in https://github.com/contao/contao/blob/4.x/core-bundle/src/Resources/contao/modules/ModuleCloseAccount.php#L75, so it would not be possible to override the widget (as mentioned in https://github.com/contao/contao/pull/2497#issuecomment-730320919).

**Comment by bennyborn** [comment]
> [...] so it would not be possible to override the widget [...].

If we changed the type to `FormPassword` we'd have the problem of the unwanted confirmation field. Leaving it as `FormTextField` we IMHO have the best possibilities for customization.

**Comment by leofeyer** [comment]
Thank you @bennyborn.

**Pull request merged**
