### PR TITLE
Support 32-bit PHP versions in event listing

### PR DESCRIPTION
**Pull request by m-vo**
see #811

### CODE REVIEW

**Comment by aschempp** [comment]
warum verwenden wir nicht direkt `PHP_INT_MAX`?

**Comment by leofeyer** [comment]
Weil das auf 64bit-Systemen viel zu groß ist und zu einem Memory-Problem bei unendlichen wiederholten Events führen würde. (Wir hatten es zuerst mit `PHP_INT_MAX` versucht.)

**Comment by leofeyer** [comment]
Es gibt noch einige andere Stellen, an denen wir `4294967295` verwenden. @m-vo Müssen wir die nicht auch anpassen?

**Comment by m-vo** [comment]
Stimmt, du hast natürlich recht.

I was about to apply the changes everywhere, but honestly I think we should just set the value to `2147483647`. That's `PHP_INT_MAX` on 32bit systems. This translates to `2038-01-19 05:14:07` (vs. `2106-02-07 07:28:15`). 

This way databases created under 64bit systems are interchangeable with 32bit ones. Alternatively we could change the values to floats everywhere, but than we would probably also need to change method signatures (BC...) and introduce another class of problems (precision).

**Comment by leofeyer** [comment]
The whole point of https://github.com/contao/contao/issues/510 was not to use `2147483647` anymore, so going back there is not an option.

**Comment by m-vo** [comment]
Right. I'll see if there is another approach. 
(Like maybe a special value that means 'max' in the database and a platform dependent interpretation when listing.)

**Comment by m-vo** [comment]
@leofeyer Can we safely change the annotated types in the legacy code (see example below) without breaking BC? Integers passed in by 3rd party code would coerce to floats - we wouldn't be able to add type hints in the method signature, though.

```php
/*
* @param integer $value
*/
function someFunction($value) 
{
    // ...
}
```
&rarr;
```php
/*
* @param float $value
*/
function someFunction($value) 
{
    // ...
}
```

This way we would not need to differentiate between platforms.

**Comment by m-vo** [comment]
This is a tricky one. 

For a simple fix it would be enough to allow the model's repository functions to work with floats as well. In fact there is only one location where this fails, namely here (due to the explicit cast):

https://github.com/contao/contao/blob/7a886bcaf3522e3c1f50f4131d5ec637c9782a0f/calendar-bundle/src/Resources/contao/models/CalendarEventsModel.php#L243-L244

For now I changed the models method signatures to also allow floats. With this, however, we silently ignore that 32 bit PHP will apply type juggling in the code before calling these functions (`$intStart` in `getAllEvents()` will then be a float for example). 

I don't see how this could be easily changed though. There is even a hook where the values are passed around. If implementers type hint against an integer there, the code will break. :man_shrugging:

**Comment by leofeyer** [comment]
See #918.

**Pull request closed without merging**
