### PR TITLE
Fix type error when trying to copy website root

### PR DESCRIPTION
**Pull request by fritzmg**
Currently you cannot copy a website root in Contao `4.12.3` and `4.12.x-dev` due to the following error:

```
TypeError:

Return value of Contao\CoreBundle\Util\LocaleUtil::formatAsLocale() must be of the type string, null returned
```

This error can also happen if an extension, like `terminal42/contao-changelanguage`, executes `PageModel::findWithDetails(…)` with the ID of the newly created record - since the record will have no language set yet at that point.

This PR will fix both instances.

### CODE REVIEW

**Comment by fritzmg** [comment]
@ausi or should `LocaleUtil::formatAsLocale` be able to handle empty (or unknown) language tags instead?

e.g.

```php
return array_pop($locales) ?? $languageTag;
```

or

```php
return array_pop($locales) ?? '';
```

**Comment by ausi** [comment]
I’m +1 for `array_pop($locales) ?? ''` but the `LocaleUtil` was created by @aschempp I think.

**Comment by fritzmg** [comment]
Right, sorry 🙈 I have changed the fix to `LocaleUtil` now, as I would prefer that as well, for ease of use within Contao.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
