### PR TITLE
Fix bug with hash comparison in migrate command

### LINKED ISSUE #4507: Migrations are executed twice with hash
### Affected version(s)

4.9.x-dev

### Description

I have added a test migration to my setup that always returns `true` for `shouldRun`.

Running the following command:
```
php74 vendor/bin/contao-console contao:migrate --format=ndjson --no-interaction --hash=e9f96ef856986faa41e14d5af622a6e341dcb6a8f2757a01f79435828f8a38f5
```

gives this result:
```
{"type":"migration-pending","names":["App\\Migration\\TestMigration"],"hash":"e9f96ef856986faa41e14d5af622a6e341dcb6a8f2757a01f79435828f8a38f5"}
{"type":"migration-result","message":"App\\Migration\\TestMigration executed successfully","isSuccessful":true}
{"type":"schema-pending","commands":[],"hash":"4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"}
{"type":"migration-pending","names":["App\\Migration\\TestMigration"],"hash":"e9f96ef856986faa41e14d5af622a6e341dcb6a8f2757a01f79435828f8a38f5"}
{"type":"migration-result","message":"App\\Migration\\TestMigration executed successfully","isSuccessful":true}
```

the migration seems to be executed twice. Possibly because of the same hash, but it still shouldn't. And it apparently stops after one time.

PS: not sure if the same issue exists if a schema migration cannot be executed and the hash stays the same?

### PR DESCRIPTION
**Pull request by ausi**
Fixes #4507

### CODE REVIEW

**Comment by aschempp** [comment]
Why do I need `--migration-only` or `--schema-only` now to use `--hash`?

**Comment by ausi** [comment]
> Why do I need `--migration-only` or `--schema-only` now to use `--hash`?

Because you can only pass one hash value via the `--hash` option, but the migrations as well as the schema-updates have their own hash each.

**Comment by aschempp** [comment]
Yeah, but currently I run without argument and use schema if there are no migrations 😔

**Comment by ausi** [comment]
> Yeah, but currently I run without argument and use schema if there are no migrations

That should be no problem:

1. `contao:migrate --format=ndjson --dry-run` prints pending migrations **and** schemas
2. `contao:migrate --format=ndjson --no-interaction --migrations-only --hash=MIGRATIONS_HASH`
3. `contao:migrate --format=ndjson --no-interaction --schema-only --hash=SCHEMA_HASH`

**Comment by ausi** [comment]
Changed that now. 

The current procedure now looks like this:

```
$ contao:migrate --format=ndjson --dry-run
{"type":"migration-pending","names":["Contao\\CoreBundle\\Migration\\Version409\\CeAccessMigration"],"hash":"b6cd502f63cd820325e637d577a30a242905bc9debb5efb34ee63d526b332da6"}
{"type":"schema-pending","commands":["ALTER TABLE tl_article DROP foobarbaz"],"hash":"c179ba1f35fa53b3ae039d5f1c4f7ea70bfe76179d02453e75c9ed4677898536"}

$ contao:migrate --format=ndjson --no-interaction --hash=b6cd502f63cd820325e637d577a30a242905bc9debb5efb34ee63d526b332da6
{"type":"migration-pending","names":["Contao\\CoreBundle\\Migration\\Version409\\CeAccessMigration"],"hash":"b6cd502f63cd820325e637d577a30a242905bc9debb5efb34ee63d526b332da6"}
{"type":"migration-result","message":"Contao\\CoreBundle\\Migration\\Version409\\CeAccessMigration executed successfully","isSuccessful":true}
{"type":"schema-pending","commands":["ALTER TABLE tl_article DROP foobarbaz"],"hash":"c179ba1f35fa53b3ae039d5f1c4f7ea70bfe76179d02453e75c9ed4677898536"}

$ contao:migrate --format=ndjson --no-interaction --hash=c179ba1f35fa53b3ae039d5f1c4f7ea70bfe76179d02453e75c9ed4677898536
{"type":"migration-pending","names":[],"hash":"4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945"}
{"type":"schema-pending","commands":["ALTER TABLE tl_article DROP foobarbaz"],"hash":"c179ba1f35fa53b3ae039d5f1c4f7ea70bfe76179d02453e75c9ed4677898536"}
{"type":"schema-execute","command":"ALTER TABLE tl_article DROP foobarbaz"}
{"type":"schema-result","command":"ALTER TABLE tl_article DROP foobarbaz","isSuccessful":true}
```

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
