### PR TITLE
Add `@return never` to methods that never return

### PR DESCRIPTION
**Pull request by aschempp**
Same as https://github.com/contao/contao/pull/7327 but for Contao 4.13

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
The `never` return type is only available since PHP 8.1. Contao 4.13 is still compatible with PHP 7.4.

// edit: I am guessing you meant to use `@return never` for `tl_templates::compareTemplate()` as well.

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Did you notice this in your own app? Because we don't check the legacy classes with PHPStan.

**Comment by aschempp** [comment]
Yes I did (because I used `File::sendToBrowser()`)

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
