### PR TITLE
Fix the contao.image.sizes keys

### LINKED ISSUE #1081: Unify the configuration style
**Affected version(s)**

4.9

**Description**  

I just noticed that most of the bundle configuration uses snake case but a few recently introduced configuration keys use camel case.
We should definitely review those before the release.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #1081

### CODE REVIEW

**Comment by Toflar** [comment]
Nice! Do you think we should have a general test that takes all possible configuration keys and checks them for `[a-z_]` so that this inconsistency doesn't happen again?

**Comment by leofeyer** [comment]
I do. Want me to add the test here or in a separate PR?

**Review by Toflar — DISMISSED** [review]
Up to you, but I approve this one because it's correct as is imho.

**Comment by leofeyer** [comment]
Test added in 2d59f051c5150ce17a6b429ec3e77d01fc2b6744.

**Review by Toflar — APPROVED** [review]
Wonderful! I think this is going to help us in the future 👍

**Review by aschempp — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Pull request merged**
