### PR TITLE
Use `instanceof` instead of `null !==`

### PR DESCRIPTION
**Pull request by leofeyer**
This is a follow-up on #6280.

Rector kindly replaced all `if (null !== $obj)` with `if ($obj instanceof Class)` for us, which adds type safety and simplifies static analysis. 🎉

### CODE REVIEW

**Review by bytehead — APPROVED** [review]
❤️ IMHO this improves readability a lot.

**Comment by m-vo** [comment]
> which adds type safety and simplifies static analysis

I don't think this is true. Could you explain or give an example?

I agree that it improves readability in some places, but I don't think we should simply apply this "rule" to the code base. If a function has a return type hint `Foo|null`, I sometimes want to specifically check for the `null` case:

```php
function foo() : Foo|null { … }

// Check for the null case
if(foo() === null)) { … }
$result = foo() ?? $bar;
```

Replacing this by `! instanceof Foo` is looking way more obscure to me and hides the original intent. Now it looks like there can either be something of type `Foo` or of any other type. But the only other option really is `null`. That's why you can safely use the null coalescing operator in the "fallback pattern" (`$a ?? $b ?? $c`) for instance.

IMHO the problem gets even more apparent when there is another function that returns a nullable scalar, like `int|null`: now you cannot use `instanceof` and there are two patterns mixed.

**Comment by leofeyer** [comment]
> Could you explain or give an example?

See #6280.

**Comment by ausi** [comment]
I agree with @m-vo here, for simple types like `SomeClass|null` the `=== null` check seems way more intuitive to me. 
With `instanceof SomeClass` I’d also wrongly assume that there might be other classes possible too.

> > > which adds type safety and simplifies static analysis
> > 
> > Could you explain or give an example?
> 
> See #6280.

This is a different case IMO, `findBy()` returns the type `Collection|Model|null` and in that case the `instanceof` check makes perfect sense (and also suggests to the developer reading the code that `Collection` is not the only type that can be returned here).

But for the simple case like `SomeClass|null` I don’t see how this helps with type safety or static analysis.

**Comment by leofeyer** [comment]
Checking for `null` would be overly complex in a simple case like `SomeClass|null`.

```php
// This check is overly complex
if (null !== ($someClass = $this->returnSomeClassOrNull())) {
}

// This check is sufficient
if ($someClass = $this->returnSomeClassOrNull()) {
}
```

The Rector rule would not try to change the latter. And in all other cases where there are more options than just "nothing" and "something", using `instanceof` instead of `!== null` seems the right choice in terms of defensive programming.

So in my opinion, we should keep the Rector rule but we should adjust the PR and simplify all the "something or null" cases.

**Comment by m-vo** [comment]
In your code example, I really prefer the "overly complex" version. :see_no_evil: It makes clear that `$someClass` *can* be `null`, i.e. `null` is a valid case. To me, this is much more expressive than checking for truthy/falsy values (old discussion I know).

Take the following example:

```php
$thing = $this->getThing();

// version 1
if ($thing === null) {
}

// version 2
if (!$thing) {
}
```

Now what happens if  `getThing()` returns `string|null` vs `Thing|null`? The second version suddenly fails for `''`. IMHO exactly for defensive programming I like the first version, so that you can refactor the return type without introducing subtle errors.

But maybe it's also more about the interpretation of `null`. I do not consider it as `nothing` in general (compare to `undefined` in JS). In many cases it's a special/valid value in normal control flow. Otherwise one should consider exceptions for instance.

**Comment by ausi** [comment]
I’m totally happy with `if ($someClass = $this->returnSomeClassOrNull())`. To me this is perfectly readable and safe for all `SomeClass|null` use cases.

> The Rector rule would not try to change the latter.

We should not add [`BinaryOpNullableToInstanceofRector`](https://github.com/rectorphp/rector/blob/fbd33e5f98872411cd257b581cdcd4d7b7c2ebd3/docs/rector_rules_overview.md#binaryopnullabletoinstanceofrector) then, right?

> And in all other cases where there are more options than just "nothing" and "something", using `instanceof` instead of `!== null` seems the right choice in terms of defensive programming.

Agree, for `SomeClass|OtherClass|null` we should use `instanceof` if we want to handle only one of the two classes.

> So in my opinion, we should keep the Rector rule but we should adjust the PR and simplify all the "something or null" cases.

But as the rector rule only handles the “something or null” case, it would not have any effect anymore, right?

**Comment by leofeyer** [comment]
I guess so. I will try and get back to you.

**Comment by leofeyer** [comment]
I agree that the two Rector rules do too much, therefore I am closing this PR in favor of #6322 (where the Rector rules are no longer included).

**Pull request closed without merging**
