### PR TITLE
fix multiple slider in swiper.html.twig

### LINKED ISSUE #7271: Feature Request: Place multiple customized swiper elements on a page
### Description

Contao 5.3 Content Element Content-Slider
Currently, it is only possible to display a single functional (template customized) slider element on a page. From the second swiper element with customized templates onwards, only (the last) one on the page works.

I am referring to the request for adjustments within the `{% block script %}` `<script{{ script_attributes }}>` in a template `mycustomizedswipertemplate.html.twig`.

### PR DESCRIPTION
**Pull request by delirius**
Implements  #7271

### CODE REVIEW

**Comment by fritzmg** [comment]
I am not sure about this. By default, this is not needed. If you only need the default settings and you have multiple sliders on the same page, this would put the same initialization script multiple times on the page unnecessarily (one for each slider).

In my own application I would adjust the script to use a singular JSON data attribute, containing the whole Swiper configuration and then adjust the one initialization script accordingly (or rather use a Simulus controller).

We could instead introduce such a JSON attribute by default (instead of having multiple data attributes for only specific settings), thus making it easier for others to adjust it to their use case.

**Comment by delirius** [comment]
At the moment, if there are several sliders on a page, the script is loaded and processed for each slider. The configuration of the last slider is applied to all of them. If, for example, autoplay is selected for the last slider, all sliders are set to autoplay.

When the swiper script and the configuration script are separated, the configuration script for the corresponding slider is loaded.

{% add "swiper_js" to body %}
	General swiper script, in my opinion only loaded once as it is loaded with "swiper_js"
{% endadd %}

{% add to body %}
	Configuration script, is loaded for each slider and assigned via the id.
{% endadd %}

**Comment by zoglo** [comment]
I also / still think that https://github.com/contao/contao/issues/7271#issuecomment-2156650329 is the best solution to do so.
It'd just be an adapter that will listen to those data attributes - thus even making it more configurable and even allow to configure options via DCA / something else.

**Comment by fritzmg** [comment]
@delirius I understand the issue. But if you only need the default options, this adjustment creates the same init script unnecessarily for each slider. Personally I would solve it differently (see https://github.com/contao/contao/issues/7271#issuecomment-2156650329 and https://github.com/contao/contao/pull/7438#issuecomment-2286494236).

**Comment by delirius** [comment]
Due to the constellation that the init script is only loaded once, the init_options is also only loaded once. And the inti_options from the last slider of a page is applied to all sliders.

Inspired by a Slack entry, I found another approach. With an additional Twig variable ‘slider_settings’, which is passed to ‘data-settings’ with set and json_encode, and is read out in the script for each slider. 
Global settings can be made in the ‘init_options’ block and is backwards compatible. 
Specific settings can be made in the variable ‘slider_settings’ and assigned to ‘slider_attributes’.
#7470

**Comment by leofeyer** [comment]
Closing this in favor of #7470.

**Pull request closed without merging**
