### PR TITLE
Use the service ID instead of the class name for cron jobs

### PR DESCRIPTION
**Pull request by Toflar**
If you register the same PHP class as a cronjob with different arguments, Contao is going to treat them identically in the `tl_cron_job` table. So if you e.g. configure `TestClass` with 3 different service IDs (and different arguments), Contao will ignore 2 of them and only keep track of one of them (randomly) because they all share `TestClass` as their name.
This PR fixes this by using the service ID as the name.

### CODE REVIEW

**Comment by ausi** [comment]
Isn’t it possible that the same service has two methods that are tagged as a cron job? Should we instead store the service ID plus the method name?

**Comment by fritzmg** [comment]
The method name is already appended (see a few lines below).

**Review by aschempp — DISMISSED** [review]
This only solves the issue of registering the same class in two services with a cron tag each. It will not work if the same service has multiple cron tags on the same method. Imho we should have a name on the cron tag (which can be set on the attribute as well), and use a compiler pass that generates a name for each tag if necessary (which can be based on the service ID or class or method etc.), but make sure it is unique across the system.

**Comment by Toflar** [comment]
Yes, somebody else is very welcome to work on that if they think it's needed. But this PR fixes my issue and there's no reason not to merge it as is 🤷‍♂️

**Comment by aschempp** [comment]
I think it would be wrong to merge this, because it would generate new cron job names that then again change if we actually fix the issue…

**Comment by Toflar** [comment]
I have found a bug which this PR fixes and I need the fix in the next release. You found another bug which this PR does not fix. Fine. So we're not going to fix one bug because you found a second bug?

If you manage to provide an alternative PR that solves both problems in time, then you are free to do so. But blocking this PR and requesting changes is just wrong. I'm not going to work on an alternative.

**Comment by fritzmg** [comment]
> I think it would be wrong to merge this, because it would generate new cron job names that then again change if we actually fix the issue…

We should be able to create a migration for this. I will try to work on it today.

**Comment by fritzmg** [comment]
> It will not work if the same service has multiple cron tags on the same method.

No, that will still work. The cronjobs will still be executed, despite only the last execution being tracked in the database. For example:

```php
#[AsCronJob('0 10 * * *')]
#[AsCronJob('0 20 * * *')]
class ExampleCronJob
{
}
```

At first the cronjob will be executed at 10:00 for example. In `tl_cron_job` 10:00:00 will be logged for the last execution time for `ExampleCronJob`. And then at 20:00 the cronjob will be executed again, as the last cronjob execution time was at 10:00:00 for this day.

```php
$expression = new CronExpression('0 10 * * *');
var_dump($expression->getNextRunDate(new \DateTime('00:00:00'))->format('Y-m-d H:i:s'));
// string(19) "2024-08-16 10:00:00"

$expression = new CronExpression('0 20 * * *');
var_dump($expression->getNextRunDate(new \DateTime('10:00:00'))->format('Y-m-d H:i:s'));
// string(19) "2024-08-16 20:00:00"
```

**Comment by fritzmg** [comment]
Sorry, forgot about this.

I decided that it is not worth migrating the old cron job names to the new ones - as this would require either storing the service information during a compiler pass, or implementing a `Cron::getCronJobs()` method, which I find is not necessary to have other than for this migration.

However, I do feel like we should at least `TRUNCATE` the `tl_cron_job` table once to not pollute the table with the old legacy names - all of Contao's cronjobs would have an old and a new entry in the `tl_cron_job` table otherwise:

Screenshot 2024-09-22 174431

\
https://github.com/Toflar/contao/pull/17 adds such a migration, using the old name of the `contao.cron.purge_preview_links` cron job.

**Comment by Toflar** [comment]
This one specific migration doesn't really add any value, imho. The number of entries will be absolutely negligible anyway and it's a lot of code for no real benefit.

If we really want to have a cleanup procedure, I don't think the migration is the right way to go because it doesn't solve the issue for all use cases. Wouldn't it be smarter to have a general "prune" cronjob that cleans our internal table with all entries that are older than a year? Or a cleanup maintenance job that just truncates the table in case one thinks that those 100 entries there are bothering them?

**Review by fritzmg — DISMISSED** [review]
> and it's a lot of code for no real benefit.

It's not that much code, the migration is pretty small imho.

But approving in any case, as I agree that it is not really that important.

**Comment by aschempp** [comment]
> I have found a bug which this PR fixes and I need the fix in the next release. You found another bug which this PR does not fix. Fine. So we're not going to fix one bug because you found a second bug?

I'm sorry but that's just not true. You found a bug that cronjob names are not unique. Your PR fixes one case, but doesn't fix all cases. Both are the same bug: names are not unique. If we apply this fix now, we would **still** have non-unique names, and possibly need to change the names yet again once we have a fix (and e.g. @fritzmg will (try to) write a migration again) 😆 

The fix is also really simple! Our `Cron.php` should include the interval in the name of the database entry, not just the cronjob name. We could even have it automatically fall back to old names (including `get_class`) if we think that is necessary (instead of having a migration). 
@contao/developers wdyt? I could give that a try if we agree.

**Comment by Toflar** [comment]
Sure, if you want to fix the **second** bug, then go ahead.

**Comment by fritzmg** [comment]
@aschempp see https://github.com/contao/contao/pull/7444#issuecomment-2293199270

There is no need to separate intervals.

**Comment by fritzmg** [comment]
Added to up for discussion so that this PR won't be blocked ad infinitum ;)

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
