### PR TITLE
Adjust the text line height

### PR DESCRIPTION
**Pull request by xchs**
Adjust the line height so that the help text is not clipped:

settings

### CODE REVIEW

**Comment by leofeyer** [comment]
Which browser and OS are you using?

**Comment by xchs** [comment]
> Which browser and OS are you using?

Tested with Firefox, Chrome and Edge on Windows 10.

**Comment by xchs** [comment]
I have adjusted the line height in the system log, too.

system_log

[Tested with Firefox, Chrome and Edge on Windows 10.]

**Comment by leofeyer** [comment]
We have to check thoroughly that this change does not reintroduce the problems discussed in #79.

**Comment by leofeyer** [comment]
Can you please check if the following adjustments fix the issue for the help text?

```css
.tl_help, .tl_help a {
    margin-bottom: 0;
    line-height: 1.2; /* previously 1.25*/
    color: gray;
}
.tl_box h3, .tl_tbox h3, .tl_xpl h3 {
    margin: 0;
    padding-top: 13px; /* previously padding: 14px 0 1px */
    font-size: .875rem;
}
.tl_text, .tl_text_2, .tl_text_3, .tl_text_4, .tl_textarea, .tl_text_unit, .tl_text_trbl, .tl_text_interval {
    margin: 3px 0; /* previously 2px 0 */
    box-sizing: border-box;
    padding: 5px 6px 6px;
    border: 1px solid #aaa;
    border-radius: 2px;
    background-color: #fff;
    -moz-appearance: none;
    -webkit-appearance: none;
}
```

**Comment by xchs** [comment]
The proposed adjustments are working fine. I have updated the PR accordingly.

**Review by leofeyer — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @xchs.

**Pull request merged**
