### PR TITLE
4.8 multi domain: root pages in individual navigation

### PR DESCRIPTION
**Pull request by bit7ms**
We have a multi domain contao project. to give the visitors a better overview of the group of companies and domains,  we decided to display a meta navigation with the single web projects to the user.
We tried to use the classical individual navigation. I was wondering why I can't choose a root pages. If I do, it won't be displayed in FE.
The behavior should be like internal or external links. The Name (and css classes) should appear in the FE. A click on the navigation point should redirect to the "main page", with is shown, when the domain is loaded.

Would be great to have that feature. Thx!

### CODE REVIEW

**Comment by fritzmg** [comment]
Your PR contains previous commits. Also this was already implement in https://github.com/contao/core-bundle/issues/1641 and then later restricted in https://github.com/contao/contao/issues/72

**Comment by aschempp** [comment]
I think this was meant to be an issue and not a pull request 🙈

**Comment by bit7ms** [comment]
yes, should be an issue. Sorry 🙈

**Comment by leofeyer** [comment]
@mimamuxx Then please close the PR and create an issue instead.

**Pull request closed without merging**
