### PR TITLE
Move assets/images/deferred to var/deferred-images

### LINKED ISSUE #3898: Move assets/images/deferred to var/deferred-images
### Description

Because the JSON files are not meant to be accessible via HTTP.

### PR DESCRIPTION
**Pull request by ausi**
Fixes #3898

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by aschempp** [comment]
shound't this be in the cache directory?

**Comment by ausi** [comment]
> shound't this be in the cache directory?

I don’t think so, as clearing the cache would then remove the deferred images.

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by aschempp** [comment]
But I could have a different image configuration per environment? Or disable deferred images in dev environment?

**Comment by fritzmg** [comment]
> But I could have a different image configuration per environment?

Different image configurations yield different URLs, regardless of the environment.

> Or disable deferred images in dev environment?

If deferred images are disabled then the physical file already exists and thus no request is passed to the application - so this is also independent from the environment.

**Pull request merged**
