### PR TITLE
Fix dependency for symfony/doctrine-bridge

### PR DESCRIPTION
**Pull request by bytehead**
```
$ composer show | grep symfony
...
symfony/doctrine-bridge              v2.7.0             Symfony Doctrine Bridge
symfony/dom-crawler                  v3.4.0             Symfony DomCrawler Component
symfony/inflector                    v3.1.0             Symfony Inflector Component
symfony/options-resolver             v3.4.0             Symfony OptionsResolver Component
symfony/property-access              v3.4.0             Symfony PropertyAccess Component
symfony/stopwatch                    v3.4.0             Symfony Stopwatch Component
symfony/var-dumper                   v4.1.1             Symfony mechanism for exploring and dumping PHP variables
...
```

See also https://github.com/contao/phpstan/pull/5

### CODE REVIEW

**Comment by aschempp** [comment]
Does your comment suggest your installation did not install the latest versions? Then why should that be, if we did not specify a requirement? I don't think we should require components that we don't actually need (even if a dependency needs them)?

**Comment by leofeyer** [comment]
The main reason for doing so are the `--prefer-lowest` unit tests, which fail because of `doctrine/doctrine-bundle` allowing too low a version of `symfony/doctrine-bridge` (see https://travis-ci.com/contao/contao/jobs/208055180#L567). Would you prefer a conflict instead?

**Comment by fritzmg** [comment]
Conflict is surely the way to go - but why does this error happen in the first place? Seems like a dependency has wrong requirements?

**Comment by leofeyer** [comment]
Yes, it seems that `symfony/doctrine-bridge` is not compatible with `symfony/contracts` in some combinations. I don't know it it is worth fixing this in Symfony though, as it only affects `--prefer-lowest` installs?

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
