### PR TITLE
Add the primary image of news and events to the metadata

### PR DESCRIPTION
**Pull request by fritzmg**
In #2801 we introduced the possibility for search results to automatically show the `primaryImageOfPage` for the `WebPage` meta data. However, this is currently not utilised (by default) in Contao. This PR would add the teaser image of news and events as the `primaryImageOfPage` and thus the teaser image would automatically be displayed in the search results (after https://github.com/contao/contao/pull/5848 gets merged upstream).

_Note:_ since this is a simple template change, we could also introduce this as a bugfix in Contao 4.13? wdyt?

### CODE REVIEW

**Comment by Toflar** [comment]
I didn't do this because there can only ever be one primary image. You would now override this if any other extension set it earlier. But yeah, probably not a problem in 99% of all cases. I'd still vote for not doing this in a bugfix release.

**Comment by fritzmg** [comment]
> I didn't do this because there can only ever be one primary image. You would now override this if any other extension set it earlier.

Which imho would be expected behaviour.

> I'd still vote for not doing this in a bugfix release.

👍

**Comment by fritzmg** [comment]
Failing test is unrelated.

**Comment by leofeyer** [comment]
I have fixed the CI chain. However, don‘t we have the same problem here as in #5848?

**Comment by fritzmg** [comment]
> I have fixed the CI chain. However, don‘t we have the same problem here as in #5848?

Yes, that's why I wrote

> (after https://github.com/contao/contao/pull/5848 gets merged upstream)

**Review by Toflar — APPROVED** [review]

**Comment by fritzmg** [comment]
I'll do a final test once https://github.com/contao/contao/pull/5855 is merged upstream.

**Comment by leofeyer** [comment]
#5855 has been merged. 🎉

**Comment by fritzmg** [comment]
> #5855 has been merged. 🎉

Works 👍

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
