### PR TITLE
Consolidate the route definitions in invokable controllers

### PR DESCRIPTION
**Pull request by leofeyer**
Follow-up on #7227

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]
But as I mentioned in https://github.com/contao/contao/pull/7227 - wouldn't it be better to consolidate the two `@Route` definitions into one on the class itself?

**Comment by leofeyer** [comment]
> to consolidate the two `@Route` definitions into one on the class itself?

Yes, although I‘m not sure if it should be at class or method level. Are there any best practices for this in Symfony?

**Comment by fritzmg** [comment]
> Are there any best practices for this in Symfony?

In the [invokable controllers example](https://symfony.com/doc/5.x/controller/service.html#invokable-controllers) they use it on the class level.

Irrespective of the Symfony example I think it should be consistent with how _we_ use annotations and attributes everywhere else - which means class level when using `__invoke()`.

**Comment by leofeyer** [comment]
Changed in 366a331ec9a67c921c16b9fa3e51775091db1c3b.

**Review by fritzmg — APPROVED** [review]

**Pull request merged**
