### PR TITLE
Disable zlib.output_compression on CLI

### PR DESCRIPTION
**Pull request by aschempp**
Spotted due to https://github.com/contao/contao-manager/issues/445

### CODE REVIEW

**Comment by aschempp** [comment]
The failing tests are not related to this PR.

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Comment by aschempp** [comment]
@leofeyer please also backport the `contao-console` fix to Contao 4.4

**Comment by leofeyer** [comment]
Backported in 3777e663597fb15a65fe17f77cb7235525c9d191.

**Pull request merged**
