### PR TITLE
Add lightboxPicture in addition to imageHref

### PR DESCRIPTION
**Pull request by ausi**
This makes it possible to use a lightbox script with `<picture>`/`srcset` support.

### CODE REVIEW

**Review by Toflar — APPROVED** [review]
And now that we have deferred images we don‘t even generate them without using them👏🏻

**Comment by leofeyer** [comment]
Should we also enhance this regular expression to support `.svgz?` and possibly `.webp`?

https://github.com/contao/contao/blob/43b4a54e1accf926b24a975019f8b2e6884402f1/core-bundle/src/Resources/contao/library/Contao/Controller.php#L1671-L1674

**Comment by Toflar** [comment]
I think so yes. I don't know what this does anyway because only the script itself can define what it supports so if that check has to be there, it should be in the template imho.

**Comment by ausi** [comment]
Yes, I think we should check the imageUrl against the `contao.image.valid_extensions` list.

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by leofeyer** [comment]
> Yes, I think we should check the imageUrl against the `contao.image.valid_extensions` list.

Changed in 18e4ee6202a9e9397d4209a5c218c9d2e78f7505.

**Comment by ausi** [comment]
I’m wondering why this check was case-sensitive. Should we change that too?

**Comment by leofeyer** [comment]
Changed in b48f650dd49a58daae5883ded66aac311ccffd75.

**Pull request merged**
