### PR TITLE
Check template is fresh

### LINKED ISSUE #6068: Twig template not being re-compiled after a change whilst in 'dev' environment
### Affected version(s)

5.1

### Description

Using latest Contao 5.1, there seems to be a bug in the **isFresh** method of **src/Twig/Loader/ContaoFilesystemLoader.php**.

I am creating a custom content element, my template is located in:
`/contao/templates/content_element/my_template.html.twig`

APP_ENV is set to 'dev'. I can see the Twig Enviornment is set correctly too, both 'autoReload' and 'debug' are set to true.

The issue is that **isFresh** returns true even when I have made a change to my template. Making a change to a twig template whilst in the dev enviroment should trigger the template to be re-compiled when the frontend is refreshed.

I believe is issue is caused because the `isFresh` method is checking to see if my template is part of a theme, then when it determines that it isn't the `parent::isFresh` check is never done.

So, the template itself is never checked for freshness but the inheritance chain is.

```php
// my template is /contao/templates/content_element/my_template.html.twig

public function isFresh(string $name, int $time): bool
 {
        // $this->getThemeTemplateName($name) returns null, so this whole block is skipped
        
        if ((null !== ($themeTemplate = $this->getThemeTemplateName($name))) && !parent::isFresh($themeTemplate, $time)) {
            return false;
        }
        
        // The inheritance chain is then checked, but the template itself ($name) never is.

        $chain = $this->getInheritanceChains()[ContaoTwigUtil::getIdentifier($name)] ?? [];

        foreach (array_keys($chain) as $path) {
            $mTime = @filemtime($path);

            if (false === $mTime || $mTime > $time) {
                return false;
            }
        }

        return true;
}
```

I think the solution is to check `parent::isFresh($name, $time)` before the chain is checked. This fixes it for me, I will submit a PR.

### PR DESCRIPTION
**Pull request by jamesdevine**
Fixes #6068

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
please fix the coding style: https://github.com/contao/contao/actions/runs/5037586019/jobs/9034526403?pr=6069

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
@jamesdevine Can you please also adjust the unit tests?

**Review by fritzmg — DISMISSED** [review]
~This makes the condition in line 264 pointless, since it also has `!parent::isFresh($themeTemplate, $time)`. So sholudn't rather line 264 be changed?~

```diff
-if ((null !== ($themeTemplate = $this->getThemeTemplateName($name))) && !parent::isFresh($themeTemplate, $time)) {
+if (!parent::isFresh($themeTemplate, $time)) {
```

// Sorry, missed that it checks a different template name then.

**Review by ausi — CHANGES_REQUESTED** [review]
We should wait with merging this until the open discussion in #6068 is resolved I think.

**Comment by jamesdevine** [comment]
Solved in #6068

**Pull request closed without merging**
