### PR TITLE
Example of PHPStorm meta data

### PR DESCRIPTION
**Pull request by aschempp**
see https://blog.jetbrains.com/phpstorm/2019/02/new-phpstorm-meta-php-features/

### CODE REVIEW

**Comment by leofeyer** [comment]
Nice! 😎 

Why did you create a separate file for the back end template definitions?

**Comment by aschempp** [comment]
Just a thought on how we could "split" the ultra large file. It might also make things easier to keep the file list and metadata up to date. There can be multiple definitions for the same file, so we could have one for the front end templates in each folder.

Unfortunately, it is currently not supported to autocomplete the return value of our `getAdapter()` method (or I was unable to get that working).

**Comment by leofeyer** [comment]
> autocomplete the return value of our `getAdapter()`

That would be the icing on the cake.

**Comment by aschempp** [comment]
@contao/developers how should we continue here?

**Comment by leofeyer** [comment]
Which features are missing?

**Comment by aschempp** [comment]
🤷‍♂  none specifically but a million options. I think the most relevant question is if we want to split the files into the separate directories. Or have this at all 😂

**Comment by leofeyer** [comment]
I would create one file per bundle. And "autocomplete the return value of `getAdapter()`" would be one of the key features for me.

**Comment by m-vo** [comment]
Is there already also a procedural way to generate these files? I assume it would be hard to maintain if there were hundreds of options in there. But I totally like having these :D.

**Comment by aschempp** [comment]
They are manually created and updated. I'm pretty sure they will become incorrect and always will miss stuff. That's the point, I'm not sure they are _that_ useful – for as long as the `Adapter` case is not supported anyway.

**Comment by leofeyer** [comment]
> I'm not sure they are _that_ useful – for as long as the `Adapter` case is not supported anyway.

Good point.

**Comment by aschempp** [comment]
I agree. Closing this then.

**Pull request closed without merging**
