### PR TITLE
Fixes Warning: Undefined array key "includeChmod" at BackendUser

### PR DESCRIPTION
**Pull request by xprojects-de**
Fixes Warning: Undefined array key "includeChmod"

The BackendUser is indeed deprecated but I think it should be fixed anyway...

### CODE REVIEW

**Comment by leofeyer** [comment]
How can `$row['includeChmod']` not be defined? Did you unset the field in the DCA?

**Comment by fritzmg** [comment]
@xprojects-de please post a stack trace of the error.

**Comment by xprojects-de** [comment]
It happens when checking if a BackendUser is allowed to edit Article by Id in onGetContentElement.

```php
$parentArticleModel = ArticleModel::findById($element->pid);
if ($parentArticleModel !== null) {
       $canEdit = $this->backendUser->isAllowed(BackendUser::CAN_EDIT_ARTICLES, $parentArticleModel->row());
}
```

The row does not have includeChmod.
Bildschirmfoto 2022-02-04 um 12 28 36

```
ErrorException:
Warning: Undefined array key "includeChmod"

  at vendor/contao/core-bundle/src/Resources/contao/classes/BackendUser.php:306
  at Contao\BackendUser->isAllowed(4, array('id' => 114, 'pid' => 19, 'sorting' => 128, 'tstamp' => 1610899194, 'title' => 'Test', 'alias' => 'test', 'author' => 1, 'inColumn' => 'main', 'keywords' => null, 'showTeaser' => '', 'teaserCssID' => 'a:2:{i:0;s:0:"";i:1;s:0:"";}', 'teaser' => null, 'printable' => '', 'customTpl' => '', 'protected' => '', 'groups' => null, 'guests' => '', 'cssID' => 'a:2:{i:0;s:0:"";i:1;s:0:"";}', 'published' => '1', 'start' => '', 'stop' => '', 'isParallax' => '', 'vAlign' => '', 'hAlign' => '', 'size' => '', 'singleSRC' => null, 'sizemodus' => '', 'hasParallaxBackgroundImage' => '', 'vParallax' => '', 'hasAnimationeffects' => '', 'alpdeskanimation' => null, 'headline' => 'Test', 'multiMode' => false))
     (vendor/alpdesk/alpdesk-frontendediting/src/Listener/HooksListener.php:219)
  at Alpdesk\AlpdeskFrontendediting\Listener\HooksListener->onGetContentElement(object(ContentModel), '<!-- TEMPLATE START: vendor/contao/core-bundle/src/Resources/contao/templates/elements/ce_text.html5 --><div class="ce_text block">            <h2>Ich will Drag</h2>              <p>asdf</p>      </div><!-- TEMPLATE END: vendor/contao/core-bundle/src/Resources/contao/templates/elements/ce_text.html5 -->', object(ContentText))
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:603)
  at Contao\Controller::getContentElement(object(ContentModel), 'main')
     (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:202)
  at Contao\ModuleArticle->compile()
     (vendor/contao/core-bundle/src/Resources/contao/modules/Module.php:216)
  at Contao\Module->generate()
     (vendor/contao/core-bundle/src/Resources/contao/modules/ModuleArticle.php:72)
  at Contao\ModuleArticle->generate(false)
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:524)
  at Contao\Controller::getArticle(object(ArticleModel), false, false, 'main')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php:366)
  at Contao\Controller::getFrontendModule('0', 'main')
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:186)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:56)
  at Contao\PageRegular->getResponse(object(PageModel), true)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:316)
  at Contao\FrontendIndex->renderPage(object(PageModel))
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/preview.php:46) 
```

**Comment by fritzmg** [comment]
That's an error within the `alpdesk/alpdesk-frontendediting` extension. `$row` must always include a database record that includes `includeChmod`, either by using a record of `tl_page` or by joining from `tl_page`.

**Comment by xprojects-de** [comment]
yes I just saw that too!  Thanks and sorry...

**Comment by xprojects-de** [comment]
i close it!

**Pull request closed without merging**
