### PR TITLE
Show the picker menu even if there is only one tab

### LINKED ISSUE #1783: Articles tab missing in the universal picker
**Affected version(s)**

Contao 4.9.3

**Description**

When Contao is installed without news or events it is impossible to switch to the article overview in the include content element to select the referenced element. The navigation is missing.

missing

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1783
| Docs PR or issue | -

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Review by aschempp — COMMENTED** [review]
do we really need to check the count at all?

**Comment by leofeyer** [comment]
IDK. What if there are no menu items at all?

**Comment by aschempp** [comment]
There can't be no menu items if there is a picker? 🤷

**Comment by leofeyer** [comment]
Good point. 😄 Removed in 5ea15174365eb1e41df5dec571a8598bdcaee798.

**Review by aschempp — APPROVED** [review]

**Pull request merged**
