### PR TITLE
Handle nested content elements in the back end breadcrumb menu

### LINKED ISSUE #6804: Improve BE breadcrumb with regard to the new nested content elements
### Description

The new nested content elements are great to reduce the clutter in the backend.
Yet it would be great, if the breadcrumb navigation in the backend could visualize, that I'm currently in an nested element. It can get quite confusing especially if you have nested elements inside another nested element (e.g. a grid container with column containers in it).

Maybe this also qualifies as a bugfix?!

### PR DESCRIPTION
**Pull request by ausi**
The idea is that the service can retrieve information from a request object about the current entity the DCA handles. This makes it possible to create (stable) breadcrumbs that can also be used for the “back” navigation.

To be usable for other requests than the current main request we probably need #6955 as well.

### CODE REVIEW

**Comment by ausi** [comment]
Feedback: Return the breadcrumbs as KnpMenu? (@Toflar)

**Review by ausi — COMMENTED** [review]
✅ #7822 needs to be merged first

**Comment by leofeyer** [comment]
I tested the changes and most of them already work fine. However, there is one thing that I stumbled upon:

```
Articles
  |_ Page
    |_ Content slider [Main column]
       |_ Accordion
          |_ Text
          |_ Content slider
            |_ Slide 1
            |_ Slide 2
          |_ Text
```

* Open the articles module and click on "edit children" of the "Content slider" article.
* Click on "edit children" of the accordion element.
* Click on "edit children" of the content slider element.

Now the breadcrumb correctly shows `Articles > Content slider [Main column] > Accordion > Content slider` but when I click on the "Go back" button, I am taken to `Articles > Content slider [Main column]` (2 levels above) instead of to `Articles > Content slider [Main column] > Accordion` (one level above).

**Review by leofeyer — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
