### PR TITLE
Fix versioning condition in DC_Folder edit action

### LINKED ISSUE #3301: Creating a new folder in dev env, PHP 8 causes an ErrorException
**Affected version(s)**

 Contao 4.11 (PHP 8.0.9)

**Description**
When **creating a new folde**r in the backend in **APP_ENV=dev** a warning occurs:
```Attempt to read property "id" on null```
This leads to an ErrorException in vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Folder.php (line 1324)

**Solution**
Check, if $objModel is not null:
```$objVersions = new Versions($this->strTable, $objModel->id ?? null);```

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3301

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Comment by bytehead** [comment]
LGTM (tested in Contao 4.11.x-dev with patch / PHP 8.0.9)

**Comment by bytehead** [comment]
I'm not sure if this should go against 4.11 as 4.9 should not be run with warnings enabled under PHP 8?

**Comment by ausi** [comment]
> I'm not sure if this should go against 4.11 as 4.9 should not be run with warnings enabled under PHP 8?

IMO this was not only a missing `null` check but the wrong logic. But I would be fine merging it in 4.11 only too.

**Comment by fritzmg** [comment]
Since `$objVersions` is now not always initialized, are we sure lines 

https://github.com/contao/contao/blob/866e4c31ab16f4d0e1169da5283872c02fca0b1a/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L1514

and 

https://github.com/contao/contao/blob/866e4c31ab16f4d0e1169da5283872c02fca0b1a/core-bundle/src/Resources/contao/drivers/DC_Folder.php#L1547

won't get executed now?

**Comment by ausi** [comment]
Both check for `$objModel !== null` so this should be fine.

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
