### PR TITLE
Register a web processor to add log extras

### PR DESCRIPTION
**Pull request by aschempp**
This adds the current request URL to every log entry, making it possible to see where an error occurent in the website.

### CODE REVIEW

**Comment by Toflar** [comment]
Shouldn't this get added to the manager-bundle?

**Comment by fritzmg** [comment]
> Shouldn't this get added to the manager-bundle?

I am not sure. The Monolog config is done in the `manager-bundle` - but the `Processor` is, I think, independent of that and thus can reside in the Contao Core.

**Comment by Toflar** [comment]
The way I understand it is that the tag `{ name: monolog.processor }` will add this processor to any logger configured in the system which is probably not what you want if you install only the `contao/core-bundle` to your app but do not use the Managed Edition?

Also, do you guys think it would be helpful to add the `http_method` on top of the URI just so that we know if an error happened e.g. during a POST request or not?

**Comment by aschempp** [comment]
Fully agree. The manager bundle configures monolog, we should only add the processor here. And I added the request method.

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
