### PR TITLE
Remove the `feViewable` configuration

### PR DESCRIPTION
**Pull request by fritzmg**
The `feViewable` `eval` property is a remnant from Contao 2's `memberlist` module which does not exist anymore since Contao 3.

### CODE REVIEW

**Comment by katgirl** [comment]
but it is still included in the current documentary.
Shouldn't it have been stated somewhere that it is no longer applicable? I haven't found anything :-(

image

https://docs.contao.org/dev/reference/dca/fields/

**Comment by fritzmg** [comment]
> but it is still included in the current documentary.

Yes, by mistake. See https://github.com/contao/docs/pull/1368

**Comment by fritzmg** [comment]
Just to clarify: that part of the documentation was re-used from the [old docs](https://github.com/contao/docs-archive) which in turn still had things in them that were relevant for Contao 2 - including this `eval` property. But as already mentioned, this property has no meaning for the Contao Core anymore since Contao 3, as there is no member list module.

**Review by ausi — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Pull request merged**
