### PR TITLE
Disable copying and deleting of tl_undo records

### PR DESCRIPTION
**Pull request by lukasbableck**
Since Contao 5 the tl_undo records can be deleted and copied via the all operation. In Contao 4.13 this was not the case.
Deleting could maybe make sense, but copying does not even do anything because the records can not be pasted, so this is definitely a bug.
I guess this was introduced by #6528.

Contao 5:
image
image

Contao 4.13:
image

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]

**Comment by aschempp** [comment]
Although, we should actually fix that in Contao 4.13, because the permissions were incorrect there. The operation didn't show, but it could still be done by URL!

**Comment by lukasbableck** [comment]
Ok, should I rebase onto 4.13 then?

**Comment by zoglo** [comment]
> Ok, should I rebase onto 4.13 then?

If that's not too much work for you.

Opening another PR for 4.13 with a note that it should not be upstreamed would work as well

**Comment by lukasbableck** [comment]
> If that's not too much work for you.

Done 🙂

**Review by zoglo — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Comment by zoglo** [comment]
> Although, we should actually fix that in Contao 4.13, because the permissions were incorrect there. The operation didn't show, but it could still be done by URL!

Just confirmed this in a 4.13 :)

**Comment by leofeyer** [comment]
Thank you @lukasbableck.

**Pull request merged**
