### PR TITLE
Load protected status from parent pages in customnav

### PR DESCRIPTION
**Pull request by patrickjDE**
The custom navigation module does render protected pages if not logged in, even with the "Show protected items" option disabled, if they do not have the protected status set on the page itself, but rather inherited the status from one of its ancestor pages.

This PR adds a call to `PageModel::loadDetails` to actually inherit the protected status and associated groups setting from parent pages before checking for them, to correctly hide protected pages.

### CODE REVIEW

**Comment by aschempp** [comment]
This is likely a big performance penalty, but I can't think of any other solution 😢

**Comment by leofeyer** [comment]
I am not sure if this is correct. In the custom navigation, there is no page hierarchy and thus no inheritance – at least this is how the module was designed. Of course, we can discuss this and agree to change it in the future.

**Comment by patrickjDE** [comment]
> In the custom navigation, there is no page hierarchy and thus no inheritance – at least this is how the module was designed.

That might have been the original intention, but it just cannot work. Which navigation module was used has no say in the protection status of a page.

When accessing the page in question, protected status from the page's hierachy is taken into account anyway, as you cannot tell from which navigation (if any) that request originated.

**Comment by aschempp** [comment]
@leofeyer is right here. A page that is published is publicly available on the website, regardless of a published parent page. Therefore it should also appear in the custom navigation. The regular navigation module does not _show_ them by accident, because it does not render the parent node and therefore it's children.

**Comment by patrickjDE** [comment]
> A page that is published is publicly available on the website, regardless of a published parent page.

~~Am I missing something here? 🤔~~

~~A page is not publicly accessible, if one of its parent pages are protected. It's in the docs, it works like this in the official demo, and did so since what feels like forever.~~

EDIT: Ah, yes, I misread. Didn't notice you were talking about a *published* parent page - which, in turn, is not what this PR is about, as @fritzmg already pointed out.

**Comment by fritzmg** [comment]
> @leofeyer is right here. A page that is published is publicly available on the website, regardless of a published parent page.

@aschempp this is about the **protected** status, not the **published** status. I agree with @patrickjDE that pages that the front end user does not have access to should _not_ show up.

**Comment by leofeyer** [comment]
As discussed in Mumble on May 12th, we want to merge this as is.

**Review by leofeyer — CHANGES_REQUESTED** [review]
As discussed in Mumble on May 12th, we want to merge this PR. However, the `->loadDetails()` call should be above the `$_groups = StringUtil::deserialize($objModel->groups);` statement.

**Comment by patrickjDE** [comment]
Updated the PR as requested

**Review by aschempp — APPROVED** [review]
Sorry about my confusion as well 😄 looks good now!

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @patrickjDE.

**Pull request merged**
