### PR TITLE
Replace the ./run script with Composer

### PR DESCRIPTION
**Pull request by leofeyer**
Because why use `./run phpunit` if you can do `composer run unit-tests`?

### CODE REVIEW

**Review by Toflar — CHANGES_REQUESTED** [review]
README needs to be adjusted. Fine with me otherwise.

**Review by bytehead — APPROVED** [review]
Nice catch! But as mentioned, `README.md` needs an update :)

**Review by bytehead — DISMISSED** [review]
Nice catch! But as mentioned, `README.md` needs an update :)

**Review by Toflar — APPROVED** [review]

**Review by bytehead — APPROVED** [review]
Works like a charm!

**Comment by bytehead** [comment]
How can you run tests only for one bundle this way?

**Review by aschempp — APPROVED** [review]
I‘m approving this as the code seems correct. But idk why this needs to be changed (again), probably will become an issue for documentation and existing forum posts etc...

**Comment by leofeyer** [comment]
> How can you run tests only for one bundle this way?

By filtering the bundle name: `vendor/bin/phpunit --filter CalendarBundle`

**Pull request merged**
