### PR TITLE
Fix a PHP8 issue in the `be_help` template

### PR DESCRIPTION
**Pull request by aschempp**
I got these through Sentry.io reportings 🙃

### CODE REVIEW

**Comment by aschempp** [comment]
related to https://github.com/contao/contao/pull/5936

**Review by leofeyer — COMMENTED** [review]
I can confirm the fixes in the `tl_calendar_events.php` and `tl_news.php` files, however, as I already explained [here](https://github.com/contao/contao/pull/5936#discussion_r1159644451), we should fix all occurrences and not just one out of four.

I cannot confirm the changes in the `be_help` template though. How do I reproduce the initial problem?

**Comment by aschempp** [comment]
> I cannot confirm the changes in the `be_help` template though. How do I reproduce the initial problem?

Create a new content element and add a label to `defaults.php`
`$GLOBALS['TL_LANG']['CTE']['foobar'] = ['Foobar'];`

Then open the tooltip wizard on the content element type.

**Comment by fritzmg** [comment]
@aschempp but that would be an incomplete label. It needs to have to elements.

**Comment by fritzmg** [comment]
Technically that would be an incomplete label. However I think we allow the missing second label element in other places (e.g. for widget labels) so I guess it should also be allowed to omit it for the label of content elements.

// (sorry, misclicked)

**Review by leofeyer — APPROVED** [review]
> Technically that would be an incomplete label.

I think so, too. It should either be a string or an array with label and help text:

```php
// Only a label
$GLOBALS['TL_LANG']['CTE']['foo'] = 'Foo';

// Label and help text
$GLOBALS['TL_LANG']['CTE']['foo'] = ['Foo', 'Bar'];
```

But the `BackendHelp` controller does not handle the first case, either, so we should merge this PR now and deal with the rest in a separate one.

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
