### PR TITLE
Fix the widget headline and help wizard alignment

### PR DESCRIPTION
**Pull request by leofeyer**
### After

@fritzmg I think with the `height: 16px` applied to the `h3` elements, we can even revert the `min-height: 81px` changes. Can you check this PR in all browsers on Windows and also check what happens if you reset the min-height to `80px` and `46px`?

### CODE REVIEW

**Comment by fritzmg** [comment]
Oh yes, good find. If we revert these changes: https://github.com/leofeyer/contao/compare/fix/help-wizard...fritzmg:fix/help-wizard-revert-previous the layout will be fixed in Firefox, Chrome and Edge :)

**Comment by leofeyer** [comment]
I think we can keep the following:

**Comment by fritzmg** [comment]
Btw. one small thing (unrelated to this PR but related to the layout changes in general): the version select is not the same height as the restore button any more... because of the `height: 30px` for selects. May be we should revert my previous PR completely :(.

Annotation 2020-06-26 123434

**Comment by fritzmg** [comment]
> I think we can keep the following:
> 
> 

We'd also need to keep the `.cbx.m12` style then. I'd revert it, to keep it more simple, since that change is not necessary anymore.

**Comment by leofeyer** [comment]
Ok, so how do we proceed? Shall I merge this PR and then you create a new PR reverting your changes?

**Comment by fritzmg** [comment]
> Ok, so how do we proceed? Shall I merge this PR and then you create a new PR reverting your changes?

Yes, you can merge this and I'll look at it in more detail again.

**Comment by leofeyer** [comment]
Done. 👍

**Pull request merged**
