### PR TITLE
Show the route configuration in the news feed page

### PR DESCRIPTION
**Pull request by aschempp**
It sure makes sense to see that the RSS page has a .xml suffix, right? Not sure if the page can have parameters at all?

Bildschirmfoto 2024-03-04 um 15 31 33

### CODE REVIEW

**Comment by leofeyer** [comment]
There are two problems IMHO:

1. The page cannot have parameters, so the `{parameters}` part is misleading.
2. I now see potential route conflicts with other pages, although those are not `.xml` requests:

**Comment by fritzmg** [comment]
> 1. The page cannot have parameters, so the `{parameters}` part is misleading.

This is something we can fix on the service tag of the page controller (I think?).

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Comment by aschempp** [comment]
why did you add the `clr` class? Did you check with all the other page types?

**Comment by leofeyer** [comment]
Yes, it was missing there, too.

**Pull request merged**
