### PR TITLE
made notification bell counter more visible

### LINKED ISSUE #191: make notification bell counter more visible
Imho the counter on the notification bell currently goes unnoticed pretty easily (red on orange). Just a small suggestion on how it could look differently:

nb_org

vs.

nb_alt1

Example with bigger numbers:

nb_alt2

CSS used:

```css
{
  top: 4px;
  left: 20px;
  width: 18px;
  height: 18px;
  background-color: white;
  color: red;
  text-align: center;
  line-height: 18px;
  font-size: 10px;
  border-radius: 100%;
  padding: 0;
  font-weight: 700;
}
```

Any thoughts? :)

### PR DESCRIPTION
**Pull request by mktcode**
Fixes https://github.com/contao/contao/issues/191

image

I used [this website](https://csscompressor.com/) to minify the css.

### CODE REVIEW

**Comment by leofeyer** [comment]
Since this is a new feature, please change the base branch to `master`.

**Comment by leofeyer** [comment]
@contao/developers Or do we consider this a bug fix?

**Comment by ausi** [comment]
It is a feature IMO.

**Comment by mktcode** [comment]
changed base to master and resolved conflicts.

**Comment by leofeyer** [comment]
Implemented in 11d2b1ffa6864d8ce3187e6e3d56839939fbf6f1.

Before:



After:

**Pull request closed without merging**
