### PR TITLE
Fix the routing SSL logic

### LINKED ISSUE #2171: {{link_url}} Insert-Tag broken on roots with different domains
**Affected version(s)**

Contao 4.10

**Description**

When creating a link to a page from another root with a different domain the link generated by e.g `{{link_url::1}}` should be an absolute but Contao generates a relative one.

**Steps to reproduce**

- Create two roots with domain `a.com` and `b.com`
- Create a link on `a.com` which links to a site on `b.com` using e.g `{{link_url::1}}`
- The generated link says `/b.com/site.html` which will be interpreted as `http://a.com/b.com/site.html` because of the base path

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2171
| Docs PR or issue | -

This PR replaces #2262 and #2279.

## As discussed at the developer's meeting:

- Only switch to using absolute paths in Contao 5
- Fix the routing in Contao 4.10:
  - Checkbox not checked -> HTTP (not also HTTPS anymore!)
  - Checkbox checked -> HTTPS
- Use radio buttons instead of a checkbox

## Why radio buttons do not work

In order to remain BC, the option values need to be `''` and `'1'`, however, our `RadioButton` class interprets `''` as "not checked" and therefore never renders the HTTP option as checked. Of course, we could adjust the `Widget::optionChecked()` method, however, it would most likely have side effects. I therefore went with a select menu:

## What the PR fixes

The UrlGenerator now prepends the `http://` protocol if the current website uses HTTPS and the target website does not. ✅ 

## What the PR still does not fix

If both the current and the target website use HTTPS, the UrlGenerator still generates a network path, therefore we still need #2279 to actually fix #2171. 🤷🏻‍♂️

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Review by aschempp — COMMENTED** [review]
I wouldn't switch the palette field position, even though I understand the intention. 

Also, can you also add the fix for #2171 here so we have one place for it all? However, we should accept that Symfony generates a network path and simply accept that, and not append the protocol on our own.

**Comment by ausi** [comment]
> However, we should accept that Symfony generates a network path and simply accept that, and not append the protocol on our own.

Would be OK for me too. IMO we should then change the if condition from

```php
if (0 === strncmp($strUrl, '/', 1))
```

to:

```php
if (0 === strncmp($strUrl, '/', 1) && 0 !== strncmp($strUrl, '//', 2))
```

**Comment by leofeyer** [comment]
> Also, can you also add the fix for #2171 here so we have one place for it all?

Will do.

> we should accept that Symfony generates a network path and simply accept that

Ok, if you both think so. I would prefer to generate absolute URLs, but I will bow to the majority.

**Review by aschempp — APPROVED** [review]

**Comment by m-vo** [comment]
The description of this PR says it does not fix #2171, but #2279 does.
But #2279 is closed and points back to this PR which would solve the issue.

 I'm confused.

**Comment by ausi** [comment]
> The description of this PR says it does not fix #2171

This PR was later updated to actually fix #2171.

**Comment by m-vo** [comment]
Ah, thanks, think I got it now.

**Pull request merged**
