### PR TITLE
Do not add the preview script when rebuilding the search index

### LINKED ISSUE #942: sitemap.xml is generated with /preview.php/ URLs
We currently have the problem, that sometimes the sitemap.xml is generated with preview.php URLs.

Regular site count is at about 256 pages, and we get errors in our SEO tool and from the Google Search Console as well, that ~250 pages of ~500 pages are redirects with "noindex".

So every page is in the list twice.

Is it possible that the sitemap is created depending on the user that is logged in?

Current Contao version is 4.8.4.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #942

### CODE REVIEW

**Review by Toflar — CHANGES_REQUESTED** [review]
This implementation is incorrect. 
It will cause all links to not contain the preview.php anymore which is not what we want when browsing the site in preview mode. The correct fix is to dynamically mark a page noindex/nofollow as well as „do not add to sitemap“ if the preview token is activated imho.

**Comment by leofeyer** [comment]
You are right. 👍

**Comment by leofeyer** [comment]
Would you prefer

1) stripping the preview script from the URLs when rebuilding the search index or
2) not offering to rebuild the search index if the preview script is in the back end URL?

Because it is a bad UX if you only learn that nothing has been indexed because of the preview script after you have rebuilt the search index. 😄

**Comment by Toflar** [comment]
I think it should get stripped when finding the searchable pages. But making them noindex should be done as well. There‘s an event listener that sends X-Robots-Tag: noindex when in dev mode afaik. Guess we need the same for our preview mode. The check whether preview is enabled or not should be done the same as @richardhj does in his preview bar PR.

**Comment by leofeyer** [comment]
I have adjusted the PR as discussed.

**Review by Toflar — APPROVED** [review]

**Pull request merged**
