### PR TITLE
Switch to first allowed type if default type is not allowed in element group

### PR DESCRIPTION
**Pull request by dennisbohn**
Unfortunately, I broke my [last pull request](https://github.com/contao/contao/pull/7100). So here is the second attempt.

Currently, the type field of a content element is set to "article" by default, which leads to an unknown option being displayed in the drop-down list of the type if you create it in an element group where the type "article" is not contained in "allowedTypes".

```
#[AsContentElement(category: 'custom', template:'content_element/element_group', nestedFragments: ['allowedTypes' => ['image']])]
class ImageGroupController extends AbstractContentElementController
{
    protected function getResponse(FragmentTemplate $template, ContentModel $model, Request $request): Response
    {
        return $template->getResponse();
    }
}
```

image

In this case, the added callback function automatically changes the value to the first supported type.

Furthermore the tl_content.php was modified to close the content element, if the user has no permission for the nested elements.

### CODE REVIEW

**Comment by dennisbohn** [comment]
I wonder why PHPStan gives an error. According to PHPStan, I am using the User class here, although I am using the BackendUser class. Can this be ignored or do I have to adjust something here?

It has no problems with BackendUser in tl_content.php.

**Comment by aschempp** [comment]
Thanks for the follow-up @dennisbohn! I have two issues here:
 1. this fix is kinda duplicated by #7088. However, we recently discussed a voter should not decide on non-user permissions (nested elements), so I dunno what @contao/developers think here?
 2. I dislike that the functionality is now split across multiple places (`tl_content` and the listener). Additionally, this will create an incorrect record and then modify it after, instead of making sure the correct data is saved to the database. Maybe this could be done using an `options_callback` or the `widget_callback`? 🤔

**Comment by leofeyer** [comment]
> However, we recently discussed a voter should not decide on non-user permissions (nested elements), so I dunno what @contao/developers think here?

What do you mean? The pull request adds a listener, not a voter.

**Comment by aschempp** [comment]
I mean that my content-element access voter would fix this as well, but it would vote on the allowed nested elements.

**Comment by leofeyer** [comment]
Ah, that‘s a tricky one.

There is a user setting for allowed content elements, which per our definition is the responsibility of the security voters. But there is also the `allowedTypes` property that can be used to limit the types of elements in a set of nested fragments, which per our definition is not the responsibility of a security voter.

However, since both `tl_user.elements` and `allowedTypes` do the same thing, I think a security voter should be allowed to vote on both. @ausi WDYT?

**Comment by ausi** [comment]
> However, since both `tl_user.elements` and `allowedTypes` do the same thing, I think a security voter should be allowed to vote on both. @ausi WDYT?

I don’t agree. For me the security voter should only handle the `tl_user.elements` part.

**Comment by m-vo** [comment]
If you think what an admin would experience, it's clear that the `allowedTypes` must be enforced outside the voter. ☺️

**Comment by leofeyer** [comment]
You are absolutely right.

**Comment by leofeyer** [comment]
As discussed in the Contao call, @aschempp will integrate the changes into #7088 where necessary.

**Comment by leofeyer** [comment]
@dennisbohn Can you test if the changes from #7088 fix your problem?

**Comment by dennisbohn** [comment]
I finally got around to testing the changes. Unfortunately, it is not yet working as expected. I have now installed version 5.x-dev and created the following content element.

```php
<?php

namespace App\Controller\ContentElement;

use Contao\ContentModel;
use Contao\CoreBundle\Controller\ContentElement\AbstractContentElementController;
use Contao\CoreBundle\DependencyInjection\Attribute\AsContentElement;
use Contao\CoreBundle\Twig\FragmentTemplate;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

#[AsContentElement(category: 'custom', template:'content_element/element_group', nestedFragments: ['allowedTypes' => ['image']])]
class ImageGroupController extends AbstractContentElementController
{
    protected function getResponse(FragmentTemplate $template, ContentModel $model, Request $request): Response
    {
        return $template->getResponse();
    }
}
```

The “allowedTypes” have been restricted to “image”. 

When I create a nested content element the option "text" is still preselected.

image

image

The type is not only preselected. It is also created when saving.

image

**Comment by aschempp** [comment]
see https://github.com/contao/contao/pull/7515 for the actual fix. Unfortunately, voters have not been checked yet for this case 😉

**Comment by leofeyer** [comment]
@dennisbohn Does #7515 fix the issue eventually?

**Comment by dennisbohn** [comment]
It works. If I now create a new content element within a restricted content group, it automatically selects the appropriate element.

I have noticed a few minor problems, but these occur probably only rarely or not at all in practice:

**Testcase 1**

| User permissions | Content element group |
| --- | --- |
| text only | image |

If a user who does not have permission for ‘image’ tries to create a content element within a content group that only allows ‘image’, it automatically switches to ‘text’. This can then also be saved.

**Testcase 2**

| User permissions | Content element group |
| --- | --- |
| headline only | image |

If a user is not permited to create either ‘text’ or ‘image’, they receive the error message ‘Not enough permissions to update’ when he tries to create an entry. There is then an empty text element in the content group, which the user can not delete.

It might be useful to deactivate the ‘new content element’ link in both cases.

**Comment by aschempp** [comment]
should be fixed by the latest changes in https://github.com/contao/contao/pull/7516. You cannot create new elements if none are allowed now.

**Pull request closed without merging**
