### PR TITLE
Allow creating modern templates from within the back end

### PR DESCRIPTION
**Pull request by m-vo**
Addresses https://github.com/contao/contao/issues/5223#issuecomment-1236307138

This PR adds a simple way to create modern templates from within the back end. 

image

There now is a `@Contao/backend/template_skeleton.html.twig` that gets used to create the content of the derived templates. As an example, for the default text content element template this produces an output like this:

```twig
{% extends "@Contao/content_element/text.html.twig" %}

{#
  ** Add changes to the base template here. **

  Hint: Try adjusting blocks and attributes instead of
  overwriting the whole template. This way your version
  can remain compatible with future changes to the base
  template as well as adjustments made by extensions.

  Currently available blocks:
    "picture_component", "image", "sources", "source",
    "schema_org", "figure_component", "media",
    "media_link", "caption", "caption_inner",
    "content", "text_media", "text",
    "text_attributes", "headline_component",
    "headline_attributes", "headline_inner",
    "wrapper", "wrapper_tag", "attributes", "inner"

  Example:
    {% block picture_component %}
       {{ parent() }}
       My additional content for 'picture_component'…
    {% endblock %}
#}

```

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

**Review by leofeyer — CHANGES_REQUESTED** [review]
The PR is technically flawless. There is just one thing that should be optimized IMHO:



As you see, the **new** templates are all grouped nicely. However, the **legacy** templates are not:



Why are they not grouped under the `forms/` namespace?

**Comment by m-vo** [comment]
> Why are they not grouped under the forms/ namespace

I did not touch the grouping of the old templates but I reckon changing this could be problematic: In your example `forms` is just a directory and not part of the template and there could be multiple `forms` directories. :thinking: 

I'm also not fully getting the idea behind the existing grouping - care to explain? :smile:

**Comment by leofeyer** [comment]
> I did not touch the grouping of the old templates

You must have. Templates are grouped by bundle in Contao 4.13:



There is no **forms/form_upload.html5** group header in Contao 4.13.

**Comment by m-vo** [comment]
Ah interesting! I'll have a look.

**Comment by m-vo** [comment]
I reverted the unrelated change to the old template listing. I had that in there because this produced an exception in my setup where `contao/contao` is a symlinked composer resource: 

```
Path "/path/to/symlinked/core-bundle/contao/templates/analytics/analytics_matomo.html5" is not inside the Contao root dir "/path/to/app"
```

But we should fix this independently of this PR (and also in 4.9 / 4.13 I guess). Edit: see #5270

**Comment by aschempp** [comment]
Is there an option whether I want to copy the whole template or "only" get the "extends" option? Because I can't easily inspect the current template can I?

**Comment by m-vo** [comment]
> Is there an option whether I want to copy the whole template or "only" get the "extends" option? Because I can't easily inspect the current template can I?

There is no option, we can think about one in #5223. But honestly, I'm not sure what this should achieve. Would you want to have all the sources of all inherited templates including all used templates in your template? 

If you want get fancy, use an IDE like PhpStorm with the Symfony plugin, then you can follow extends like with PHP classes. The `debug:contao-twig <optional prefix>` command also outputs a preview of the first lines to identify a template.

**Comment by m-vo** [comment]
With the changes from #5270 this is how it looks now (filtered for "headline" in this example):

image

**Review by ausi — APPROVED** [review]

**Comment by aschempp** [comment]
> Would you want to have all the sources of all inherited templates including all used templates in your template?

No, I would expect exactly the same as it is now: get a copy of the current template with all its content and a new name. Otherwise I have no chance to get to what I want without extensively looking at the original template (which is currently not possible through the back end).

Also be aware that the diff options makes little sense now with this feature 🤷

**Comment by m-vo** [comment]
> No, I would expect exactly the same as it is now: get a copy of the current template with all its content and a new name. 

It's a hierarchy - the current template is just the last one and it likely extends from the same managed name as well. And even if there is one template, it will most definitely extend from yet another template (e.g. the CE base template) and include components. Maybe at some point the template inspector can return the original/last contents (source) of the found blocks and we could improve the `template_skeleton` but that's definitely out of scope for this quick fix.

Copying the *source* template instead of extending it will just destroy every adjustment made by extensions and never makes sense to me.

> Also be aware that the diff options makes little sense now with this feature :shrug:

That's a different issue.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
