### PR TITLE
Quote all schema names, same as we do for inserts

### LINKED ISSUE #4420: Increase compatibility between MariaDB and MySQL 8 in contao:backup tasks
### Description

As discussed in Slack, `contao:backup:create` in a MariaDB instance creates a dump that is not importable in MySQL 8, because ` groups` is a reserved keyword in MySQL 8 and needs backticks like 
```
`groups`
```

### PR DESCRIPTION
**Pull request by ausi**
Fixes #4420

Our dumper already quotes all names for the `INSERT` statements.
This PR now does the same for the schema statements.

### CODE REVIEW

**Review by m-vo — APPROVED** [review]
After reviewing the code of `AbstractPlatform`, using reflection is IMHO the most sensible thing to do here. The `_keywords` property is protected and should therefore be covered by their BC promise. The alternative, creating a decorator, is way too complex for this use case.

**Comment by Toflar** [comment]
Can't we just not use `$connection->quote()` and simply quote ourselves? 🤔

**Comment by ausi** [comment]
> Can't we just not use `$connection->quote()` and simply quote ourselves? 🤔

I tried that first by replacing all column and table objects with quoted ones, but that was way harder and complex and in the end I didn’t reach every identifier that the mysql platform creates.

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
