### PR TITLE
Replace contao/php-cs-fixer with contao/easy-coding-standard

### PR DESCRIPTION
**Pull request by leofeyer**
This PR changes quite a lot of files, therefore you probably want to review the single commits instead of everything.

There are three main differences compared to our previous coding style:

### 1. Generic type hints

**OLD**

```php
/**
 * @return EscargotSubscriberInterface[]
 */
```

**NEW**

```php
/**
 * @return array<EscargotSubscriberInterface>
 */
```

**Motivation:** generic type hints are newer than array type hints and are meant to replace them.

### 2. Unnecessary @inheritdoc comments

**OLD**

```php
/**
  * {@inheritdoc}
  */
public function foo() {}
```

**NEW**

```php
public function foo() {}
```

**Motivation:** a doc block must not contain only an @inheritdoc tag (see https://docs.phpdoc.org/guides/inheritance.html#the-inheritdoc-tag).

### 3. Multi-line whitespace before closing semicolon

**OLD**

```php
$framework
    ->method('isInitialized')
    ->willReturn(false)
;

$this
    ->setName('contao:automator')
    ->addArgument('task', InputArgument::OPTIONAL, "The name of the task:\n  - ".implode("\n  - ", $this->getCommands()))
    ->setDescription('Runs automator tasks on the command line.')
;

$container
    ->registerForAutoconfiguration(EscargotSubscriberInterface::class)
    ->addTag('contao.escargot_subscriber')
;
```

**NEW**

```php
$framework
    ->method('isInitialized')
    ->willReturn(false);

$this
    ->setName('contao:automator')
    ->addArgument('task', InputArgument::OPTIONAL, "The name of the task:\n  - ".implode("\n  - ", $this->getCommands()))
    ->setDescription('Runs automator tasks on the command line.');

$container
    ->registerForAutoconfiguration(EscargotSubscriberInterface::class)
    ->addTag('contao.escargot_subscriber');
```

**Motivation:** no strong motivation here, it is just shorter with the semicolon on the same line as the closing parentheses. It also seems to be the more common style; at least I get 2.788 occurrences if I search for ` +->[^(]+\([^)]+\);` in PhpStorm (with regex) and only 469 occurrences if I search for ` +->[^(]+\([^)]+\)\n +;` – and that includes our own code!

### Votes

| User | 1. Generic type hints | 2. Useless @inheritdoc | 3. Closing semicolon |
| --- | --- | --- | --- |
| @leofeyer | 👍 | 👍 | 👍 |
| @bytehead | 👍 | 👍 | 👎 |
| @ausi | - | - | - |
| @Toflar | 👍 | 👍 | 👎 |
| @aschempp | 👍 | 👍 | 👎 |
| @fritzmg  | - | 👍 | 👎 |
| @m-vo  | 👎 | 👍 | 👍 |

### CODE REVIEW

**Comment by bytehead** [comment]
Why this replacement?

**Comment by leofeyer** [comment]
My goal is to completely automate CS fixes, so I don't have to do it everytime someone creates a PR. The new package combines sniffs from PHP_CodeSniffer and fixers from PHP-CS-Fixer and is able to detect and fix a lot more than the old package. 💪

**Comment by bytehead** [comment]
I personally don't like the CS introduced in 8494b87 (Enable the multi-line whitespace before semicolon fixer).

**Comment by fritzmg** [comment]
d8ec68f 👍 finally, those have been bothering me for a while now 😁 

I agree with @bytehead though. Isn't having the semicolon in the next line (at the beginning) more common with this coding style?

**Comment by m-vo** [comment]
> Motivation: generic type hints are newer than array type hints and are meant to replace them.

But they are still not recognized by phpstorm. Their reasoning (was): As long as it's not finally in the standard, we are not going to implement it. The only available [generic types plugin (beta)](https://github.com/Haehnchen/idea-php-generics-plugin) doesn't support this syntax either.

**Comment by m-vo** [comment]
To me having semicolons on the same line is more readable. This seems to be rather a personal thing. :smile:

**Comment by bytehead** [comment]
> This seems to be rather a personal thing. 

It totally is a personal thing. 

Another perspective: it is entirely for convenience so you can easily add another method call to the chain without having to move the semicolon to the (new) last method call.

**Comment by leofeyer** [comment]
> you can easily add another method call to the chain without having to move the semicolon to the (new) last method call.

That is more or less the only pro argument I could come up with. 😄

**Comment by bytehead** [comment]
It's the same as trailing commas for arrays 😉

**Comment by m-vo** [comment]
Besides that altering arrays is way more common than dealing with fluent interfaces (or return-type-independent additions to call chains). :smiley:

**Comment by leofeyer** [comment]
Also, a stand-alone semicolon looks weird to me.

```php
class FooBarTest
{
    public function testFooBar(): void
    {
        $foo = $this->createMock(FooBar::class);
        $foo
            ->expects($this->once())
            ->method('foo')
            ->willReturn('foo')
        ;

        $foo
            ->expects($this->once())
            ->method('bar')
            ->willReturn('bar')
        ; // <-- What are you doing here all by yourself? Shall I call your Mum? 😂 
    }
}
```

**Comment by fritzmg** [comment]
Well it signifies at a glance where the object method calls of `$foo` end, just like with `if () {` & `}` ;).

You could also write

```php
if ($moo) {
   $something = $this->sometingElse();
   $anotherSomethign = $foo; }
```

but you wouldn't do that, would you?

**Comment by leofeyer** [comment]
> Well it signifies at a glance where the object method calls of `$foo` end

I used to think this way, too, however there are plenty of exceptions to this rule already.

```php
switch ($val) {
    case 1:
        return 'foo';
        break:

    default:
        return 'bar';
}
```

```php
public function foo($document): bool
{
    $isDateTime = isset($document['object'])
        && $document['object'] instanceof UTCDateTime;

    if ($isDateTime) {
        // do something
    }
}
```

```php
if (isset($document['object'])
    && $document['object'] instanceof UTCDateTime) {
    // do something
}
```

**Comment by leofeyer** [comment]
Since this is a matter of personal preference, I guess the best thing we can do is to cast votes. I have therefore added a table in my initial post.

**Comment by Toflar** [comment]
1. Generic type hints: 👍 
2. Useless @inheritdoc: 👍 
3. Closing semicolon: 👎 

There's actually a reason for the `;` on its own line. It's the same reason as trailing `,` in array elements and also the reason why trailing `,` support in function calls was introduced in PHP 7.3: it doesn't look pretty but it allows appending new elements quickly and when adding a new argument/element, you only see one changed line in the diff instead of two.

**Comment by bytehead** [comment]
I'm 👍 for the generic type hints as well.

**Comment by aschempp** [comment]
👍👍👎

The closing semicolon is obvious to me. Closing brackets of functions and if-conditions belong to new lines as well.

**Review by bytehead — APPROVED** [review]

**Comment by leofeyer** [comment]
Since the semicolon changes have already been declined, I have reverted them in 8fd4797381122b982e9c0006b12e32503c40a346.

**Review by fritzmg — APPROVED** [review]

**Review by Toflar — APPROVED** [review]
I've gone through most of the changes and they all look good to me 👍 Nice work!

**Pull request merged**
