### PR TITLE
Change the default value for tl_layout.viewport

### LINKED ISSUE #4436: Set default Viewport-tag
### Description

https://docs.contao.org/manual/en/layout/theme-manager/manage-page-layouts/#expert-settings

The FE output
`<meta name="viewport" content="width=device-width,initial-scale=1.0">`
currently only occurs when

- responsive.css is selected or
- the "Viewport-tag" entry is set manually

It would be easier & clearer if the "viewport-tag" entry is set by default with: 
`width=device-width, initial-scale=1.0`

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #4436

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Review by ausi — APPROVED** [review]

**Comment by aschempp** [comment]
Wouldn't `shrink-to-fit=no` cause any page that is **not** response to be basically inaccessible on mobile?

**Comment by fritzmg** [comment]
I think you are confusing this with `user-scalable=no`.

**Comment by aschempp** [comment]
no, `user-scalable` means a user cannot zoom in our out of the viewport. If I open a non-responsive website on a mobile, I will get a "zoomed out" view of everything on the page (because it will "shrink to fit" the view). I would assume this is no longer the case?

**Comment by fritzmg** [comment]
> If I open a non-responsive website on a mobile, I will get a "zoomed out" view of everything on the page

If you have a non-responsive website, then you will need to adjust the viewport in any case, because then even `width=device-width,initial-scale=1.0` will be wrong.

**Pull request merged**
