### PR TITLE
Check page no search setting

### PR DESCRIPTION
**Pull request by tsarma**
As discussed, and suggested by @Toflar. This creates a callback on the `noSearch` field to remove indexes when it's checked. (https://github.com/contao/contao/pull/3766)
But for a unit test, I don't have any idea, how to write one!

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
Instead of adding a new class, I would suggest to add the additional callback to the existing class, just below https://github.com/contao/contao/blob/4.x/core-bundle/src/EventListener/DataContainer/PageUrlListener.php#L81-L93 or thelike. For the unit test, maybe you can also copy the existing one and adjust?

Regarding the code in this implementation, you should check `$value` and not `$dc->activeRecord` and I don't see why you would purge anything that is not type `regular`?

**Comment by tsarma** [comment]
> Instead of adding a new class, I would suggest to add the additional callback to the existing class.

Hi @aschempp, there is no such class `PageUrlListener` in the branch `4.9`.
Regarding the code, I'll check against `$value`instead of `$dc->activeRecord` and not `regular` page check was there just in case, if someone changes some regular page, which might already be in the index, into some other type, say extrenal url.

**Comment by aschempp** [comment]
Hmm, I guess we can/should only "fix" that for Contao 4.12 then. I assume purging the search if the alias changes is also not implemented in 4.9?

**Comment by aschempp** [comment]
Closed in favour of https://github.com/contao/contao/pull/3839

**Pull request closed without merging**
