### PR TITLE
Correcting polish translation - branch 4.10

### PR DESCRIPTION
**Pull request by qbadev**
General correction of polish translation. Mainly misspelings, but also punctation and factual corrections.
It was a rebase using branch 4.9 PR

### CODE REVIEW

**Comment by aschempp** [comment]
Is there a reason you're not using Transifex to do this?

**Comment by qzminski** [comment]
@aschempp the discussion on that was already here https://github.com/contao/contao/pull/2242 but no real conclusion in fact.

**Comment by qbadev** [comment]
@aschempp it was because I finished translation before I got knew that there was Transifex. Leo than took translation and imported it into Transfiex, reverse way.

**Comment by leofeyer** [comment]
I have pushed the changes to Transifex (Contao 4.11).

**Pull request closed without merging**
