### PR TITLE
Add a conflict for PhpStan 0.12.12

### PR DESCRIPTION
**Pull request by leofeyer**
This will fix the CI tests so we can continue to merge issues. We will have to analyze the underlying problem at some point though.

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Comment by ondrejmirtes** [comment]
What's the problem with PHPStan?

**Comment by leofeyer** [comment]
Actually, we don't even know if it is a PhpStan problem. 😄 We are currently having a code sprint and we cannot merge issues with the CI pipeline failing, therefore we have added the conflict as intermediate solution so we do not have to spend time analyzing the actual problem.

This is the error message:

```
 ------ ---------------------------------------------------------------------- 
  Line   src/Controller/BackendCsvImportController.php                         
 ------ ---------------------------------------------------------------------- 
         Internal error: Warning: Use of undefined constant TL_MODE - assumed  
         'TL_MODE' (this will throw an Error in a future version of PHP)       
         Run PHPStan with --debug option and post the stack trace to:          
         https://github.com/phpstan/phpstan/issues/new                         
 ------ ---------------------------------------------------------------------- 
```

The code base defines the `TL_MODE` constant, however, the constant is not used in the `BackendCsvImportController.php` file. That is probably why the line number is empty. 🤷‍♂

**Comment by ondrejmirtes** [comment]
Interesting! You should add all constant definitions to a file and put it to `parameters.bootstrap` in your phpstan.neon. Otherwise PHPStan cannot see those constants.

**Comment by leofeyer** [comment]
What is also interesting is that the error does not occur on my local system when running PhpStan with the `--debug` flag. Could this be a cache problem?

**Comment by ondrejmirtes** [comment]
No idea. It would be best to find out where the constant is actually used.

**Comment by leofeyer** [comment]
Any idea why the issue does not occur in debug mode?

**Comment by ondrejmirtes** [comment]
It might do something with different order of analysed files thanks to the parallel mode.

Anyway, doesn't make sense to investigate it unless you follow my advice from https://github.com/contao/contao/pull/1451#issuecomment-593372331 - you're definitely missing this part and it might be just a coincidence that it sometimes works.

**Comment by leofeyer** [comment]
I followed your advice (see https://github.com/contao/phpstan/commit/c1dafe0975899353f80b35069b1550558e60ae7d). I just wanted to understand why it suddenly stopped working. But "parallel mode" is already the answer to that. 😄

**Pull request merged**
