### PR TITLE
Hash the autologin token in the database

### PR DESCRIPTION
**Pull request by leofeyer**
This PR implements contao/core#8888 for Contao 4.6. Thanks to our database token provider, the implementation was not too hard. 😄

### CODE REVIEW

**Comment by aschempp** [comment]
I'm not sure this is the correct approach. You are hashing the `series` which is basically the username, but we are not hasing the `token` (which is kindof the *password*).

**Comment by leofeyer** [comment]
The `series` is what is in the cookie, isn't it?

**Comment by aschempp** [comment]
Both are in the cookie. Series is staying consistent across logins, token is updated on every successful authentication. This way it can be detected if the token of a series has been used, and therefore a cookie has been used twice.

**Comment by leofeyer** [comment]
You are right, we have to hash both. I will update the PR.

**Comment by leofeyer** [comment]
However, this does not work, because we need the unhashed token here:

https://github.com/contao/contao/blob/926709cd4a0a5f7b7d4e677789a3b8ea79e89a01/core-bundle/src/Security/Authentication/RememberMe/DatabaseTokenProvider.php#L61

So we also would have to adjust Symfony [here](https://github.com/symfony/symfony/blob/4.1/src/Symfony/Component/Security/Http/RememberMe/PersistentTokenBasedRememberMeServices.php#L69).

**Comment by leofeyer** [comment]
So in a first step, we could hash the series, which already prevents the attack. Once symfony/symfony#27910 has been merged, we can also hash the value, however, given that this is a BC break, it can only be implemented in Symfony 5.

@contao/developers What do you think?

**Comment by aschempp** [comment]
I think it can be changed in Symfony 4, but I agree we could just hash the series in our implementation to practically prevent the attach.

**Pull request merged**
