### PR TITLE
Fixed cutting off the descenders in backend breadcrumb and text logo overlap in mobile header.

### PR DESCRIPTION
**Pull request by ghost**
I changed the main.css of the flexible theme to avoid cutting off the descenders in the backend breadcrumb.

Before
image

After
image

### CODE REVIEW

**Comment by fritzmg** [comment]
Issue: #2686

**Comment by bohnmedia** [comment]
It seems there is another problem with the contao header in the current main.css in the repository I didnt see on my first check.

image

I am not sure, what to do now.

**Comment by bohnmedia** [comment]
The problem came with changes on "#header h1 a" in the "main.css" in this commit.

https://github.com/contao/contao/commit/b730ac07ddb14fde79c2bbcbdb64bedb0036c91b#diff-725dfe6721aaccd983e9436b6408927acc163e02cc376e6b3aa2bead73eccb7b

**Comment by bohnmedia** [comment]
Fixed both now.

**Comment by richardhj** [comment]
It should be targeted 4.9, I guess.

**Comment by bohnmedia** [comment]
I'll create a pull request from 4.9.

**Comment by m-vo** [comment]
Why not reuse this one? 

`git rebase --onto 4.9 4.x your/branch/name` + `git push -f your/origin`.

**Comment by bohnmedia** [comment]
There were some other changes in 4.x that caused problems in the backend header. I thought it was better to make a clean start from 4.9.

New Pull Request: https://github.com/contao/contao/pull/2751

**Pull request closed without merging**
