### PR TITLE
Automatically disable reverse proxy if request has surrogate capability

### PR DESCRIPTION
**Pull request by Toflar**
This would automatically disable the Symfony HttpCache if the request already has surrogate capability. One has to configure this anyway for Symfony to send ESI requests so there's no need for yet another variable.

If you want to have e.g. Varnish render the ESI tags, you have to add `Surrogate-Capability: ESI/1.0` to the request before it's passed on to Symfony,[ otherwise it will not understand that there's a proxy in front of it that does understand ESI](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpCache/AbstractSurrogate.php#L54) and thus it will never render `<esi>` tags in the final output.
So you already have to configure your proxy to provide this information. There's no need to set yet another environment variable to tell Contao to disable `HttpCache`. We can use the same information here 😄 
/cc @aschempp

### CODE REVIEW

**Comment by aschempp** [comment]
What about the existing `$_SERVER['DISABLE_HTTP_CACHE']` flag?

**Comment by Toflar** [comment]
Removed because not needed as explained?

**Comment by leofeyer** [comment]
I like the idea, especially since `DISABLE_HTTP_CACHE` is something we came up with ourselves.

**Comment by aschempp** [comment]
FYI @Toflar contrary to our discussion, this is already present in Contao 4.6:
https://github.com/contao/contao/blob/4.6.6/manager-bundle/src/Resources/skeleton/web/app.php#L46

**Comment by leofeyer** [comment]
@aschempp Has your question been answered? I would merge this then.

**Comment by aschempp** [comment]
I like the concept, but isnt it a BC break if the constant is no longer supported?

**Comment by Toflar** [comment]
It is not. ESI support is required for Contao to work properly (e.g. for insert tags). So you have to also add ‚HTTP_SURROGATE_CAPABILITY=ESI/1.0‘ to the request anyway, otherwise it would have never generated any ESI tags. So until now you had to set both amyway.

**Comment by leofeyer** [comment]
> but isnt it a BC break if the constant is no longer supported?

I'm not sure. `DISABLE_HTTP_CACHE` is part of the Contao Manager API but as far as I can see, it is not currently used, is it?

**Comment by aschempp** [comment]
> `DISABLE_HTTP_CACHE?  is part of the Contao Manager API but as far as I can see, it is not currently used, is it?

Not necessarily, someone could set that in `.env`. But I guess we can get rid of it …

**Comment by leofeyer** [comment]
@Toflar I have replaced `new ContaoCache()` with `$kernel->getHttpCache()`. Please review the changes.

**Comment by Toflar** [comment]
Yeah this changed 20 days ago so this is fine, thx!

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
