### PR TITLE
Add helper function array_insert_before

### PR DESCRIPTION
**Pull request by Exotelis**
With this function you can add modules in front of specific module type

### CODE REVIEW

**Comment by leofeyer** [comment]
Thank you for your contribution @Exotelis. The `functions.php` file  is part of the old Contao 3 framework, therefore we will not add new features to it. However, we could discuss moving the array functions into an `ArrayUtil` helper class. @contao/developers WDYT?

**Comment by m-vo** [comment]
This can probably be done in a one-liner though (ommited check for array):

```PHP
// array_insert_before(&$array, $key, $newValue)
array_splice($array, array_search($key, array_keys($array)), 0, $newValue);
```

Not sure if this is worth a helper function.

**Comment by Toflar** [comment]
Should we really introduce yet another utility class if there are billions of array packages out there, tested and ready to be used?

**Comment by leofeyer** [comment]
As discussed in Mumble on March 7th, we do not want to add new methods to the deprecated `functions.php` file and we do not want to move the array functions into an `ArrayUtil` class, either, because we cannot foresee if we will need the functions in Contao 5.

**Pull request closed without merging**
