### PR TITLE
Drop useless framework initialization

### PR DESCRIPTION
**Pull request by m-vo**
/cc @ausi

### CODE REVIEW

**Review by bytehead — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Are you sure that the initialization is useless? The method gets a `Contao\Template` object which likely does not work without the Contao 3 framework.

**Comment by fritzmg** [comment]
I think the idea is that the `getResponse` method gets object instances of legacy classes and thus the framework must be initialized already beforehand.

**Review by ausi — APPROVED** [review]

**Comment by leofeyer** [comment]
Sounds like a "don‘t rely on your dependencies‘ dependencies" situation. 🤷‍♂️

**Comment by fritzmg** [comment]
But then we would also need to inject and initialize the ContaoFramework in every Hook that uses any legacy class - which we currently do not do.

**Comment by m-vo** [comment]
I don't think a method is responsible for initializing the arguments, the caller is. But up to you. In Contao 5 things will be a bit different anyway.

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
