### PR TITLE
Add removal of user agent body class to UPGRADE.md

### PR DESCRIPTION
**Pull request by fritzmg**
So far this change was only documented in https://github.com/contao/contao/pull/482

### CODE REVIEW

**Comment by Toflar** [comment]
I think we should slip in a word about "feature detection", wdyt?

**Comment by fritzmg** [comment]
Hm, may be simply
```
Adjust your CSS or JavaScript to use feature detection instead.
```
?

// although technically this would be incorrect, since you don't need feature detection to distinguish between certain difference in styling behavior between browsers.

**Comment by Toflar** [comment]
Yeah I'm just lacking the info on "why has it been removed?", you know. So some nice way to tell the people that relying on the user agent is nonsense anyway in most cases :)

**Comment by leofeyer** [comment]
Besides the fact that there is no BC promise for templates, is this change really a BC break that needs to be documented in the `UPGRADE.md` file?

**Comment by Toflar** [comment]
It's not a BC break but it's a nice hint anyway.

**Comment by leofeyer** [comment]
Yes, however, "nice hints" should go into the release announcement and not into the `UPGRADE.md` file. Developers need to know about API changes, renamed resources and other stuff which could break their code. We should not clutter up the file with nice hints, which have little or no relevance for the reader.

**Comment by fritzmg** [comment]
> Besides the fact that there is no BC promise for templates, is this change really a BC break that needs to be documented in the `UPGRADE.md` file?

Other [template content changes](https://github.com/contao/contao/blob/master/UPGRADE.md#template-changes) are documented there too.

**Comment by fritzmg** [comment]
> Yes, however, "nice hints" should go into the release announcement and not into the `UPGRADE.md` file. Developers need to know about API changes, renamed resources and other stuff, which could break their code. We should not clutter up the file with nice hints, which have little or no relevance for the reader IMHO.

But then we need to remove the following:

* https://github.com/contao/contao/blob/master/UPGRADE.md#template-changes
* https://github.com/contao/contao/blob/master/UPGRADE.md#meta-keywords
* https://github.com/contao/contao/blob/master/UPGRADE.md#template-changes-1
* https://github.com/contao/contao/blob/master/UPGRADE.md#markup-changes
* https://github.com/contao/contao/blob/master/UPGRADE.md#css-class-changes

If we don't remove those, then we should definitely add the notice about the body class, since it is a fairly big change.

**Comment by leofeyer** [comment]
Hm, you are right. There are two "template changes" sections in the document already. Then I guess we can add the CSS class changes as well. 🤷‍♂

**Comment by fritzmg** [comment]
> Yeah I'm just lacking the info on "why has it been removed?", you know. So some nice way to tell the people that relying on the user agent is nonsense anyway in most cases :)

Yeah... I don't have any idea on the wording for that though 😁

**Comment by leofeyer** [comment]
@fritzmg Can you rebase this PR onto the current master branch please?

**Comment by fritzmg** [comment]
> @fritzmg Can you rebase this PR onto the current master branch please?

Done (I think...)

**Review by leofeyer — CHANGES_REQUESTED** [review]
The paragraph should go into the "Version 4.* to 4.8" section, shouldn't it?

**Review by leofeyer — APPROVED** [review]

**Comment by fritzmg** [comment]
> The paragraph should go into the "Version 4.* to 4.8" section, shouldn't it?

Well, it also affects people upgrading from Contao 3.5.40 to 4.8, not just from 4.* to 4.8. Isn't this what the 

### Version 3.* to 4.0

section is for?

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Comment by leofeyer** [comment]
> Isn't this what the Version 3.* to 4.0 section is for?

No. If someone updates from 3.* to 4.0, they are not affected, because the user agent is still present.

**Pull request merged**
