### PR TITLE
Remove replaces

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Comment by aschempp** [comment]
Any description why?

**Comment by Toflar** [comment]
Because this makes contao/contao to be treated as contao/core which all bundles conflict with :D

**Comment by aschempp** [comment]
Hehe, I thought about this too but wanted to test it first (which you apparently did).

**Comment by aschempp** [comment]
However, then this should also conflict with contao/core.

**Comment by leofeyer** [comment]
Then the solution is wrong, because the meta package does replace `contao/core`. We should rather remove the "conflict" entries from the bundles, shouldn't we?

**Comment by Toflar** [comment]
I don't get why any of those is replacing `contao/core` anyway. `contao/core` never existed, it's just something @discordier registered for their integration to work but this meta package is not replacing it. It's a complete new version...

**Comment by aschempp** [comment]
I think *conflict* would work very well, it would disallow to install both which is exactly what we want.

**Comment by leofeyer** [comment]
Yes, but we cannot conflict with `contao/core` if `contao/contao` actually replaces it. So either we are replacing it (which we technically are **not**, because we do not provide the same API) or we conflict with it.

If I look at it this way, the PR is just fine :)

**Comment by aschempp** [comment]
I think both `contao/contao` and `contao/core-bundle` should conflict with `contao/core`. Its not a 1:1 replacement, its a new version that will conflict with the old version.

**Comment by leofeyer** [comment]
This is exactly what I just said :)

**Pull request merged**
