### PR TITLE
Do not try to add an image if the source is empty

### PR DESCRIPTION
**Pull request by leofeyer**
@m-vo This will prevent an exception if `$this->singleSRC` is empty.

### CODE REVIEW

**Comment by fritzmg** [comment]
afaik this should not be necessary when using `buildIfResourceExists`.

**Comment by leofeyer** [comment]
Ok, then we must ensure that the method accepts and handles `null`:

```
Contao\CoreBundle\Image\Studio\FigureBuilder::fromPath(): Argument #1 ($path) must be of type string, null given, called in …/vendor/contao/contao/core-bundle/src/Image/Studio/FigureBuilder.php on line 306
```

@m-vo /cc

**Comment by fritzmg** [comment]
I am not sure now actually. @m-vo what do you think? How lenient should the FigureBuilder be? We could change it to 

```php
        return $this->fromPath((string) $identifier);
```

in `from()` and may be add

```php
        if (empty($identifier)) {
            $this->lastException = new InvalidResourceException("Given path is empty.");

            return $this;
        }
```

at the beginning of `fromPath()`, which would cover this case.

**Comment by m-vo** [comment]
Ah, now I see. IMHO we should not weaken the type constraints for any of the more specific "from methods" (like `fromPath(string $path)`) but we could allow `null` in the generic `from(mixed $resource)`.

**Comment by leofeyer** [comment]
Allowing `null` in the `from()` method sounds reasonable, however, we also have to handle the value. The method currently returns `int|string|FilesModel|ImageInterface` and none of these types makes sense for `null`, does it?

**Comment by m-vo** [comment]
Here is how it could look: #3073

**Comment by m-vo** [comment]
> The method currently returns int|string|FilesModel|ImageInterface and none of these types makes sense for null, does it?

They are all fluent interface methods that return `self`. I think you might have confused it with the input argument?

**Comment by leofeyer** [comment]
See #3073

**Pull request closed without merging**
