### PR TITLE
Allow multiple label callbacks

### LINKED ISSUE #4759: Improve label generation in DataContainer list
### Description

While working on #4682 I wanted to add one more information to the page label (the selected feed format) and keep everything else exactly as is:

Since there can only be one `label_callback`, I have to overwrite the Core label listener, copy its implementation and keep it updated. I have no suggestion, but just wanted to leave a note. Maybe somebody has an idea on how to solve this in the future?

### PR DESCRIPTION
**Pull request by leofeyer**
Implements #4759

However, there are a few things to discuss:

1. Do we want to deprecate passing non-array values as currently implemented, or do we want to support both?
2. Should we generally allow multiple callbacks for all "singletons"?

https://github.com/contao/contao/blob/aec63b668f40584cd242dae658b02ec4badd6555/core-bundle/src/EventListener/DataContainerCallbackListener.php#L20-L32

### CODE REVIEW

**Comment by leofeyer** [comment]
As discussed in the Contao call, allowing multiple callbacks only makes sense if both the argument and the return value is a string. The current singletons cannot be chained, because they e.g. receive an array as argument and return a string.

**Comment by aschempp** [comment]
which means this PR should be closed, right?

**Comment by ausi** [comment]
> which means this PR should be closed, right?

No, this PR allows for multiple `label_callback`s, and they are chainable because `$label` gets passed to the callback and the return value is used to set `$label`.

**Review by ausi — DISMISSED** [review]
`header_callback` and `group_callback` can also be chained I think, so we might change them to multiple too?

**Comment by leofeyer** [comment]
* `group_callback` added in 843d6f4016f463a96581e814e3d7ac7aa3a823ce
* `header_callback` added in c5aece7ab66d3aa4df1f30b5d832263f3ae04fd1

**Review by ausi — APPROVED** [review]

**Pull request merged**
