### PR TITLE
Remove the first/last/even/odd/col_/row_ CSS classes

### LINKED ISSUE #2868: Remove the "first", "even", "odd" and "last" CSS classes
**Affected version(s)**

I think that's been forever.

**Description**

The generated classes of news_list items are mixed up
image

Not a big deal - i just wodered why i was getting strange results while using css like such:
```css
mod_newslist>.even { }
mod_newslist>.odd { }
/* vs */
mod_newslist>:nth-child(even) { }
mod_newslist>:nth-child(odd) { }
```
One/first is an odd number but i think somebody startet counting from zero 😂
FunFact: ```:nth-child(even/odd)``` behaves like ```.even``` if your mod_newslist has a headline.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #2868

### CODE REVIEW

**Comment by m-vo** [comment]
Is this a duplicate of https://github.com/contao/contao/pull/4178?

Also: Do we really want to change this for the old modules? We won't have any of these classes in the new content elements as fragment controllers and we want people to migrate to these anyway. Maybe we should keep the old implementation as is and simply deprecate it.

**Comment by leofeyer** [comment]
No, the classes are already deprecated in Contao 4, so let‘s remove them now.

**Comment by leofeyer** [comment]
> Is this a duplicate of #4178?

No, rather a more complete version. See https://github.com/contao/contao/pull/4178#pullrequestreview-948253198.

**Comment by leofeyer** [comment]
Closed in favor of #4178.

**Pull request closed without merging**
