### PR TITLE
Hide the member widget if searching protected sites is disabled

### LINKED ISSUE #1280: Crawler: Anzeige Frontend-Mitglied nur bei aktivierter Suche von geschützten Seiten
**Affected version(s)**
C 4.9.x-dev

**Description**
Im Bereich Systemwartung sollte beim "Crawler" die Auswahlmöglichkeit eines Frontend-Mitglieds nur angezeigt werden, wenn die Suche für geschützte Seiten über die config.yml explizit aktiviert wurde.

Aktuell geht man davon aus, dass der Crawler nach der Auswahl eines Frontend Mitglieds auch geschützte Seiten indexiert, was aber nicht stimmt, da die Indexierung von geschützten Seiten standardmäßig deaktiviert ist.

Laut @Toflar kann man die Indexierung über die config.yml mittels

`contao.search.index_protected: true`

aktivieren und das funktioniert auch bestens, siehe auch:
https://contao.slack.com/archives/CK4J0KNDB/p1580798092210200

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #1280

@contao/developers Should we disable indexing protected pages by default?

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Comment by fritzmg** [comment]
> @contao/developers Should we disable indexing protected pages by default?

Isn't it already? At least that's how it used to be.

**Review by bytehead — APPROVED** [review]

**Comment by Toflar** [comment]
> @contao/developers Should we disable indexing protected pages by default?

It is disabled by default.

**Comment by leofeyer** [comment]
I see. Sorry 🙄

**Comment by aschempp** [comment]
Shouldn't we show a hint if indexing protected pages is disabled?

**Comment by Toflar** [comment]
I don't think we should. There are so many configuration options, we'd need loads of hints everywhere to tell the users what they could enable. That's just something that belongs into the docs.

**Pull request merged**
