### PR TITLE
Send the correct content type for SVG favicons

### PR DESCRIPTION
**Pull request by Toflar**
| Q                | A
| -----------------| ---
| Fixed issues     | https://github.com/contao/contao/pull/1551

### CODE REVIEW

**Comment by fritzmg** [comment]
Hm, what happens if you already have

```
AddType image/x-icon ico
```

in your `.htaccess` 🤔 . iirc this would override any headers set by PHP? At least in some environments.

**Comment by Toflar** [comment]
Yeah, then you have misconfigured your server. Simple :)

**Comment by fritzmg** [comment]
In what way? This seems pretty standard to me. I want to configure my server to output the `Content-Type: image/x-icon` if `files/foo.ico` is requested.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
`AddType image/x-icon ico` is quite common indeed, however, since the specs allow using other MIME types than `image/x-icon` and the browsers support it, it is no longer correct to add a fixed type for `.ico` files. 🤷‍♂

**Comment by fritzmg** [comment]
> `AddType image/x-icon ico` is quite common indeed, however, since the specs allow using other MIME types than `image/x-icon` and the browsers support it, it is no longer correct to add a fixed type for `.ico` files. 🤷‍♂

What's the correct solution here then? Shouldn't the web server respond with a `Content-Type`?

**Comment by Toflar** [comment]
I don't know what you guys are even discussing. If that's your `.htaccess` then that's it. Nothing we can do about it so why do we even discuss that?

**Comment by fritzmg** [comment]
@Toflar as already said, having `AddType image/x-icon ico` or `AddType image/x-icon cur ico` should be a pretty common occurrence, even in the general server configuration, not just each individual's `.htaccess` (@leofeyer I think Hostingwerk uses it too?). It is also part of the [html5-boilerplate](https://github.com/h5bp/html5-boilerplate/) and was part of Contao 3's `.htaccess`. I am merely wondering if this will lead to problems, if someone uses this feature in Contao 4.9 and uses an SVG instead of an ICO file. And if it does lead to problems, I am wondering what the solution is.

**Comment by Toflar** [comment]
You will get the wrong HTTP content type header which means the SVG icon is just not going to work. Period.
So fix your server config if you want to benefit from using svg icons.
One last time: There's **nothing** we can do about that.

**Comment by fritzmg** [comment]
> So fix your server config

But how? What is the solution to this?

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Comment by ausi** [comment]
@fritzmg I was not able to reproduce that. `AddType` shouldn’t overwrite headers set by PHP I think.

**Comment by fritzmg** [comment]
@ausi thx for testing - though were you able to check if there is any difference between running PHP either via `mod_php` or via PHP-FPM/FastCGI? As far as I know, response headers for requests that were processed by an external application via (Fast)CGI (PHP in this case) cannot be altered using Apache directives, but it is possible with `mod_php`. But then that would be an edge case anyway …

**Comment by Toflar** [comment]
> `AddType` shouldn’t overwrite headers set by PHP I think.

It will, depending on the SAPI probably. Otherise, how do you explain https://github.com/contao/contao/issues/1433? :)

**Comment by ausi** [comment]
> Otherise, how do you explain #1433? :)

`ExpiresByType` is different to `AddType` AFAIK.

**Comment by Toflar** [comment]
Yeah, mixed that up, sorry.

**Comment by ausi** [comment]
> were you able to check if there is any difference between running PHP either via `mod_php` or via PHP-FPM/FastCGI?

I was not able to reproduce that in `mod_php` either.

**Pull request merged**
