### PR TITLE
Deprecate the `MergeHttpHeadersListener` class

### PR DESCRIPTION
**Pull request by leofeyer**
It seems we forgot to remove this in Contao 5.

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]
I agree with those changes for several reasons:

- This listener adds a considerable overhead, especially when having lots of content elements/front end modules and running through the entire request stack over and over again. It amounts to 10% of a profile of a request of mine.
- It was a BC layer for `session_start()` and `header()` to ease migration between Contao 3 and 4 and should've been removed in `5.0`. 
- It was impossible for us to throw deprecation notices because we could not know where `header()` and `session_start()` were used. We could've added one in `fetchHttpHeaders()` but it could've likely been ignored because a message like `something in your code might use header() or session_start()` would've been only partially helpful. 
- I try to always balance potential damage vs. potential gains. And here, to me personally, the advantages would well outweigh the disadvantages for the absolute majority of our users.

**Comment by fritzmg** [comment]
Regardless of the usefulness of a particular deprecation message, it is a BC break. You cannot make the argument that we cannot deprecate something just because the message would not be useful. That might apply to other already existing deprecation messages.

**Comment by leofeyer** [comment]
Related: #6430

**Review by aschempp — CHANGES_REQUESTED** [review]
as discussed, we should only remove this in Contao 6 (but optimize the behaviour in Contao 4/5)

**Comment by leofeyer** [comment]
As discussed, I have reverted the changes and deprecated the listener instead.

**Review by Toflar — APPROVED** [review]

**Pull request merged**
