### PR TITLE
Remove remaining deprecations

### LINKED ISSUE #3936: Remaining deprecations (not security related)
### Affected version(s)

4.13

### Description

The following non security related deprecations are still present and could be fixed:

```
  3x: Since symfony/framework-bundle 5.3: Not setting the "framework.session.storage_factory_id" configuration option is deprecated, it will default to "session.storage.factory.native" and will replace the "framework.session.storage_id" configuration option in version 6.0.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
    1x in RoutingMigrationTest::testShouldRun from Contao\CoreBundle\Tests\Functional\Migration
    1x in StatementTest::setUp from Contao\CoreBundle\Tests\Functional
```

```
  3x: Since symfony/framework-bundle 5.3: The "session" service and "SessionInterface" alias are deprecated, use "$requestStack->getSession()" instead. It is being referenced by the "contao.security.backend_user_provider" service.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
    1x in RoutingMigrationTest::testShouldRun from Contao\CoreBundle\Tests\Functional\Migration
    1x in StatementTest::setUp from Contao\CoreBundle\Tests\Functional
```

```
  3x: Since contao/core-bundle 4.13: Using the "Contao\CoreBundle\Cron\Cron" service ID has been deprecated and will no longer work in Contao 5.0. Please use "contao.cron" instead. It is being referenced by the ".service_locator.8OmPk8a" service.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
    1x in RoutingMigrationTest::testShouldRun from Contao\CoreBundle\Tests\Functional\Migration
    1x in StatementTest::setUp from Contao\CoreBundle\Tests\Functional
```

```
  3x: Since contao/core-bundle 4.13: Using the "Contao\CoreBundle\Csrf\ContaoCsrfTokenManager" service ID has been deprecated and will no longer work in Contao 5.0. Please use "contao.csrf.token_manager" instead. It is being referenced by the ".service_locator.w0O2Xp9" service.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
    1x in RoutingMigrationTest::testShouldRun from Contao\CoreBundle\Tests\Functional\Migration
    1x in StatementTest::setUp from Contao\CoreBundle\Tests\Functional
```

```
  1x: The "Symfony\Bridge\Doctrine\Logger\DbalLogger" class implements "Doctrine\DBAL\Logging\SQLLogger" that is deprecated Use {@see \Doctrine\DBAL\Logging\Middleware} or implement {@see \Doctrine\DBAL\Driver\Middleware} instead.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
```

### PR DESCRIPTION
**Pull request by bytehead**
Fixes #3936 

**Deprecations**: 
- [x] Not setting the "framework.session.storage_factory_id" - https://github.com/contao/contao/pull/3938#issuecomment-1013917398
- [ ] The "session" service and "SessionInterface" - https://github.com/contao/contao/pull/3938#issuecomment-1013918081
- [x] Contao\CoreBundle\Cron\Cron - https://github.com/contao/contao/pull/3938#issuecomment-1013920466
- [x] Contao\CoreBundle\Csrf\ContaoCsrfTokenManager - https://github.com/contao/contao/pull/3938#issuecomment-1013924775
- [ ] Symfony\Bridge\Doctrine\Logger\DbalLogger - https://github.com/contao/contao/pull/3938#issuecomment-1013925517

### CODE REVIEW

**Comment by bytehead** [comment]
```
3x: Since symfony/framework-bundle 5.3: Not setting the "framework.session.storage_factory_id" configuration option is deprecated, it will default to "session.storage.factory.native" and will replace the "framework.session.storage_id" configuration option in version 6.0.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
    1x in RoutingMigrationTest::testShouldRun from Contao\CoreBundle\Tests\Functional\Migration
    1x in StatementTest::setUp from Contao\CoreBundle\Tests\Functional
```
Fixed in 3831f880a.

**Comment by bytehead** [comment]
```
3x: Since symfony/framework-bundle 5.3: The "session" service and "SessionInterface" alias are deprecated, use "$requestStack->getSession()" instead. It is being referenced by the "contao.security.backend_user_provider" service.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
    1x in RoutingMigrationTest::testShouldRun from Contao\CoreBundle\Tests\Functional\Migration
    1x in StatementTest::setUp from Contao\CoreBundle\Tests\Functional
```

Probably impossible to fix in 4.13, as it would be a BC break to replace `SessionInterface` by `RequestStack`: 
https://github.com/contao/contao/blob/cf2ca71c614232865301443b71c66b6a31152a38/core-bundle/src/Security/User/ContaoUserProvider.php#L32-L41

**Comment by bytehead** [comment]
```
 3x: Since contao/core-bundle 4.13: Using the "Contao\CoreBundle\Cron\Cron" service ID has been deprecated and will no longer work in Contao 5.0. Please use "contao.cron" instead. It is being referenced by the ".service_locator.8OmPk8a" service.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
    1x in RoutingMigrationTest::testShouldRun from Contao\CoreBundle\Tests\Functional\Migration
    1x in StatementTest::setUp from Contao\CoreBundle\Tests\Functional
```

~We can't deprecate the FQCN and use method injection afaik. Should we use constructor inejction instead?~

~Edit: adjusted to have an example in cd3126a70.~

Edit2: Correct fix in dc272da1c.

A bit more background to this from [Ryan](https://symfonycasts.com/screencast/symfony4-doctrine/service-subscriber#comment-4807656858):
> Now let’s talk about service subscribers :slightly_smiling_face:. By default, they work via autowiring: your getSubscribedServices method returns an array of autowiring type-hints that you want to be included in your service locator.

> If you use a interface/class that doesn’t have an autowireable alias, it won’t work.

> Your solution above (which is correct) is how you explicitly configure a service inside a service locator when it doesn’t have an autowireable alias.

**Comment by bytehead** [comment]
```
3x: Since contao/core-bundle 4.13: Using the "Contao\CoreBundle\Csrf\ContaoCsrfTokenManager" service ID has been deprecated and will no longer work in Contao 5.0. Please use "contao.csrf.token_manager" instead. It is being referenced by the ".service_locator.w0O2Xp9" service.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
    1x in RoutingMigrationTest::testShouldRun from Contao\CoreBundle\Tests\Functional\Migration
    1x in StatementTest::setUp from Contao\CoreBundle\Tests\Functional
```

~Same problem as with `Contao\CoreBundle\Cron\Cron`, see https://github.com/contao/contao/pull/3938#issuecomment-1013920466.~

Fixed in 0f9c5b0ea.

**Comment by bytehead** [comment]
```
  1x: The "Symfony\Bridge\Doctrine\Logger\DbalLogger" class implements "Doctrine\DBAL\Logging\SQLLogger" that is deprecated Use {@see \Doctrine\DBAL\Logging\Middleware} or implement {@see \Doctrine\DBAL\Driver\Middleware} instead.
    1x in DbafsTest::setUpBeforeClass from Contao\CoreBundle\Tests\Functional
```

It will be fixed by `symfony/doctrine-bridge` and/or `doctrine/doctrine-bundle`, see https://github.com/symfony/symfony/discussions/44307#discussioncomment-1709594.

**Review by aschempp — DISMISSED** [review]

**Review by m-vo — DISMISSED** [review]

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @bytehead.

**Pull request merged**
