### PR TITLE
Suggest using the contao-setup binary with @php prefix

### LINKED ISSUE #2776: Using contao-setup with different PHP versions
**Affected version(s)**

Contao 4.11

**Description**

Please see https://github.com/composer/composer/issues/9707 for the original issue. I had used the symfony binary to test different PHP environments but apparently this makes a difference. :unamused: 

Here are some ideas how we could deal with this problem until (hopefully) there is a fix or workaround in Composer:

1. Make the info message suggest `@php vendor/bin/contao-setup` instead of `contao-setup` with `/` being `\` when running on windows. 
1. Create a symlink to `contao-console` in the root directory. :see_no_evil: 
1. …?

Ideas are welcome - here as well as in the Composer issue.

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2776 
| Docs PR or issue | -

related https://github.com/contao/managed-edition/pull/57

### CODE REVIEW

**Comment by richardhj** [comment]
The branch 😉

**Comment by m-vo** [comment]
Ah.. dammit. Thanks for reminding me. Again. :smile:

**Review by fritzmg — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Comment by xchs** [comment]
It seems that this causes a problem in a local development environment on Windows (see https://community.contao.org/de/showthread.php?74042-Contao-amp-Laragon-Schritt-f%C3%BCr-Schritt-zur-lokalen-Entwicklungsumgebung-unter-Windows&p=541256&viewfull=1#post541256 )

**Comment by fritzmg** [comment]
@xchs you need to update Composer to at least version 2.0.10 and may be also delete the `vendor/bin/contao-console*` files and run `composer update` again.

**Pull request merged**
