### PR TITLE
Backport lazy services for CronJob repository

### PR DESCRIPTION
**Pull request by aschempp**
Somehow https://github.com/contao/contao/pull/4265 only made it into 4.13 even though the same problem exists in the current 4.9 version. Running `contao-console list --format=json` results in a database exception.

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by leofeyer** [comment]
Test are failing…

**Comment by aschempp** [comment]
Failing prefer-lowest tests seem unrelated

**Comment by aschempp** [comment]
hmmm… or maybe not, maybe the lower allowed does not support `!service_closure`?

**Comment by aschempp** [comment]
looks like this was fixed in Symfony 4.4.23 only (https://github.com/symfony/symfony/commit/1aa9a249fc81a68a1dfad6900305052a36935d70). Not sure if we can raise our minimum dependency of the symfony/dependency-injection component?

**Comment by fritzmg** [comment]
> Not sure if we can raise our minimum dependency of the symfony/dependency-injection component?

Why not? Currently we require `4.4.*`. Should be no issue to increase it to `~4.4.23`?

**Review by leofeyer — APPROVED** [review]

**Pull request merged**
