### PR TITLE
Update readme.md - add installation note

### PR DESCRIPTION
**Pull request by zonky2**
add installation note

### CODE REVIEW

**Comment by fritzmg** [comment]
This problem is not specific to the Newsletter Bundle - it would happen with any Contao Bundle. Also I think this should be documented elsewhere.

**Comment by zonky2** [comment]
that's correct - but there are the "sub-bundles" with their own readme... then there should be a note in the readmes about the "main readme"

**Comment by leofeyer** [comment]
> Also I think this should be documented elsewhere.

I second this.

**Comment by zonky2** [comment]
see https://contao.slack.com/archives/CK4J0KNDB/p1560698231104100

**Pull request closed without merging**
