### PR TITLE
Fix memory leaks in the "resize images" command

### PR DESCRIPTION
**Pull request by ausi**
This implements the fix for #849 as described in https://github.com/contao/contao/issues/849#issuecomment-546679544

Todo:

- [ ] Rework the console output
- [ ] Implement `--throttle` and `--time-limit`
- [ ] Update tests

### CODE REVIEW

**Comment by Toflar** [comment]
🎉 That works! We were able to resize well over 2000 images without any issue here. Memory consumption and disk usage remained at a constant level. No serious CPU usage issues noticed either.
There were two memory drops of about 1 GB but I think they were related to just two very big images that had to be resized.
So that's certainly the way to go here. I wonder, however, if we should still introduce a memory limit option. It would allow us to limit memory usage in favor of swapping to make sure we don't interfere with each other on a shared host.

**Comment by ausi** [comment]
> I wonder, however, if we should still introduce a memory limit option.

I don’t think so. Resizing a single image should always be possible, even on a shared host. Otherwise we would have seen more bug reports already for the image resizes that happen in the HTTP request.

**Comment by Toflar** [comment]
I just wonder what happens if I run this command with a concurrency of 10.
But yeah, you might be right. We may still add the memory limits later on if really required.

**Comment by leofeyer** [comment]
I am closing this in favor in #1486

**Pull request closed without merging**
