### PR TITLE
Use HTTP status code 303 instead of 307 for redirects

### PR DESCRIPTION
**Pull request by leofeyer**
See #2096

### CODE REVIEW

**Comment by fritzmg** [comment]
Why the switch back to `302` for any redirects that use `RedirectResponse` directly? Now we have a mixture of `302` and `303` (again).

**Comment by leofeyer** [comment]
We just stick to the Symfony defaults. See https://github.com/symfony/symfony/issues/10766 for the discussion.

**Comment by fritzmg** [comment]
> We just stick to the Symfony defaults.

But shouldn't we use it for `Controller::redirect` too then? Now some parts of Contao's code base return `302` and some return `303`. That does not make much sense to me, nor does it make sense to stick with `302` imho.

And the Symfony discussion is from over 6 years ago. As discussed elsewhere, browser support is not an issue any more.

**Comment by leofeyer** [comment]
The bottom line from the Symfony discussion (and https://stackoverflow.com/questions/5129076/after-a-post-should-i-do-a-302-or-a-303-redirect/5129148#5129148) is that is does not matter whether you send 302 or 303. We have updated our own methods to use `303`, Symfony has decided to stick with `302`. It still does not matter. 🤷🏻‍♂️ 

(If it really bothers you, you should create a PR to adjust the Symfony default status code.)

**Pull request merged**
