### PR TITLE
Fix compatibility with knplabs/knp-time-bundle 1.11.0

### LINKED ISSUE #1136: Fehler bei Cache Warmup während Installation
Fehlermeldung:
````
21:54:25 ERROR     [console] Error thrown while running command "--ansi cache:warmup --env=prod". Message: "Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Contao\CoreBundle\Translation\Translator given, called in /www/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.php on line 108" ["exception" => TypeError { …},"command" => "--ansi cache:warmup --env=prod","message" => "Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Contao\CoreBundle\Translation\Translator given, called in /www/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.php on line 108"]

In DateTimeFormatter.php line 17:

  Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct()
   must implement interface Symfony\Contracts\Translation\TranslatorInterface
  , instance of Contao\CoreBundle\Translation\Translator given, called in /ww
  w/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.p
  hp on line 108


cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command>

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred while executing the "cache:warmup" command: 21:54:25 ERROR     [console] Error thrown while running command "--ansi cache:warmup --env=prod". Message: "Ar
  gument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Contao\CoreBundle\Translation\
  Translator given, called in /www/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.php on line 108" ["exception" =>
  [38;5;38mTypeError { …},"command" => "--ansi cache:warmup --env=prod","message
  ;208m" => "Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Cont
  ao\CoreBundle\Translation\Translator given, called in /www/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.php on line 108"]

  In DateTimeFormatter.php line 17:

    Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct()
     must implement interface Symfony\Contracts\Translation\TranslatorInterface
    , instance of Contao\CoreBundle\Translation\Translator given, called in /ww
    w/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.p
    hp on line 108


  cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command>


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
````
Vollständige Konsolenausgabe:
````
$ php73 -d memory_limit=-1 composer create-project contao/managed-edition test-4.8/ 4.8
Installing contao/managed-edition (4.8)
  - Installing contao/managed-edition (4.8): Loading from cache
Created project in test-4.8/
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 162 installs, 0 updates, 0 removals
  - Installing ocramius/package-versions (1.5.1): Loading from cache
  - Installing contao-components/installer (1.3.1): Loading from cache
  - Installing symfony/polyfill-ctype (v1.13.1): Loading from cache
  - Installing psr/log (1.1.2): Loading from cache
  - Installing symfony/polyfill-php73 (v1.13.1): Loading from cache
  - Installing symfony/debug (v4.4.2): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.13.1): Loading from cache
  - Installing symfony/polyfill-php72 (v1.13.1): Loading from cache
  - Installing symfony/polyfill-intl-idn (v1.13.1): Loading from cache
  - Installing symfony/mime (v4.4.2): Loading from cache
  - Installing symfony/http-foundation (v4.3.9): Loading from cache
  - Installing symfony/event-dispatcher-contracts (v1.1.7): Loading from cache
  - Installing psr/container (1.0.0): Loading from cache
  - Installing symfony/event-dispatcher (v4.3.9): Loading from cache
  - Installing symfony/http-kernel (v4.3.9): Loading from cache
  - Installing symfony/service-contracts (v1.1.8): Loading from cache
  - Installing symfony/dependency-injection (v4.3.9): Loading from cache
  - Installing symfony/filesystem (v4.3.9): Loading from cache
  - Installing symfony/config (v4.3.9): Loading from cache
  - Installing symfony/routing (v4.3.9): Loading from cache
  - Installing contao/manager-plugin (2.7.1): Loading from cache
  - Installing contao/conflicts (dev-master 1ef5c8d)
  - Installing symfony/yaml (v4.3.9): Loading from cache
  - Installing psr/cache (1.0.1): Loading from cache
  - Installing patchwork/utf8 (v1.3.2): Loading from cache
  - Installing php-http/discovery (1.7.3): Loading from cache
  - Installing clue/stream-filter (v1.4.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing php-http/message-factory (v1.0.2): Loading from cache
  - Installing php-http/message (1.8.0): Loading from cache
  - Installing php-http/promise (v1.0.0): Loading from cache
  - Installing php-http/httplug (v1.1.0): Loading from cache
  - Installing symfony/options-resolver (v5.0.2): Loading from cache
  - Installing php-http/client-common (1.10.0): Loading from cache
  - Installing ralouphie/getallheaders (3.0.3): Loading from cache
  - Installing guzzlehttp/psr7 (1.6.1): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.5.2): Loading from cache
  - Installing php-http/guzzle6-adapter (v1.1.1): Loading from cache
  - Installing friendsofsymfony/http-cache (2.8.0): Loading from cache
  - Installing twig/twig (v2.12.3): Loading from cache
  - Installing true/punycode (v2.1.1): Loading from cache
  - Installing paragonie/random_compat (v9.99.99): Loading from cache
  - Installing doctrine/lexer (1.2.0): Loading from cache
  - Installing doctrine/annotations (v1.8.0): Loading from cache
  - Installing terminal42/service-annotation-bundle (1.0.0): Loading from cache
  - Installing symfony/var-dumper (v4.3.9): Loading from cache
  - Installing symfony/translation-contracts (v1.1.7): Loading from cache
  - Installing symfony/twig-bridge (v4.4.2): Loading from cache
  - Installing symfony/twig-bundle (v4.3.9): Loading from cache
  - Installing symfony/translation (v4.3.9): Loading from cache
  - Installing symfony/polyfill-iconv (v1.13.1): Loading from cache
  - Installing egulias/email-validator (2.1.13): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.2.3): Loading from cache
  - Installing symfony/swiftmailer-bundle (v3.4.0): Loading from cache
  - Installing symfony/inflector (v5.0.2): Loading from cache
  - Installing symfony/property-access (v4.4.2): Loading from cache
  - Installing symfony/security (v4.3.9): Loading from cache
  - Installing symfony/security-bundle (v4.3.9): Loading from cache
  - Installing symfony/process (v4.3.9): Loading from cache
  - Installing symfony/lock (v4.3.9): Loading from cache
  - Installing symfony/finder (v4.3.9): Loading from cache
  - Installing symfony/var-exporter (v4.4.2): Loading from cache
  - Installing symfony/cache-contracts (v1.1.7): Loading from cache
  - Installing symfony/cache (v4.3.9): Loading from cache
  - Installing symfony/framework-bundle (v4.3.9): Loading from cache
  - Installing psr/simple-cache (1.0.1): Loading from cache
  - Installing symfony/expression-language (v4.3.9): Loading from cache
  - Installing symfony/console (v4.3.9): Loading from cache
  - Installing symfony/asset (v4.3.9): Loading from cache
  - Installing symfony-cmf/routing (2.1.1): Loading from cache
  - Installing symfony-cmf/routing-bundle (2.2.0): Loading from cache
  - Installing doctrine/cache (1.10.0): Loading from cache
  - Installing beberlei/assert (v3.2.7): Loading from cache
  - Installing paragonie/constant_time_encoding (v2.3.0): Loading from cache
  - Installing spomky-labs/otphp (v9.1.4): Loading from cache
  - Installing simplepie/simplepie (1.5.4): Loading from cache
  - Installing scssphp/scssphp (1.0.6): Loading from cache
  - Installing lcobucci/jwt (3.3.1): Loading from cache
  - Installing scheb/two-factor-bundle (v4.11.1): Loading from cache
  - Installing phpunit/php-token-stream (3.1.1): Loading from cache
  - Installing phpspec/php-diff (v1.1.0): Loading from cache
  - Installing oyejorge/less.php (v1.7.0.14): Loading from cache
  - Installing nelmio/cors-bundle (1.5.6): Loading from cache
  - Installing michelf/php-markdown (1.9.0): Loading from cache
  - Installing matthiasmullie/path-converter (1.1.2): Loading from cache
  - Installing matthiasmullie/minify (1.3.62): Loading from cache
  - Installing league/uri-parser (1.4.1): Loading from cache
  - Installing league/uri-interfaces (1.1.1): Loading from cache
  - Installing league/uri-schemes (1.2.1): Loading from cache
  - Installing league/uri-hostname-parser (1.1.1): Loading from cache
  - Installing league/uri-components (1.8.2): Loading from cache
  - Installing league/uri-manipulations (1.5.0): Loading from cache
  - Installing league/uri (5.3.0)
  - Installing symfony/templating (v5.0.2): Loading from cache
  - Installing knplabs/knp-time-bundle (v1.11.0): Loading from cache
  - Installing knplabs/knp-menu (2.6.0): Loading from cache
  - Installing knplabs/knp-menu-bundle (v2.3.0): Loading from cache
  - Installing doctrine/reflection (v1.0.0): Loading from cache
  - Installing doctrine/event-manager (1.1.0): Loading from cache
  - Installing doctrine/collections (1.6.4): Loading from cache
  - Installing doctrine/persistence (1.3.3): Loading from cache
  - Installing doctrine/inflector (1.3.1): Loading from cache
  - Installing doctrine/common (v2.11.0): Loading from cache
  - Installing imagine/imagine (1.2.3): Loading from cache
  - Installing friendsofsymfony/http-cache-bundle (2.8.0): Loading from cache
  - Installing doctrine/instantiator (1.3.0): Loading from cache
  - Installing doctrine/dbal (v2.10.0): Loading from cache
  - Installing doctrine/orm (v2.7.0): Loading from cache
  - Installing symfony/doctrine-bridge (v4.3.9): Loading from cache
  - Installing doctrine/doctrine-cache-bundle (1.4.0): Loading from cache
  - Installing jdorn/sql-formatter (v1.2.17): Loading from cache
  - Installing doctrine/doctrine-bundle (1.12.6): Loading from cache
  - Installing contao/imagine-svg (0.2.2): Loading from cache
  - Installing webmozart/assert (1.6.0): Loading from cache
  - Installing webmozart/path-util (2.3.0): Loading from cache
  - Installing contao/image (1.0.1): Loading from cache
  - Installing contao-components/tinymce4 (4.9.6): Loading from cache
  - Installing contao-components/tablesorter (2.1.1): Loading from cache
  - Installing contao-components/tablesort (4.0.1): Loading from cache
  - Installing contao-components/swipe (2.2.0): Loading from cache
  - Installing contao-components/simplemodal (2.1.1): Loading from cache
  - Installing contao-components/mootools (1.6.0.6): Loading from cache
  - Installing contao-components/mediabox (1.5.5): Loading from cache
  - Installing contao-components/jquery-ui (1.12.1.1): Loading from cache
  - Installing contao-components/jquery (3.4.1): Loading from cache
  - Installing contao-components/highlight (9.16.1): Loading from cache
  - Installing contao-components/dropzone (5.5.0): Loading from cache
  - Installing contao-components/datepicker (2.3.1): Loading from cache
  - Installing contao-components/contao (9.1.0): Loading from cache
  - Installing contao-components/colorpicker (1.5.1): Loading from cache
  - Installing contao-components/colorbox (1.6.5): Loading from cache
  - Installing contao-components/chosen (1.2.4): Loading from cache
  - Installing contao-components/ace (1.4.7): Loading from cache
  - Installing dasprid/enum (1.0.0): Loading from cache
  - Installing bacon/bacon-qr-code (2.0.0): Loading from cache
  - Installing ausi/slug-generator (v1.1.0): Loading from cache
  - Installing contao/core-bundle (4.8.7): Loading from cache
  - Installing contao/calendar-bundle (4.8.7): Loading from cache
  - Installing contao/newsletter-bundle (4.8.7): Loading from cache
  - Installing contao/news-bundle (4.8.7): Loading from cache
  - Installing toflar/psr6-symfony-http-cache-store (2.1.1): Loading from cache
  - Installing symfony/web-profiler-bundle (v4.3.9): Loading from cache
  - Installing zendframework/zend-eventmanager (3.2.1): Loading from cache
  - Installing zendframework/zend-code (3.4.1): Loading from cache
  - Installing ocramius/proxy-manager (2.2.3): Loading from cache
  - Installing symfony/proxy-manager-bridge (v4.3.9): Loading from cache
  - Installing monolog/monolog (1.25.3): Loading from cache
  - Installing symfony/monolog-bridge (v4.3.9): Loading from cache
  - Installing symfony/monolog-bundle (v3.5.0): Loading from cache
  - Installing symfony/dotenv (v4.3.9): Loading from cache
  - Installing symfony/debug-bundle (v4.3.9): Loading from cache
  - Installing composer/ca-bundle (1.2.5): Loading from cache
  - Installing ua-parser/uap-php (v3.9.2): Loading from cache
  - Installing nelmio/security-bundle (2.7.0): Loading from cache
  - Installing lexik/maintenance-bundle (v2.1.5): Loading from cache
  - Installing sensiolabs/ansi-to-html (v1.1.3): Loading from cache
  - Installing contao/installation-bundle (4.8.7): Loading from cache
  - Installing contao/manager-bundle (4.8.7): Loading from cache
  - Installing contao/listing-bundle (4.8.7): Loading from cache
  - Installing contao/faq-bundle (4.8.7): Loading from cache
  - Installing contao/comments-bundle (4.8.7): Loading from cache
symfony/event-dispatcher-contracts suggests installing psr/event-dispatcher
symfony/http-kernel suggests installing symfony/browser-kit
patchwork/utf8 suggests installing ext-wfio (Use WFIO for UTF-8 filesystem access on Windows)
php-http/discovery suggests installing puli/composer-plugin (Sets up Puli which is recommended for Discovery to work. Check http://docs.php-http.org/en/latest/discovery.html for more details.)
php-http/message suggests installing zendframework/zend-diactoros (Used with Diactoros Factories)
php-http/message suggests installing slim/slim (Used with Slim Framework PSR-7 implementation)
php-http/client-common suggests installing php-http/logger-plugin (PSR-3 Logger plugin)
php-http/client-common suggests installing php-http/cache-plugin (PSR-6 Cache plugin)
php-http/client-common suggests installing php-http/stopwatch-plugin (Symfony Stopwatch plugin)
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/twig-bridge suggests installing symfony/form (For using the FormExtension)
symfony/twig-bridge suggests installing symfony/stopwatch (For using the StopwatchExtension)
symfony/twig-bridge suggests installing symfony/web-link (For using the WebLinkExtension)
symfony/security suggests installing symfony/form
symfony/security suggests installing symfony/validator (For using the user password constraint)
symfony/security suggests installing symfony/ldap (For using the LDAP user and authentication providers)
symfony/framework-bundle suggests installing ext-apcu (For best performance of the system caches)
symfony/framework-bundle suggests installing symfony/form (For using forms)
symfony/framework-bundle suggests installing symfony/serializer (For using the serializer service)
symfony/framework-bundle suggests installing symfony/validator (For using validation)
symfony/framework-bundle suggests installing symfony/property-info (For using the property_info service)
symfony/framework-bundle suggests installing symfony/web-link (For using web links, features such as preloading, prefetching or prerendering)
symfony-cmf/routing-bundle suggests installing doctrine/phpcr-odm (To enable support for the PHPCR ODM documents (^1.4))
symfony-cmf/routing-bundle suggests installing doctrine/phpcr-bundle (To enable support for the PHPCR ODM documents)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
simplepie/simplepie suggests installing mf2/mf2 (Microformat module that allows for parsing HTML for microformats)
imagine/imagine suggests installing ext-imagick (to use the Imagick implementation)
imagine/imagine suggests installing ext-gmagick (to use the Gmagick implementation)
friendsofsymfony/http-cache-bundle suggests installing sensio/framework-extra-bundle (For Tagged Cache Invalidation)
symfony/doctrine-bridge suggests installing symfony/form
symfony/doctrine-bridge suggests installing symfony/validator
symfony/doctrine-bridge suggests installing symfony/property-info
symfony/doctrine-bridge suggests installing doctrine/data-fixtures
doctrine/doctrine-cache-bundle suggests installing symfony/security-acl (For using this bundle to cache ACLs)
bacon/bacon-qr-code suggests installing ext-imagick (to generate QR code images)
contao/core-bundle suggests installing contao/tcpdf-bundle (To export articles as PDF files)
zendframework/zend-eventmanager suggests installing container-interop/container-interop (^1.1.0, to use the lazy listeners feature)
zendframework/zend-eventmanager suggests installing zendframework/zend-stdlib (^2.7.3 || ^3.0, to use the FilterChain feature)
zendframework/zend-code suggests installing zendframework/zend-stdlib (Zend\Stdlib component)
ocramius/proxy-manager suggests installing ocramius/generated-hydrator (To have very fast object to array to object conversion for ghost objects)
ocramius/proxy-manager suggests installing zendframework/zend-xmlrpc (To have the XmlRpc adapter (Remote Object feature))
ocramius/proxy-manager suggests installing zendframework/zend-json (To have the JsonRpc adapter (Remote Object feature))
ocramius/proxy-manager suggests installing zendframework/zend-soap (To have the Soap adapter (Remote Object feature))
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
contao/manager-bundle suggests installing contao/tcpdf-bundle (To export articles as PDF files)
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
contao/manager-plugin: Generating plugin class...
contao/manager-plugin: ...done generating plugin class
> Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication
Added the web/.htaccess file.
Added the web/index.php file.
Added the web/preview.php file.
Added the web/app.php file.
Added the web/robots.txt file.

 // Clearing the cache for the prod environment with debug
 // false


 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.



 // Warming up the cache for the prod environment with debug
 // false

21:54:25 ERROR     [console] Error thrown while running command "--ansi cache:warmup --env=prod". Message: "Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Contao\CoreBundle\Translation\Translator given, called in /www/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.php on line 108" ["exception" => TypeError { …},"command" => "--ansi cache:warmup --env=prod","message" => "Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Contao\CoreBundle\Translation\Translator given, called in /www/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.php on line 108"]

In DateTimeFormatter.php line 17:

  Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct()
   must implement interface Symfony\Contracts\Translation\TranslatorInterface
  , instance of Contao\CoreBundle\Translation\Translator given, called in /ww
  w/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.p
  hp on line 108


cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command>

Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-update-cmd event terminated with an exception


  [RuntimeException]
  An error occurred while executing the "cache:warmup" command: 21:54:25 ERROR     [console] Error thrown while running command "--ansi cache:warmup --env=prod". Message: "Ar
  gument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Contao\CoreBundle\Translation\
  Translator given, called in /www/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.php on line 108" ["exception" =>
  [38;5;38mTypeError { …},"command" => "--ansi cache:warmup --env=prod","message
  ;208m" => "Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct() must implement interface Symfony\Contracts\Translation\TranslatorInterface, instance of Cont
  ao\CoreBundle\Translation\Translator given, called in /www/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.php on line 108"]

  In DateTimeFormatter.php line 17:

    Argument 1 passed to Knp\Bundle\TimeBundle\DateTimeFormatter::__construct()
     must implement interface Symfony\Contracts\Translation\TranslatorInterface
    , instance of Contao\CoreBundle\Translation\Translator given, called in /ww
    w/htdocs/xxx/test-4.8/var/cache/prod/ContainerSO1SRGo/getTwigService.p
    hp on line 108


  cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command>


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
````

### PR DESCRIPTION
**Pull request by ausi**
Fixes #1136

After this gets merged and released we should revert https://github.com/contao/conflicts/pull/9

### CODE REVIEW

**Review by leofeyer — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Comment by aschempp** [comment]
Does that work with Symfony 4.2? Implementing an interface that does not exist?

**Comment by leofeyer** [comment]
The contracts package has been [documented for Symfony 4.2](https://symfony.com/doc/4.2/components/contracts.html), so I guess it should work. Not 100% sure though.

**Comment by ausi** [comment]
> Does that work with Symfony 4.2? Implementing an interface that does not exist?

What do you mean by that? Which interface does not exist?

**Pull request merged**
