### PR TITLE
Skip insert tags when converting relative URLs

### LINKED ISSUE #5867: Fehlerhafter Link mit Inserttag {{news_url::*}}
### Affected version(s)

5.1

### Description

Hallo,

wenn ich im HTML-Editor über den Menüpunkt 'Link einfügen/bearbeiten' etwas im Format `{{news_url::123}}` eingebe, sieht das in der Quellcode-Ansicht so aus:
`<p><a href="{{news_url::123|urlattr}}">Newsletter</a></p>`
Beim Anzeigen des Textes im Frontend oder einer E-Mail sieht der Link dann so aus:
`https://baseurl.com//news-leser/newsletter.html`
Hinter der BaseUrl stehen 2 statt einem Slash (baseurl.com//news... statt baseurl.com/news...)
Dadurch funktionieren die Links nicht mehr

Gruß, Lutz

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #5867

### CODE REVIEW

**Review by ausi — DISMISSED** [review]

**Review by fritzmg — CHANGES_REQUESTED** [review]
That would be a BC break. The newsletter module relies on this method in order to convert all relative URLs automatically to absolute URLs as relative URLs will not work when receiving the newsletter. Insert Tags that generate relative URLs would now be omitted.

**Comment by leofeyer** [comment]
So what would you suggest?

**Comment by ausi** [comment]
> The newsletter module relies on this method in order to convert all relative URLs automatically to absolute URLs as relative URLs will not work when receiving the newsletter. Insert Tags that generate relative URLs would now be omitted.

I cannot reproduce that. When sending a newsletter, the insert tags get replaced first in https://github.com/contao/contao/blob/0ccd07c6b3548e667e80c551317917d83acd2cd0/newsletter-bundle/contao/classes/Newsletter.php#L98 and after that the relative URLs get converted in https://github.com/contao/contao/blob/0ccd07c6b3548e667e80c551317917d83acd2cd0/newsletter-bundle/contao/classes/Newsletter.php#L104

**Comment by fritzmg** [comment]
@ausi see https://github.com/contao/contao/issues/5867#issuecomment-1557336431

The relative URLs are converted when you submit the text in the back end, not during runtime when the newsletter is sent.

**Comment by fritzmg** [comment]
> So what would you suggest?

I already RFCed a suggestion here: https://github.com/contao/contao/issues/5867#issuecomment-1557342008

**Comment by fritzmg** [comment]
> and after that the relative URLs get converted in 

That code is only executed if `externalImages` is enabled.

**Comment by fritzmg** [comment]
> > So what would you suggest?
> 
> I already RFCed a suggestion here: [#5867 (comment)](https://github.com/contao/contao/issues/5867#issuecomment-1557342008)

Alternatively I guess we could just remove the `$objNewsletter->externalImages` check and _always_ convert relative URLs when sending the newsletter - unless there is any potential harm to that?

**Comment by ausi** [comment]
> I already RFCed a suggestion here: [#5867 (comment)](https://github.com/contao/contao/issues/5867#issuecomment-1557342008)
> 
> > I think the correct solution would be to replace the insert tags for `$strContent` within `Controller::convertRelativeUrls`.
> 
> Correction: only replace `$strUrl` further down within `preg_match` (otherwise we would save the replaced state to the database).

But then we would still save the replaced state of all insert tags in URLs to the database, which is wrong IMO.

I think the correct solution would be to merge this PR and remove the if-condition around the conversion here: https://github.com/contao/contao/blob/0ccd07c6b3548e667e80c551317917d83acd2cd0/newsletter-bundle/contao/classes/Newsletter.php#L101-L105 so that the URLs are always absolutized after insert tags got replaced.

**Comment by fritzmg** [comment]
> But then we would still save the replaced state of all insert tags in URLs to the database, which is wrong IMO.

No, I meant only in the `preg_match` check.

> I think the correct solution would be to merge this PR and remove the if-condition around the conversion here: 

But this would still be a BC break I think.

**Comment by ausi** [comment]
> > But then we would still save the replaced state of all insert tags in URLs to the database, which is wrong IMO.
> 
> No, I meant only in the `preg_match` check.

This would still fail under some circumstances. E. g. saving while surfing on domain A (which would add the base) and then sending the newletter on domain B (where the insert-tag is replaced again but is absolute this time).

> > I think the correct solution would be to merge this PR and remove the if-condition around the conversion here:
> 
> But this would still be a BC break I think.

You mean because `Controller::convertRelativeUrls()` changes its behavior? IMO adding a base-href to an insert-tag is always a bug because it cannot be known if the insert tag actually returns a relative URL.

**Comment by fritzmg** [comment]
> This would still fail under some circumstances. E. g. saving while surfing on domain A (which would add the base) and then sending the newletter on domain B (where the insert-tag is replaced again but is absolute this time).

Yes, but that was the status quo in Contao 4 anyway.

> IMO adding a base-href to an insert-tag is always a bug because it cannot be known if the insert tag actually returns a relative URL.

Agreed, so then this PR + always converting relative URLs (by removing `if ($objNewsletter->externalImages)`).

**Comment by leofeyer** [comment]
No, that cannot be right. Then we could not use embedded images anymore.

**Comment by ausi** [comment]
> No, that cannot be right. Then we could not use embedded images anymore.

Why? The images would still be embedded I think, as the code for that strips the base URL before embedding.

**Comment by fritzmg** [comment]
Detecting embedded images in `Controller::convertRelativeUrls` should be possible though? The check needs to additionally ignore `data:` and `cid:` (if it doesn't already do so).

**Comment by leofeyer** [comment]
> Why? The images would still be embedded I think, as the code for that strips the base URL before embedding.

Ah, I missed that. Sorry.

**Review by fritzmg — APPROVED** [review]

**Pull request merged**
