### PR TITLE
Skip pages in sitemap.xml if URL cannot be generated

### PR DESCRIPTION
**Pull request by aschempp**
I'm using a custom page controller in my project that requires additional route parameters. The `/sitemap.xml` route generates a 500 error because one page URL could not be generated.

### CODE REVIEW

**Comment by Toflar** [comment]
Why is requireItem not true for this route then?

**Comment by aschempp** [comment]
because only regular Contao pages have `requireItem`. My controller does not have a `parameters` parameter.

**Review by Toflar — CHANGES_REQUESTED** [review]
Then this is fine for me but we need a test to prevent regression bugs.

**Review by fritzmg — DISMISSED** [review]
lgtm, apart from missing test

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
