### PR TITLE
Define controller service dependencies

### PR DESCRIPTION
**Pull request by aschempp**
This fixes issues introduced in 2f9ccef9aebd9b74478c7ee3ba956c054293eb44

### CODE REVIEW

**Comment by aschempp** [comment]
Also, it is discussable whether changing the parent class should be allowed, as this is actually kinda a BC break in itself…

**Comment by leofeyer** [comment]
What issues exactly does this PR fix?

**Comment by aschempp** [comment]
You cannot `$this->get('contao.framework`)` if you do not tell the container that you need that service first!

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
