### PR TITLE
Use generic image format labels

### PR DESCRIPTION
**Pull request by leofeyer**
We could save our translators some tedious work this way.

### CODE REVIEW

**Review by bytehead — APPROVED** [review]
I like.

**Review by aschempp — APPROVED** [review]
assuming they don't translate PNG to Japanese or so? @taca

**Review by Toflar — APPROVED** [review]

**Comment by leofeyer** [comment]
> assuming they don't translate PNG to Japanese or so? @taca

We could make the labels even more generic and use `.png → .webp` then, which should be valid in all languages.

**Comment by taca** [comment]
> > assuming they don't translate PNG to Japanese or so? @taca
> 
> We could make the labels even more generic and use `.png → .webp` then, which should be valid in all languages.

I did not understand what's going on.

Anyway, these name of file format would not be translated, so no problem.

**Review by fritzmg — APPROVED** [review]

**Comment by aschempp** [comment]
Thank you @taca, your answer was exactly what I was looking for 👍

**Pull request merged**
