### PR TITLE
Fix a PHP8 error if a user has no groups

### PR DESCRIPTION
**Pull request by aschempp**
Got this error after creating a new back end user that does not have any groups.

### CODE REVIEW

**Review by fritzmg — CHANGES_REQUESTED** [review]
With which Contao version did you test this? Wouldn't this already be fixed by https://github.com/contao/contao/pull/7462 ?

**Comment by aschempp** [comment]
That would still return an empty list of groups, wouldn't it?

**Review by fritzmg — APPROVED** [review]
Ah, yes, I missed the zero index.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
