### PR TITLE
Do not return empty strings in the link_url insert tag

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2395
| Docs PR or issue | -

### CODE REVIEW

**Comment by fritzmg** [comment]
Hm, what about other insert tags, that might generate a link to the start page? e.g. `{{news_url::*}}` and `{{event_url::*}}`, if the news or event points to the start page (for whatever reason). Shouldn't `Page::generateFrontendUrl` generally return `./` instead, to cover all possibilities?

**Comment by leofeyer** [comment]
News and events will always have an auto_item and can therefore never generate an empty URL.

**Comment by fritzmg** [comment]
> News and events will always have an auto_item and can therefore never generate an empty URL.

If the `source` is `internal` for example, the `{{news_url::*}}` might be an empty string, if the selected page is the `index` page. Though that's of course an unlikely edge case.

**Comment by ausi** [comment]
A news can have a jumpTo page, if this page is the home page it would be the empty url.

**Comment by ausi** [comment]
> Though that's of course an unlikely edge case.

Yeah, but IMO it would make sense to fix all cases by adjusting the source of the URL `Page::generateFrontendUrl`.

**Comment by leofeyer** [comment]
> If the `source` is `internal` for example, the `{{news_url::*}}` might be an empty string, if the selected page is the `index` page. Though that's of course an unlikely edge case.

No, that is not correct. The path would be `index/news-alias.html` in this case.

**Comment by fritzmg** [comment]
> No, that is not correct. The path would be `index/news-alias.html` in this case.

No it would not. You are confusing this with `source = default` where the redirect page of the news archive is pointing to `index`. I am talking about `source = internal` - i.e. selecting a target page within the news article itself.

**Comment by leofeyer** [comment]
I see. My bad. 🙈

**Review by aschempp — DISMISSED** [review]
I think this can be merged regardless of any other changes, it's a safety guard against an invalid URL. But we sure should fix the other places and `PageModel::getFrontendUrl`.

**Comment by leofeyer** [comment]
Support for news, events and FAQs has been added in 9639096c3ebc8b678824b0329d0ad8982a996e62.

**Review by fritzmg — APPROVED** [review]

**Pull request merged**
