### PR TITLE
Ignore secret check in Install Tool

### PR DESCRIPTION
**Pull request by fritzmg**
If you do a fresh install of Contao in a non-local environment and then immediately delete the `APP_SECRET`, accessing the Install Tool is not possible anymore due to the secret check. Since the Install Tool would generate a secret for you in the `parameters.yml` and since only the `/_fragment` route is the one that would be exposed by a missing secret, it should be safe to ignore the secret check on the `/contao/install` route.

### CODE REVIEW

**Comment by fritzmg** [comment]
Failing test is unrelated.

**Comment by leofeyer** [comment]
> If you do a fresh install of Contao in a non-local environment and then immediately delete the `APP_SECRET`

How and why would you do that?

**Comment by fritzmg** [comment]
> How and why would you do that?

» https://github.com/contao/contao/issues/6088

**Comment by leofeyer** [comment]
This begs the question, why don’t we write the auto-generated secret into the `parameters.yml` as well?

**Comment by fritzmg** [comment]
I'd rather avoid dumping anything to `parameters.yml` and then clearing the Symfony Cache.

**Comment by leofeyer** [comment]
Which apparently is what the install tool already does?

**Comment by fritzmg** [comment]
> Which apparently is what the install tool already does?

Yes, which is not ideal anyway and only exists because there was no other way prior to environment variables.

Besides, I don't want a `parameters.yml` to be created when installing Contao.

**Review by ausi — APPROVED** [review]

**Review by leofeyer — CHANGES_REQUESTED** [review]
As discussed in the Contao call, we don‘t want the install tool to generate a secret anymore.

**Comment by leofeyer** [comment]
See #6121.

**Pull request closed without merging**
