### PR TITLE
Do not start the session to check if a property exists

### PR DESCRIPTION
**Pull request by aschempp**
If legacy code calls `exists($_SESSION['foo'])`, we're starting the session in our `LegacySessionAccess`. However, this is totally unnecessary if there is no previous session, because the value can obviously never be there.

### CODE REVIEW

**Comment by ausi** [comment]
Did you check if code like `isset($_SESSION['FORM_DATA'][$strKey])` does not start the session now?

**Comment by Toflar** [comment]
That looks correct to me. Just wondering if we should inject the Request (nullable) as we're injecting the whole session too.

**Comment by aschempp** [comment]
> That looks correct to me. Just wondering if we should inject the Request (nullable) as we're injecting the whole session too.

Then we wouldn't need to inject the session. But that would be unnecessary coupling to me and make tests harder. I don't think we'll ever need the full request?

**Review by Toflar — DISMISSED** [review]
LGTM but @ausi's question should be double checked.

**Review by leofeyer — APPROVED** [review]

**Pull request merged**
