### PR TITLE
Do not query for PIDs when building the breadcrumb of a File data container

### LINKED ISSUE #2317: File DataContainer cannot be part of back end modules with Table DataContainers anymore
### Affected version(s)

**4.9.5**

Contao **4.4.51** (and **3.5.40**) are _not_ affected.

### Description

If you have a back end module consisting of `Table` and `File` `dataContainer`s, the latter cannot be used anymore due to the following error:

```
Doctrine\DBAL\Exception\TableNotFoundException:
An exception occurred while executing 'SELECT * FROM tl_example_settings WHERE id=NULL LIMIT 0,1':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'c49dev.tl_example_settings' doesn't exist
```

<details>
  <summary>Stack Trace</summary>

  ```
    at vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:46
    at Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException()
      (vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:172)
    at Doctrine\DBAL\DBALException::wrapException()
      (vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:151)
    at Doctrine\DBAL\DBALException::driverExceptionDuringQuery()
      (vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:918)
    at Doctrine\DBAL\Connection->executeQuery()
      (vendor/contao/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:274)
    at Contao\Database\Statement->query()
      (vendor/contao/contao/core-bundle/src/Resources/contao/library/Contao/Database/Statement.php:248)
    at Contao\Database\Statement->execute()
      (vendor/contao/contao/core-bundle/src/Resources/contao/classes/Backend.php:527)
    at Contao\Backend->getBackendModule()
      (vendor/contao/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:167)
    at Contao\BackendMain->run()
      (vendor/contao/contao/core-bundle/src/Controller/BackendController.php:48)
    at Contao\CoreBundle\Controller\BackendController->mainAction()
      (vendor/symfony/http-kernel/HttpKernel.php:158)
    at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
      (vendor/symfony/http-kernel/HttpKernel.php:80)
    at Symfony\Component\HttpKernel\HttpKernel->handle()
      (vendor/symfony/http-kernel/Kernel.php:201)
    at Symfony\Component\HttpKernel\Kernel->handle()
      (web/index.php:31)
    at require('…/c49dev/web/index.php')
      (web/app.php:4)
  ```
</details>

### Reproduction

Use the following DCA and config files:

<details>
  <summary><code>contao/config/config.php</code></summary>
  
  ```php
  $GLOBALS['BE_MOD']['content']['example_module'] = [
    'tables' => ['tl_example', 'tl_example_settings'],
  ];
  ```

</details>

<details>
  <summary><code>contao/dca/tl_example.php</code></summary>
  
  ```php
  $GLOBALS['TL_DCA']['tl_example'] = [
      'config' => [
          'dataContainer' => 'Table',
          'sql' => [
              'keys' => [
                  'id' => 'primary',
              ],
          ],
      ],
      'list' => [
          'sorting' => [
              'mode' => 1,
              'fields' => ['name'],
              'flag' => 1,
              'panelLayout' => 'limit',
          ],
          'label' => [
              'fields' => ['name'],
              'format' => '%s',
          ],
          'global_operations' => [
              'settings' => [
                  'label' => ['Settings', 'Example settings.'],
                  'href' => 'table=tl_example_settings',
                  'class' => 'header_example_settings',
                  'icon' => 'header.svg',
              ],
          ],
          'operations' => [
              'edit' => [
                  'href' => 'act=edit',
                  'icon' => 'header.svg',
              ],
              'delete' => [
                  'href' => 'act=delete',
                  'icon' => 'delete.svg',
              ],
          ],
      ],
      'fields' => [
          'id' => [
              'sql' => ['type' => 'integer', 'unsigned' => true, 'autoincrement' => true],
          ],
          'tstamp' => [
              'sql' => ['type' => 'integer', 'unsigned' => true, 'default' => 0],
          ],
          'name' => [
              'inputType' => 'text',
              'eval' => ['tl_class' => 'w50', 'maxlength' => 255, 'mandatory' => true],
              'sql' => ['type' => 'string', 'length' => 255, 'default' => ''],
          ],
      ],
      'palettes' => [
          'default' => '{example_legend},name',
      ],
  ];
  ```
</details>

<details>
  <summary><code>contao/dca/tl_example_settings.php</code></summary>
  
  ```php
  $GLOBALS['TL_DCA']['tl_example_settings'] = [
      'config' => [
          'dataContainer' => 'File',
          'closed' => true,
      ],
      'fields' => [
          'foobar' => [
              'inputType' => 'text',
          ],
      ],
      'palettes' => [
          'default' => '{example_settings_legend},foobar',
      ],
  ];
  ```
</details>

This is a simple back end module that allows you to manage data records of `tl_example` as well as having a link to some example settings in the global operations of `tl_example`. This leads to the aforementioned error in Contao **4.9.5**, but works in Contao **4.4.51** (and **3.5.40** and presumably any prior Contao version).

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #2317

Looks like I was already affected by that bug, but instead of fixing it I used a workaround in https://github.com/madeyourday/contao-rocksolid-slider/commit/ae2dd521f0890dab33ad2e07d95b79e474190e43 🙈

### CODE REVIEW

**Comment by fritzmg** [comment]
Unfortunately, that fix is not quite the same. In Contao 3, the breadcrumb would still reflect the sub module. Expanding on my original reproduction example:

<details>
  <summary><code>contao/languages/en/modules.php</code></summary>
  
  ```php
  $GLOBALS['TL_LANG']['MOD']['example_module'] = ['Example module', 'Example module'];
  $GLOBALS['TL_LANG']['MOD']['tl_example_settings'] = 'Example settings';
  ```
</details>

With this example, the back end in Contao 3 looks like this:



With this PR, the back end in Contao 4.9 looks like this:



i.e. _Example settings_ is missing from the back end bread crumb.

[example.zip](https://github.com/contao/contao/files/5975537/example.zip)

Btw. I think the title of this PR is wrong? 😁

**Comment by ausi** [comment]
Ah, I see, my example doesn’t have that language key set. I updated the PR, now it works with that label too.

**Review by fritzmg — APPROVED** [review]
Works 👍 :)

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
