### PR TITLE
Add a command to debug manager plugins

### PR DESCRIPTION
**Pull request by aschempp**
This provides a new `debug:plugins` command in the Contao Managed Edition to debug the plugins. Only details about the `BundlePluginInterface` is implemented yet, but we should add more info as far as possible (e.g. what commands an `ApiPluginInterface` provides).

**Examples:**
<details>

1.  `vendor/bin/contao-console debug:plugins`

```
Contao Manager plugins with their package name
==============================================

 ------------------------------------------------ ---------------------------- -------- --------- -------- ----------- ----------- ----- 
  Plugin class                                     Package name                 Features / Plugin Interfaces                             
 ------------------------------------------------ ---------------------------- -------- --------- -------- ----------- ----------- ----- 
                                                                                Bundle   Routing   Config   Extension   Dependent   API  
 ------------------------------------------------ ---------------------------- -------- --------- -------- ----------- ----------- ----- 
  Contao\CoreBundle\ContaoManager\Plugin           contao/core-bundle           ✔        ✔                                               
  Contao\CalendarBundle\ContaoManager\Plugin       contao/calendar-bundle       ✔                                                        
  Contao\CommentsBundle\ContaoManager\Plugin       contao/comments-bundle       ✔                                                        
  Contao\FaqBundle\ContaoManager\Plugin            contao/faq-bundle            ✔                                                        
  Contao\InstallationBundle\ContaoManager\Plugin   contao/installation-bundle   ✔        ✔                                               
  Contao\ListingBundle\ContaoManager\Plugin        contao/listing-bundle        ✔                                                        
  Contao\NewsBundle\ContaoManager\Plugin           contao/news-bundle           ✔                                                        
  Contao\NewsletterBundle\ContaoManager\Plugin     contao/newsletter-bundle     ✔                                                        
  Contao\ManagerBundle\ContaoManager\Plugin        contao/manager-bundle        ✔        ✔         ✔        ✔           ✔           ✔    
 ------------------------------------------------ ---------------------------- -------- --------- -------- ----------- ----------- ----- 

```

2. `vendor/bin/contao-console debug:plugins --bundles`

```
Available registered bundles in loading order
=============================================

 ----------------------------------- ---------------------------------------------------------------------- 
  Bundle name                         Contao Resources path                                                 
 ----------------------------------- ---------------------------------------------------------------------- 
  KnpMenuBundle                                                                                             
  KnpTimeBundle                                                                                             
  SchebTwoFactorBundle                                                                                      
  CmfRoutingBundle                                                                                          
  Terminal42ServiceAnnotationBundle                                                                         
  FrameworkBundle                                                                                           
  SecurityBundle                                                                                            
  TwigBundle                                                                                                
  MonologBundle                                                                                             
  SwiftmailerBundle                                                                                         
  DoctrineBundle                                                                                            
  DoctrineCacheBundle                                                                                       
  LexikMaintenanceBundle                                                                                    
  NelmioCorsBundle                                                                                          
  NelmioSecurityBundle                                                                                      
  FOSHttpCacheBundle                                                                                        
  ContaoManagerBundle                                                                                       
  ContaoCoreBundle                    ../../Projects/Contao/contao/core-bundle/src/Resources/contao/        
  ContaoCalendarBundle                ../../Projects/Contao/contao/calendar-bundle/src/Resources/contao/    
  ContaoCommentsBundle                ../../Projects/Contao/contao/comments-bundle/src/Resources/contao/    
  ContaoFaqBundle                     ../../Projects/Contao/contao/faq-bundle/src/Resources/contao/         
  ContaoInstallationBundle                                                                                  
  ContaoListingBundle                 ../../Projects/Contao/contao/listing-bundle/src/Resources/contao/     
  ContaoNewsBundle                    ../../Projects/Contao/contao/news-bundle/src/Resources/contao/        
  ContaoNewsletterBundle              ../../Projects/Contao/contao/newsletter-bundle/src/Resources/contao/                                              
 ----------------------------------- ---------------------------------------------------------------------- 

```

3. `vendor/bin/contao-console debug:plugins contao/manager-bundle`

```
Bundles registered by plugin "Contao\CoreBundle\ContaoManager\Plugin"
=====================================================================

 ---------------------------------------------------------------------- ---------- --------------------------------------------------------- ------------- 
  Bundle                                                                 Replaces   Load after                                                Environment  
 ---------------------------------------------------------------------- ---------- --------------------------------------------------------- ------------- 
  Knp\Bundle\MenuBundle\KnpMenuBundle                                                                                                         All          
 ---------------------------------------------------------------------- ---------- --------------------------------------------------------- ------------- 
  Knp\Bundle\TimeBundle\KnpTimeBundle                                                                                                         All          
 ---------------------------------------------------------------------- ---------- --------------------------------------------------------- ------------- 
  Scheb\TwoFactorBundle\SchebTwoFactorBundle                                                                                                  All          
 ---------------------------------------------------------------------- ---------- --------------------------------------------------------- ------------- 
  Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle                                                                                           All          
 ---------------------------------------------------------------------- ---------- --------------------------------------------------------- ------------- 
  Terminal42\ServiceAnnotationBundle\Terminal42ServiceAnnotationBundle                                                                        All          
 ---------------------------------------------------------------------- ---------- --------------------------------------------------------- ------------- 
  Contao\CoreBundle\ContaoCoreBundle                                     core       Symfony\Bundle\FrameworkBundle\FrameworkBundle            All          
                                                                                    Symfony\Bundle\SecurityBundle\SecurityBundle                           
                                                                                    Symfony\Bundle\TwigBundle\TwigBundle                                   
                                                                                    Symfony\Bundle\MonologBundle\MonologBundle                             
                                                                                    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle                     
                                                                                    Doctrine\Bundle\DoctrineBundle\DoctrineBundle                          
                                                                                    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle                
                                                                                    Knp\Bundle\MenuBundle\KnpMenuBundle                                    
                                                                                    Knp\Bundle\TimeBundle\KnpTimeBundle                                    
                                                                                    Lexik\Bundle\MaintenanceBundle\LexikMaintenanceBundle                  
                                                                                    Nelmio\CorsBundle\NelmioCorsBundle                                     
                                                                                    Nelmio\SecurityBundle\NelmioSecurityBundle                             
                                                                                    Scheb\TwoFactorBundle\SchebTwoFactorBundle                             
                                                                                    Symfony\Cmf\Bundle\RoutingBundle\CmfRoutingBundle                      
                                                                                    Contao\ManagerBundle\ContaoManagerBundle                               
 ---------------------------------------------------------------------- ---------- --------------------------------------------------------- ------------- 

```
</details>

### CODE REVIEW

**Comment by aschempp** [comment]
I think this can be merged. Failing tests are not related to the PR.

**Comment by leofeyer** [comment]
Merging is blocked because of the failing coverage check. I guess you have to provide a unit test for the new command.

**Comment by aschempp** [comment]
Failing tests don't seem related to this PR?

**Comment by leofeyer** [comment]
The are not. We have to merge #1012 to fix this.

**Comment by leofeyer** [comment]
@aschempp If you rebase the PR onto the latest master branch, the build chain should run successfully again.

**Edit:**  NVM, I have rebased it myself. 😄

**Review by Toflar — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
