### PR TITLE
Add a command to debug the page controllers

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by bytehead** [comment]
Nice!

**Review by fritzmg — CHANGES_REQUESTED** [review]
🚀 

Please also link to a PR or issue at https://github.com/contao/docs/ :)

**Comment by m-vo** [comment]
Just thinking: Are we sure command names in the debug namespace (like `debug:pages` or `debug:plugins`) won't collide with symfony's in the future or should we maybe prefix them with `contao-`?

On the other hand it's probably no big deal to change them should there be collisions at some point as that's not used in a programmatic way.

**Comment by m-vo** [comment]
@leofeyer/@aschempp this issue should probably be labeled with `feature` and go into 4.12? :slightly_smiling_face:

**Comment by leofeyer** [comment]
> Just thinking: Are we sure command names in the debug namespace (like `debug:pages` or `debug:plugins`) won't collide with symfony's in the future or should we maybe prefix them with `contao-`?

We should discuss this in a separate issue, as we have already added `debug:fragments`, `debug:dca` and `debug:plugins`, which would have to be prefixed then, too.

> @leofeyer/@aschempp this issue should probably be labeled with `feature` and go into 4.12? 🙂

The `debug:pages` command was planned to be released in Contao 4.11, however, it did not make it. Without the command, there is no way to debug the new page controllers, therefore it can be considered both a bug and a feature. 🤷🏻‍♂️

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
> Please also link to a PR or issue at https://github.com/contao/docs/ :)

See https://github.com/contao/docs/issues/696

**Pull request merged**
