### PR TITLE
Fix SearchIndexSubscriber not respecting noindex hint

### LINKED ISSUE #4795: Contao search engine: News article with "noindex" is still indexed
### Affected version(s)

4.13.5

### Description

When you select "Robots tag: noindex,follow" in a single news article setting, this article is still indexed by the Contao search engine and visible in the list of search results.

**How to reproduce:**

- Contao installation with newslist and newsreader (both pages with default "robots: index" settings)
- some news articles
- a page with the search engine module

Now go to the news articles and change the robots settings of one single news article to "noindex".

Then under "Maintenance" do "Purge the search index" and after that "Update the search index" > "Start crawling".

Then to the frontend: If you now search for a term that is only mentioned in the "noindex" news article, this article is still shown in the search results (but shouldn't because of the "noindex" setting).

### PR DESCRIPTION
**Pull request by Toflar**
Fixes https://github.com/contao/contao/issues/4795

### CODE REVIEW

**Comment by ausi** [comment]
Just to double check: Even if `"noSearch": false,` is specified in the JSON-LD, meta robots noindex should overrule that?

**Comment by fritzmg** [comment]
I think so. We never really specified/documented this, but at the moment (meaning even without this PR via the `kernel.terminate` indexing) it's like this:

* You can allow Google to index a page, while disallowing it for Contao's search index independently.
* You can set a page to `noindex`, which will then not be indexed by either Google or Contao.
* Disallowing Google while still allowing Contao is not possible.

**Comment by Toflar** [comment]
Needs work -> draft.

**Comment by Toflar** [comment]
Needs work -> draft.

**Comment by Toflar** [comment]
Now we're good here :)

**Review by fritzmg — DISMISSED** [review]

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
