### PR TITLE
4.9 Variable for newsletter reader view link

### PR DESCRIPTION
**Pull request by Kahmoon**
Hi,

i hope this is the right place to put the request.

Can we get a variable for "view at website" link in a newsletter? Actually there is no such variable. You have to build an almost static link to archive this.

<?= $this->replaceInsertTags( '{{env::url}}/' ); ?>intern/newsletter/<?= $this->alias ?>.html

Greetings Frank

### CODE REVIEW

**Comment by fritzmg** [comment]
I think you made a mistake with your PR. Did you even mean to create one?

**Comment by Kahmoon** [comment]
I should open a pull request for this. This went obviously wrong!? Should i open an issue instead? Can i delete this? Sorry :(

**Comment by ausi** [comment]
> I should open a pull request for this.

It seems like you are mixing up “pull request” with “feature request”.

With a pull request you make the changes in the source yourself and create a pull request here so that the Contao developers can merge your changes.

With a feature request you can tell us about a new feature you would like to have in a future version of Contao.

> Should i open an issue instead?

If what you want is a “feature request” then yes.

> Can i delete this? Sorry :(

You can close this pull request, deletion is not necessary.
Nothing to be sorry about ☺️

Please also read our contributing guidelines for more information: https://github.com/contao/contao/blob/master/.github/CONTRIBUTING.md

**Comment by Kahmoon** [comment]
Now i found the right place. Sorry!

**Pull request closed without merging**
