### PR TITLE
CS fixes that went unnoticed

### PR DESCRIPTION
**Pull request by m-vo**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes -
| Docs PR or issue | -

Currently our legacy and template checks do not work due to an ecs cache issue.

### CODE REVIEW

**Comment by leofeyer** [comment]
Can we work around the issue somehow? You have mentioned that inserting `rm -rf /tmp/ecs_<container>` after each step.

**Comment by m-vo** [comment]
I'll see if we can do this programmatically in the config files or if this is already to late. I fear it will depend on the inner workings of the library, though.

**Review by ausi — DISMISSED** [review]

**Comment by m-vo** [comment]
There is already a fix https://github.com/symplify/symplify/pull/3399. I did not test it, yet.

**Comment by m-vo** [comment]
See https://github.com/symplify/symplify/pull/3403 - this is now in 9.4.21. I updated the `tools/ecs(composer.lock` file accordingly.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @m-vo.

**Pull request merged**
