### PR TITLE
Add compatibility with terminal42/escargot 1.0

### PR DESCRIPTION
**Pull request by ausi**
@Toflar anything more to do here or should version 1.0 be completely backwards compatible?

Related: #2263

### CODE REVIEW

**Comment by Toflar** [comment]
We can require `^1.0` only imho. It's the same as the latest `0.6.x` other than php 8 compatibility.
Sorry, could've done the PR myself, thought you wanted to incorporate it into the other PR :)

**Comment by ausi** [comment]
AFAIR we tried in the past to not increase dependency versions in bugfix versions unless necessary. This should keep updating more easy for people that use extensions that require escargot in version 0.6

**Comment by ausi** [comment]
But we should create a PR for Contao 4.11 that removes `0.6` IMO. (Done: https://github.com/contao/contao/pull/2510 )

**Comment by Toflar** [comment]
Fine for me either way

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
