### PR TITLE
Use classnames instead of service IDs

### PR DESCRIPTION
**Pull request by leofeyer**
This is a new take on #763. Before I do all the work, I would like to know if you agree with the concept.

Basically, I am planning on having a nice, forward-compatible `services.yml` file that imports a `deprecated.yml` file with all the old service IDs. In Contao 5, all we have to do is to remove the `deprecated.yml` files.

@contao/developers WDYT?

### CODE REVIEW

**Comment by ausi** [comment]
LGTM!

**Comment by fritzmg** [comment]
👍 from me. Though do we really want to remove these service IDs in Contao 5.0 already? Personally I am still in favour, just wondering.

**Comment by m-vo** [comment]
Just to be sure, we're aware of this? https://symfony.com/doc/current/bundles/best_practices.html#services

image

Because we're half bundle half application framework? And we don't care about inconsistencies e.g. when there is a need for a class to be used twice as two different services?

**Comment by leofeyer** [comment]
I was aware that we are not supposed to use autowiring in a bundle. But that we cannot use FQCNs is new information.

**Comment by leofeyer** [comment]
Closed in favor of #3686.

**Pull request closed without merging**
