### PR TITLE
Use a textarea for the image caption field

### PR DESCRIPTION
**Pull request by Toflar**
An image caption shouldn't be limited to 255 chars only, that makes no sense to me.

That's the result:

Bildschirmfoto 2020-11-27 um 13 12 19

### CODE REVIEW

**Review by fritzmg — DISMISSED** [review]

**Comment by m-vo** [comment]
What should happen to newlines in this field?

**Comment by Toflar** [comment]
They’re kept? Why would I care?

**Comment by asaage** [comment]
I wouldn't vote against it but that would be the only textarea in the BE without richtext-editor...
mabe revisit https://github.com/contao/contao/issues/2197
I personally would rather use a ce_text and add an image if there is so much text - just my opinion.

**Review by bytehead — DISMISSED** [review]

**Comment by asaage** [comment]
What about "overwrite metadata" in a ce_image?

**Review by leofeyer — APPROVED** [review]

**Review by bytehead — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
