### PR TITLE
Remove request tokens from more operations

### PR DESCRIPTION
**Pull request by fritzmg**
Follow up to #5461 and #5670. This PR removes the request token from more actions - which will allow Turbo prefetching on these operations, making them feel 'faster'. In particular this PR removes the the request tokens from URLs/operations that are just table views (`table=…`) which do not require a request token anymore.

It's a bit clunky. Should we instead may be inspect the URL in `Backend::addToUrl` and see if there is an `act=…` parameter that actually requires a request token, as per #5461? wdyt?

### CODE REVIEW

**Comment by leofeyer** [comment]
> Should we instead may be inspect the URL in `Backend::addToUrl` and see if there is an `act=…` parameter that actually requires a request token, as per #5461? wdyt?

Good idea if that works reliable 👍

**Comment by fritzmg** [comment]
Changed to the automatic variant.

Since we have now removed the `rt=` parameter from most links, we also need more `data-turbo-prefetch="false"` attributes (we prevented prefetching generally when the `href` of a link contained an `rt` parameter - but now that's not the case anymore).

**Comment by fritzmg** [comment]
@m-vo I noticed that despite Turbo now prefetching the response of the  `children` and `edit` buttons for example, Turbo does not render the prefetched document (instead it makes a new request on click). Do you have an idea why?

**Comment by leofeyer** [comment]
This looks more like a bugfix for Contao 5.4. If we only merge it into the `5.x` branch, we have to backport the `e.target.hasAttribute('onclick')` and all the `data-turbo-prefetch="false"` fixes.

**Comment by fritzmg** [comment]
> we have to backport the `e.target.hasAttribute('onclick')` and all the `data-turbo-prefetch="false"` fixes.

Backporting is not necessary. In Contao 5.4 the affected links all have `rt` parameters and thus are not pre-fetched.

**Comment by aschempp** [comment]
I'm not sure I would hardcode these on some specific action. This is all only about prefetching, isn't it? Maybe we should simply only prefetch the main navigation and never prefetch any operations?

**Comment by fritzmg** [comment]
> This is all only about prefetching, isn't it?

No, part of the PR is to remove the `rt` parameter from all URLs that do not require the `rt` parameter anymore since #5461, regardless of Turbo.

> Maybe we should simply only prefetch the main navigation and never prefetch any operations?

Why? The `children` operation should also be prefetchable for example. The child view is not really different from the parent view, the latter of which is accessible directly via the main navigation. 

And imho so can the `edit` action.

**Comment by aschempp** [comment]
> > This is all only about prefetching, isn't it?
> 
> No, part of the PR is to remove the `rt` parameter from all URLs that do not require the `rt` parameter anymore since #5461, regardless of Turbo.

Unnecessary calls to the method were removed, as well as actually parsing the request token. Same as in the front end, you might have a cookie, but we only check it if necessary. This PR removes it from the URL for some cases known to us, which might only work for DC_Table etc.

> > Maybe we should simply only prefetch the main navigation and never prefetch any operations?
> 
> Why? The `children` operation should also be prefetchable for example. The child view is not really different from the parent view, the latter of which is accessible directly via the main navigation.
> 
> And imho so can the `edit` action.

Because this would fix all issues we currently have. Prefetch is an optimization that is nice to have, but currently a PITA to fix every little place. The system works exactly as well without it (especially compared to without-Turbo). Not having it in operations for 5.4.0 would possibly solve a lot of issues, also for other extensions. For example I have an export button in my global operations that sure does not have a request token, this would fail now afair.

**Comment by fritzmg** [comment]
> Because this would fix all issues we currently have.

What issues? This is not a bugfix PR. This is a feature PR for 5.5.

> Not having it in operations for 5.4.0 would possibly solve a lot of issues, also for other extensions.

Not having prefetch you mean? Sure, but this PR is not about that.

> For example I have an export button in my global operations that sure does not have a request token, this would fail now afair.

You mean your global operation would now prefetch by default with this PR? Yes, that is an issue - but that would occur in 5.4 as well if your global operation does not have an `rt` parameter. We'll need a general solution for that, regardless of this PR.

**Comment by m-vo** [comment]
It's possible to add `data-turbo-prefetch="false` to any ancestor of a link as well, so we could put it to whole containers (for example the global operations).

Also, with Turbo it's now easy to use other HTTP methods with `data-turbo-method`, so we could maybe solve some cases by directly using the "correct" method (over GET).

**Comment by aschempp** [comment]
It just feels like this will create **a lot** of issues in Contao 5.4 that _could_ be solved by turbo data attributes etc, but currently are not so they will break a lot of stuff.

**Comment by fritzmg** [comment]
> It just feels like this will create **a lot** of issues in Contao 5.4

Again: this is a feature PR for Contao 5.5.

**Comment by fritzmg** [comment]
> It's possible to add `data-turbo-prefetch="false` to any ancestor of a link as well, so we could put it to whole containers (for example the global operations).

Yes, we should definitely do that for the global and regular operations. This way we can make sure that they do not prefetch by default (including any additional operations added by the App or extensions) and we can instead enable prefetching for specific operations (like edit).

We probably need to implement a more convenient way to add HTML attributes in various places for Turbo related stuff in general, e.g. to easily add the `data-turbo-prefetch="true"` attribute to your own operation for example.

**Comment by m-vo** [comment]
> We probably need to implement a more convenient way to add HTML attributes in various places for Turbo related stuff in general

I agree 👍 We could probably do this in our HtmlAttributes class (or an extension of it). Symfony UX has some Twig functions for Stimulus controllers as well, maybe we can build things compatible to that.

**Comment by fritzmg** [comment]
> I agree 👍 We could probably do this in our HtmlAttributes class (or an extension of it). Symfony UX has some Twig functions for Stimulus controllers as well, maybe we can build things compatible to that.

Well I meant primarily for things like operations or additional save buttons. e.g.

```php
$GLOBALS['TL_DCA']['tl_news']['list']['operations']['foobar'] => [
    'label' => ['My operation', 'My custom operation that can be prefetched'],
    'route' => MyBackendOperationController::class,
    'attributes' => [
        'data-turbo-prefetch' => 'true',
    ],
];
```

**Comment by aschempp** [comment]
> @m-vo I noticed that despite Turbo now prefetching the response of the `children` and `edit` buttons for example, Turbo does not render the prefetched document (instead it makes a new request on click). Do you have an idea why?

Because `Theme.setupCtrlClick();` adds a `event.stopPropagation()` on all operations.

**Comment by fritzmg** [comment]
Superseded by #7600

**Pull request closed without merging**
