### PR TITLE
Make the RegisterFragmentType compiler pass reusable

### PR DESCRIPTION
**Pull request by richardhj**
I use the [`RegisterFragmentsPass`](https://github.com/contao/contao/blob/4.13/core-bundle/src/DependencyInjection/Compiler/RegisterFragmentsPass.php) for custom fragment types. I utilize the `RegisterFragmentsPass` by simply registering it in my App Bundle:
```php
$container->addCompilerPass(new \Contao\CoreBundle\DependencyInjection\Compiler\RegisterFragmentsPass(\App\DashboardWidgetReference::TAG_NAME));
```

What changed from #5619 is, that the compiler pass now requires the `template` attribute for the registered services, and if the attribute is not given, falls back to `ce_` or `mod_` templates. However, my fragments do not require a `template` attribute because it is hardcoded.

```yaml
services:
    App\Controller\ContentElement\ExampleController:
        tags:
            -
                name: contao.content_element # <- this should not be limited to contao.content_element or contao.content_element
                template: ce_example  # <- this should not be mandatory (will be automatically guessed in the compiler pass)
```

How I perceived the `RegisterFragmentsPass` is, that it is a) _fragment type agnostic_ and b) _non-internal._
Consequently, the compiler pass should not expect `contao.content_element` and `contao.frontend_module` to be the only fragment types.

This issue was introduced in 55a78ce9117bb5379363c2d959735bad9026c70e.

### CODE REVIEW

**Comment by m-vo** [comment]
> How I perceived the RegisterFragmentsPass is, that it is a) fragment type agnostic and b) non-internal.

Compiler passes are not part of the BC promise (see https://docs.contao.org/dev/internals/bc-promise) and I would even say they are never meant to be reused.

However, I think I agree with the reasoning, that the pass should be fragment type agnostic (or at least it could try to).

**Comment by aschempp** [comment]
> Compiler passes are not part of the BC promise (see https://docs.contao.org/dev/internals/bc-promise) and I would even say they are never meant to be reused.

This compiler pass _IS_ intended to be reused, [we've stated that before](https://github.com/contao/contao/pull/2417#issue-717630476). It is also intentionally not marked as `@internal` in my opinion (though there seems to be no consistency in our compiler passes about that).

I agree with @richardhj this should not be hardcoded to our known types. Not sure how we would make this template-agnostic though

**Review by aschempp — DISMISSED** [review]
I have updated this PR to only set template data if the `templateOptionsListener` constructor property is given. I think this shoud be fixed in 4.13 to make the compiler pass reuseable as intended.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @richardhj.

**Pull request merged**
