### PR TITLE
Use the status code 307 to redirect on the logout page

### LINKED ISSUE #1032: Force browser to not store cache for logout page
**Affected version(s)**

4.4.41 (and superior?)

**Description**  

With a logout cache, `Cache-Control` header is set to `private` by default.

If we refer to the documentation on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#Cacheability), this does not prevent browser from caching the page.

> Indicates that the response is intended for a single user and must not be stored by a shared cache. A private cache may store the response.

If a user disconnects, reconnects and tries to disconnect again (it happens, trust me!), Chrome caches the page (it seems that Firefox doesn't). So the redirection is made correctly but user is not disconnected.

**How to reproduce**  

 - Connect
 - Disconnect
 - Re-connect
 - Try to disconnect again

You may not be able to reproduce because I didn't experience this behaviour on my staging server. Anyway, this `private` value does not seem like a way to avoid caching for this kind of page.

**How to solve**

I solved this bug by adding headers to the `RedirectResponse` constructor called in [PageLogout.php](https://github.com/contao/core-bundle/blob/master/src/Resources/contao/pages/PageLogout.php):

```php
return new RedirectResponse($strRedirect, 302, [
    'Cache-Control' => 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
]);
```

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #1032

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Comment by aschempp** [comment]
Should we use this by default on redirects?

**Review by bytehead — APPROVED** [review]

**Review by aschempp — APPROVED** [review]
Should we use this by default on redirects?

**Comment by leofeyer** [comment]
I don't think so. Normally it is safe to cache redirects, isn't it?

**Comment by aschempp** [comment]
Well, not for most of our cases. E.g. submitting a form should not mean the form page should be redirected. But I have never seen something like that, so maybe browsers don't cache redirects to POST requests…?

**Pull request merged**
