### PR TITLE
Handle `$objPage` not being set in the InsertTags class

### LINKED ISSUE #3827: Warning: Attempt to read property "parentPageTitle" on null
### Affected version(s)

4.x / PHP 8.0

### Description

Happens while opening a layout in the Contao demo (backend, `/contao?do=themes&id=15&table=tl_layout&act=edit`):

```
ErrorException:
Warning: Attempt to read property "parentPageTitle" on null

  at /contao/core-bundle/src/Resources/contao/library/Contao/InsertTags.php:804
  at Contao\InsertTags->executeReplace('  <h3><label for="ctrl_titleTag">Title tag</label></h3>  <input type="text" name="titleTag" id="ctrl_titleTag" class="tl_text" value="-  - foobar" maxlength="255" placeholder="{{page::pageTitle|attr}} - {{page::rootPageTitle|attr}}" onfocus="Backend.getScrollOffset()">', true)
     (/contao/core-bundle/src/Resources/contao/library/Contao/InsertTags.php:103)
  at Contao\InsertTags->replaceInternal('  <h3><label for="ctrl_titleTag">Title tag</label></h3>  <input type="text" name="titleTag" id="ctrl_titleTag" class="tl_text" value="-  - foobar" maxlength="255" placeholder="{{page::pageTitle}} - {{page::rootPageTitle}}" onfocus="Backend.getScrollOffset()">', true)
     (/contao/core-bundle/src/InsertTag/InsertTagParser.php:73)
  at Contao\CoreBundle\InsertTag\InsertTagParser->callLegacyClass('  <h3><label for="ctrl_titleTag">Title tag</label></h3>  <input type="text" name="titleTag" id="ctrl_titleTag" class="tl_text" value="-  - foobar" maxlength="255" placeholder="{{page::pageTitle}} - {{page::rootPageTitle}}" onfocus="Backend.getScrollOffset()">', true)
     (/contao/core-bundle/src/InsertTag/InsertTagParser.php:37)
  at Contao\CoreBundle\InsertTag\InsertTagParser->replaceChunked('  <h3><label for="ctrl_titleTag">Title tag</label></h3>  <input type="text" name="titleTag" id="ctrl_titleTag" class="tl_text" value="-  - foobar" maxlength="255" placeholder="{{page::pageTitle}} - {{page::rootPageTitle}}" onfocus="Backend.getScrollOffset()">')
     (/contao/core-bundle/src/InsertTag/InsertTagParser.php:32)
  at Contao\CoreBundle\InsertTag\InsertTagParser->replace('  <h3><label for="ctrl_titleTag">Title tag</label></h3>  <input type="text" name="titleTag" id="ctrl_titleTag" class="tl_text" value="-  - foobar" maxlength="255" placeholder="{{page::pageTitle}} - {{page::rootPageTitle}}" onfocus="Backend.getScrollOffset()">')
     (/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:163)
  at Contao\Widget->inherit()
     (/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:601)
  at Contao\Widget->parse()
     (/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:779)
  at Contao\DataContainer->row('{title_legend},name;{header_legend},rows,[rows],headerHeight,footerHeight,[EOF];{column_legend},cols;{sections_legend:hide},sections;{image_legend:hide},lightboxSize,defaultImageDensities;{style_legend},framework,stylesheet,external,loadingOrder,combineScripts;{feed_legend},newsfeeds,calendarfeeds;{modules_legend},modules;{script_legend},scripts,analytics,externalJs,script;{jquery_legend:hide},addJQuery,[addJQuery],jquery,[EOF];{mootools_legend:hide},addMooTools;{static_legend:hide},static,[static],width,align,[EOF];{expert_legend:hide},template,minifyMarkup,viewport,titleTag,cssClass,onload,head')
     (/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:1948)
  at Contao\DC_Table->edit()
     (/contao/core-bundle/src/Resources/contao/classes/Backend.php:651)
  at Contao\Backend->getBackendModule('themes', null)
     (/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:43)         
```

I guess `$objPage` is never set in backend context or do I miss something here? 

https://github.com/contao/contao/blob/b2bb27db3782884edd1f44e5aa9100a0d743910a/core-bundle/src/Resources/contao/library/Contao/InsertTags.php#L114-L119

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #3827

### CODE REVIEW

**Review by aschempp — APPROVED** [review]

**Review by Toflar — APPROVED** [review]

**Review by bytehead — APPROVED** [review]
Tested in local demo 👍

**Review by fritzmg — CHANGES_REQUESTED** [review]
Insert Tags are not supposed to be replaced in the back end. We need to revert #3622 as discussed in https://github.com/contao/contao/pull/3722#issuecomment-989727351 (or as we will discuss today).

**Review by fritzmg — APPROVED** [review]
As discussed in the Slack Huddle we want to merge this anyway, even after reverting #3622.

**Comment by leofeyer** [comment]
As discussed in the Contao call, we want to revert #3622 in Contao 4.13 (and add it again in Contao 5.0). This also implies that we will not merge #3722 into Contao 4.13.

The changes from this PR should be merged anyway, otherwise the problem would reappear in Contao 5.0.

**Pull request merged**
