### PR TITLE
Fix bug with huge PDF files in the back end preview

### PR DESCRIPTION
**Pull request by ausi**
Currently all pages of a PDF file are shown in the file manager if you open the popup. For PDFs with many sites this can cause issues so this PR limits the pages to 8, and shows a *“More pages...”* message if there are more than 8 pages in that PDF.

/cc @Toflar

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]

**Comment by leofeyer** [comment]
Do we really need more than one page as a preview?

**Comment by ausi** [comment]
> Do we really need more than one page as a preview?

I think it can be very helpful to have more than one page, depending on the document. These previews are only shown in the filemanager popup (not in the list view).

**Comment by leofeyer** [comment]
Even then, eight pages seem way too much to me. How about three pages if it absolutely has to be more than one?

**Comment by ausi** [comment]
> Do we really need more than one page as a preview?

Changed to only showing the first page in ce631de5487a8df63f415704c6366e3794e14daf

**Comment by leofeyer** [comment]
But now you have also removed the "More pages…" option, haven‘t you?

**Comment by ausi** [comment]
Yes it only shows a single image now (similar to a file preview in an operating system), the “More pages” is not necessary then I think.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
