### PR TITLE
Prevent loading of DCA column types in User class

### PR DESCRIPTION
**Pull request by ausi**
This is an attempt to fix https://github.com/contao/contao/issues/5029#issuecomment-1216531922

But I’m not sure if I’m happy with this solution 😐

### CODE REVIEW

**Comment by m-vo** [comment]
This feels very hacky to honest. But I did not investigate too much, so I'm not sure there is a better solution :relaxed:.

IMHO the root of the problem is the `DcaExtractor` running without loading the language files first. Can't we fix this? Maybe we are overoptimizing by trying not to load unnecessary language files?

**Comment by ausi** [comment]
The user object gets loaded very early (by the firewall), we don’t know the language at this point I think.

**Comment by bytehead** [comment]
Isn't there a default language on the `Request` object in case there is no language set on the user?

**Comment by ausi** [comment]
> Isn't there a default language on the `Request` object in case there is no language set on the user?

Yes, but this would mean that when using the debug mode all language files of all DCAs would get loaded in the wrong language, for every single request.

Maybe a better solution would be to fall back to the live schema from the database if the type cache is missing. This way we wouldn’t have to load the DCAs at all.

**Comment by ausi** [comment]
> Maybe a better solution would be to fall back to the live schema from the database if the type cache is missing. This way we wouldn’t have to load the DCAs at all.

See #5428

**Pull request closed without merging**
