### PR TITLE
Disable double encoding in the `HtmlAttributes` class

### LINKED ISSUE #5976: something wrong with url-de/encoding
### Affected version(s)

5+

### Description

If you use the filemanager and store a link with queryparameters in the meta-data of an image an then use the image in a content-text element the link is broken.
```https://www.yt.com/watch?v=videoid``` is becoming ```https://www.yt.com/watch?v&#61;videoid```

(it's not happening if you use "overwrite-metadata")

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #5976

### CODE REVIEW

**Review by m-vo — APPROVED** [review]
I hope this doesn't lead to other problems; e.g. if a blob of data contains a sequence of characters like `&lt;`…

**Review by ausi — APPROVED** [review]
As I noted in https://github.com/contao/contao/issues/5976#issuecomment-1516923488 I can’t think of a better fix and I hope we can switch to output encoding in Contao 6.

**Comment by ausi** [comment]
> I can’t think of a better fix

Maybe I can, how about https://github.com/contao/contao/pull/6000 ?

**Comment by m-vo** [comment]
At first I thought #6000 is overkill… however, after playing around with some examples, I think I prefer it over this PR. :see_no_evil:  We still break some cases but then there is at least a workaround.

**Comment by leofeyer** [comment]
Closing this in favor of #6000.

**Pull request closed without merging**
