### PR TITLE
Use a different session bag in the picker and other modal dialogs

### LINKED ISSUE #7176: State (filters, breadcrumbs) etc. should use a separate session key if popup=1
### Description

Right now, if you filter or search (or use the breadcrumb feature to limit tree views) in files, or the `DC_Table`, this will also affect all the pickers.

This means that when you search e.g. for images ending on `*.jpg` and then you go and pick some icon that only allows `.svg` files, you will get the restricted view from before. 

Imho, pickers and the "regular" back end session/state should be separated for better UX.

### PR DESCRIPTION
**Pull request by leofeyer**
This is a possible implementation for #7176. It uses a separate session bag and a `contao.session.finder` service to retrieve the correct session bag depending on the scope and the `popup` parameter.

@contao/developers WDYT?

### CODE REVIEW

**Comment by Toflar** [comment]
I think the concept is fine, but we'll need a BC layer for the existing way as this is used heavily in popular extensions: https://github.com/search?q=-%3EgetBag%28%27contao_backend%27%29&type=code

**Comment by leofeyer** [comment]
What do you mean? Using `System::getContainer()->get('session')->getBag('contao_backend')` will still work after this pull request has been merged.

**Comment by Toflar** [comment]
Well I mean that `->getBag('contao_backend')` would automatically give you the popup bag. But that's not really possible and also, maybe someone explicitly wants to access the other one. So I guess if developers want to use the new feature they have to use the new service.
But it's not really a SessionFinder, is it? There is only one. It is a SessionBagFinder, maybe?

**Comment by aschempp** [comment]
I agree that this is not a _session finder_. It could also give us the opportunity of making sure the respective bag always exists, so I don't need to use the `$session->getBag()` method and check the return value.

Maybe we could use something like `getBackendBag(string $namespace = null)` so we could use a dynamic part and NULL would return the popup if necessary? Also, can we dynamically register the bags if used only?

**Comment by leofeyer** [comment]
> It is a SessionBagFinder, maybe?

Renamed in 81b8a1e94655c901a86e422a4ed6d7766ac35a5e.

**Comment by leofeyer** [comment]
Closing this in favor of #7269. The session bag finder approach is too cumbersome, because we would have to inject an additional service into classes that already have the request stack or even the current request and thus the session.

You can see what I mean when you e.g. look at the changes in the `BackendFavoritesListener` in the new PR. There is no need for an additional service to decide whether to use the popup bag or the regular one.

**Pull request closed without merging**
