### PR TITLE
Fix some edge cases when parsing HTML style attributes

### PR DESCRIPTION
**Pull request by ausi**
Some edge cases were not yet supported for `style=""` in our `HtmlAttributes` class, especially the use of `/*` comments.

This PR changes the style parser implementation a little bit. It now keeps the style rules exactly as written without removing ~~whitespaces (see diff of the test cases) or~~ other things. But it now also handles upper and lower case correctly as it sees `color` and `COLOR` as the same while differing between `--foo` and `--FOO`. I think this should be more stable and better fits the mental modal of the `HtmlAttributes`.

### CODE REVIEW

**Comment by ausi** [comment]
It now also recognizes that `COLOR`, `c\6F lor`, `c\olor`, `/* Farbe: */ color` and `color` are all the same property.

**Comment by ausi** [comment]
I now brought whitespace normalization back with the style `color: red; background: blue;` to be compliant with the CSSOM standard: https://www.w3.org/TR/cssom-1/#serialize-a-css-declaration

**Review by m-vo — DISMISSED** [review]
IMHO this is the best out of two worlds: allowing as much standard-conformity as possible (future-proof) but still producing nice output. Love it! :heart_eyes:

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
