### PR TITLE
Always generate absolute URLs in the `PageModel` class

### LINKED ISSUE #6081: `PageModel::getFrontendUrl` generates only scheme relative URLs
### Affected version(s)

4.13, 5.1, 5.x

### Description

`PageModel::getFrontendUrl` is supposed to return an absolute URL if the page for which the URL is generated is on a different domain than the current domain. However, it only generates a _scheme relative_ URL currently. i.e., if you are currently on `https://example.com` and an URL is generated for a page that is within a website root with the domain `foobar.com`, the resulting URL will be

```
//foobar.com/page
```

This will break canonical URLs for example. Instead of

```html
<link rel="canonical" href="https://foobar.com/page">
```

it will be

```html
<link rel="canonical" href="https://example.com///foobar.local/page">
```

when you set the canonical URL of a page via the picker.

By comparison `PageModel::getFrontendUrl`  in Contao 4.9 generates an absolute URL (including the scheme) as expected if the target page is on a different domain.

### Reproduction 1

1. Create a second website root with a different domain.
2. Create a page within that website root with the alias `page`.
3. In your first website root create a text (or HTML) content element with the content `{{link_url::*}}` (replace `*` with the ID of the page within the other website root.

The generated URL will be `//foobar.com/page` instead of `https://foobar.com/page`.

### Reproduction 2

1. Create a second website root with a different domain.
2. Create a page within that website root with the alias `page`.
3. In your first website root edit the setting of a page.
5. Under _Canonical URL_ » **Custom URL** click the picker.
6. In the page picker, select the previously generated page of the other website root.
7. Visit the page in your first website root in the front end.

The generated canonical tag will be invalid.

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #6081

This fixes the issue, however, I have no idea if this is the "correct" fix. 🙈

### CODE REVIEW

**Comment by aschempp** [comment]
why would the canonical link incorrectly prepend a domain in the first place?

**Comment by aschempp** [comment]
I don't think this fix is correct. The network URL (protocol relative) is absolutely correct, and the routing system would correctly prepent the protocol if the current domain was on `http` but the target domain (root page) requires `https`. So I would rather investigate why we prepend a domain for canonical links if we shouldn't…

**Comment by leofeyer** [comment]
Prepending the domain is not the problem because we are talking about two root pages with different domains.

The question is why Symfony generates a protocol-relative URL even though `https` is in `$route->getSchemes()`?

**Comment by fritzmg** [comment]
> The network URL (protocol relative) is absolutely correct, and the routing system would correctly prepend the protocol if the current domain was on `http` but the target domain (root page) requires `https`. So I would rather investigate why we prepend a domain for canonical links if we shouldn't…

`$page->getFrontendUrl()` is always supposed to return an absolute URL, including the scheme, if the target is on a different domain than the current one, it should never return a protocol relative URL.

**Comment by aschempp** [comment]
> `$page->getFrontendUrl()` is always supposed to return an absolute URL, including the scheme, if the target is on a different domain than the current one, it should never return a protocol relative URL.

That is not how Symfony works. If you ask for a relative URL and the target is on another domain, it **automatically** generates a protocol-relative (network) URL if the current protocol is allowed. Protocol-relative URLs are perfectly valid to me, I don't see why we would need to manipulate that?

**Comment by fritzmg** [comment]
> That is not how Symfony works.

That's how it worked in Contao 3 and 4 before (including 4.9).

> Protocol-relative URLs are perfectly valid to me, I don't see why we would need to manipulate that?

Because we never expect protocol relative URLs in various places.

**Comment by leofeyer** [comment]
I also think we should not use protocol-relative URLs. They are not handled correctly all throughout the system and they are unnecessary because we always know the protocol.

**Comment by aschempp** [comment]
well in _my_ opinion, we should just always use absolute URLs, as we've discussed before. They solve a lot of problems as well, and the byte overhead is neglectible with gzip compression 🤷 

> Because we never expect protocol relative URLs in various places.

then that's a bug, because every user is exactly as allowed to enter a protocol-relative URL in any field 🤷

**Comment by leofeyer** [comment]
> well in _my_ opinion, we should just always use absolute URLs, as we've discussed before. 

Yes, and these absolute URLs should not be protocol-relative. 😉

**Comment by aschempp** [comment]
> Yes, and these absolute URLs should not be protocol-relative. 😉

They are not, if you always ask Symfony to generate absolute URLs 😉. But if we ask for relative URLs, it will add the host if necessary but keep the protocol relative.

**Comment by fritzmg** [comment]
> but keep the protocol relative.

And this is unexpected from Contao's (and its extensions') perspective. This must not change in Contao 4 (and 5 for that matter) imho.

**Comment by aschempp** [comment]
it has not changed since we use Symfony routing 🤷

**Comment by leofeyer** [comment]
I don‘t understand why we are discussing this? Protocol-relative URLs are currently **not working correctly** (see #6081) and this PR fixes it. Who cares since when this has not changed?

**Comment by fritzmg** [comment]
@aschempp wants to change all the occurrences where we use `PageModel::getFrontendUrl` to accommodate protocol relative URLs, rather than changing `PageModel::getFrontendUrl` itself. Which is wrong imho as `PageModel::getFrontendUrl` is not supposed to return a protocol relative URL, at least not in Contao 4 and 5.

However, rather than fixing this only in `PageModel::getFrontendUrl` may be we can find a way so that the Router itself always returns an absolute URL in such a case? In our Url Generator we introduced the `_ssl` parameter for such cases as far as I can see.

**Comment by aschempp** [comment]
what I see in #6081 is that the canonical URL appears to be relative, which causes issue because someone is incorrectly appending a wrong host. To me, canonical URLs should always be absolute, and never relative, which would solve this problem. Right?

**Comment by leofeyer** [comment]
> may be we can find a way so that the Router itself always returns an absolute URL in such a case?

It won‘t. We would have to always require absolute URLs, but our use case is "relative URL unless it is a different domain".

**Comment by fritzmg** [comment]
> It won‘t. We would have to always require absolute URLs, but our use case is "relative URL unless it is a different domain".

It works in Contao 4.9. There we are using the `_ssl` parameter in our own URL generator.

**Comment by aschempp** [comment]
We cannot modify the Symfony router to behave this way (without duplicating >150 LOC).

What I'm trying to say with _this is a perfectly valid URL_ is, that this could also be used by any user! If I enter `//example.com/foobar` into the canonical URL field of a page, what do you expect to happen? It would also incorrectly prepend the host, wouldn't it?

**Comment by fritzmg** [comment]
@aschempp see https://github.com/contao/contao/pull/6134#issuecomment-1587499184

> IMO we should not use scheme relative URLs at all, but absolute URLs instead.
> But we should additionally also add support for these types of URLs for the canonical URL.

`PageModel::getFrontendUrl` should not return a scheme relative URL as this is not expected.

**Review by ausi — APPROVED** [review]
IMO this fix is correct.

But I think we should add support for protocol relative URLs as canonical links too here: https://github.com/contao/contao/blob/8fca9e49714006921d9cdcaec5006141233b0f87/core-bundle/src/Routing/ResponseContext/HtmlHeadBag/HtmlHeadBag.php#L92 ~~probably in a second PR.~~ See #6139

**Review by aschempp — CHANGES_REQUESTED** [review]
https://github.com/contao/contao/pull/6140 is a better fix imho

**Pull request closed without merging**
