### PR TITLE
Correctly show custom templates in "override all" mode

### LINKED ISSUE #938: Kein individuelles Template bei "Mehrere bearbeiten > Mehrere überschreiben"
**Affected version(s)**
4.8.x
##
**Description**  
Ich hatte gerade den Fall das in einem Artikel 12 ce_text Elemente ein anderes Template bekommen sollten. Wollte Mehrere bearbeiten > Überschreiben und das neue Template zuweisen, die Liste ist aber leer. Wenn ich die Elemente einzeln bearbeite, dann wird das neue Template angezeigt.

Durch die Templateauswahländerung in 4.8 kann man bei **Mehrere bearbeiten** > **Mehrere überschreiben** kein individuelles Template mehr auswählen, die Liste ist leer.

Dies tritt überall auf wo man ein **Individuelles Template** auswählen kann (Inhaltselemente, Frontend-Module).

< 4.8 wurden ja alle Templates angezeigt, dies sollte auch in diesem Fall (Mehrere bearbeiten) sein, sonst macht die Funktion **Mehrere bearbeiten** > **Mehrere überschreiben** keinen sinn.
##
**How to reproduce**  

- ein Artikel mit mehreren (gleichen) Inhaltselementen auswählen
- auf **Mehrere bearbeiten** klicken
- Inhaltselemente auswählen
- auf **Überschreiben** klicken
- **Individuelles Template [customTpl]** auswählen
- Individuelles Template Auswahlliste ist leer

### PR DESCRIPTION
**Pull request by leofeyer**
Fixes #938

### CODE REVIEW

**Comment by aschempp** [comment]
Why would anyone want to select `form_row` etc. in a field?

**Comment by leofeyer** [comment]
They would not. The additional mapping entries **prevent** the templates from being listed.

**Review by aschempp — COMMENTED** [review]
Can I still use a custom `mod_article` template if it is listed in the mapper then?

**Comment by leofeyer** [comment]
Yes, you can.

**Comment by leofeyer** [comment]
Yes, you can. The mapper only helps to determine which templates belong to a bundle and which ones are custom. But since `article` is not part of `$GLOBAL['FE_MOD']`, the method would treat `mod_article` as custom template without the additional mapping.

**Review by aschempp — APPROVED** [review]

**Pull request merged**
