### PR TITLE
Correctly apply custom CSS in the ContentModule class

### LINKED ISSUE #1947: ContentModule: custom cssID not applied
Custom cssID is set to ModuleProxy class but gets never applied to the fragment controller. As a quick fix move line 50/51 after line 67. So the custom cssID is directly changed on the ModuleModel like the typePrefix.

https://github.com/contao/contao/blob/f2651755fce858d40d298ec59dab148bb8af166d/core-bundle/src/Resources/contao/elements/ContentModule.php#L50-L77

### PR DESCRIPTION
**Pull request by leofeyer**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #1947
| Docs PR or issue | -

### CODE REVIEW

**Review by aschempp — CHANGES_REQUESTED** [review]
This should be fixed in Contao 4.4 as well

**Comment by leofeyer** [comment]
Why? There is no `ModuleProxy` class in Contao 4.4, so the problem will never occur there.

**Comment by aschempp** [comment]
just looks inconsistent to me … obviously if someone does something similar as the proxy it would have the same problem?

**Comment by leofeyer** [comment]
Rebased to the `4.4` branch.

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
It seems that we have to revert these changes (see #2203).

**Pull request merged**
