### PR TITLE
Generate the file manager preview images with a 1x, 2x source set

### PR DESCRIPTION
**Pull request by leofeyer**
The file manager preview images were missing a high resolution source for retina displays.

### CODE REVIEW

**Review by fritzmg — APPROVED** [review]

**Comment by aschempp** [comment]
wouldn't it be easier to just render them in 2x the size of what the browser will display? Just because they're very small anyway?

**Comment by fritzmg** [comment]
@aschempp that's not necessary due to deferred resizing. Only the size requested by the browser will actually be generated.

**Comment by aschempp** [comment]
as far as I remember (and thats the problem in the original issue), the image will not be resized if not necessary (= its smaller than the requested size), and the original image path would be returned. Which can't be displayed because it's in a protected folder.

**Comment by fritzmg** [comment]
No, that is not the case. Images are always resized, unless you specify `skip_if_dimensions_match`.

Also I think you replied in the wrong issue? 😁

**Comment by leofeyer** [comment]
> Also I think you replied in the wrong issue? 😁

Indeed. I think he refers to #6299.

> wouldn't it be easier to just render them in 2x the size of what the browser will display?

It would be easier for sure, but it would also double the file size. The thumbnails may be small, but if you have 10,000 or even more, it will make a difference.

**Comment by leofeyer** [comment]
> Also I think you replied in the wrong issue? 😁

Indeed. I think you are looking for #6299.

**Pull request merged**
