### PR TITLE
Remove the license screen from the install tool

### PR DESCRIPTION
**Pull request by leofeyer**
See https://github.com/contao/contao/pull/6121#issuecomment-1578417088

Not sure if we really want to do this, but since Contao 5 does not require to accept the license, why should Contao 4 still do?

### CODE REVIEW

**Review by Toflar — APPROVED** [review]

**Review by fritzmg — APPROVED** [review]

**Comment by ausi** [comment]
AFAIK, this also ensured that there is always a _localconfig.php_ present. Not sure if this is still the case and needed by anyone, but we should be sure not to introduce a bug with this change IMO.

And should we maybe add a BC layer so that `Config::get('licenseAccepted')` returns `true`?

**Comment by aschempp** [comment]
@leofeyer did you backport the changes from Contao 5 or re-implement this?

**Comment by fritzmg** [comment]
> AFAIK, this also ensured that there is always a _localconfig.php_ present. Not sure if this is still the case and needed by anyone, but we should be sure not to introduce a bug with this change IMO.

The `$blnHasLcf` ("has localconfig") check is still there, so that should not be an issue. I agree about `Config::get('licenseAccepted')` though.

**Comment by aschempp** [comment]
> The `$blnHasLcf` ("has localconfig") check is still there, so that should not be an issue. I agree about `Config::get('licenseAccepted')` though.

Hmm, that wouldn't fix the issue for the Contao Manager then though. Currently, the Contao Manager redirects to the install tool after setup, because Contao would redirect the user to the install tool anyway because of this flag … I though this is only related to the `licenseAccepted` flag, but it apparently is not?

**Comment by fritzmg** [comment]
You still need to set an Install Tool password in Contao 4.

**Comment by leofeyer** [comment]
Then we might as well leave everything as is. 😄

**Comment by aschempp** [comment]
hmm, that's true. The only solution I can think of would be for the manager to automatically lock the install tool 🤔

**Comment by ausi** [comment]
As discussed in the call today, we still need the install tool to set the install tool password as well as for the SQL template import.
We might be able to enable entering database credentials in the manager though.

**Comment by ausi** [comment]
> We might be able to enable entering database credentials in the manager though.

@aschempp should we create an issue for that in the manager repo?

**Comment by aschempp** [comment]
not necessary, I got that on my radar 😊

**Pull request closed without merging**
