### PR TITLE
Store the referrer by default in `backend` scope

### LINKED ISSUE #7190: Referer is not saved in the session for custom backend routes
### Affected version(s)

4.13

### Description

In my custom backend route, I have a link to the user profile, and I want the “Go back” button to lead back to my route. But this doesn’t work, the route is never stored in the session under `'referer'`, and the button leads to the last visited “core” backend url. Custom backend routes are skipped.

The developer docs say [here](https://docs.contao.org/dev/framework/routing/#request-scope):

> If the scope is backend, <...> Contao will also automatically generate a "referer ID token" and store it as another request attribute under `_contao_referer_id`. _Plus the current and last URL will be stored in the session._ This is used in the back end for the "go back" links for example.

However, the referer is not actually stored in this case, because `StoreRefererListener` specifically checks for the `contao_backend` route here: https://github.com/contao/contao/blob/74afbb06af7373388a3239c086ffc347170d71ba/core-bundle/src/EventListener/StoreRefererListener.php#L88-L97

I was able to verify that by commenting out just that one line.

### PR DESCRIPTION
**Pull request by fritzmg**
#7190

This implements my opt-out suggestion from https://github.com/contao/contao/issues/7190#issuecomment-2094788128.

Any back end route will now store the referrer by default - but you can opt-out via `_store_referrer: false` in your route defaults/attributes.

/cc @ameotoko

### CODE REVIEW

**Review by aschempp — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Comment by leofeyer** [comment]
What about the `BackendCsvImportController`?

**Comment by fritzmg** [comment]
> What about the `BackendCsvImportController`?

`BackendCsvImportController` has no actual routes. It is only used for back end module callbacks, as far as I can see.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @fritzmg.

**Comment by fritzmg** [comment]
> [Make the configuration explicit](https://github.com/contao/contao/pull/7227/commits/0cfb6ec27345c790bcc4d3230ed7dc4dcd4f685c)

Imho it should be the other way around for safety. i.e. we want to make sure that _only_ the `contao_backend` route from that controller gets the referrer stored - as this was the previous state. Besides, now the definition is inconsistent with the other back end controller route definitions. But it's a minor nitpick.

**Comment by leofeyer** [comment]
> Besides, now the definition is inconsistent with the other back end controller route definitions.

What do you mean? The routes now explicitly have `_store_referrer: false`, just like the other back end controllers. It was inconsistent before, when the main controller had `_store_referrer: true`, even though `false` is the only handled option.

**Comment by fritzmg** [comment]
Before your change the general route definition on all the classes had `"_store_referrer" = false`. In your change you removed that from the general route definition of the `BackendController` class alone - but not from the other two back end controllers (hence the inconsistency). Again, the idea was to ensure in the general route definition that the referrer is not stored for all the routes in the `BackendController` - and only enable it specifically for the `contao_backend` route.

For the other back end controllers it is not so much of an issue. While they do have a general route definition on their respective classes, they only have _one_ route anyway - which is defined on the `__invoke` method (imho this should be consolidated, but that's another issue).

**Comment by leofeyer** [comment]
#7232 fixes the inconsistency.

My reasoning is as follows: If an option can be anything or `false`, that is a classic opt-out case. And opt-out means that it is **on** by default and **off** in certain cases. Therefore, it is not correct to turn it off by default for all routes and turn it on for only one route, because that would be opt-in.

**Comment by fritzmg** [comment]
The functionality is currently opt-out in general.

For the `BackendController` we want to disable it by default and only enable it for one specific route - the `contao_backend` route - which is what this PR did originally. _And this will work regardless of whether the feature is opt-out or opt-in by default._

With your change the latter is not the case anymore. If the feature is, for whatever reason, switched to opt-in, the `contao_backend` route will not store its referrer anymore in the current state.

With the original state of this PR you would not have to worry about this.

**Comment by leofeyer** [comment]
If you want it to be opt-in, then please implement it accordingly. It should be `true === $request->attributes->get('_store_referrer')` instead of `false !== …` then.

**Comment by fritzmg** [comment]
> If you want it to be opt-in, then please implement it accordingly. It should be `true === $request->attributes->get('_store_referrer')` instead of `false !== …` then.

That's not what I meant. The implementation I did was opt-out, and deliberately so (see description above and discussion in the other issue).

My point was that the `BackendController` does not need to be concerned about the implementation detail of whether it is implemented in an opt-in or opt-out way. Nor does it need to be concerned about the way the opt-in or opt-out logic is implemented in the respective listener. 

The point is that we want to ensure that none of the `BackendController` routes store the referrer, except for the `contao_backend` route. The original state of this PR would ensure this and as a bonus it would ensure this regardless of whether the actual implementation is opt-in or opt-out.

**Comment by fritzmg** [comment]
The same applies to the `_token_check` attribute for example. While `_token_check` is `true` by default for the `frontend` and `backend` `_scope`, we still set it deliberately to `false` or `true` depending on what the route or the controller's defaults need.

The controller/route definition should not care about the default handling of an attribute, if it wants to _ensure_ something. You only need to be concerned about being able to enable or disable the CSRF token check, if you use `_token_check = true` or `_token_check = false`. Likewise you do only need to be concerned being able to enable or disable storing the back end referrer, when you use `_store_referrer = true` or `_store_referrer = false`.

**Comment by fritzmg** [comment]
Or look at it this way: let's say we release the current state in Contao 4.13.44 and 5.3.9 respectively. And then it turns out that having this enabled by default for all `backend` routes breaks too many extensions somehow, so we decide to flip it to opt-in instead for the next bugfix release. With your last changes you now have to remember to also adjust the `contao_backend` route and not just the default behavior in the listener.

With the previous state of this PR this would not be necessary.

It's about defining things defensively in a forward compatible way and keeping the concerns separate to avoid possible future pitfalls.

And my assumption is that @Toflar thought about this similarly when implementing https://github.com/contao/contao/commit/92ba02ef260b72e3195d11364645bdf8fcc76ef3 for Contao 4.1.0.

**Comment by leofeyer** [comment]
I have no problems implementing this as an opt-in! But the pull request has implemented it as an opt-out, so just create a new PR and change the implementation.

**Comment by fritzmg** [comment]
You are misunderstanding the point. I do not want this to be opt-in. The recent discussion is about [your change](https://github.com/contao/contao/pull/7227/commits/0cfb6ec27345c790bcc4d3230ed7dc4dcd4f685c) which I disagree with (see my comments).

**Comment by leofeyer** [comment]
You did not implement the opt-out pattern correctly, so I fixed it. 🤷‍♂️

**Comment by fritzmg** [comment]
Whether the attribute is opt-in or opt-out is solely defined by the implementation in the respective listener. It is not defined by the route definition itself.

**Pull request merged**
