### PR TITLE
Validate start/stop date

### LINKED ISSUE #812: Validate stop date > start date
**Affected version(s)**

I think all versions will be affected.

**Description**

Actually the function _show from/show until_ is working just for the following cases:

1. _show from_ is activated
2. _show until_ is activated
3. _both options_ are activated, but _show until_ must be a higher date than _show from_

The following option is not working:
4. _both options_ are activated, but _show until_ is a smaller date than _show from_ 

**How to reproduce**

I have a text element (I think, the problem also exists for articles and pages), which is online, but I want to hide it for a day:
_show from_ is **2019-10-04 00:01**
_show until_ is **2019-10-03 00:01**

I expect, that the text is shown until 2019-10-03 00:01, hidden the whole day of 2019-10-03 and visible again until 2019-10-04 00:01.

But the result is: the text is never visible.

### PR DESCRIPTION
**Pull request by aschempp**
Fixes https://github.com/contao/contao/issues/812

### CODE REVIEW

**Review by Toflar — DISMISSED** [review]
LGTM. Any reason this is a draft?

**Comment by aschempp** [comment]
Nope, just the stupid GitHub defaults 🤦‍♂️

**Review by fritzmg — DISMISSED** [review]

**Review by Toflar — DISMISSED** [review]

**Review by leofeyer — CHANGES_REQUESTED** [review]
The changes are fine, however, there is a usability problem. After entering a stop date that is before the start date, the back end scrolled down to the input fields again, making it look like everything went fine:



Only if I scroll up, I notice that there has actually been an error:



To improve this, we could either auto-focus the error message on top of the page or we could make the widgets available in the `onbeforesubmit_callback`, so I can call `->addError()` on the "stop date" widget. (We then would have to move the `$this->noReload` check after the `onbeforesubmit_callback`.)

What do you think?

**Comment by aschempp** [comment]
The widgets are rendered in `row`, making them available would not render an error message. I tried that first 😂

However, we can easily fix the scrolling, it already checks if an error exists. Should probably be a separate PR though?

**Comment by leofeyer** [comment]
Since the invisible error message is a consequence of the changes in this pull request, I think the fix should also be in this pull request.

**Comment by leofeyer** [comment]
#4846 has to be merged first.

**Comment by aschempp** [comment]
> #4846 has to be merged first.

Why? #4846 improves the widget error "possibilities", but everything here still works as is? This check method could be improved in #4846 to output the error to the widget, then we'd also have a test case for #4846

**Review by leofeyer — APPROVED** [review]

**Pull request merged**
