### PR TITLE
Convert count() to empty array comparison

### PR DESCRIPTION
**Pull request by leofeyer**

### CODE REVIEW

**Comment by m-vo** [comment]
Is this equivalent, performance wise? Because it's a completely different operation.

**Comment by leofeyer** [comment]
IDK. I am trusting Rector to know what they are doing, but feel free to validate yourself.

**Comment by m-vo** [comment]
Tested and confirmed that it has a better performance esp. for large arrays. :+1: 

But I still hate the looks of it, especially together with the yoda style. :see_no_evil:

**Comment by m-vo** [comment]
Btw.: if you randomize the test data enough, no one really is a clear winner anymore: https://3v4l.org/TXU1V#v8.1.4 (run multiple times)

**Comment by ausi** [comment]
I’d favor the following style:

If we need to make sure `$foo` is an array (and want to throw a type error if not) use:

```php
if (\count($foo))
if (!\count($foo))
```

If `$foo` is already type safe (via type hint or was defined inline) use:

```php
if ($foo)
if (!$foo)
```

They are very readable (to me at least ☺️) and have the same performance as `!== []` and `=== []`.

**Pull request merged**
