### PR TITLE
Add blank insert tag argument to open links in new window

### PR DESCRIPTION
**Pull request by ausi**
| Q                | A
| -----------------| ---
| Fixed issues     | Fixes #3142
| Docs PR or issue | contao/docs#796

This replaces #3142

### CODE REVIEW

**Comment by leofeyer** [comment]
Should we also adjust the calendar/news/etc. bundles? They already support `::absolute`.

https://github.com/contao/contao/blob/af1cbd762b5bb3a9b33ee4d006f0c758df32e0e2/news-bundle/src/EventListener/InsertTagsListener.php#L95

**Comment by ausi** [comment]
> Should we also adjust the calendar/news/etc. bundles?

/cc @aschempp ?

**Comment by aschempp** [comment]
I don't see a reason why not 👍

**Comment by ausi** [comment]
> Should we also adjust the calendar/news/etc. bundles?

Done in dc643ebba13fb2c0e6abb99f00ed0ed55ab2fb3f

**Review by aschempp — DISMISSED** [review]

**Review by leofeyer — DISMISSED** [review]

**Comment by leofeyer** [comment]
@ausi Can you please rebase the PR and resolve the conflicts?

**Comment by ausi** [comment]
Done.

**Review by aschempp — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
