### PR TITLE
Automatic login for cross-domain preview links

### PR DESCRIPTION
**Pull request by aschempp**
After reading up on https://symfony.com/doc/current/security/login_link.html (see https://github.com/contao/contao/pull/5404#issuecomment-1848417707) I realized this should be fairly simple, so here it is 😆 

There are two culprits I had to work around:
 1. The Symfony login URL authenticator does not handle the redirect URL of a login link. And our authentication success handler only accepts a target URL from POST data, not from the request URI (contrary to the default Symfony success handler). I think I worked around the potential security issue of a query parameter by using signed URLs.
 2. Symfony login URL does not handle anything related to 2FA, because that's a third-party bundle. In a default login link case (e.g. login via email link), you still have to enter 2FA credentials. However, for a back end preview this does not make much sense. So I discussed this with @Toflar, and we agreed if the back end user was already 2FA-authenticated, we don't need to authenticate again. The respective query parameter is kept secure through a signed URL as well.

### CODE REVIEW

**Comment by leofeyer** [comment]
> I think I worked around the potential security issue of a query parameter by using signed URLs.

@ausi Did he? 😄

**Comment by ausi** [comment]
> > I think I worked around the potential security issue of a query parameter by using signed URLs.
> 
> @ausi Did he? 😄

I’m not sure if I understand what potential security issue is meant here. The Symfony login link already uses signed URLs. From reading the code it looks to me like we are modifying the login link URL and “re-sign” it afterwards, right?

Besides, [Symfony itself writes](https://symfony.com/doc/current/security/login_link.html#important-considerations):

> Login links are a convenient way of authenticating users, but it is also considered less secure than a traditional username and password form. It is not recommended to use login links in security critical applications.
> 
> However, the implementation in Symfony does have a couple extension points to make the login links more secure. In this section, the most important configuration decisions are discussed

I think we should at least reduce the lifetime to something like `lifetime: 5` (seconds) and set `max_uses: 1`.

**Comment by aschempp** [comment]
> I’m not sure if I understand what potential security issue is meant here. The Symfony login link already uses signed URLs. From reading the code it looks to me like we are modifying the login link URL and “re-sign” it afterwards, right?

We are adding additional parameters (bypass 2fa and target URL), these are not signed by Symfony (and never will, because Symfony only accepts user properties afaik).

> I think we should at least reduce the lifetime to something like `lifetime: 5` (seconds) and set `max_uses: 1`.

The login link includes the `lastLogin` property of the user. Which means as soon as someone is logged in, the link will expire. `max_uses` would use the cache storage to store **all used links**, which I think is inferior to this approach. I intentionally did not change the lifetime because the feature might be used for other cases as well (since we're just configuring the standard Symfony authenticator).

**Review by bytehead — DISMISSED** [review]
LGTM, way easier approach 😅

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @aschempp.

**Pull request merged**
