### PR TITLE
Deprecated the return of null response in fragments

### PR DESCRIPTION
**Pull request by aschempp**
This should never have made it into the code base. When I suggested this in https://github.com/contao/contao/pull/622 I actually thought you don't need to write `return …` in the `getResponse()` method. But writing `return null` does not make sense at all…

The idea is that we can change the return value of the abstract method again in Contao 5

### CODE REVIEW

**Comment by m-vo** [comment]
Funny, I was just in the process of writing an issue that covers the exact same method. :smile: 

IMO we should return an empty response instead of rendering the template when `null` was returned in `getReponse()`. 

:+1: for deprecating that `null` could be returned in the first place.

**Comment by m-vo** [comment]
If we're at it: Should anyone ever call `return $template->getResponse()` in their fragment controllers? Shouldn't that be `return new Response($template->parse());`? 

If so, we should fix the docs and maybe make it more clear how to use this somehow…

**Comment by leofeyer** [comment]
You have assigned the PR to the `4.12` milestone but the base branch is `4.x`. Can you rebase the PR please?

**Comment by aschempp** [comment]
> IMO we should return an empty response instead of rendering the template when `null` was returned in `getReponse()`.

No, we can't change that. We shouldn't allow `null` at all. Just return an empty response yourself.


> If we're at it: Should anyone ever call `return $template->getResponse()` in their fragment controllers? Shouldn't that be `return new Response($template->parse());`?

This was an issue in earlier Contao 4 versions. It should be fixed so that `$template->getResponse()` works correctly and is the correct way to do it. It will for example generate correct caching headers.

**Comment by m-vo** [comment]
> It should be fixed so that $template->getResponse() works correctly and is the correct way to do it. 

It will also currently execute `FrontendTemplate#compile()` which cannot be right.

**Comment by m-vo** [comment]
If we are setting cache headers, why not in the `AbstractFragmentController`? 

There are multiple ways how users will return a response in a fragment's `getReponse()` method:

- `return $template->getResponse();`
- `return new Response('foo');`
- `return $this->render('foo.html.twig');`

For the last two cases I would have to set headers myself while the first one would set them for me?

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
I am merging this PR as it is correct to add the deprecation.

@m-vo Can you open a separate issue regarding `$template->getResponse()` vs. `new Response($template->parse())`? I think you have a point here.

**Comment by m-vo** [comment]
> @m-vo Can you open a separate issue regarding $template->getResponse() vs. new Response($template->parse())? I think you have a point here.

see https://github.com/contao/contao/issues/3263

**Pull request merged**
