### PR TITLE
Removed deprecated TL_CSS_UNITS superglobal

### PR DESCRIPTION
**Pull request by Toflar**

### CODE REVIEW

**Review by bytehead — DISMISSED** [review]

**Review by fritzmg — DISMISSED** [review]

**Review by aschempp — COMMENTED** [review]
should it also be removed from the `DEPRECATED.md`?

**Review by leofeyer — COMMENTED** [review]
You also have to delete the corresponding entry in the `DEPRECATED.md`.

**Comment by Toflar** [comment]
Done.

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @Toflar.

**Pull request merged**
