### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xchs**
Remove the shell prompt sign.

### CODE REVIEW

**Comment by leofeyer** [comment]
Thank you @xchs.

**Comment by Toflar** [comment]
Why is that? CLI examples always use the $ sign?

**Comment by leofeyer** [comment]
It is pretty common to use the $ sign in CLI examples, but there are quite a few projects out there that do not, such as Doctrine, phpDocumentor, Guzzle or PhpStan. I guess it is easier to copy and paste a whole line if there is no $ sign, so the change made sense to me. I can revert it of course if you want.

**Comment by Toflar** [comment]
Feels really strange to me but I also don‘t really care :D Just wondered if there‘s a specific reason.

**Comment by leofeyer** [comment]
At least it is consistent now, for what it's worth. It used to be

```bash
$ composer create-project --no-install contao/managed-edition <directory> <branch>
```

and 

```bash
$ composer update
```

together with

```bash
./run phpunit
```

and 

```bash
mysql -e "CREATE DATABASE contao_test"
```

**Pull request merged**
