### PR TITLE
Correctly show past events if "hide running events" is active

### LINKED ISSUE #6387: no events with this combination: show all past events /  hide running events
### Affected version(s)

4.13.30

### Description

With the combination:
-  show all past events
-  hide running events

within the event listing module no events will be shown altough we have events in the past.

image

### PR DESCRIPTION
**Pull request by janborg**
Fixes #6387

this change fixes a bug in the behavior of the "hide running events". when showing past events.

### CODE REVIEW

**Review by fritzmg — COMMENTED** [review]
I don't think matching the `cal_format` is the right solution at all here, since the `cal_format` can be arbitrary.

I think https://github.com/contao/contao/issues/6387#issuecomment-1857704077 is the correct solution?

**Comment by janborg** [comment]
when using `effectiveEndTime` as in [512838e](https://github.com/contao/contao/pull/6798/commits/512838e299fa2e703b4c4a736a947cedbc8fe43d) no events are shown, when listing upcoming events.

**Comment by janborg** [comment]
not showing events, when startTime < time() && effectiveEndTime > time() is the right behaviour, when 'hide running events' is active as implemented in last commit 4a5d7fe!

**Review by leofeyer — APPROVED** [review]

**Comment by leofeyer** [comment]
Thank you @janborg.

**Pull request merged**
